### ISSUE TITLE
Audio Up/Down keys do not work on a Mac client

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#1230]
**Imported issue:**

* Author: sammiller0 (SourceForge user)
* Date: 2006-07-25 18:59:55
* Legacy ID: 1243

Running synergy server on a 1.42 GHz Mac Mini, client on a 1 GHz 17"   
powerbook G4.  The sound up and down keys on my apple bluetooth   
keyboard only work on the mac mini running the synergy server.

**Comment by the-wes** [comment]
+2 - user reported it, and I reproduced it. The audio buttons just plain don't work on a Mac, whether they're the native keyboard buttons (which work on the server and Windows clients) or a hotkey-mapped button.

**Comment by Tom-E** [comment]
+1, reproing and annoying

**Comment by dmland** [comment]
+1 Still missing under 1.8.3-rc1-e36a7ae

**Comment by scopp** [comment]
agree with dmland, media controls still do not work on OSX clients for `1.8.3-rc1-e36a7ae`.

El Capitan 10.11.6 for both server/client.

**Comment by nlyan** [comment]
Closing in lieu of #3305 being more general.
