### ISSUE TITLE
synergys.exe: no configuration available

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#1267]
**Imported issue:**
- Author: tpd1001 (SourceForge user)
- Date: 2006-09-23 14:05:12
- Legacy ID: 1280

I'm running synergy as a server on Windows 2000 Server  
(Build 2195 SP4) with Citrix MetaFrame 1.80 (Build 260  
SP4). The client is Windows XP SP2.  

I clicked on AutoStart and then on Install for "When  
Computer Starts" and it duely created the service.  

However, when I start the service it pops up a dialog  
with "synergys.exe: no configuration available" and  
the service fails to start correctly.  

On going to services.msc and then Synergy Server  
service properties, I see that the path to executable  
is just "C:\Program Files\Synergy\synergys.exe" with  
no parameters, and there's nothing in the Start  
Parameters field.  

I tried adding the following:  
 --no-daemon --debug WARNING --name aardvark --  
address :24800  
to both start paramaters and the executable name (via  
the registry) in turn, but the same error was produced.  

This command when installed as AutoStart "When you log  
in" works fine with exactly that command line.  

I've also tried it in reverse with Windows XP as the  
server and Win 200 Server as the client and it works  
fine.  

Tom

**Comment by sonicer105** [comment]
I'm re-opening this issue as it's still affecting me.

Synergy Version: 1.10.1-stable-8941241e
Synergy Build Date August 28, 2018
Running on Windows 10 Enterprise 1809 17763.195

`[2018-12-20T09:39:52] INFO: connecting to service...
[2018-12-20T09:39:54] INFO: connection established
[2018-12-20T09:13:44] INFO: starting new process
[2018-12-20T09:13:44] INFO: activeDesktop:Winlogon
[2018-12-20T09:13:44] INFO: starting new process
[2018-12-20T09:13:44] INFO: drag and drop enabled
synergys.exe: no configuration available
[2018-12-20T09:13:45] ERROR: failed to launch, error: process immediately stopped
[2018-12-20T09:13:45] INFO: backing off, wait=10s, failures=5364`

**Comment by IamMark86** [comment]
After struggling with this lot I found that synergy wasn't able to load my configuration, because the default location is under User/Appdata/... and my Username had an accent character "á" in it.

**Workaround**: I saved my configuration into the root folder of the drive and the issue stopped.

> I'm re-opening this issue as it's still affecting me.
> 
> Synergy Version: 1.10.1-stable-8941241e
> Synergy Build Date August 28, 2018
> Running on Windows 10 Enterprise 1809 17763.195
> 
> ```
> [2018-12-20T09:39:52] INFO: connecting to service...
> [2018-12-20T09:39:54] INFO: connection established
> [2018-12-20T09:13:44] INFO: starting new process
> [2018-12-20T09:13:44] INFO: activeDesktop:Winlogon
> [2018-12-20T09:13:44] INFO: starting new process
> [2018-12-20T09:13:44] INFO: drag and drop enabled
> synergys.exe: no configuration available
> [2018-12-20T09:13:45] ERROR: failed to launch, error: process immediately stopped
> [2018-12-20T09:13:45] INFO: backing off, wait=10s, failures=5364
> ```

**Comment by turrini** [comment]
Why this issue was closed if it is not fixed? I'm facing the same issue btw even on the latest stable: 1.11.1

**Comment by riteshpanjwani** [comment]
I'm facing the same issue.

**Comment by lemw** [comment]
The same issue has haunted me for weeks now.
I moved the configuration.sgc file to a part without "strange characters" (in my case it was the "å" in my last name that cause the issue .

**Comment by recks** [comment]
Still a problem - and for the same reason. But the workaround works.

**Comment by andreacndn** [comment]
Hi @recks which version are you using?

**Comment by recks** [comment]
> Hi @recks which version are you using?

I am using the latest version; just downloaded an hour or so before.

**Comment by andreacndn** [comment]
1.14.1 was released a few days ago.
It would be very useful to know if the same problem still happens there.

**Comment by thoufeekx** [comment]
> 

where is this configeration file located?

**Comment by thoufeekx** [comment]
> 

where to find and how to move configuration.sgc, truth be told i find no configeration.sgc anywhere. I think i am missing something.

**Comment by desymless** [comment]
> > 
> 
> where to find and how to move configuration.sgc, truth be told i find no configeration.sgc anywhere. I think i am missing something.

The configuration file tends to be under the user/home directory (depending on the operating system), although you can find where to Configure server>Advanced config.

You can also create a copy of the configuration file by going to File>Save configuration as

**Comment by lanpsyr** [comment]
I resolved this by reviewing the configuration, in my case, I noticed that when I use the keybind (CTRL+SHIFT+#) it comments out a portion of the configuration, rendering it invalid. I removed that keybinding and the service started right up.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
