### ISSUE TITLE
Installation fails on Windows 7

### ISSUE THREAD

**Issue by sukky** [symless/synergy#2339]
Hi

When I try to install Synergy on my Windows 7, it always shows "Internal error" which is in Korea.

synergy-1.5.1-r2398-Windows-x64.msi

Please let me know what should I do.

![synergy-internal-error](https://cloud.githubusercontent.com/assets/1179962/4609084/d469e212-5294-11e4-8710-74c064fa4ccd.png)
![synergy-internal-error2](https://cloud.githubusercontent.com/assets/1179962/4609083/d46548ce-5294-11e4-940e-299a2f3771f1.png)

**Comment by XinyuHou** [comment]
Close as an obsolete issue
