### ISSUE TITLE
Highlighting is buggy in Windows 7 64-bit

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#2695]
**Imported issue:**

* Author: John Warren
* Date: 2010-11-16 14:41:07
* Legacy ID: 2751

**Steps to reproduce:**  
  
1. Run Synergy+ as admin in server mode on Windows 7 64-bit  
2. Open Google Chrome 64-bit (7.0.517.44)  
3. Highlight portion of URL in address box and hit control-c (copy to clipboard)  
4. Attempt to highlight different portion of URL in address box.  
  
Expected: Text is highlighted  
Actual: Unable to highlight text  
  
**Versions (Synergy, OS):**  
  
Server: 1.3.4 Windows 7 64-bit  
Client 1: 1.3.4 Windows XP 32-bit  
  
**Workaround:**  
  
Sometimes, but not always, pasting the clipboard contents somewhere re-enables highlighting.  
  
**Comments:**  
  
A similar issue was raised in Bug #1496 which was unfortunately closed due to a lack of information.  It would be great if that didn't happen in this case and that any additional necessary information was asked for rather than rejecting the bug.

**Comment by rw01** [comment]
Encountering this bug also with clean install of Windows 7 64-bit (as server) and Word 2010 with Synergy 1.6.2.  Client is Mac OS X.  Stopping Synergy service resolves the issue.

**Comment by XinyuHou** [comment]
Duplicate to #3044
