### ISSUE TITLE
Hangul/English toggle and hanja function key for Korean Keyboard is not working

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3071]
**Imported issue:**
- Author: Chung Whan Lee
- Date: 2012-03-31 19:56:03
- Legacy ID: 3141

**Steps to reproduce:**  
1. Use the Korean keyboard.  
2. press Hangul/English toggle key.  
3. press Hanja Key.  

Expected: Pressing Hangul/English key have to toggle between Hangul and English. pressing Hanja Key have to convert Hangul to Hanja  
Actual: Pressing Hangul/English key don't any function. Also Hanja key don't  

**Versions (Synergy, OS):**  

Server: repository revision 1309, windows 7 64bit  
Client 1: repository revision 1309, windows 7 64bit  
Client 1: repository revision 1309, ubuntu 10.04 lucid 32bit  

**Workaround:**  

This problem issued many times like these  
http://synergy-foss.org/osqa/questions/1047/korean-keyboard-support  
issue #redmine:662  
issue #redmine:684  
issue #redmine:705  

I made the simple patch that is not interfering other one, and it works perfectly.   

**Comments:**  

This problem is critical to korean because can't type a korean. So when each times use other version of synergy, korean must apply patch.

**Comment by the-wes** [comment]
A user submitted a patch which may help with this issue:

diff -Naur synergy-1.2.7.org/lib/platform/CMSWindowsKeyState.cpp synergy-1.2.7/lib/platform/CMSWindowsKeyState.cpp 
--- synergy-1.2.7.org/lib/platform/CMSWindowsKeyState.cpp 2005-12-19 03:41:33.000000000 +0900 
+++ synergy-1.2.7/lib/platform/CMSWindowsKeyState.cpp 2006-01-27 00:55:25.000000000 +0900 
@@ -56,7 +56,7 @@ 
/* 0x012 */ { kKeyAlt_L }, // VK_MENU 
/* 0x013 */ { kKeyPause }, // VK_PAUSE 
/* 0x014 */ { kKeyCapsLock }, // VK_CAPITAL 
- /* 0x015 */ { kKeyNone }, // VK_KANA 
+ /* 0x015 */ { kKeyShiftSpace }, // VK_KANA 
/* 0x016 */ { kKeyNone }, // VK_HANGUL 
/* 0x017 */ { kKeyNone }, // VK_JUNJA 
/* 0x018 */ { kKeyNone }, // VK_FINAL 
diff -Naur synergy-1.2.7.org/lib/synergy/KeyTypes.h synergy-1.2.7/lib/synergy/KeyTypes.h 
--- synergy-1.2.7.org/lib/synergy/KeyTypes.h 2005-11-26 07:34:15.000000000 +0900 
+++ synergy-1.2.7/lib/synergy/KeyTypes.h 2006-01-27 00:54:11.000000000 +0900 
@@ -130,6 +130,7 @@ 
static const KeyID kKeyCancel = 0xEF69; /* Cancel, stop, abort, exit */ 
static const KeyID kKeyHelp = 0xEF6A; /* Help */ 
static const KeyID kKeyBreak = 0xEF6B; 
+static const KeyID kKeyShiftSpace = 0xEF7D; 
static const KeyID kKeyAltGr = 0xEF7E; /* Character set switch */ 
static const KeyID kKeyNumLock = 0xEF7F;

see helpdesk ticket 2907.

**Comment by nbolton** [comment]
@the-wes What sort of priority would you give this issue?

**Comment by the-wes** [comment]
@nbolton the patch should at least get a tryout ASAP. if it doesn't work, I'd set it to priority-later.

**Comment by nbolton** [comment]
@the-wes Good point, I'll set it to high since we have a patch.

**Comment by nlyan** [comment]
Apparently fixed by PR #5196
