### ISSUE TITLE
Investigate ways of improving CPU usage on Mac OS X

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3224]
**Imported issue:**
- Author: Nick Bolton
- Date: 2012-07-22 13:30:25
- Legacy ID: 3294

The `synergyc` process currently uses around 5-10%% in most cases, but in some cases uses 10%%-20%% of CPU. We should investigate ways of improving the CPU usage.

**Comment by XinyuHou** [comment]
Duplicate of #5991
