### ISSUE TITLE
Eclipse toolbar problem with Synergy + NoMachine

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3250]
**Imported issue:**
- Author: Roger Lucas
- Date: 2012-08-03 10:53:21
- Legacy ID: 3320

**Steps to reproduce:**
1. Install Eclipse and NoMachine server onto Machine A (tested running Debian Squeeze)
2. Install Synergy and NoMachine client onto Machine B (tested using Ubuntu 12.04)
3. From machine B, connect to Machine A using NoMachine client which starts a Gnome Terminal.
4. From the Gnome Terminal, start Eclipse
5. The toolbar icons in Eclipse do not raise as the mouse goes over them and you cannot click on them
6. Stop the Synergy server on Machine B
7. The toolbar icons in Eclipse now work correctly
8. Start the Synergy server on Machine B
9. The toolbar icons in Eclipse do not raise as the mouse goes over them and you cannot click on them

**Versions and operating systems:**

Machine A is running a fully updated Debian Squeeze (x86_64)
NxNode on Machine A is nxnode_3.5.0-9_amd64.deb
NxServer on Machine A is nxserver_3.5.0-11_amd64.deb

Machine B is running a fully updated Ubuntu 12.04 (x86_64)
Synergy server on Machine B has been manually updated to 1.4.10 from the Synergy web site
NxClient on Machine B is 3.5.0-7

There is also Machine C running Windows XP (fully updated) that is a Synergy client to machine B, but I don't think it has any effect.

**Temporary workarounds:**

Restarts do not fix this problem.
The only solution is to temporarily shut down synergy server on Machine B to access the toolbar on Eclipse.

**Additional comments:**

If you run locally Eclipse on Machine B, the Eclipse toolbar works perfectly, so it doesn't appear to be a Synergy + Eclipse problem.
I'm comfortable with Linux (kernel developer, etc) so will happily patch + recompile + update Synergy to try solutions or provide more debug data.

**Comment by XinyuHou** [comment]
Close as an obsolete issue
