### ISSUE TITLE
Mouse invisible on Mac client when screen zoomed

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3289]
**Imported issue:**
- Author: Justin Novack
- Date: 2012-08-29 21:26:24
- Legacy ID: 3359

**Steps to reproduce:**

Turn on Zoom (System Preferences -> Accessibility), use Full Screen Zoom.
1. Zoom in on the Host
2. Travel to any client

Expected: Mouse to function normally on host and client.

Actual:The mouse turns invisible on client, and cannot travel back to host.

**Versions and operating systems:**

Host: 1.4.10 Beta on OSX 10.8.0 iMac with Thunderbolt Display running VMware full screen on second display.
Client: 1.4.10 Beta on OSX 10.8.1

**Temporary workarounds:**

Disable Synergy on Client.

When you disable synergy on the client, the mouse hops back to the host and you can unzoom properly.

**Additional comments:**

Temporarily, I would like an option to wrangle the mouse inside the host if I am currently zoomed.

Although, I suppose I could see a need to option to keep zoomed on the host while I'm on the client, however, I've noticed that the "top" and "bottom" are remapped as you move, which might make this impossible.

**Comment by jhboerhof** [comment]
I can also confirm the issue with the current build of Synergy: 
Using the OSX zoom feature  (System Preferences > Accessibility > Zoom) is giving Synergy trouble.
When I have my Mac-window Zoomed in, I am not able to move my mouse to the client machine.

This is my setup:
Synergy version 1.8.2-stable-36cd521
build date di sept. 13 2016

Computer 1 (set up as server)
Mac OSX Yosemite 10.10.5

Computer 2 (client - use another computer's mouse and keyboard)
Windows 8.1 Pro

Feel free to contact me if additional information is needed.

**Comment by websteris** [comment]
This is still an ongoing issue that I struggle with regularly. Any hope of implementing a fix?

**Comment by vorg** [comment]
Run into the issue 3x this week. Also have to either go and turn of pc in another room or hard reboot host mac :/

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
