### ISSUE TITLE
Crash while using VMWare Workstation 8/9

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3292]
**Imported issue:**
- Author: Samuel Trommel
- Date: 2012-09-01 13:47:37
- Legacy ID: 3362

**Steps to reproduce:**
1. Install Ubuntu 12.04 64-bit with synergys (1.4.10)
2. Install VMWare workstation 8 or 9
3. Install synergyc on a Windows 7 64-bit. 

Go inside a VM and try to move your mouse to the Windows 7 client. Synergys will crash, see stack trace below:

Program received signal SIGSEGV, Segmentation fault.
0x00007f18537cddb3 in ?? () from /usr/lib/x86_64-linux-gnu/libXi.so.6
(gdb) bt
#0  0x00007f18537cddb3 in ?? () from /usr/lib/x86_64-linux-gnu/libXi.so.6
#1  0x00007f18540318da in _XCopyEventCookie ()

   from /usr/lib/x86_64-linux-gnu/libX11.so.6
Cannot access memory at address 0x7fffb6d5a788

**Versions and operating systems:**

Ubuntu 12.04 64-bit
VMWare Workstation 8/9
Synergy 1.4.10 on both server and client

**Temporary workarounds:**

Not known

**Additional comments:**

None

**Comment by neilcar** [comment]
I'm reproing this on Ubuntu 18.04 with Synergy 1.10 and latest VMWare Player.  It only seems to repro if VMWare is on the edge of the screen that's connected to a Synergy client -- when I try to move off-screen, synergys hits the sigfault.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
