### ISSUE TITLE
Client stops working when Mumble has focus

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3565]
**Imported issue:**
- Author: Ariana Askew
- Date: 2013-06-10 03:51:29
- Legacy ID: 3635

Using the application primarily to support my gaming habit so the use of voice communication tools like Ventrilo, Teamspeak and Mumble are very important to me.

**Steps to reproduce:**

1.Applied configuration settings for both the server and client and confirmed that they see and connect each other.
1. Client screen is on the left hand side and monitor screen is on the right hand side.
2. Server settings: Hotkey(F1) and the connected action is switchInDirection(left) (F1 is no longer used after this step because the screen recognizes my mouse is on the left hand side and switches to client). Advanced Server: Switch after waiting 250ms and Sync screen savers both checked.
3. Applied settings on both server and then client to refresh connection and settings using both mice/mousepad.
4. Confirmed mouse of server controlled cursor on client. Confirmed mouse cursor could be regained on server monitor.
5. Confirmed keyboard of server controlled key presses on client. Confirmed key presses could be done on server monitor.
6. Confirmed Mumble keybind (ctrl) worked as intended.

Expected: Expected to use the program seamlessly until the program was stopped.

Actual: Client refused to work after a window of Mumble was put into the fore front of the client screen. As in, Synergy does work when the program is behind other program windows on the screen such as Google Chrome or the Synergy Client/Log screen.

Bug goes away on restart of client Synergy, but reemerges after bring the the window to the front again.

**Versions and operating systems:**

Both: Synergy Version 1.4.12 on both server and client.
Client OS: Windows 7 Home Premium 64-bit SP1
Server OS: Windows 7 Ultimate 64-bit SP1

**Temporary workarounds:**

When using Mumble(or other clients below), I'm connecting the the servers and then minimizing the program or bringing my web browser or other windows to the fore front or the screen. I then restart Synergy on the client and continue on as usual with my computer use with Syenergy working.

**Similar bugs:**

The same bug occurs with a Teamspeak or Raidcall Window. It does not happen with Ventrilo. Even with this windows running as Administrator.

**Additional comments:**

If I run Synergy as Administrator, the client doesn't recognize the mouse movement or keyboard keystrokes.

**Comment by XinyuHou** [comment]
Close as an obsolete issue
