### ISSUE TITLE
Screensaver sync not working on Mac server

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3601]
**Imported issue:**
- Author: Chris Tashjian
- Date: 2013-07-09 19:11:57
- Legacy ID: 3671

**Steps to reproduce:**
1. Configure synergy server (in my case OS X 10.8.4) to sync screensavers
2. Setup a client running OS X 10.9 beta
3. On the server, configure a hot corner to start the screensaver
4. On the server, move the mouse to said hot corner

Expected:  As when both my setup had both client and server running 10.8.x, the screensaver engages on both computers

Actual:  The screensaver only engages on the server.

**Versions and operating systems:**

Server: 1.4.12 / Mac OS X 10.8.4
Client: 1.4.12 / Mac OS X 10.9 Mavericks developer previews

**Comment by davehensley** [comment]
Version 1.7.6 was just released, and yet this is still broken even after all this time (when I put the server into screensaver mode, the client does not go into screensaver mode).

Server: Ubuntu Linux 10.04.4 LTS
Client: Mac OS X 10.11.3 El Capitan

Here is my server config:
```
section: screens
	linux:
	mac:
		super = ctrl
		ctrl = super
end

section: links
	linux:
		right = mac
	mac:
		left = linux
end

section: options
	screenSaverSync = true
end
```

**Comment by sness** [comment]
Still broken for me too.

**Comment by TinLe** [comment]
WFM now.  Synergy release 1.8.3-stable on RHEL6.6 and OSX 10.11.6

**Comment by OmgImAlexis** [comment]
Same issue here with `1.8.8-stable-25a8cb2` using OSX as the server and Windows 10 as the client.

**Comment by deekayw0n** [comment]
not working with osx + win 1.9.0-rc3, as well. Is there confirmation that this is working for paid versions?

**Comment by dtoro** [comment]
Still not working
Server: MacOS Sierra Version 10.12.6
Client: MacOS High Sierra Version 10.13.4
Synergy: 1.8.8-stable-c30301e

Happy to buy paid version if it works

**Comment by nyetwurk** [comment]
Sigh

**Comment by OmgImAlexis** [comment]
@nbolton why is this closed when paying users still have this issue? It's only "stale" because we're waiting to hear back from your team...

**Comment by nyetwurk** [comment]
I agree that bugs should not be closed just because they are old. If the bug has not been resolved, it hurts no one to keep it open. If your bug list is too long, and github's triaging isn't working for you, I recommend using a different problem tracker.  Needing a place to put "old bugs" that are cluttering your devel process implies that git's issue system is not sufficient for your needs.

**Comment by nbolton** [comment]
This issue was not meant to be marked stale. Please let me know if you see any others that are obviously not stale (or are still an issue).

**Comment by ansoni-san** [comment]
This still does not work. I'm shocked as I just paid for the software, hoping that the commercial version would work better.

Requesting an update on this issue please.

**Comment by joshmanders** [comment]
7 years later and this is still not addressed or resolved... Any alternatives to Synergy?

Guess I should just be patient and wait for Universal Control to be released in macOS.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.

**Comment by dylannorthrup** [comment]
Still an issue.

Deskflow: 1.24.0.0 (56a1bd68)
Qt: 6.9.1
System: macOS 26.1
