### ISSUE TITLE
Wrong error message when configuration goes missing

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3622]
**Imported issue:**
- Author: Justin Reinhart
- Date: 2013-08-02 07:59:17
- Legacy ID: 3692

**Steps to reproduce:**
1. Setup working Synergy with Windows 7 PC as server and any secondary PC as client. All is working fine.
2. Close Synergy (server)
3. Delete Synergy's config file? (This happened to be against my will due to an unknown third-party program, or perhaps a regular windows routine. My configuration was lost.)
4. Open Synergy on the server and Start the server.
5. BUG: Message given to user is "unrecognized client name "justins-macbookpro", check server config".  At this point, even if the user clicks "Configure Server" and adds the client PC name back in, this message continues to be shown. This is confounding because it is not accurate. What actually needs to be done is for the user go go back through the configuration wizard (bug: wizard was not automatically shown to the user when the configuration went missing) and then re-setup the encryption with the right password. The current error message is not accurate for this reason.

**Versions and operating systems:**
- Server: Windows 7 64-bit, Synergy 1.4.12
- Client: Macbook Pro with OS X 10.8.4 (client not important), Synergy 1.4.12

**Similar bugs:**
- Configuration went missing spontaneously and was not preserved
- User was not shown the wizard to setup encryption when encryption went missing and was mandatory 

**Additional comments:**

Thanks.

**Comment by XinyuHou** [comment]
Close as an obsolete issue
