### ISSUE TITLE
Synergy stops working when User Account Control or any other administrator related action needed

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3637]
**Imported issue:**
- Author: Brian Maunder
- Date: 2013-08-08 14:32:34
- Legacy ID: 3707

Using Synergy 1.4.12
1. Right click an application to "Run as Administrator"
2. Window pops up asking for permission, Synergy stops working.

Installing a program when it asks for user permissions, it will halt synergy from interacting.

**Comment by gr0g** [comment]
Hi - this issue is still relevant in the latest synergy - was any fix released?

**Comment by mkeida** [comment]
Hi, why is this issue closed when the bug is still there? It ruins otherwise great software. Lot of issues here are being closed when they are not fixed apparently. Please provide some fix, we expect working solution for our money.

**Comment by andreacndn** [comment]
@mkeida, could you please detail the steps to reproduce the problem so we can investigate it?

Thanks,
Andrea

**Comment by mkeida** [comment]
> @mkeida, could you please detail the steps to reproduce the problem so we can investigate it?
> 
> Thanks,
> Andrea

Hello, thanks for your time and sorry for late reply. I will try to explain my problem. I run Synergy between my MacOS as server and Windows PC as a client. Everything works fine except these scenarious:

**1. login screen of Windows 10**
Cursor seems to be stuck at server PC for about 5-6 seconds which makes client PC unusable for that time. After that, cursor lag disappears and I can login properly.

**2. Windows administrator rights window **
For example when I run program which needs administrator rights cursor again freezes and disappear for 3-6 seconds. Only after that I can close the window. Usually at that time I'm moving mouse like a crazy and at some point mouse appears on different place than before.

Thanks for your time!

**Comment by fostro** [comment]
I was seeing a similar issue with my Windows 10 client from my Linux server.  Changing the Elevate setting in the client from 'As Needed' to 'Always' seems to work.

**Comment by andreacndn** [comment]
Thank you @mkeida for the details, and @fostro for the useful feedback!

**Comment by mkeida** [comment]
> my Windows 10 client from my Linux server. Changing the Elevate setting in

That actually solved my issue! Thank you very much!

**Comment by drew7579** [comment]
> I was seeing a similar issue with my Windows 10 client from my Linux server. Changing the Elevate setting in the client from 'As Needed' to 'Always' seems to work.

How did I NEVER notice this option before? At any rate, this absolutely worked for me as well—I can now continue to use my mouse and keyboard during UAC popups. I am so annoyed with myself that I never noticed that before as this was my primary annoyance with Synergy.

**Comment by fweep** [comment]
See [this thread on the Symless forums](https://forums.symless.com/topic/6143-delay-in-cursor-move-around-windows-login/) for a little more background. Elevate setting works for me!

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
