### ISSUE TITLE
Colemak layout on Mac types wrong characters

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3673]
**Imported issue:**
- Author: Chris Laprise
- Date: 2013-10-03 04:22:34
- Legacy ID: 3743

**Steps to reproduce:**
1. If OSX is pre-10.7, install colemak layout from colemak.com.
2. Enable colemak under Prefs/Language/Input Sources. Make sure colemak is selected in the OSX menu bar, and set Ubuntu to colemak under System settings/Keyboard Layout.
3. Use synergy to connect Ubuntu server and OSX client
4. Using server's keyboard and mouse, move over to the OSX screen and start typing

Expected: Typing across home row yields 'a r s t'

Actual: Get 'a p r g' instead. Typing on the server (Ubuntu) remains OK.

**Versions and operating systems:**
Ubuntu 13.04 with built-in colemak layout and synergy 1.4.10
Mac OS X 10.6.8 with installed colemak layout and synergy 1.4.12 (GUI)

**Temporary workarounds:**
Change either server or client to qwerty after connecting synergy

**Similar bugs:**

TODO

**Additional comments:**

Difference between qwerty and colemak layouts appear to be applied TWICE to the input stream on the client.
Have not tried this in reverse (OSX as server) or with Linux-Linux or Mac-Mac pairings. Have not tried this with built-in colemak in OSX 10.7.

**Comment by brmurphy** [comment]
I still have this issue in mac osx 10.10 to mac osx 10.10.

sad panda

Any updates? Workaround still works.

**Comment by mijoharas** [comment]
Same here (with dvorak).

**Comment by kivoli** [comment]
I have a very similar problem using the [Neo Layout](http://neo-layout.org/). Think of it as a Dvorak-like keyboard layout designed for German-speaking users. I use it with two Arch Linux hosts. 
Funnily enough most of my keys, including the modifiers and generally speaking the other layers (besides the second, „uppercase“, one) work fine. Unfortunately it’s the few keys which do not work which trouble me most:
- Tabulator - prints "8"
- Period (yes, ".") - instead I get "y"
- Arrow-keys - left-right-up-down prints i-e-l-a
- Number pad

The work around helps with some of these but in turn ruins it with others. The problems have changed ("." used to work in the past …) but not the overall issue. 

PS: Arch as server and Windows as client (with the Neo2 layout on both) works …

**Comment by brmurphy** [comment]
Has this been resolved? I am seeing colemak work across client/server with version 1.8.8 stable.

**Comment by brmurphy** [comment]
So fixed?

**Comment by nbolton** [comment]
Are you still seeing this in 1.9?

**Comment by petabyteboy** [comment]
> Are you still seeing this in 1.9?

Yes

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
