### ISSUE TITLE
Client can't trigger GNOME "pressure points"

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3722]
**Imported issue:**
- Author: Charles Phillips
- Date: 2013-10-24 19:16:20
- Legacy ID: 3792

I experience this bug since updating my client to Ubuntu 13.10 which has Gnome 3.8.  Server is Mac OSX 10.8.  I found this bug reported as [#972244 on RedHat's bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=972244) which contains a good description of the issue:

> Description of problem: GNOME 3.8 changed the hot corner and edge for
> Activities and Messages to use "pressure sensitivity" before
> activating.  I believe this is some sort of mouse overshoot detection.
> This works fine on my system with a direct mouse, but I can't get the
> pressured activation to work as a synergy client.
> 
> Version-Release number of selected component (if applicable): client:
> synergy-1.4.10-1.fc19.x86_64 server: synergy 1.4.12 on Win7 x64
> (nothing in the changelog from 1.4.10-12 looks relevant...)
> 
> How reproducible: 100%%%%
> 
> Steps to Reproduce:
> 1. Quickly move the mouse to the top-left corner for Activities.
> 2. Quickly move the mouse to the bottom edge for the Message Tray.    (Note, the pressure required is greater on this one.)
> 
> Actual results: Nothing.
> 
> Expected results:
> 1. The Activities Overview is shown.
> 2. The Message Tray is revealed. (and both do work with a local mouse)
> 
> Additional info: This client is configured on the left side, server to
> the right.  I do have "switchCorners = none +top-right +bottom-right"
> and "switchCornerSize = 50", but removing that makes no difference.
> 
> It does work if I set "relativeMouseMoves = true", but only while the
> cursor is locked in the client.  Normally I leave it free to go
> between screens, so this setting is not a complete solution for me.
> 
> I'm guessing that swapping so GNOME is the server and Win7 the client
> might also fix it, but that won't fit the way I use my computers.
> 
> To see where GNOME is setting this, grep for PRESSURE in
> /usr/share/gnome-shell/js/ui/layout.js.  I don't see any configuration
> to disable this new pressure sensitivity (short of editing that file),
> but if there's a way that would probably be an ok workaround for me.
> 
> **Additional comments:**
> 
> TODO

Thanks for your work!

**Comment by abmantis** [comment]
This is still a problem today with Synergy 1.6.2 and Gnome Shell 3.14.

**Comment by spacepluk** [comment]
Same with Synergy 1.6.3 and Gnome 3.16.

**Comment by HackerOO7** [comment]
Just found the same problem.

**Comment by chrisjrob** [comment]
Just for those who didn't read the whole of that Red Hat bug,

**Comment by ezakto** [comment]
Still happening with gnome 3.32 and synergy 1.10.2, and the disable-barrier extension is not working anymore. Any chance this is gonna be fixed?

**Comment by zareami10** [comment]
@nbolton It would be great if you could reopen this. This is issue is still well and alive.

**Comment by andreacndn** [comment]
@zareami10 I have reopened the issue, thanks for flagging the problem.

**Comment by andreacndn** [comment]
Could you please confirm which operating system and Synergy version you are using?

**Comment by zareami10** [comment]
> Could you please confirm which operating system and Synergy version you are using?

I'm using Synergy 1.12.0 on both machines.
Server is Windows 10, and the client Arch Linux with GNOME 3.38.2 (Xorg).

**Comment by andreacndn** [comment]
Thanks!

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
