### ISSUE TITLE
Wacom Intuos tablet does not send to client

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3828]
**Imported issue:**
- Author: Nathan Rijksen
- Date: 2014-01-23 18:26:08
- Legacy ID: 3898

**Steps to reproduce:**
1. Install WACOM tablet on OSX host
2. Move cursor to Ubuntu guest using wacom touch mode 

Expected: 

Cursor moves to other screen as expected and I can use my wacom tablet in touch mode as I do on the host.

Actual: 

Cursor is placed on outer edge of guest, can move up/down along the edge but can't move horizontally.
Additionally switching screen with a shortcut doesnt work at all with pen mode, just logs "NOTE: unknown quartz event type: 0x17"

**Versions and operating systems:**

Host: OSX Mavericks
Guest: Ubuntu 13.10 with Gnome Shell 3.10

**Temporary workarounds:**

None that I have found, the Wacom tablet is completely unusable with Synergy

**Similar bugs:**

http://synergy-foss.org/spit/issues/details/813/

**Comment by BR4DY** [comment]
Having the exact same issue here... any updates??

**Comment by the-wes** [comment]
Whoops, looks like I changed the labels but forgot to click Reopen.

**Comment by neilogd** [comment]
I'm seeing this issue also. Just tried again today at work (got a second machine for dev), and the cursor locks to the left hand side of the client machine.

Wacom is setup to map 1:1 to the server machine, and disabled switching on the edges of the screen. Only switch using hotkeys.

**Comment by BR4DY** [comment]
Just updated to 1.7.5 on brand new MacBook (10.11) and iMac (10.10) same issue! the mouse moves to the macbook as it should. but the mapped area for the ENTIRE screen is about 0.5cm square in the middle of the tablet. Keyboard works fine - but the mouse is unusable? Any updates on this?

**Comment by mottosso** [comment]
For what it's worth, I'm also seeing this between two Windows machines and an Intuos 3.

**Comment by nbolton** [comment]
@mottosso Hey, I re-worded the title. Does it still apply to you?

**Comment by mottosso** [comment]
Hi @nbolton, no, I've only tested between a Windows client and Windows server.

**Comment by nbolton** [comment]
Ah, probably not a platform specific bug in that case.

**Comment by melato** [comment]
x2x does it like this, for a secondary display "east" of the primary:
When you move the Wacom pen past the right (east) edge (assumming you are in the primary display), it appears at the right edge of the secondary display.  If you move it all the way to the left edge, it goes back to the left edge of the primary display.  In either display, the whole area of the tablet is always mapped to one screen.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
