### ISSUE TITLE
Mouse is jumpy on server when using Virtual Box

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3972]
... during full screen and seamless modes

**Imported issue:**
- Author: Joel Brengle
- Date: 2014-05-12 12:43:03
- Legacy ID: 4042

**Steps to reproduce:**
1. Synergy Server running on Linux host OS
2. Windows XP Professional running as Virtual Box guest OS
3. When the Virtual Box guest display is placed into either full screen or seamless mode, the mouse begins to jump, and sometimes does not respond at all.
4. Switching the Virtual Box guest display back to windowed mode returns functionality to the mouse

Expected: Mouse to function normally within seamless or full screen modes of VBox

Actual: Mouse jumps or ceases to function within seamless or full screen modes of VBox

**Versions and operating systems:**

Host PC-32bit: This has been tested on Ubuntu 12.04, Mint 16 (Cinnamon, Mate, and Petra), Debian, and Pear OS5
Guest PC-32 bit: Windows XP Professional

**Temporary workarounds:**

Do not use Full Screen or Seamless mode 

**Similar bugs:**

TODO

**Additional comments:**

This problem does not seem to exist on the Synergy client PC. Everything on the Client PC operates as it should, any windowed configuration of the guest OS.

**Comment by XinyuHou** [comment]
Close as an obsolete issue
