### ISSUE TITLE
Scroll wheel stops working on client machine

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#4054]
**Imported issue:**
- Author: Scott Siddall
- Date: 2014-08-12 13:08:02
- Legacy ID: 4124

**Steps to reproduce:**

I don't know how to reproduce this issue. I haven't yet determined what triggers the wheel to stop working on the client machine.

Expected: Scroll wheel should always work in the client

Actual: Scroll wheel stops working at random times on the client machine

**Versions and operating systems:**

Server OS: Windows XP with Synergy 1.5.0
Client OS: Windows 7 with Synergy 1.5.0

**Temporary workarounds:**

Pressing the "Apply" button or stopping and restarting Synergy on the server is a temporary workaround

**Similar bugs:**

TODO

**Additional comments:**

This happened with the original installation and continues to happen after upgrading to the latest version.

Using a wireless Logitech mouse. (M510)

These events stop being sent when the issue occurs:
DEBUG1: onMouseWheel +0,-120
DEBUG1: event: button wheel delta=+0,-120
DEBUG1: onMouseWheel +0,-120
DEBUG1: event: button wheel delta=+0,-120
DEBUG1: onMouseWheel +0,-120

**Comment by matelich** [comment]
This still happens and has a few posts related to it on the forums:
http://synergy-project.org/forum/viewtopic.php?f=16&t=379&p=1469

I have to restart my server several times per day.

Seen on 1.6.3, 1.7.2-1.7.4

**Comment by nyetwurk** [comment]
Still happens for me occasionally on the master branch, as of commit 17961501f640d8af9b36903ae6d64e3f949a4269

The only solution is to restart the server (not the client).

**Comment by cwizard** [comment]
This still happens.  How does a bug last for over 2 years.  Why did I pay for this?

**Comment by Enigma0** [comment]
This is happening for me Win10 > Win10.

**Comment by elafito** [comment]
This is still happening. Win10 to Win10 on a local net.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
