### ISSUE TITLE
Blocked keyboard keys in all apps  while sandboxed using Sandboxie

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#4062]
**Imported issue:**
- Author: Sev Vez
- Date: 2014-08-18 02:35:33
- Legacy ID: 4132

**Steps to reproduce:**
BASED ON THIS THREAD: http://forums.sandboxie.com/phpBB3/viewtopic.php?f=11&t=19412&p=102906#p102906
NOTE: Make sure ENABLE LUA is 1  (UAC is on) HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\policies\system

STEPS: 
1. Install Sandboxie (latest version here: http://www.sandboxie.com/SandboxieInstall-413-2.exe
2. Install Continuum inside of a sandbox (the default sandbox - defaultbox is fine)
3. Make sure Synergy is running. 
4. Quickly create an account and Try to play game. 
5. Arrow keys are blocked, as well as other erratic key behaviors. 

NOTE TO SYNERGY DEV -- These are really pain in the ass steps. I am more than willing to make a video of the problem so you can see everything without having to go through all the steps.  I can tell you 100%%%% that Synergy is the culprit when running this app sandboxed.   I will endeavor to make a video tonight

Synergy 1.5.  Win 8.1 64bit, all patches applied.

**Temporary workarounds:**
1. Not running Synergy or stopping synergy when playing continuum game
2. Running continuum OUTSIDE of sandbox fixes the problem
**3. Disabling UAC completely in Windows 8.1 64bit using following regkey**

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
EnableLUA"=dword:00000001

**Additional comments:**
DEP is enabled to ensure continuum.exe runs properly. However, this problem was confirmed and tested to have problems either way.

**Comment by XinyuHou** [comment]
Close as an obsolete issue
