### ISSUE TITLE
Client config file always requested on Mac

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#4074]
**Imported issue:**
- Author: E Jones
- Date: 2014-08-29 00:16:55
- Legacy ID: 4144

**Steps to reproduce:**

Setup - Mac as synergy client, PC (Windows 7 x64) as server

1 - Install 1.5.1 on Mac (Copy Synergy to Applications folder after mounting)
2 - Start Synergy (Acknowledge internet download, if required)
3 - Synergy will open with pop-up: 'You have not filled in a valid configuration file for the synergy server. Do you want to browse for the configuration file now?'
4 - Issue: This same pop-up will continue to repeat on every startup of synergy (ie, every system boot)
5 - User clicks 'No' for client config, verifies the 'Client' box is checked and ServerIP is properly entered.

Expected:
- After configuration to client mode, each startup of synergy should return to client mode with previous settings, without 'pop-up' from above each time

Actual: 
- Pop-up will continue to display on every startup of synergy (ie, every system boot)

**Versions and operating systems:**

Synergy Client:
Mac OS 10.8.5

Synergy 1.4.16 - No issue, pop-up is not observed

Issue exists with both versions below:

Synergy 1.5.1 (current release)
Synergy 1.6 Beta synergy-1.6.0-r2411-MacOSX108-x86_64.dmg

**Temporary workarounds:**

Continue to use 1.4.16 for Mac 10.8

**Similar bugs:**

Unknown at this time

**Additional comments:**

Previously discussed on IRC, but since it hasn't been fixed in latest beta, wanted to be sure it got looked into before more versions get pushed (is feasible). 

Thanks

**Comment by XinyuHou** [comment]
Close as an obsolete issue
