### ISSUE TITLE
Synergy Server causing problems with keyboard actions

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#4110]
**Imported issue:**
- Author: Donald Parker
- Date: 2014-10-01 20:44:54
- Legacy ID: 4180

Configuration: Windows 7 hosts the server and the physical keyboard and mouse (both USB devices). Ubuntu 14.04 hosts the client. Both server and client are version 1.6.

How to reproduce:
I'm not really sure. It is intermittent.

Problem:
Every once and a while (once every other day) I find the key strokes being sent to my Windows 7 (synergy server) computer don't match the keys I'm pressing.  I could be typing an email, and some of the letters seem to be just fine but others and being interpreted quite strangely. The strange ones are non-printing so I can't really tell what is being generated or sent to my system most of the time, but I know at least some are behaving as if 'cntrl-alt' are being held down while I type. I know this because of several 'cntrl-alt-key' short cuts I have defined to launch common applications. E.g. I was trying to type the letter "c" into an email, but the calculator app kept launching (which I have a 'cntrl-alt-c' short cut for.

I did not notice any problems with my mouse during this. I was able to make the problem go away by stopping and restarting the synergy server.

**Comment by XinyuHou** [comment]
Close as an obsolete issue
