### ISSUE TITLE
Unable to install on OSX 1.9.5 - can't give access to universalAccess

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#4119]
**Imported issue:**
- Author: Sten Carlsen
- Date: 2014-10-11 17:51:21
- Legacy ID: 4189

**Steps to reproduce:**
1. Fetch version 1.5.1 or 1.6 of Synergy for MAC (tested various versions down to 1.4.10, no luck)
2. open DMG
3. copy Synergy to Applications
4. start Synergy as any other program
5. Complains about universal Access, offers to open Preferences
6. Accept Synergy to be allowed Accessibility
7. restart Synergy
8. Apparently nothing happened, the window about universal Access comes up again as if it was not given

Expected: I expect a setup window

Actual: Nothing,visible
In the LOG in the Console I find this:

11/10/14 18.40.47,581 universalAccessAuthWarn[625]: AccessibilityAPI: pid 49368, is not allowed to access the accessibility API. Path: /Applications/Synergy.app/Contents/MacOS/Synergy
11/10/14 18.40.47,631 com.apple.launchd.peruser.503[274]: (synergy.286384[49368]) Exited with code: 1
11/10/14 18.40.47,672 universalAccessAuthWarn[625]: AccessibilityAPI: pid 49368, is not allowed to access the accessibility API. Path: /Applications/Synergy.app/Contents/MacOS/Synergy

**Versions and operating systems:**

OSX 10.9.5

**Temporary workarounds:**

NONE, so far

**Similar bugs:**
None found

**Additional comments:**

I have 3 MACs, MBP works as expected, iMAC has this fail, Mini Server has the same fail.

Possible differences:
MBP has Parallels, the others have/had Virtualbox

iMAC has used old version 1.4.10 long time ago with perfect success.

Mini has never used Synergy

Can someone advice what I could compare between the one that works and those that don't.

Obviously I need it on those two that don't work.

**Comment by XinyuHou** [comment]
Close as an obsolete issue
