### ISSUE TITLE
Synergy 1.6.0 - Elevate checkbox does not function under Windows 10 Technical Preview

### ISSUE THREAD

**Issue by belthesar** [symless/synergy#4133]
**System Info**
OS: Windows 10 Technical Preview (Build 9841)
Synergy Version: 1.6.0
Mode: Client

**Issue**
Checking the "Elevate" checkbox to be able to interact with secure desktop environments does not function.  

**Expected result** 
Checking the "Elevate" checkbox prompts for elevation and restarts Synergy, or on clicking apply.  

**Steps to reproduce**
Open Synergy, check "Elevate", click Apply.  

Happy to provide any logs that are worthwhile, and also understand that testing against a non-finalized OS is fairly moot.  If this continues to be an issue down the road however, I wanted to make sure it was brought to your attention.  Thanks!

**Comment by jcolesio** [comment]
Experiencing the same issue.

Latest Build of Windows 10 Tech Preview Enterprise running as Server
Xubuntu 14.04 running client

**Comment by XinyuHou** [comment]
Close as an obsolete issue
