### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [symless/synergy#4134]
Some parameters (like "[${doc_dir}/doxygen.cfg](https://github.com/synergy/synergy/blob/7e562273d5e0c032782d6ea5701464efddbfa9b5/CMakeLists.txt#L352)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes.).

**Comment by XinyuHou** [comment]
Close as an obsolete issue

**Comment by elfring** [comment]
Do [any update candidates](https://github.com/symless/synergy/blob/5909df9ee72de9a401421dc1cd306dce97e760a5/CMakeLists.txt#L42 "Check data processing for some strings") need further considerations for safer build scripts?
