### ISSUE TITLE
Support for out-of-source builds

### ISSUE THREAD

**Issue by elfring** [symless/synergy#4135]
The build tool "CMake" supports also [parallel build trees](http://www.cmake.org/Wiki/CMake_FAQ#What_is_an_.22out-of-source.22_build.3F). I find statements like the following inappropriate [for this functionality](http://www.cmake.org/Wiki/CMake_Useful_Variables#Locations).
- [set(EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/bin)](https://github.com/synergy/synergy/blob/7e562273d5e0c032782d6ea5701464efddbfa9b5/CMakeLists.txt#L42)
- [set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/lib)](https://github.com/synergy/synergy/blob/7e562273d5e0c032782d6ea5701464efddbfa9b5/CMakeLists.txt#L43)

**Comment by XinyuHou** [comment]
Close as an obsolete issue
