### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [symless/synergy#4136]
[An extra null pointer check is not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8) like the following.
- [CTCPListenSocket::accept](https://github.com/synergy/synergy/blob/c3aa1963c94c33a517b12f0d004d4a30d95a09af/src/lib/net/TCPListenSocket.cpp#L108)
- [ZeroconfService](https://github.com/synergy/synergy/blob/c3aa1963c94c33a517b12f0d004d4a30d95a09af/src/gui/src/ZeroconfService.cpp#L62)

**Comment by XinyuHou** [comment]
Close as an obsolete issue

**Comment by elfring** [comment]
Are there [a few update candidates left over](https://github.com/symless/synergy/blob/db9181bd11a8dfdbefcb0740333c9052072f33f5/src/lib/ipc/IpcServer.cpp#L68 "Update candidate: Destructor for IpcServer")?
