### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [symless/synergy#4137]
Would you like to add more error handling for return values from functions like the following?
- [pthread_attr_destroy](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_attr_destroy.html) ⇒ [CArchMultithreadPosix::newThread](https://github.com/synergy/synergy/blob/c3aa1963c94c33a517b12f0d004d4a30d95a09af/src/lib/arch/unix/ArchMultithreadPosix.cpp#L340)
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html) ⇒ [CArchMultithreadPosix constructor](https://github.com/synergy/synergy/blob/c3aa1963c94c33a517b12f0d004d4a30d95a09af/src/lib/arch/unix/ArchMultithreadPosix.cpp#L103)

**Comment by XinyuHou** [comment]
Close as an obsolete issue

**Comment by elfring** [comment]
Are there [a few update candidates left over](https://github.com/symless/synergy/blob/a6ff90794fbf9a6d4a0bd7201f1443faabead8fa/src/lib/arch/unix/ArchMultithreadPosix.cpp#L103 "Update candidate: Constructor for ArchMultithreadPosix")?
