### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [symless/synergy#4138]
Would you like to [replace any double quotes](https://github.com/synergy/synergy/blob/4675f29a4c55fba202f037d6a393342a71761327/src/lib/base/Log.h#L21) by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename)?

**Comment by XinyuHou** [comment]
Close as an obsolete issue
