### ISSUE TITLE
Kernel panic on Mac OS X when using external monitor

### ISSUE THREAD

**Issue by wmpay** [symless/synergy#4151]
I'm using synergy with my windows desktop as my server. When the cursor is in my mac screen, and when I have a monitor connected to my mac via hdmi + hdmi adapter, I get a kernel panic after about 10-15 minutes (rough estimate). Here is the log from the crash report:

Anonymous UUID:       996448BC-BE21-1CE1-CD65-81A28E545FB2

Wed Oct 29 13:42:58 2014
panic(cpu 0 caller 0xffffff80042dc43e): Kernel trap at 0xffffff7f85e56103, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000003d10, CR3: 0x000000005cac3037, CR4: 0x00000000001606e0
RAX: 0x0000000000000000, RBX: 0xffffff8026bd6000, RCX: 0xffffff81a50d9000, RDX: 0x000000000b400654
RSP: 0xffffff81f64139c0, RBP: 0xffffff81f6413ab0, RSI: 0x0000000000068074, RDI: 0xffffff8026bd6000
R8:  0x0000000000000000, R9:  0x000000000000005a, R10: 0xffffff81f6413730, R11: 0x0000000000000000
R12: 0xffffff81a50d5000, R13: 0x00000000e0000200, R14: 0x0000000000000000, R15: 0xffffff81a50d9000
RFL: 0x0000000000010246, RIP: 0xffffff7f85e56103, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000003d10, Error code: 0x0000000000000002, Fault CPU: 0x0

Backtrace (CPU 0), Frame : Return Address
0xffffff81f6413650 : 0xffffff8004222f79 
0xffffff81f64136d0 : 0xffffff80042dc43e 
0xffffff81f64138a0 : 0xffffff80042f3976 
0xffffff81f64138c0 : 0xffffff7f85e56103 
0xffffff81f6413ab0 : 0xffffff7f85e44820 
0xffffff81f6413b00 : 0xffffff7f8512fe29 
0xffffff81f6413b50 : 0xffffff7f85133938 
0xffffff81f6413b90 : 0xffffff80046d05fd 
0xffffff81f6413bf0 : 0xffffff80046ce1af 
0xffffff81f6413d40 : 0xffffff80042b6998 
0xffffff81f6413e50 : 0xffffff8004226bc1 
0xffffff81f6413e80 : 0xffffff80042139c5 
0xffffff81f6413ef0 : 0xffffff800421e013 
0xffffff81f6413f70 : 0xffffff80042c9b9d 
0xffffff81f6413fb0 : 0xffffff80042f4196 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOGraphicsFamily(2.4.1)[75D81741-64C1-3941-ADFA-9D6B6C434EE4]@0xffffff7f85120000->0xffffff7f85157fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[2852ACFE-FD28-3C37-9B39-885201BB8D25]@0xffffff7f848bf000
         com.apple.driver.AppleIntelFramebufferAzul(8.2.8)[2DCB5575-0682-3D1E-94CF-ED401897F540]@0xffffff7f85e33000->0xffffff7f85e9afff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[2852ACFE-FD28-3C37-9B39-885201BB8D25]@0xffffff7f848bf000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[045D5D6F-AD1E-36DB-A249-A346E2B48E54]@0xffffff7f850b4000
            dependency: com.apple.iokit.IOAcceleratorFamily2(98.23)[34E4FACD-C1F7-31CF-BF1A-58F965B7AE3E]@0xffffff7f85d43000
            dependency: com.apple.iokit.IOReportFamily(23)[EE246983-FE6F-32F3-A5A0-88F3E3CDBA89]@0xffffff7f850a3000
            dependency: com.apple.AppleGraphicsDeviceControl(3.6.22)[91D61DEC-2946-3790-8134-B808C016C4C9]@0xffffff7f85e2d000
            dependency: com.apple.iokit.IOGraphicsFamily(2.4.1)[75D81741-64C1-3941-ADFA-9D6B6C434EE4]@0xffffff7f85120000

BSD process name corresponding to current thread: WindowServer

Mac OS version:
13F34

Kernel version:
Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64
Kernel UUID: 9477416E-7BCA-3679-AF97-E1EAAD3DD5A0
Kernel slide:     0x0000000004000000
Kernel text base: 0xffffff8004200000
System model name: MacBookPro11,2 (Mac-3CBD00234E554E41)

System uptime in nanoseconds: 504385737347924
last loaded kext at 503845833528067: com.apple.driver.AppleHDAHardwareConfigDriver  2.6.3f4 (addr 0xffffff7f86307000, size 12288)
last unloaded kext at 503914430060192: com.apple.driver.AppleHDAHardwareConfigDriver    2.6.3f4 (addr 0xffffff7f86307000, size 8192)
loaded kexts:
com.apple.driver.AppleMikeyHIDDriver    124
com.apple.filesystems.smbfs 2.0.3
com.apple.filesystems.autofs    3.0
com.apple.driver.AppleUpstreamUserClient    3.5.13
com.apple.driver.AppleGraphicsDevicePolicy  3.6.22
com.apple.driver.AudioAUUC  1.60
com.apple.iokit.IOBluetoothSerialManager    4.2.7f3
com.apple.driver.ApplePlatformEnabler   2.0.9d7
com.apple.driver.AGPM   100.14.34
com.apple.driver.X86PlatformShim    1.0.0
com.apple.driver.AppleHDA   2.6.3f4
com.apple.iokit.IOUserEthernet  1.0.0d1
com.apple.driver.AppleIntelHD5000Graphics   8.2.8
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport 4.2.7f3
com.apple.driver.AppleLPC   1.7.0
com.apple.driver.AppleSMCLMU    2.0.4d1
com.apple.Dont_Steal_Mac_OS_X   7.0.0
com.apple.driver.AppleHWAccess  1
com.apple.driver.AppleThunderboltIP 1.1.2
com.apple.driver.AppleIntelFramebufferAzul  8.2.8
com.apple.driver.AppleCameraInterface   4.26.0
com.apple.driver.AppleBacklight 170.4.11
com.apple.driver.AppleMCCSControl   1.2.5
com.apple.driver.AppleUSBTCButtons  240.2
com.apple.driver.AppleUSBTCKeyboard 240.2
com.apple.driver.AppleUSBCardReader 3.4.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless 1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeLZVN 1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib 1.0.0d1
com.apple.BootCache 35
com.apple.driver.AppleUSBHub    683.4.0
com.apple.driver.XsanFilter 404
com.apple.iokit.IOAHCIBlockStorage  2.6.0
com.apple.driver.AppleAHCIPort  3.0.5
com.apple.driver.AirPort.Brcm4360   842.21.65
com.apple.driver.AppleUSBXHCI   683.4.0
com.apple.driver.AppleSmartBatteryManager   161.0.0
com.apple.driver.AppleRTC   2.0
com.apple.driver.AppleACPIButtons   2.0
com.apple.driver.AppleHPET  1.8
com.apple.driver.AppleSMBIOS    2.1
com.apple.driver.AppleACPIEC    2.0
com.apple.driver.AppleAPIC  1.7
com.apple.nke.applicationfirewall   153
com.apple.security.quarantine   3
com.apple.kext.triggers 1.0
com.apple.iokit.IOSerialFamily  10.0.7
com.apple.driver.DspFuncLib 2.6.3f4
com.apple.vecLib.kext   1.0.0
com.apple.iokit.IOAudioFamily   1.9.7fc2
com.apple.kext.OSvKernDSPLib    1.14
com.apple.iokit.IOSurface   91.1
com.apple.iokit.IOBluetoothHostControllerUSBTransport   4.2.7f3
com.apple.iokit.IOBluetoothFamily   4.2.7f3
com.apple.driver.AppleHDAController 2.6.3f4
com.apple.iokit.IOHDAFamily 2.6.3f4
com.apple.driver.X86PlatformPlugin  1.0.0
com.apple.driver.IOPlatformPluginFamily 5.7.1d6
com.apple.driver.AppleSMC   3.1.8
com.apple.AppleGraphicsDeviceControl    3.6.22
com.apple.iokit.IOAcceleratorFamily2    98.23
com.apple.driver.AppleGraphicsControl   3.6.22
com.apple.driver.AppleBacklightExpert   1.0.4
com.apple.iokit.IONDRVSupport   2.4.1
com.apple.driver.AppleSMBusController   1.0.12d1
com.apple.iokit.IOGraphicsFamily    2.4.1
com.apple.driver.AppleUSBMultitouch 240.10
com.apple.iokit.IOUSBHIDDriver  660.4.0
com.apple.iokit.IOSCSIBlockCommandsDevice   3.6.7
com.apple.iokit.IOUSBMassStorageClass   3.6.0
com.apple.iokit.IOSCSIArchitectureModelFamily   3.6.7
com.apple.driver.AppleUSBMergeNub   650.4.0
com.apple.driver.AppleUSBComposite  656.4.1
com.apple.driver.AppleThunderboltDPInAdapter    3.1.7
com.apple.driver.AppleThunderboltDPAdapterFamily    3.1.7
com.apple.driver.AppleThunderboltPCIDownAdapter 1.4.5
com.apple.iokit.IOUSBUserClient 660.4.2
com.apple.iokit.IOAHCIFamily    2.6.5
com.apple.driver.AppleThunderboltNHI    2.0.1
com.apple.iokit.IOThunderboltFamily 3.3.1
com.apple.iokit.IO80211Family   640.36
com.apple.driver.mDNSOffloadUserClient  1.0.1b5
com.apple.iokit.IONetworkingFamily  3.2
com.apple.iokit.IOUSBFamily 686.4.1
com.apple.driver.AppleEFINVRAM  2.0
com.apple.driver.AppleEFIRuntime    2.0
com.apple.iokit.IOHIDFamily 2.0.0
com.apple.iokit.IOSMBusFamily   1.1
com.apple.security.sandbox  278.11.1
com.apple.kext.AppleMatch   1.0.0d1
com.apple.security.TMSafetyNet  7
com.apple.driver.AppleKeyStore  2
com.apple.driver.DiskImages 371.1
com.apple.iokit.IOStorageFamily 1.9
com.apple.iokit.IOReportFamily  23
com.apple.driver.AppleFDEKeyStore   28.30
com.apple.driver.AppleACPIPlatform  2.0
com.apple.iokit.IOPCIFamily 2.9
com.apple.iokit.IOACPIFamily    1.4
com.apple.kec.pthread   1
com.apple.kec.corecrypto    1.0

System Profile:
Model: MacBookPro11,2, BootROM MBP112.0138.B07, 4 processors, Intel Core i7, 2.2 GHz, 16 GB, SMC 2.18f10
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (6.30.223.154.65)
Bluetooth: Version 4.2.7f3 14616, 3 services, 23 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256F, 251 GB
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

**Comment by XinyuHou** [comment]
Close as an obsolete issue
