### ISSUE TITLE
Ctrl key doesn't work in VMware on client 

### ISSUE THREAD

**Issue by hiepnm** [symless/synergy#4152]
I can not use "ctrl" key on Guest OS of Client's VMWare.

**Comment by SanojR** [comment]
+ 1
Same issue with Ubuntu host and Windows 7 in VmWare Player with synergy 1.6.2
In my case only the CTRL key is not working. Shift/Alt/Capslock... all work fine

**Comment by dragon788** [comment]
Just curious, does Left Ctrl or Right Ctrl make a difference to this? I've encountered times where only the Left Ctrl and Left Alt would work when interacting with VMs, while the right ones would apparently just get lost.

**Comment by lhung** [comment]
@dragon788 in my case, both left ctrl and right ctrl are failing

**Comment by 1kko** [comment]
@dragon788, also my case both left/right ctrl are failing.

Here's my setup.
PC A:
- Ubuntu 14.04
- Synergy Server 1.6.2

PC B: Ubuntu 14.04
- Synergy Client 1.6.2
- VMWare Workstation. 10.0.3 build-1895310
- VMWare Guest OS: Windows 7 SP1 Ultimate 64bit.

Here's my test.

Open "Onscreen Keyboard" application in windows guest os by Win+R > osk.exe
FROM Server's keyboard TO client's vmware GuestOS.

by pressing CTRL key, you get visual representation on screen.
by pressing ALT key, you get visual representation on screen.
Press Ctrl+Alt, Only Ctrl key is pressed.
Press Alt+Ctrl, Both Alt and Ctrl key is pressed.

So, seems single key press is sending over.
however, combination of CTRL+key doesn't seem to work.

I tried both enable/disable clipboard sharing on vmware, but no luck.
Open Notepad,
Alt+F opens File Menu
Alt+Tab switches between open windows.
Alt+Shift+Tab switches between open windows.
Shift+A types capital A letter
CapsLock On & type B types capital B.
Win+E opens Explorer
Ctrl+A NOT selects all.
Ctrl+C & Ctrl+V NOT copy & paste.

Open IE, open up more than 2 tabs,
CTRL+Tab Not change between Tabs.

I can't figure out where it's failling, either vmware's or synergy.

**Comment by 1kko** [comment]
Seems like this is very old issue not solving yet.
https://communities.vmware.com/message/785283#785283

**Comment by circuitbreaker303** [comment]
Yeah, I've got the issue too.  Control key refuses to work within VMware Workstation 11 running a Windows 7 guest on an Ubuntu Linux host. That's the synergy client. The synergy server is also Ubuntu. Running 1.7.3

**Comment by circuitbreaker303** [comment]
Still unsolved. 1.7.3 on Ubuntu 14.04 both server & client, client running vmware workstation 11 w/a windows 7 guest.  control works fine outside the windows 7 guest window.

**Comment by dragon788** [comment]
Has anyone with VMware issues tried remapping the VMware Workstation
hotkeys to use something other than Ctrl, or is that completely hardcoded
as one of the escape keys? I know Ctrl+Shift+Alt are the typical ones I
use, but I thought you could unmap any of them.

**Comment by circuit-breaker** [comment]
Yes, and I have, via the preferences file. Set it to windows key+alt+shift.  The problem is definitely VMware desktop/client applications clearing the keysyms when the window is active, evidenced by running xmodmap while letting the vmware window take/lose focus. I think I might write a patch to wmctrl that causes it to exit true when a specific window becomes active so I can && xmodmap -e "control = Control_L Control_R" to use my ctrl-key modifier in vmware. isn't software great?

**Comment by 1kko** [comment]
@circuit-breaker I would very appreciate if you could share that patch.

**Comment by circuit-breaker** [comment]
@1kko Sorry but I never wrote the patch. I don't use VMware any more because it just ran like garbage for me even with 1 VM using 20% of my physical RAM.  Switched to VirtualBox again (ugh). You could run: sleep 5 && xmodmap -e "control = Control_L Control_R" each time you use your VMware window :) Sorry I couldn't be more helpful.

**Comment by cezaryrk** [comment]
Same problem, wrote small script which checks if modmap was cleared and if so puts the controls back.

```
#!/bin/sh
ERG=`xmodmap | grep -c "Control_L (0x25),  Control_L (0x42),  Control_R (0x69)"`
if [ $ERG -eq 0 ]; then
    xmodmap -e "add control = Control_L Control_R"
fi
```
named it "modmap.sh" maked it executeable and start with:

```
$ watch -n 1 ./modmap.sh
```

Waiting for better solution ...

**Comment by MikeShafer** [comment]
Thanks. Works fine with Ubuntu MATE 16.04 and VM Workstation 12.5.2

**Comment by shkpk** [comment]
I have same issue in synergy 1.10.3-stable
does this patch work on it? How to run this patck?

**Comment by laughterk** [comment]
check this: https://github.com/laughterk/synergy-core
(since encryption was removed after v1.8.8)

**Comment by shkpk** [comment]
> check this: https://github.com/laughterk/synergy-core
> (since encryption was removed after v1.8.8)

your code have compilation issues. Those issues are never seen in official synergy-core repo.

`$ make
[ 87%] Built target arch
[ 87%] Built target common
[ 87%] Built target base
[ 87%] Built target shared
[ 87%] Built target io
[ 87%] Built target mt
[ 87%] Built target net
[ 87%] Built target synergy
[ 87%] Built target server
[ 87%] Built target platform
[ 87%] Built target ipc
[ 87%] Built target client
[ 87%] Built target synergyc
[ 87%] Built target synergys
[ 87%] Built target synergyd
[ 87%] Built target micro
[ 87%] Built target usynergy
[ 87%] Built target syntool
make[2]: *** No rule to make target 'src/test/CMakeFiles/gtest.dir/build'.  Stop.
CMakeFiles/Makefile2:1227: recipe for target 'src/test/CMakeFiles/gtest.dir/all' failed
make[1]: *** [src/test/CMakeFiles/gtest.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by laughterk** [comment]
> > check this: https://github.com/laughterk/synergy-core
> > (since encryption was removed after v1.8.8)
> 
> your code have compilation issues. Those issues are never seen in official synergy-core repo.
> 
> `$ make [ 87%] Built target arch [ 87%] Built target common [ 87%] Built target base [ 87%] Built target shared [ 87%] Built target io [ 87%] Built target mt [ 87%] Built target net [ 87%] Built target synergy [ 87%] Built target server [ 87%] Built target platform [ 87%] Built target ipc [ 87%] Built target client [ 87%] Built target synergyc [ 87%] Built target synergys [ 87%] Built target synergyd [ 87%] Built target micro [ 87%] Built target usynergy [ 87%] Built target syntool make[2]: *** No rule to make target 'src/test/CMakeFiles/gtest.dir/build'. Stop. CMakeFiles/Makefile2:1227: recipe for target 'src/test/CMakeFiles/gtest.dir/all' failed make[1]: *** [src/test/CMakeFiles/gtest.dir/all] Error 2 Makefile:83: recipe for target 'all' failed make: *** [all] Error 2`

This is a v1.8.8 specific problem, before compiling, you have to decompress gmock-1.6.0.zip/gtest-1.6.0.zip in directory 'ext' into sub directory gmock-1.6.0 & gtest-1.6.0 accordingly.

**Comment by Jkveen** [comment]
https://my.vmware.com/en/web/vmware/info/slug/desktop_end_user_computing/vmware_horizon_clients/5_0

Try the above link

**Comment by shkpk** [comment]
> https://my.vmware.com/en/web/vmware/info/slug/desktop_end_user_computing/vmware_horizon_clients/5_0
> 
> Try the above link

Q) how this will give the solution of bug in synergy?

**Comment by urbanslayer** [comment]
I am running the current 1.14.2 version, and this is still a problem.  The modmap.sh script above does work around it, but causes some other issues (makes the keyboard very laggy).

This isn't a problem in Windows.  My Synergy server is running on Linux, and to a Linux client with VMWare Workstation, the control key doesn't work.  To a Windows client (from the same server) with VMWare Workstation running on it, it works fine.

I haven't the above patch considering the version numbers are now so far apart.

**Comment by danmtripp** [comment]
Wow - and here I am...  Necroposting on something started NINE YEARS ago - i.e. around about the same time that Symless said that Wayland was on their radar!  
Still No fix?  For EXACTLY this issue in 2023 ???  

Synergy 1.14.6 : Server = MacOS 12.6 (middle), left client = MacOS 12.6, right client = Linux (Ubuntu 22.04).
(both Macs are MBP M1 devices)

Not VMware workstation, or vSphere or vCenter - my issue is with _**VMware HORIZON.**_

I HATE using VMware Horizon in MacOS (there doesn't seem to be a way to disable full screen - i.e. even a lower resolution will still go exclusive full screen) and - my Linux machine has 2 x 32 QHD monitors - so I prefer to use that when I'm WFH.  Anyway - NO matter what I do - CTRL key (neither left, or right) work in VMware Horizon VDI (Windows 10).  I NEED this for work - using a Terminal Window without CTRL is well night IMPOSSIBLE (note : I can get in with a browser, and CTRL works there - but - there's a HUGE LAG in the web client, enough to make it unusable).

But I'm guessing Symless don't care?  Just like they don't care about Wayland?

**Comment by desymless** [comment]
Hi @danmtripp 

Is there perhaps an option in VMware Horizon to accept unicode input? Enabling this setting might resolve the issue with modifier keys not working in the VM.

**Comment by etsauer** [comment]
Hey all, FYI I've been experiencing this same issue, running the VMWare horizon client on Fedora 38, as a secondary Synergy machine. I've tested out the modmap script fix [mentioned above](https://github.com/symless/synergy-core/issues/4152#issuecomment-278629952), and while this does solve the Ctrl key issue, it also seems to introduce a lot of lag between my keyboard and the screen, so much so that sometime I miss key presses, or get the hoooooooooooooold down affect. Is there any more troubleshooting info I could provide to help resolve this?

**Comment by espoelstra** [comment]
Rather than a script running all the time checking every second, if the issue only occurs on/immediately after the launch of the VMware Desktop/Player/Horizon client you could use a wrapper script that would go in the `vmware-${product}` EXEC call in the `vmware-${product}.desktop` file and have it launch the `vmware-${product}` executable in the background with `&`, sleep 10 seconds to let the VMware product fully load, then run the xmodmap addition, and then foreground the vmware process again.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
