### ISSUE TITLE
Typing [ and ] give 5 and 6 on Mac OS X German keyboard

### ISSUE THREAD

**Issue by Botzman** [symless/synergy#4157]
Server is Windows7 with english keyboard. Client is MacOS 10.9.4 ( english ) having german keyboard (long one with numeric pad). Enable U.S. keyboard layout in both MacOS and in Windows. Start typing in MacOS. Instead of [ and ] you get 5 and 6. Instead { and } you get \* and (.

**Comment by XinyuHou** [comment]
Duplicate of #4280
