### ISSUE TITLE
Synergy conflicts with Netatalk over using Zeroconf/mdnsresponder in Avahi

### ISSUE THREAD

**Issue by STrRedWolf** [symless/synergy#4222]
I'm trying to load in Netatalk 3.0.5 on my Gentoo Linux box, and I'm finding that it needs Avahi (which provides Zeroconf support) compiled without mdnsresponder compatibility.

Synergy requires mdnsresponder compatiblity, and doesn't talk to Avahi natively.  Plus, you can't run Avahi natively and with compatibilty at the same time.

If Synergy can be made to talk to Avahi natively, then it can coexist with Netatalk 3.0.

**Comment by XinyuHou** [comment]
Close as an obsolete issue
