### ISSUE TITLE
Non-standard keycode support

### ISSUE THREAD

**Issue by alaricljs** [symless/synergy#4231]
I use some apparently non-standard keycodes on my keyboard to facilitate macros in both Linux and Windows.

With the keyboard directly connected to either system, I see the keypress as expected (keycode 167 / 0xA7) but Synergy doesn't pass that keycode whether the server is on Windows or Linux.  On Linux I have this mapped to Hyper_L and on Windows it gets interpreted raw by AutoHotKey.

I don't see a reason that Synergy should choose not to pass a keycode that  it  doesn't understand, it should just pass the raw keycode and let the client side worry about it.

**Comment by XinyuHou** [comment]
Close as an obsolete issue

**Comment by alaricljs** [comment]
What change obsoleted this?  Does Synergy now send unrecognized key codes without filtering?
