### ISSUE TITLE
Brew cask repository update

### ISSUE THREAD

**Issue by db** [symless/synergy#4258]
Hi - I love Synergy. It makes is easy for me to use my Mac at my Windows only workplace. Is it possible to have the brew cask repository updated with new Synergy releases? I have to install 1.6.2 by downloading manually at the moment.

**Comment by romanzolotarev** [comment]
@db @nbolton How can I use `brew install` for synergy?

Getting errors:
```
$ brew install synergy
Error: No available formula for synergy 
Searching formulae...
Searching taps...
$ brew cask install synergy
Error: No available Cask for synergy
Error: nothing to install
```

**Comment by hubrix** [comment]
binaries available here
http://synergykm.com/binaries/
can someone help integrate the cask ?
also nightlies here
https://synergy-project.org/nightly

**Comment by JacopKane** [comment]
@hubrix Opened a pull request.
http://github.com/caskroom/homebrew-cask/pull/9762

**Comment by XinyuHou** [comment]
Close as an obsolete issue
