### ISSUE TITLE
Non-existant 'Xbutton2' blocks mouse switch between screens

### ISSUE THREAD

**Issue by srdlgh** [symless/synergy#4268]
Synergy refuses to switch screens when it is told by Windows that the 5th mouse button (also known as 'xbutton2') is down -- even when there is no such button and no direct way to release it. Only some machines are affected (it's really a BIOS issue). Several other Synergy users have reported this as far back as 2004, with still no resolution.  

You could argue the bug is in the BIOS or Windows that reports the button down when it doesn't exist. But given the number of times this has been reported, that it's undocumented (although findable in the sourcecode) and that presumably few people who would want Synergy controlled by this button, Synergy should have a setting that allows us to ignore it (or it should be taken out of the source code by someone more skilled than I).

I have found a workaround for now, though: as part of each system start (or restart), run a very short Autohotkey script (in either native or compiled form) to tell Windows the button has been released, and Windows then passes this updated information on to Synergy.  

The script:

 sendevent {xbutton2 up}
  GetKeystate,keystate,Xbutton2
  msgbox, Xbutton2 keystate is now %keystate%
 exit

The middle two lines are optional -- the merely tell you the script has run successfully.

Autohotkey is freeware, available from most freeware outlets and from Autohotkey.org. It's fully-developed scripting language for user interface and control -- I use it to customize many of my stock programs to work more the way I do. If you're the kind of person who tinkers with software, I highly recommend it. 

This bug is a bit like the famous apocryphal story of the man who moves out of an apartment on meter-reading day -- only to get a bill a month later from the utility for $0.00.  Of course, he initially ignores it. But in the following months, increasingly  hostile bills arrive about his arrears followed by threats of legal action if he doesn't pay.  Finally, he figures it out: he sends in a check for $0.00, and receives in return a letter thanking him for his payment and declaring the matter closed.

**Comment by XinyuHou** [comment]
Close as an obsolete issue
