### ISSUE TITLE
Ubuntu client screen locks when Windows server is active

### ISSUE THREAD

**Issue by magic-mouse** [symless/synergy#4272]
**Steps to reproduce:**

Don't use your slave machine for the duraiton of the time it takes to either lock or start screen saver. While use the master machine.

**Expected:** Slave machine should be "active" or considered active while server is active.

**Actual:** The screensaver activates, making login happen everytime.

**Temporary workarounds:**

Constant login.

Similar bugs:

Not found any

**Additional comments:**

Host is Windows 8.1, Slave is ubuntu 12.04 LTS

**Comment by XinyuHou** [comment]
Duplicate of #5886
