### ISSUE TITLE
Modifier and meta key strokes missed

### ISSUE THREAD

**Issue by d2inco** [symless/synergy#4282]
The problem seems to kick in after my machine's screen saver has kicked on.   It is independent of my synergy client being connected or not.

Synergy Server is Windows 8.1.   

I notice the problem both when I have an RDP session up to another machine, as well as noting that Keepass, running locally, willl (sometimes) have its keystrokes ignored (or intercepted elsewhere).

(pasting the message below from an  email chain, i'll need to tune it up to be a standalone trouble-report)

noting that both applications do some keyboard actions above/beyond a normal app because they intercept keys when they may not have window focus (keepass -- ctrl/alt/A or K, and RDP intercepts the Windows key, when it does have focus instead of the 'host' seeing that key).

Noting that, with keepass disabled on the main host (so just 'regular' apps running) but the RDP into my other box up, that, once this funky-mode kicks in, if I hit windows key whild the RDP has focus, I will get the remote-Start screen in one window, and a local-Start screen in the other window --- so both apps are seeing that Start key being pressed.   Hitting 'Apply' on the Synergy app (on the local desktop), brings this behavior back to normal (ie, only the remote/RDP'd host showign the start screen).

Also, noting that when I do not have an RDP up, and this 'funky mode' kicks in, and I happen to have Keepass enabled, that the ctrl/alt/A may not work.  Also, the Windows-modified sequences may not work (like Windows+Left/Right arrow to tile a window to the left or right).   Again, here, too: Hitting _Apply_ or stop/start on the Synergy window restores normal functionality.

**\* Last comment -- the commonality in these seems to be that the issues kick in after my Screensaver (default windows 8 one with the bouncy balls) kicks in, a delay, and I move mouse to regain control.

--> I just tested this one more time before I send this.  Scenario
- RDP Session is up to my work box
- Hit Windows/Start key -- Start screen shows on, for only, the Remote box (as expected).  I don't see anything from the local box (as expected).
- Hands off for 3 minutes.
- Screen saver kicks in on the local box.  Wait a 20 seconds or so and watch the screen saver.
- Hit Windows/Start key -- Start screen shows up on the left screen (4 monitors here) for the remote session, and also a (red background / local) Start Screen on the middle-monitor for the LOCAL host (should not happen).  Repeatable several times.
  Get it back to normal via:
- Un-Maximize the RDP and hit "STOP\* on the Synergy control window that I started earlier, and hit Start in the RDP window again, and I'm back to normal -- Start Screen _only_ for the Remote Desktop.
- then hit Start on the Synergy control window again, and I'm fully back to normal (with the Start button working as expected, and now i got control of my machien off to the far-left, again).

I think the above might be enough to open a ticket, at this point?   It does seem repeatable here..

**Comment by dsdee** [comment]
I believe this has been fixed with the 1.6.3 release.  I need to keep watching another few days, and then will close if it has been fixed.

**Comment by dsdee** [comment]
Nope.  still broken in 1.6.3.   Seems to be very similar to the 'window doesn't raise / gain focus' problem.... similar, but seems to definitely be only kicking in after the local lockscreen kicks in... (and then out).
