### ISSUE TITLE
Screen switch broken between x64 and x86 on Linux

### ISSUE THREAD

**Issue by mspike** [symless/synergy#4304]
When I try to move up the mouse to the x86 screen the mouse jumps back to the middle of the server.

I have a Linux x64 Server, client is a Linux x86.
I tested and it works fine between two x64 Linux.
Synergy v1.6.2

**Comment by nbolton** [comment]
@the-wes, do you think this might be a bug?

**Comment by XinyuHou** [comment]
Close as an obsolete issue
