### ISSUE TITLE
Hotkey combo alt+shift+~ also binds to alt+shift+h

### ISSUE THREAD

**Issue by MetaDark** [symless/synergy#4314]
This is bizzare; setting a keybinding against alt+shift+~ also binds alt+shift+h to the same command. I have no idea where to start with this bug since I can't seem to reproduce it with any other binding.

**Details:**
Operating System: Arch Linux (Client & Server)
Keyboard Layout: Colemak
Synergy: 1.6.2

**Comment by XinyuHou** [comment]
Close as an obsolete issue
