### ISSUE TITLE
OSX+linux / trackpad gestures

### ISSUE THREAD

**Issue by dobkeratops** [symless/synergy#4316]
I'm curious - is it possible to map OSX trackpad gestures to key-bindings when using an OSX synergy server and a Linux Synergy client.

The use I have in mind is the binding the 3-finger swipes to switch desktops (and possibly up/down to invoke scale etc, but thats' less important), just as they do in mission control by default;

if any linux desktop manager key combination is common enough for this action, it might be a nice default to give people.. it's usually Ctrl-Alt left/right ? Up/down is more ambiguous, since you might want that to be vertical navigation in a desktop grid, or invoking 'scale'

**Comment by stevemcmillen** [comment]
I'd also like to know the answer to this.  Kinda a bummer when you try a gesture and it is just ignored. In my case I'm going from mac to mac.

**Comment by kerrhome** [comment]
I'm in the same boat as Steve, Mac to Mac.  I paid money into the bucket for this feature way back when and I'd really like to see it come to fruition.  Anything we can do to escalate this?

**Comment by wrossmck** [comment]
same as above. Would like to see gestures from Mac-to-Mac. Happy for it to be mac-client-only, tbh.

Currently we get `WARNING: unknown quartz event type: 0x1e` in the logs.

**Comment by intel352** [comment]
Same here, OSX-to-OSX is a fair minimum expectation...

**Comment by fabbr** [comment]
Same here. Not only the " and '  doesn't work none of the trackpad gestures are translated. Those two items are the only ones from making this app AMAZING

**Comment by oshaughnessy** [comment]
This is huge. Looking around, I haven't found any mouse/keyboard sharing apps that support trackpad gestures. Without gestures, I'd lose way too much functionality -- it ruins the idea of using a virtual KVM as an input-sharing solution.

**Comment by fabbr** [comment]
It’s really not an ideal situation. The worst part is that the developers know about the issue and I haven’t found an official statement about it. I really like this app, but I could easily LOVE IT

**Comment by dobkeratops** [comment]
Just revisiting this, I'm still after this functionality for a perfect setup.

I note that 'gnome-shell' does indeed use 'ctrl-alt+up', 'ctrl-alt-down' for desktop switching (it arranges workspaces vertically) , as did most other window-managers i've tried.
The mac also uses ctrl-alt-left, ctrl-alt left.

It would certainly suit all the environments I use for '3-finger drag' to default to dispatching ctrl-alt+(left, right,up,down) keypresses in a manner similar to the '2-finger-drag' issuing quantised mouse wheel events.

I'm sure a few options could be given that would allow people to get something fairly consistent with whatever combination of OS's they're using.

The multitouch desktop switching is a joy to just, it's extremely untuitive.. 1finger=move cursor, 2fingers=scroll window, 3fingers=scroll desktops. All the navigation in one place, without having to move the cursor to panels/switchers, and without having to contort to key combinations.

**Comment by nbolton** [comment]
Duplicates #2905
