### ISSUE TITLE
Linux GUI shows the "Start" button even when server is already running

### ISSUE THREAD

**Issue by phalpern** [symless/synergy#4340]
To reproduce:
 1. Start a Synergy server through the GUI.
 2. Go to Edit|Setting on the menu bar
 3. Change nothing.  Click "Cancel"
 => The "Stop" button changes to "Start".

 4. Click the "Start" button"
 => The Server STOPS.  The button still says "Start"

 5. Click "Start" again.
 => The server restarts.  The button changes back to "Stop"

 6. On the system notification bar (e.g., in Gnome), click on the synergy icon.
 => On the menu that drops down "Start" is enabled and "Stop" is dimmed, even though the server is running.

Reproduced on Synergy 1.6.2, Ubuntu 14.10, Gnome 3.

**Comment by kepi** [comment]
I have same problem on both Linux and Windows.

**Comment by speaker** [comment]
Reproduces on Windows as well 1.7.0

**Comment by XinyuHou** [comment]
Duplicates to #4836
