### ISSUE TITLE
Can't set keyboard layout on client to Hebrew 

### ISSUE THREAD

**Issue by eyalzek** [symless/synergy#4343]
I'm on version 1.6.2, the server is on a Windows 7 machine, client is Xubuntu 14.04.
I have 2 keyboard layouts installed on both machines; English and Hebrew.
I am unable to change the keyboard layout to Hebrew on the client (both machines use L-SHIFT+L-Alt to change the layout). When changing it using the client keyboard, as soon as I type a character on the server's keyboard - it'll reset back to English.

**Comment by XinyuHou** [comment]
Duplicate of #5798
