### ISSUE TITLE
Unicode is printed as question mark on client

### ISSUE THREAD

**Issue by eyalzek** [symless/synergy#4344]
I'm on version 1.6.2, the server is on a Windows 7 machine, client is Xubuntu 14.04.
I have 2 keyboard layouts installed on both machines, English and Hebrew.

When my server's layout is set to Hebrew, typing letters on the client produces nothing but question marks. Numbers and characters seem to work fine.

**Comment by mikhailidim** [comment]
Have the very same issue with Russian keyboard. Windows 7 & Windows 8.1

**Comment by speaker** [comment]
Quick question for both, are both the client and server machines set to the same language and codepage?

**Comment by mikhailidim** [comment]
Hello,
Thank you for asking. Actually  yes, I have.
  Windows 7 & 8 are both unicode-based, so default language for non unicode apps shouldn't matter.  Both system are on English (US) but it doesn't work at all. 
 My normal (in-normal) behavior is:
1. Focus on guest (Windows 8.1)  
   1.1 System changes keyboard to proper layout <RU> 
   1.2 The very first keystroke falls layout back to primary <EN> and type English letter
   1.3 Server system (Windows 7)   keeps primary layout unchanged <EN>
2. Focus on server system (Win7)
  2.1 System changes keyboard layout to <RU>
  2.2 Host works normally and I can enter Russian characters.
  2.3 Guest system (Win8.1) shows primary layout <EN>. Enters '?' while typing
  2.4 Switch on guest system (Win8.) shows proper layout <RU> input chars still '?' 
  2.5 Switch back to host (Win7) fails back layout to primary <EN> input proper chars
  2.6 Keystroke on guest (Win8,1) fails back <RU> layout to <EN>

Hope it sheds some light 

Regards,
Michael M.

**Comment by iliask** [comment]
Same issue with Greek language. I have English (EN) and Greek (EL) languages, same on both machines with Default Language to English (United States) - US.
![en-el](https://cloud.githubusercontent.com/assets/3329123/6635851/e9d8b628-c972-11e4-976c-142834f94952.PNG)

Host Engish (EN)->Guest types English (EN). If I change language on guest (EL), I see the language change on the taskbar but as soon as I press a key, the language changes back to EN and types english.
Host Greek (EL)->Guest types mostly ? with some English characters (e t p a s d f). If I change language on guest (EL), again it changes back to EN as soon as I press a key.

Incentive: If you fix this, a little more donation coming your way. :)

**Comment by pongpon** [comment]
I've the same issue and already solved.

Environment
Server
- Windows 7
- Synergy 1.6.3

Client
- Windows 7 and Windows 8.1
- Synergy 1.6.3

My Solution is

On server change the Language for non-Unicode programs (Control panel > Region and Language > Administrative >Language for non-Unicode programs) 
to the second language (non-english) then restart server.

**Comment by eyalzek** [comment]
Not working for me on a Windows 7 server and Xubuntu 14.04 client (I changed the language on the server from English to Hebrew...).

**Comment by iliask** [comment]
@pongpon Not working for me either. Now when I type, I don't see ? but instead it is not typing anything.

**Comment by mikhailidim** [comment]
Default language configuration on both systems doesn't work for me too.
setup, system restarts neither helps. The only difference:
- Switch keyboard to Russian on host (W7).
- Can't type even ? characters on guest (W8.1)

**Comment by mnag156** [comment]
Have the same problem with Hebrew and Russian. Both systems are Windows 8.1.

**Comment by YellowAfterlife** [comment]
Same issue with Russian keyboard layout here. If the default language for non-unicode applications is set to English, Cyrillic characters produce question-marks "?". Changing it to Russian causes the Cyrillic characters to produce no output at all. Keyboard shortcuts involving letter keys will not work either. At the same time copying-pasting works fine.
Windows 10 32-bit on server, Windows 8.1 32-bit on client.
Synergy Basic 1.7.3 on both ends.

**Comment by YellowAfterlife** [comment]
I've found a very interesting thing with the [current](https://github.com/synergy/synergy/tree/19835b6aaa75f3241f92fc347e4dd7d656f4deb2) version of Synergy: On 64-bit Windows 8.1 client (with 32-bit Windows 10 server) If you go to "Personalization" - "Themes", and click "Save theme", that little popup input allows to switch to non-Latin input *and* the input works. What does it do differently from the rest of the OS? Can this be replicated with settings for other applications?

Having the server run on Ubuntu 15 makes non-English letter input work on the client machines at all times, but symbols either do not produce any output or produce something that they are not meant to (e.g. pressing "1" on Russian keyboard layout produces "!" while that should normally be from "Shift+1").

Makes me wonder how Mouse Without Borders' developers got around this.

**Comment by mikhailidim** [comment]
After year of self-tortures
I have switched to Input Director.
Its far from perfect, windows limited but it do what I want most of the
time.
I do love Synergy, but this layout switch issue kills me.

Regards,
Michel

**Comment by iliask** [comment]
Any update on this issue? This is killing me! Already Michel above had to switch to Input Director because of this issue. I don't want to switch so please fix it!
As I said, if you fix this issue, I will send a small donation your way (already have paid license version).

**A small update:**

On the server (Windows 10 - Synergy 1.8.7) I switch from ENG to ΕΛ (Greek). I can type English/Greek fine on the server.
I move to the client (Windows 10 - Synergy 1.8.7), and any letters I type do nothing.
If I switch the client input from ENG to ΕΛ still, I get nothing when typing letters.
The only keys that work across are: `;-=[]',./{space}{enter}{tab} and of course the shift-alternative (i.e. shift + = gives +).
If I use the actual keyboard on the client, I can type English/Greek letters fine.

**Comment by danislav** [comment]
Guys, are you going to fix this?

**Comment by mikhailidim** [comment]
The issue is here for ages. I've stopped use synergy because of it.

**Comment by CostisB** [comment]
I will probably do the same. Quit synergy....

**Comment by YellowAfterlife** [comment]
There's some irony in fact that I've originally bought Synergy to reduce the number of input devices lying around at the workplace, but two years later it still hadn't had much or any effect on that. I was eventually able to reduce the number of non-embedded (laptop) keyboards to 1 by purchasing a bt keyboard with a device switch, but it's a shame that this remains an issue for so long.

**Comment by w0www** [comment]
Hello, any update of this? I pay a license and i think that this error is important error to fix it.

**Comment by mikhailidim** [comment]
Yeah, but it does not affect US/UK audience. I have moved from synergy to
the alternative solution because of that issue 3 years ago.

**Comment by eyalzek** [comment]
In the meantime I keep getting emails from the synergy team suggesting that I buy synergy 2 :|

**Comment by belst** [comment]
Same issue.

Host: Win 10 Synergy 1.8.8
Client: Archlinux Synergy 1.8.8

copy pasting special characters such as `ßäöü` results in ? on the client (havent tried the other way around)

I cannot type the special characters on the client at all. (no output)

**Comment by mikhailidim** [comment]
Welcome to the club.

On Oct 17, 2017 4:43 AM, "Joshua" <notifications@github.com> wrote:

Same issue.

Host: Win 10 Synergy 1.8.8
Client: Archlinux Synergy 1.8.8

copy pasting special characters such as ßäöü results in ? on the client
(havent tried the other way around)

I cannot type the special characters on the client at all. (no output)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/symless/synergy-core/issues/4344#issuecomment-337161079>,
or mute the thread

**Comment by OronDF343** [comment]
Seriously? This makes Synergy v1 absolutely useless to me! And I can't use Synergy 2 behind a proxy so I don't know if it's fixed there...

**Comment by Nixellion** [comment]
Actually one more fun fact.

If I use Linux as a client (Kubuntu 18.04) - then I can switch languages\layouts without any problems, both on the client and the server. In any order, freely, it changes on the Server and correct letters are sent to the client, no question marks.

But if I use Windows (10) as a Server, then I get question marks whenever I try to use non-latin characters (Cyrillic).

**Comment by mikhailidim** [comment]
Unsubscribed. 
I bought Synergy 1.2 and I have struggled with that issue for years. I kinda had a hope that new and shine 2.x will address the problem, but it's still there. Good luck @nbolton.

**Comment by Nixellion** [comment]
Same. Wish my money back actually.
I ended up just buying a cheap-ish UGreen USB switch, **not** a KVM. Just USB switch. Works well enough.

**Comment by darioxz** [comment]
I bought Synergy 1 some years ago. Today I bought Synergy 2 and I still have the same bug. Can't use it. 

Is there a way to help finding the bug and fixing it?

**Comment by CodeEnamoured** [comment]
For me solved by set both windows to same language layout (ENG)

Persian(first) - English(Second) ---------------> not working

English(first) - English(Second) ---------------> working
Persian(first) - Persian(Second) ---------------> working

Good Luck :)

**Comment by therist** [comment]
06.10.2019 this issue is still not fixed.

**Comment by mikhailidim** [comment]
That's why I don't use it anymore.

**Comment by Nixellion** [comment]
> Persian(first) - English(Second) ---------------> not working
> 
> English(first) - English(Second) ---------------> working
> Persian(first) - Persian(Second) ---------------> working

I think I did mention that I also tried different combinations of layouts and languages and none worked.

However it seems that Barrier also has this same issue, I believe it's a fork of synergy. I wonder where this issues comes from exactly.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
