### ISSUE TITLE
Does not traverse to client on exceptionally wide screens

### ISSUE THREAD

**Issue by tilghman** [symless/synergy#4366]
I have two computers, both with dual monitors positioned side-by-side.  The Synergy client is positioned above the Synergy server screens (2x2 setup).  The left server screen can traverse up to the left client screen, the mouse will traverse between client screens, and the mouse will continue from the bottom of the right client screen to the right server screen.  However, if I attempt to move the mouse up on the right server screen, the mouse does not continue onto the right client screen, but remains stuck at the top of the right server screen.

**Comment by beporter** [comment]
Possibly related to #3744?

**Comment by tilghman** [comment]
I certainly see #3744 on part of mine, but the right server screen does not traverse to the right client screen on _any_ border.  The left server screen's edge traverses to the far left side of the right client screen, so there is plenty of area left that the right server screen ought to traverse to.

**Comment by tilghman** [comment]
This issue appears to be fixed as of version 1.8.3.
