### ISSUE TITLE
Add _XKEYCHECK_H to preprocessor definitions

### ISSUE THREAD

**Issue by JoshMcCullough** [symless/synergy#4388]
After running `hm conf -g1` and then opening the solution in VS2013, I get complaints from every project:

```
Error   3   error C1189: #error :  The C++ Standard Library forbids macroizing keywords. Enable warning C4005 to find the forbidden macro.
```

Adding `_XKEYCHECK_H;` to each project's properties (C/C++ > Preprocessor > Proprocessor Definitions) removes this error. Perhaps this should be added to `/CMakeLists.txt`

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
