### ISSUE TITLE
Linux: When XRandR adds a screen, it is inaccessible

### ISSUE THREAD

**Issue by hexmode** [symless/synergy#4420]
When xrandr adds a screen it is inaccessible because synergy doesn't allow me to use it until I kill and restart the synergy daemon.

**Comment by hexmode** [comment]
(from https://twitter.com/hexmode/status/571044345811496962)

**Comment by nbolton** [comment]
Please let me know your versions of Synergy, OS and xrandr.

**Comment by hexmode** [comment]
$ dpkg -l synergy x11-xserver-utils linux-image-amd64
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name                                      Version                   Architecture              Description
    +++-=========================================-=========================-=========================-=====================================
    ii  linux-image-amd64                         3.16+63                   amd64                     Linux for 64-bit PCs (meta-package)
    ii  synergy                                   1.6.2                     amd64                     Keyboard and mouse sharing utility
    ii  x11-xserver-utils                         7.7+3+b1                  amd64                     X server utilities

    $ xrandr --version
    mah@flynn:~/home-files/dotfiles/emacsxrandr program version       1.4.2
    Server reports RandR version 1.4

    $ uname -a
    Linux flynn 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt4-3 (2015-02-03) x86_64 GNU/Linux

**Comment by nbolton** [comment]
Awesome, thanks!

**Comment by moben** [comment]
This is because the corresponding code in synergy is never compiled because of an error in the  CMakeLists.txt.

See https://github.com/synergy/synergy/pull/4148
Or https://github.com/synergy/synergy/pull/4542 which cleans the  CMakeLists.txt up significantly, but at the moment doesn't set the necessary defines.

Extremely likely to be the same as https://github.com/synergy/synergy/issues/4036 and https://github.com/synergy/synergy/issues/4399

**Comment by pavels** [comment]
Hi
this is probably not fixed
i am using XFCE on Arch and synergy, when both of my monitors initialize, i can use only the main one (external monitor connected to notebook) but only to extents of the second one (notebook monitor, which is smaller)

When i explicitly call xrandr to set the correct setup and than kill synergy ant start it again, all works. Without this, it still works as before.

Linux 4.7.6-1-ARCH
synergyc 1.8.4, protocol version 1.6
xrandr program version       1.5.0
Server reports RandR version 1.5

**Comment by nlyan** [comment]
@pavels at the moment I think we only detect resolution changes of a single monitor.

**Comment by nlyan** [comment]
Related follow up:

https://github.com/symless/synergy/issues/5831
