### ISSUE TITLE
Client crash on Windows 7 when exiting from suspend

### ISSUE THREAD

**Issue by mcatkins** [symless/synergy#4434]
About one time in 5-10, when unsuspending Windows 7, the synergy client crashes, and I get the Windows "do you want to send debug information to Microsoft" message box, which I decline :-).

Synergy Vesion: 1.6.2
Windows version: Version 6.1 (Build 7601: Service Pack 1)

(I _think_ this also happened with the previous version 1.5.1, but couldn't swear to it!)

**Comment by nbolton** [comment]
Is it the GUI that crashes or the service (synergyd) or the client? A screenshot would be helpful.

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
