### ISSUE TITLE
Three finger tap gesture broken on Mac client

### ISSUE THREAD

**Issue by hu6360567** [symless/synergy#4440]
When I tried to have a three finger tap on a word in PDF. It doesn't work.
But three-finger drag is working fine.

**Comment by oxoxoxox** [comment]
Ye Mine is too. RMBP Yosemite 10.10.2, Synergy 1.6.2, three-finger-tap is not working when Synergy start running. No print about three-finger-tap in synergy log. I guess Synergy just ignored the three-finger-tap message.

**Comment by nbolton** [comment]
I'm guessing this happens on Mac client?

**Comment by hu6360567** [comment]
@nbolton Yes, on Mac Client. I have never tried when Mac is server.

**Comment by nbolton** [comment]
@hu6360567 Thanks!

**Comment by XinyuHou** [comment]
Duplicate of #2905
