### ISSUE TITLE
Synergy on OSX terminates when accessibility permission is needed; does not re-open

### ISSUE THREAD

**Issue by the-wes** [symless/synergy#4484]
When a new user launches Synergy for the first time on a Mac, it pops a dialog asking to give Accessibility permission. Synergy terminates at this point to allow the user to enable the required permission. Users are then left to wonder what to do next. Synergy should either re-launch at this point, or remain open and wait for permission in a loop.

**Comment by XinyuHou** [comment]
Close as an obsolete issue
