### ISSUE TITLE
GUI plugin auto update check

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#4529]
Problem: When the GUI starts, it doesn't check to see if the local plugins are out of date, or if there is a new version on the server.

Solution: Make sure plugins are up to date when the GUI starts.

**Comment by speaker** [comment]
Running an old plugin can lead to a number of issues including missing security fixes as well as difficult to debug scenarios. #4650 is one example of a problem that running an old plugin can make difficult to manage.

**Comment by speaker** [comment]
Perhaps it is adequate to just download a new plugin every time a new synergy is installed even w/o the gui?

**Comment by nbolton** [comment]
Yeah, that'll certainly do for now. I just updated the wizard version which should download a new version of the plugin. The downside is that the user has to login again.

**Comment by nlyan** [comment]
Plugins are gone
