### ISSUE TITLE
Plugins should be downloaded over HTTPS connection

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#4556]
Problem: An attack vector exists here, where an attacker could intercept the download request for plugins.

Solution: All plugins should be signed by us, and verified by the program loading the plugin.

**Comment by robchahin** [comment]
You should also force the initial application download over HTTPS - as far as I can tell, there's currently not even an option for an HTTPS download.

**Comment by the-wes** [comment]
Please also take care of the issue with the SSL cert CA not being recognized by default OS trust stores. Browsers get around this by shipping their own, but if we don't do the same, we'll get a lot of errors relating to validating the SSL cert before starting the download. We already get a ton of these for the login, it would be great to fix it for both.

**Comment by nlyan** [comment]
Plugins are gone
