### ISSUE TITLE
Switching keyboard layout doesn't work

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#460]
**Imported issue:**
- Author: junk.and.blured (Google user)
- Date: 2010-05-12 00:00:00
- Legacy ID: 470

> What list of steps will reproduce the problem?  
> Try to switch keyboard layout with alt+shift on client machine -- it  
> doesn't work.   
> 
> What version of operating system, and Synergy+ are you using?  
> Both (client&server): windows 7 x64, synergy+ 1.3.5-rc-Windows-x64  
> 
> What is the expected behaviour, and what happens instead?  
> It's expected that language switch could work on server and client machines  
> both  
> 
> Is there a way of temporarily working around your problem?  
> Yes. It works with these steps:  
> 1) return mouse pointer to server machine  
> 2) tap alt+shift  
> 3) language switched  
> 4) return to client machine screen  
> 5) language switched  

Repeating these actions every time i need to switch language is annoying a  
bit  

> Would you like to solve the problem yourself and submit a patch?  
> Unfortunately not :(

**Comment by quarckster** [comment]
Why it was closed? This bug still here for me in 1.6.3. To change language on client I need to move pointer to server and to change language there. It's very uncomfortable. Please fix it.

**Comment by dotancohen** [comment]
I can confirm that this issue exists in Synergy 1.7.4.

**Comment by Shuky** [comment]
Confirming bug still exists, please re-open

**Comment by Leon53** [comment]
Using synergy 1.7.4, Windows 7, both client and server . Noticed, that switching layouts works normally in apps like Internet Explorer , but not working in apps which using Java, like Android studio or Open Office. But, after I launched Open office and Android studio with elevated privileges, as Administrator - it started working normally also

**Comment by joepreludian** [comment]
On linux clients I realize when using xfce or another lightweight Window manager I got problems. To Solve it I've edited the xorg.conf.d file on keyboard and added the layout. I think it has anything on gnome desktop that overrides the default keyboard layout.

I use Synergy on mac -> linux. My mac is US Layout and Linux, ABNT2.
Try to adapt to Your keyboard settings. If this works it will only work for current session.

    sudo setxkbmap -model abnt2 -layout br -variant abnt2

To put this config to work Forever edit the xorg.conf file and put the following:

    sudo nano /etc/X11/xorg.conf.d/10-evdev.conf

Append the following:

Section “InputClass”
    Identifier “evdev keyboard catchall”
    MatchIsKeyboard “on”
    MatchDevicePath “/dev/input/event*”
    Driver “evdev”
    Option “XkbLayout” “br”
    Option “XkbVariant” “abnt2"
EndSection

It Might Work.

**Comment by XinyuHou** [comment]
Close as an obsolete issue

**Comment by pborbas** [comment]
Maybe it helps to someone. I had this issue between Win10 server, OSX high sierra client with HU / US keyboad layouts on both machines. On client change did not work. It changed the icon on top bar but actual layout remained the servers. I had to move mouse to server, change layout and back to client. The solution was that while on windows I had HU / US, I had to change mac to HU / UK, so looks like the 2 US layouts did not match for some reason.

**Comment by lactarius** [comment]
A little workarround. Very ugly - but should I start praying?

**kb.sh**
```
#!/bin/bash
if $(setxkbmap -query | grep -q us,cz) 
then
  LAYOUT="cz,us";
else
  LAYOUT="us,cz";
fi
setxkbmap "$LAYOUT";
```
"**Install**"
```
sudo cp kb.sh /usr/local/bin/kb
```
Settings => Keyboard => Application Shortcuts => Add:
**/usr/local/bin/kb**
Shortcut:
**Alt + k** (or whatever combo)

Try it - working for me...
