### ISSUE TITLE
Better error when non-TLS connects to TLS

### ISSUE THREAD

**Issue by speaker** [symless/synergy#4600]
When a non-SSL enabled version of 1.7 (Unregistered or Basic) tries to connect to an SSL enabled server, the message is "Connection was refused".

A message such as "SSL support required to connect to this server" or something similar would be much more helpful in identifying the problem.

Workarounds are to upgrade all clients to Pro, or downgrade server to non-SSL enabled version.

**Comment by devurandom** [comment]
I am using 1.10.2 on the client and it appears this feature is still missing. Could you please reopen?

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
