### ISSUE TITLE
Error code -65563 on Yosemite if discoveryd is restarted

### ISSUE THREAD

**Issue by gizmotronic** [symless/synergy#4639]
A bug in OS X Yosemite that's been present since at least 10.10.2 occasionally causes discoveryd to stop responding to DNS lookup requests after waking from sleep. One solution to the problem is to restart discoveryd; but this causes the Synergy server to repeatedly display a dialog with "Error code: -65563". In spite of this, the server continues to work and clients are able to connect and seem to work fine.

It's obviously true that the discoveryd problem is an Apple bug, but this is an unexpected result regardless. It's certainly a nuisance as this makes it difficult to quit Synergy without resorting to a CLI.

**Comment by speaker** [comment]
Looks like this might be related to #4303

**Comment by gizmotronic** [comment]
Apple has since abandoned discoveryd, reverting to MDNSResponder in 10.10 and 10.11. This issue is moot.
