### ISSUE TITLE
Key repeat fails intermittently on Linux client

### ISSUE THREAD

**Issue by gclayburg** [symless/synergy#4658]
Server: synergy 1.6.2 on linux
Client: synergy 1.6.2 on linux

To reproduce
1. open console window on linux client 
2. type "ls -l" in the console window.  This works fine.
3. use up arrow to browse command history.  This works fine.
4. use ctrl-b emacs key binding to move cursor backward one character.  This works fine.
5. hold down ctrl and "b".  This will sometimes insert a "b" character on the command line.  When it does this the command line looks like this:
$ ls -bl

Notice, the first ctrl-b is sent correctly to the command window, but the second one (and first repeating one) is sent as a "b" character without the ctrl modifier.  If you continue to hold down ctrl and the "b" key, the correct and repeating ctrl-b keystrokes are sent to the command window.  Only one "b" character is inserted in the command line.

The same thing occurs if you press ctrl-f to move the cursor forward.  The issue does not occur if you press and hold down the right or left arrow keys.

This is quite annoying since the command line is changed just by navigating the cursor.  This seems to happen about once every 3 or 4 times I hold down ctrl-b and it occurs in any application that uses repeating keystrokes with a modifier.  When it fails like this, it always inserts only one "b" character and it is always in the same relative position.  This issue does not occur on the synergy 1.6.2 windows client.

**Comment by gclayburg** [comment]
Has anyone else seen this issue?

**Comment by speaker** [comment]
@gclayburg , I have been unable to reproduce this behavior on the 1.7.4 (nightly), with an ubuntu 14.04 server, and Fedora 21 client. Have you tried with any of the 1.7 builds?

**Comment by gclayburg** [comment]
@speaker   Thanks for checking.  I just upgraded to the last stable version 1.7.3 on both the client and server.  The issue still exists for me.  I also have tried multiple applications that need keyboard input.  They all have the same problem with key repeat.

If it matters, the server is running CentOS 6.6 and the client is Linux mint 17 with cinnamon

**Comment by gclayburg** [comment]
I just discovered another important part about this issue.  On my linux mint desktop that has this issue with synergy, I have mapped the caps lock key to ctrl.  This allows me to press "caps lock-f" on the linux mint keyboard to navigate command history in a console window, for example.  When I use the normal keyboard on the linux mint desktop, I can use either "caps lock-f" or "ctrl-f" without any issue.  

The issue only arises when synergy is brought into the mix and I try to use "caps lock-f" from the keyboard attached to the synergy server.  If I instead press "ctrl-f" on this keyboard, there is no issue.  So it appears that there is some sort of race condition when caps lock is mapped to ctrl when synergy is used.

**Comment by gclayburg** [comment]
FYI - I just upgraded to the latest version 1.7.4 stable release on both client and server.  This issue still exists when using synergy and the setting "Make Caps Lock an additional Ctrl" on the linux mint client.

**Comment by gclayburg** [comment]
Still broken in 1.8.5-stable

**Comment by Unknow0** [comment]
Hi,

i had a similar issues.
The server on linux some time fail to detect key repeat.
I did a fix that seem to works for me you can try it with patch #5735

Regards.

**Comment by gclayburg** [comment]
oh cool. maybe this will help.  I'll see if I can dust off my cpp skills and figure out how to build this thing and give it a whirl.

**Comment by XinyuHou** [comment]
@gclayburg 
Please test this nightly which includes Unknow0's pr fixes.
http://symless.com/nightly?filter=linux-key-repeat-rc2-03ec531

**Comment by gclayburg** [comment]
Thanks for looking at this, Jerry.  I'll try it out today.

**Comment by gclayburg** [comment]
Ok, I am now running this version on both the client and server.  Unfortunately the same issue remains

**Comment by gclayburg** [comment]
Update - this same issue occurs when the server is Ubuntu 16.04 and the client is CentOS 6.6.

**Comment by gclayburg** [comment]
So  I see this issue is closed.  Has there been progress on this issue?

**Comment by nbolton** [comment]
Are you still seeing this issue in 1.9?

**Comment by gclayburg** [comment]
It looks like I am running 1.8.6.  I can test out 1.9 and see what happens.

**Comment by gclayburg** [comment]
Ok, the new (to me) version 1.9 has new library dependencies so maybe updating my system and the synergy client will solve it for me.  Fingers crossed!

**Comment by LeadManPL** [comment]
@nbolton Hi Nick, I just got 967 (over nine hundred) emails about closed issues in synergy-core . What the hell is happening?

**Comment by gclayburg** [comment]
OK, once again I find myself running into trouble installing synergy.  It seems like each time I try to upgrade the software something odd pops up.  This time, it complains of missing dependencies:

```
$ sudo rpm -Uvh synergy-1.9.1-322.stable.2a0225c1.el7.centos.x86_64.rpm
[sudo] password for gclaybur: 
error: Failed dependencies:
	libQt5Core.so.5()(64bit) is needed by synergy-1.9.1-322.stable.2a0225c1.el7.centos.x86_64
	libQt5Core.so.5(Qt_5)(64bit) is needed by synergy-1.9.1-322.stable.2a0225c1.el7.centos.x86_64
	libQt5Core.so.5(Qt_5.6)(64bit) is needed by synergy-1.9.1-322.stable.2a0225c1.el7.centos.x86_64
	libQt5Gui.so.5()(64bit) is needed by synergy-1.9.1-322.stable.2a0225c1.el7.centos.x86_64
	libQt5Gui.so.5(Qt_5)(64bit) is needed by synergy-1.9.1-322.stable.2a0225c1.el7.centos.x86_64
	libQt5Network.so.5()(64bit) is needed by synergy-1.9.1-322.stable.2a0225c1.el7.centos.x86_64
	libQt5Network.so.5(Qt_5)(64bit) is needed by synergy-1.9.1-322.stable.2a0225c1.el7.centos.x86_64
	libQt5Widgets.so.5()(64bit) is needed by synergy-1.9.1-322.stable.2a0225c1.el7.centos.x86_64
	libQt5Widgets.so.5(Qt_5)(64bit) is needed by synergy-1.9.1-322.stable.2a0225c1.el7.centos.x86_64
	libc.so.6(GLIBC_2.14)(64bit) is needed by synergy-1.9.1-322.stable.2a0225c1.el7.centos.x86_64
	libcrypto.so.10(OPENSSL_1.0.2)(64bit) is needed by synergy-1.9.1-322.stable.2a0225c1.el7.centos.x86_64

```

This system happens to be running centos 6, which is old but it was mostly working, aside from the key repeat issue.

It would be ideal if these synergy installation dependencies were documented.  I.e., what linux distributions do you support?  What version of glibc does this upgrade require? openssl? libqt?   Maybe I missed the installation documentation?  If so, should it be more obvious at install time?
It might be possible to get these installed and go through hoops setting up LD_LIBRARY_PATH and such, but at this time I'm just not looking for another weekend project.

I guess what I'm saying is that the install experience really does matter.

**Comment by nbolton** [comment]
> @nbolton Hi Nick, I just got 967 (over nine hundred) emails about closed issues in synergy-core . What the hell is happening?

Wow, that's not good. That could be the GitHub automated stale issue close workflow. Sorry about that.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
