### ISSUE TITLE
Screen saver security constantly disabled

### ISSUE THREAD

**Issue by dsm1212** [symless/synergy#4666]
I've got some security software constantly complaining that ScreenSaverIsSecure is not enabled. I keep enabling it and it gets turned off. I just determined and see in the synergy source code that synergy is changing this registry setting while it is running. I see the code is also disabling the screen saver. Disabling my password seems like a risky thing to do security wise without even warning me. Also, I don't understand why synergy needs to change this setting if it is already disabling the screen saver. Please find a way to avoid having to disable the security on my laptop.

**Comment by dsm1212** [comment]
I no longer work for IBM (whose security crud they force me to run even at home was complaining about this). So frankly you can drop this if you want as far as I'm concerned. It's not impacting me any more.

**Comment by XinyuHou** [comment]
Duplicate of #4116
