### ISSUE TITLE
check if plugin already exists (and is the correct file) before downloading

### ISSUE THREAD

**Issue by the-wes** [symless/synergy#4673]
Problem: If I run through the wizard a second time, it downloads the plugin again.

Solution: Check if the plugin already exists, and verify that it's the correct file. This could be done with a checksum or hash check. This way we can work around the problem of being unable to download the plugin, by downloading it manually and placing it in the plugins folder, and the wizard can complete all the other steps.

**Comment by speaker** [comment]
Presently there is only one plugin in use and in 1.7.4 it will no longer be delivered by download. Keping this around in case we address the issues surrounding this more completely in the future.

**Comment by nlyan** [comment]
Plugins are gone
