### ISSUE TITLE
client occasionally stops

### ISSUE THREAD

**Issue by TinLe** [symless/synergy#4685]
I am using Synergy v1.7.2 on both Linux and OSX
Linux RHEL 6.4 (desktop server - keyboard and mouse)
OSX 10.10.3 (macbook client - use keyboards and mouse from Linux desktop)

I've tried using both WIFI and cable (via Thunderbolt to ethernet dongle).   Every so often, a few times per hour, Synergy on the Mac/OSX will stop.   Clicking on icon shows that it is in "stop" state.  Clicking on "start" gets it going again.   This is very annoying.  (Only happens on OSX/client side).

The lag has improved in v1.7.2, however, with WIFI, I still seeing the pauses and lags, just not as bad.   This is why I still have and prefer using the Thunderbolt dongle.

**Comment by ayerram** [comment]
I still see this happening on my Ubuntu client in version 1.7.3

**Comment by speaker** [comment]
@TinLe @ayerram ,

A number of issues that could cause this behavior have been addressed in 1.7.4. The Nightly builds for master can be found using: http://synergy-project.org/nightly?filter=master

If these do not address this issue, would you please turn on debug logging and supply both server and client logs via gisy? https://gist.github.com/

**Comment by TinLe** [comment]
@speaker 

There is no date/time stamps for the nightly build.   Am I correct in assuming that the top most is the newest?

Before I go off and test it, want to make sure I got the correct version.

**Comment by speaker** [comment]
@TinLe yes, the build are listed in chronological build order, so although on very rare occasions an older build ends up above, the ones on top are either newest or 2nd newest.

**Comment by TinLe** [comment]
This bug seem to be fixed in v1.7.6.   Can be closed
