### ISSUE TITLE
Mac server not sending keystrokes to Windows client

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#47]
**Imported issue:**
- Author: Issue Importer
- Date: 2009-05-14 00:00:00
- Legacy ID: 56
- Version: 1.4.17

Note: Problem present in Lion as well.  

**What steps will reproduce the problem?**  
1. Start server on Mac OS X  
2. Start client Win XP  
3. Move mouse to client  
4. Start a text editor  
5. Type something  

Expected: Characters appear on Win XP client.  
Actual: Characters appear on Mac OS X server.  

**What version of the product are you using? On what operating system?**  
trunk as of May 13 2009 on OS 10.5 and 1.3.3 binary download from Apr 09.  

**Please provide any additional information below.**  
If I run the 1.3.1 server and the 1.3.3 win client keyboard support works.

**Comment by gerrywastaken** [comment]
Obsolete? Hmmmm... I have this issue with version 1.6.2

**Comment by Swaagie** [comment]
Can confirm that closing Chrome worked for me as well with a dual OSX setup with both running 1.6.3

**Comment by moyuki** [comment]
Finally figured out what was causing this behavior in my case.  Keychain Access had prompted me to enter a password which I had cancelled out of.  For some reason, this caused the keystrokes to stop reaching my synergy client even after the Keychain prompt had been dismissed.  After eventually entering in my keychain password, the keystrokes started getting sent to my client again.

From the comments, it sounds like this has something to do with how OS X handles password prompts.

**Comment by cburyta** [comment]
For me this has still happened as of the time of this comment. The fix ended up being the System Preferences flow suggested by @andrewculver! (and it's important to close system preferences out totally after each change, otherwise it won't fix the issue.)

**Comment by nipunarora** [comment]
I'm having this same issue with version 1.7.2 with a mac server and ubuntu client.

**Comment by barcher** [comment]
Can confirm this is happening on synergy-adam-sandbox-3191347-MacOSX1010-x86_64.dmg with manually configured IP address on client.

**Comment by krisdante** [comment]
It worked for me always and now it is not. Restarting anything is not helping at all.
Some of you are posting that arrows works but not letters. For me nothing works.

Is this really random?

**Comment by pho3nixf1re** [comment]
Closing Chrome and all background Chrome apps on the server fixed this for me as well. Mac server -> Windows client.

**Comment by CeramicGod** [comment]
I can confirm that this is Chrome related.   Closing Chrome restores keyboard functionality 100% of the time.

**Comment by flexlee** [comment]
Closing chrome on my mac server solved the problem. I use Windows client. Glad to find this thread. Have been struggling with this for months now.

**Comment by deepseven** [comment]
Indeed, closing Chrome (or rather Chromium, as the case may be) fixed it for me too (Ubuntu server 1.4.17, Windows client 1.5.0).

**Comment by tremby** [comment]
This does not fix the issue for me. Is there anything I need to do aside from closing Chrome on the Mac server? Using Synergy 1.7.4 on both server and client.

**Comment by SynVisions** [comment]
Closing Chrome on the OS X server fixed the issue for me. Strange.

**Comment by the-wes** [comment]
For everyone who closes Chrome and still have the problem: you may be affected by the Secure Keyboard Entry bug.

Open Terminal
Click the Terminal menu
Click Secure Keyboard Entry
Click the Terminal menu a second time
If Secure Keyboard Entry is now checked, click it again to uncheck it, then quit Terminal
If it's not checked, click Quit Terminal

The point is to turn the option on and then off again, if it wasn't already on. There's a bug in OSX which causes it to act as if it's enabled when it isn't, and there are various ways it can be set on by other software like SecureAnywhere.

**Comment by mrichmon** [comment]
On OS X 10.11 it appears that the issue with Chrome blocking keystrokes being sent to clients is triggered by Safari.

I noticed the following sequence will trigger the issue:
* Launch Chrome on OS X (running synergy server)
* Move mouse to Linux synergy client (CentOS 7). No problem with keystrokes.
* Move mouse back to OS X.
* Launch Safari v9.0.1
* Move mouse to Linux synergy client. No keystrokes are delivered to client.
* Quit Chrome on OS X.
* Move mouse to Linux synergy client. Keystrokes are delivered to client.

I've confirmed this sequence a couple of times. Not sure if this is just happening on my system.

**Comment by ylluminate** [comment]
Testing 1.7.6rc1 and I cannot, for the life of me, get control-a, control-c, control-x, etc. to activate from my Mac OS X server on  a Windows virtual machine on my Linux client running Synergy 1.7.6rc1.  This is happening in every app in a virtual machine as far as I can tell.

**Comment by allanjackson** [comment]
For me this problem occurs after I log into my LastPass extension in Chrome on the server. Quitting chrome on the server restores the keyboard on the client.

**Comment by djneely** [comment]
The terminal 'Secure Keyboard Entry' toggling is what sorted the issue on my machines.

**Comment by stormsilver** [comment]
Yep, LastPass is causing this problem for me.

* Mac OS X 10.11.2 server
* Win 10 client
* As soon as I log into the LastPass extension on Safari 9.0.2 _and open the LastPass vault_, no more keystrokes are delivered. Quitting Safari re-enables them.
* The Secure Keyboard Entry option did not have any effect for me.

**Comment by jsprad** [comment]
Another data point -- I'm having the same problem with LastPass. OS X 10.10.2 server, Ubuntu 14.04 client.

The act of logging in to the LastPass extension (on Chrome 47.0.2526.111) is what triggers it for me. If I log in, keys stop being sent. Quitting Chrome fixes it. I can reopen Chrome -- and still be logged in to LastPass -- and keys will be sent again. So at least there's a workaround for me.

Also tried the Secure Keyboard Entry option, but that didn't help.

**Comment by ggentzke** [comment]
This was an infuriating issue for me today but after [finally] getting to the end of this thread I found @jsprad's comment to solve the mystery.  I tried various solutions with Privacy settings, closing apps, etc.  Server running on OS X 10.10.5, client on Windows 7 Enterprise.

*Only required action: Sign out of the LastPass Chrome extension.*  Then I could use my keyboard again on the Windows client.

I hope this helps!

**Comment by ggentzke** [comment]
FWIW the latest updates to LastPass seem to have exacerbated the issue.  I now have to not only sign out of LastPass but also kill chrome entirely to regain the ability to type in the Windows client.

**Comment by allanjackson** [comment]
@ggentzke You don't actually have to sign out of LastPass. Set LastPass to not log you out until your browser has been closed for at least 1 minute. Then do this:
1. Sign into LastPass.
2. Close Chrome.
3. Reopen Chrome within a minute.

At this point you will be logged into LastPass and still able to use your keyboard on the client. Super annoying, but it works.

**Comment by ggentzke** [comment]
Here's the support ticket I filed with LastPass: https://lastpass.com/my.php?token=61ET5BWY1878
They also left this request:

> Please encourage other impacted users to contact us about the issue as well so that we can gauge customer impact.

Thanks for the tip, @allanjackson. I'll try that out.

**Comment by alexjhart** [comment]
Looks like the prebuild Lastpass made available a couple days ago resolved this. Are you guys seeing that as well if you uninstall the stable version and replace with https://lastpass.com/dlpre?

**Comment by allanjackson** [comment]
The latest version of LastPass (not the prebuild, just regular) seems to have fixed this issue. While the LastPass login dialog is actually displaying, the keyboard will not work on the client (which makes sense because of the secure keystroke code), but as soon as you finish logging in, the keyboard works again on the client.

I'm thinking this bug can be closed out.

**Comment by legonigel** [comment]
I didn't see this open issue before, but I commenter [here](https://github.com/symless/synergy/issues/5203#issuecomment-201919291) about the lastpass/secure input issue. I also found a script to check if secure input is enabled [here](https://github.com/symless/synergy/issues/5203#issuecomment-201964619). 

Just because the bug in LastPass is fixed, is not really a good reason to close this issue. I think the best solution to this is for Syngery got check occasionally if `IsSecureEventInputEnabled` and if so change the synergy icon to notify the user, so that if other apps use secure input syngery can let the user know that it won't be able to receive any input. 

@allanjackson I would like to add, from my research that the issue with LastPass keeping secure input is not consistent. Simply logging into LastPass will not always trigger the issue. There is a specific sequence of keyboard and mouse clicks that causes the issue to appear. It very likely has been fixed, but there might still be edge cases that have not yet been resolved. It is also possible some users are running old versions of LastPass.

**Comment by doublerebel** [comment]
Mac server OSX 10.11.3, Linux client Ubuntu 15.10.
Had this problem with 1.6.2 and then I upgraded to current 1.7.6.  Both unregistered and registered.

I tried the secure keyboard input toggle in Terminal and that had no effect.

Closing Chrome on the Mac server fixed the issue.  Reopening Chrome does not immediately cause the issue, can't tell what the trigger is.  I do not have LastPass installed on the Mac.  I do have Dashlane installed, if that matters?

Chrome is Version 49.0.2623.112 (64-bit)

I've been using Synergy for years, in this same configuration, and the first time this happened to me was yesterday (?!).  Thanks to all who reported.

**Comment by badloop** [comment]
I'm seeing this same activity still.  Windows server, any client
My steps to reproduce:
1) Open terminal services window on windows, open notepad
2) Move mouse cursor to another computer
3) Begin typing... keyboard is sent to terminal services window on the windows server, not the machine that is active. 

I've tried launching terminal services (RDP) connections from the clients and this bug is not reproducible using that methodology.

Let me know if any more info is needed.

**Comment by foodini** [comment]
I might as well chime in. I'm seeing this issue with an OSX 10.11.1 server running version 10.11 of Synergy. My client is an OSX 10.10.2 machine running version 10.10 of Synergy. Both machines are macbook pros.

I hadn't seen anything that suggested that I couldn't run differing versions of the software. I had installed on the server first, but couldn't put 10.11 on the client because it's behind by an OSX release.

**Comment by XinyuHou** [comment]
Hi guys, can you test this nightly for Mac? It's valid for Mac 10.9 and above.
http://symless.com/nightly?filter=synergy-issue5592-ctrl-up-key-rc1-e8145aa-MacOSX-x86_64.dmg

**Comment by XinyuHou** [comment]
@badloop @doublerebel @allanjackson @ggentzke @jsprad @stormsilver 

Hi guys, can you test this nightly for Mac? It's valid for Mac 10.9 and above.
http://symless.com/nightly?filter=synergy-issue5592-ctrl-up-key-rc1-e8145aa-MacOSX-x86_64.dmg

**Comment by doublerebel** [comment]
@XinyuHou I haven't seen that bug again since the report, and I have been using Synergy with the same devices.  However, I am on new versions of each OS. Better to find a reviewer who is still experiencing the issue.  Best of luck!

**Comment by XinyuHou** [comment]
@doublerebel 
Thanks for the feedback. Some people say the lastst version of LastPass plugin seems to fix the problem as well.

**Comment by XinyuHou** [comment]
Hi guys,

Could you try out this nightly?
http://symless.com/nightly?filter=v1.8.6-rc2-a49de58

**Comment by Gus1977** [comment]
+1 on the lastpass thing... have Windows client / Mac server, tried various diagnostics from above and landed on "Close Chrome and restart" and *poof*, fixed. I do have lastpass installed in chrome as well.

**Comment by XinyuHou** [comment]
@Gus1977 
Could you try out this nightly?
http://symless.com/nightly?filter=v1.8.6-rc2-a49de58

**Comment by Gus1977** [comment]
I’ll try?

**Comment by XinyuHou** [comment]
@Gus1977 
Yes, please.

**Comment by 1player** [comment]
@XinyuHou Same problem, tried 1.8.6-stable and bug isn't fixed. It happens only when on my Mac server iTerm is focused and I try to write something on the Windows client. Keystrokes directed to the client affect iTerm on the server.

Changing the focus to another window on the server reenables the keyboard on the client.

**Comment by karnag3** [comment]
Any update here?  I seem to be having the same issue with keyboard not being passed.  Also a lastpass user, however, not able to replicate functionality on lastpass logoff.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it. Please let me know if this is still an issue and I'll reopen it.
