### ISSUE TITLE
Stop button resets to Start when settings dialog canceled

### ISSUE THREAD

**Issue by ColinCreamer** [symless/synergy#4836]
Sometimes the label for the "Start" / "Stop" service toggle button gets out of sync with the action it is going to preform.
![image](https://cloud.githubusercontent.com/assets/2904388/8435660/9907d57c-1f20-11e5-8429-426fef840080.png)

I noticed this would happen every so often while I troubleshooting the clipboard bug (Issue 4735).

I started testing various things to see what was causing the button to say the wrong label.
Turns out to be the Settings Dialog Window. If you click 'Cancel' in the settings dialog, the toggle button's label gets reset to read 'Start', even though the service is still running.

![image](https://cloud.githubusercontent.com/assets/2904388/8436484/a954fd46-1f26-11e5-8b7d-998d2bb8c0ef.png)

Clicking the what now says 'Start' btn, will still stop the running service. It's just the label is now incorrect. Clicking 'Apply' or stopping and starting the service will update the button label back to the correct text.

Synergy Version: 1.7.4
Tested OS: win7 & win8.1
Tested Modes: Both Client and Server

**Comment by alexwhitman** [comment]
Related to #4955

**Comment by GollyRojer** [comment]
Tested on client.  Stop button remains unchanged after Edit|Settings|Cancel.

Synergy Version: 1.8.2-rc1-12e0120
Tested OS: win10

**Comment by TxRxFx** [comment]
Tested in win10 client, Stop button remains unchanged 

Synergy Version: 1.8.2-rc1-12e0120

**Comment by LeadManPL** [comment]
Status of test: SUCCESS (Button remains "Stop")

Server:
Linux 4.4.0-33-generic #52-Ubuntu SMP Fri Jul 22 19:16:44 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
synergy-v1.8.2-rc1-12e0120-Linux-x86_64.deb

Client:
Windows 7 Professional SP 1
synergy-v1.8.2-rc1-12e0120-Windows-x64

**Comment by cmerlo441** [comment]
1.8.2, Mac OS X 10.11.6, can't reproduce the error.
