### ISSUE TITLE
Client mouse move affects app on Mac server

### ISSUE THREAD

**Issue by discentem** [symless/synergy#4849]
(affects web page elements)

Server: Yosemite 10.10.3, Synergy 1.7.4
Client: Windows 7, Synergy 1.7.4

**Comment by b419kid** [comment]
More detail: When my mouse moves to the client computer and I click on a window, the server machine window that was just active stays active.

**Comment by nbolton** [comment]
> Why was this closed? Was it fixed?

Sorry, no this was not fixed.

This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
