### ISSUE TITLE
SSL does not automatically reconnect on error

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#4857]
1. Turn your back
2. Connection is lost
3. Check log, see: ssl error occurred (system call failure)
4. No attempt to reconnect is made

```
ERROR: ssl error occurred (system call failure)
```

**Comment by Cpuroast** [comment]
I'm still seeing this on 2edcfe9 using:
Server: synergy-v1.7.4-stable-2edcfe9-Windows-x64.msi
Client: synergy-v1.7.4-stable-2edcfe9-MacOSX1010-x86_64.dmg

**Comment by XinyuHou** [comment]
@Cpuroast
> [2015-07-28T09:11:59] ERROR: ssl error occurred (system call failure) 
I assume this is from your client side?

**Comment by Cpuroast** [comment]
Yes, on the OSX Client

**Comment by XinyuHou** [comment]
@Cpuroast 
Did you rerun the wizard to get latest plugin?

**Comment by Cpuroast** [comment]
I did on server and client.
I've been following the nightlies so I have run the wizard several times due to the plugin changes in recent commits.

**Comment by XinyuHou** [comment]
@Cpuroast 
Do you mean you need to click start on client side and don't have to do anything on server side?

Is you Mac a laptop? If so. do you bring it home with you?

**Comment by Cpuroast** [comment]
>Do you mean you need to click start on client side and don't have to do anything on server side?
That is indeed the case.
>Is you Mac a laptop? If so. do you bring it home with you?
It's not a laptop, it's an iMac it stays permanently connected to a wired Ethernet connection.

**Comment by XinyuHou** [comment]
@Cpuroast 
Thanks for the info. I suspect that is caused by a crash.

Could you send us the whole logging from Synergy and the system log from console?

**Comment by nbolton** [comment]
We're going to implement a workaround enhancement (#4901) instead of fixing this bug, since its very hard to reproduce reliably and sounds like it might take a while to fix.

**Comment by nbolton** [comment]
Related: https://github.com/synergy/synergy/issues/4558

**Comment by nbolton** [comment]
"100% reproducible on my end by killing synergys." @the-wes

**Comment by Aronax666** [comment]
Hi guys, what is the status of this issue?

For me "ERROR: ssl error occurred (system call failure)" is 100% reproducible.

Setup: Mac laptop OSX 10.10 server with Linux box Client.
1) Connect successfully over SSL/TLS.
2) Lock screen (CMD+Shift+Eject)
3) wait until battery saving mode kicks in (few minutes)

Upon awaking mac again and logging in, client never recovers and reconnects.
It's very disrupting to daily work.

**Comment by SvenRieke** [comment]
Hi,
this problem is getting very annoying here on my setup, it happens almost every 10 minutes here.
I see this error:
```
    ERROR: ssl error occurred (system call failure)
    ERROR: eof violates ssl protocol
    INFO: stopping synergy desktop process
    INFO: process exited normally
```
In my setup I have the server on LinuxMint and two clients, a LinuxMint next to the server and then a Windows 7.
Especially, the client on the LinuxMint is getting disconnected all the time (maybe because he's in the middle).
I tried also using non-SSL, but its the same.
Downgrading back to 1.7.4 ... the same.
BTW, copy&paste between the three doesn't work neither, between the two LinuxMint sometimes, for the Windows client never.

**Comment by dunhamsteve** [comment]
I get this consistently in my client (OSX) the released version of 1.7.5 whenever I press "stop" on the server side. When I press "start" again on the server (OSX), the client does not reconnect until I do a subsequent stop/start on the client.

    [2015-12-08T09:02:13] ERROR: ssl error occurred (system call failure)
    [2015-12-08T09:02:13] ERROR: eof violates ssl protocol
   (no further log messages until I kill the client)

Unfortunately, I regularly have to restart the server to deal with the mouse acceleration issue.

**Comment by SvenRieke** [comment]
I'm using 1.8.0-beta-4ff3cdd now, and it is still disconnectinng all the time.

In my current setup I use two LinuxMint 17.3, one in 32-bit, the other in 64-bit.

Connection gets lost very often (while writting this entry 2 times), sometimes
* without any error message at all in any of the both
* ```WARNING: can't leave screen``` on the server
* ```
ERROR: ssl error occurred (system call failure)
ERROR: eof violates ssl protocol
``` either on the client or the server

Moreover, the icons status in the desktop is always *off*, as the applets menu as well, while the button in the opened dialogue has the right state.

Both machines are plugged into the same switch, so it shouldn't be a network error.

**Comment by rbrenton** [comment]
I'm reproducing this 20+ times a day, along with a clipboard triggered bug causing synergys to die.  I've resorted to writing a script to constantly monitor synergys and restart it if the thread count changes, but the OSX client still won't reconnect automatically.  I guess the next step is to do a remote ssh restart of synergyc or disable SSL until it's stable.

My setup is OSX 10.11.6, Ubuntu 16.04  and Windows 10; all running 1.8.0-beta-4ff3cdd.

**Comment by Avamander** [comment]
I get the same error:
```
ERROR: ssl error occurred (system call failure)
ERROR: eof violates ssl protocol
```

On Ubuntu 17.04 and Windows 10, restarted both syncanies on both devices multiple times, still the same error.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
