### ISSUE TITLE
Detect existing plugins from system directory

### ISSUE THREAD

**Issue by ltrager** [symless/synergy#4880]
Currently Synergy gets SSL support by downloading libns.so from the web and installing it into ~/.synergy/plugins. If the distribution Synergy is running on isn't supported(i.e Gentoo, Arch) the wizard fails with an error and Synergy does not have SSL support. This also causes issues in environments with no network access.

Synergy should be modified to search a system location(i.e /usr/lib/synergy) by default to allow OS vendors to ship plugin's with their packages.

**Comment by nlyan** [comment]
No longer relevant, as we ship plugins now.
