### ISSUE TITLE
Mouse jittery/laggy with Windows 10 server and client

### ISSUE THREAD

**Issue by kingofzeal** [symless/synergy#4911]
We fixed the WiFi lag on macOS in Synergy v1.9.0. Login to our forum using your Synergy account & [Download Synergy v1.9.0](https://symless.com/forums/topic/2587-synergy-v190-release-candidate/).
---
Similar to the issue described here: https://github.com/synergy/synergy/issues/4132

But running into this with a Windows 10 (Enterprise x64) as a Server and Client. Running Synergy 1.7.3 on both machines. When initially moving between machines, it works fine for about 5-10 seconds, then the cursor begins to jump around, and the keypresses/clicks are delayed or difficult to trigger.

I uninstalled Bonjour and that seemed to clean it up a little bit, but not completely.

The ping trick in the other issue does not help 100%, but it (again) does make it last a bit longer before starting to act up.

**Comment by dayjavid** [comment]
I just got Synergy up and running on a new Win10 installation and am having lag issues.
Client computer has not changed - is still Win7.

**Comment by kingofzeal** [comment]
I'm not 100% positive, but this may have disappeared in the last day or two. Possibly a Windows Update applied in the last week. @dayjavid Can you confirm by chance? Except for an occasional mouse jump (once every second for maybe .25 seconds) I'm not having any more lag.

**Comment by dayjavid** [comment]
I'll keep an eye on it. Thanks for the feedback

**Comment by mrconnerton** [comment]
I experience this issue with a Ubuntu server (over wifi), Win10 client (over wifi). The win10 is a surface pro 3 and I don't have a usb Ethernet adapter so I can't test it via Ethernet.

I have a Win8 desktop on the same network as a client over Ethernet and that works fine with the ubuntu server connected via wifi.

**Comment by mrconnerton** [comment]
So I just had to reset my win10 to a fresh install. Kept my files but deleted all the programs. I reinstalled synergy and things seem to be running normal now. I did install the 1.8 beta so I'm not sure if fresh windows or beta solved it for me. If I notice anything I will report here again.

**Comment by hnkent** [comment]
any updates ?

**Comment by dayjavid** [comment]
I haven't noticed any issues with it recently.

**Comment by dev-guy** [comment]
Updated client (64 bit windows 10) and server (el capitan) - using pro. Same problem. Intermittent. Keyboard is laggy too.

**Comment by pfz** [comment]
This is still quite urgent from me. It seems I can repeat the bug.
Here is my conf:
- Wired gigabyte network, no ping (<1ms). CPU i7 4770. RAM 16Gb. SSD hd.
- server : win 10.14931
- clients: win 10.14931 + macOs 10.11.6

What happens and how to reproduce:
- I start on the windows client a process consuming all vcores of my cpu/i7 4770 ( i this case, YARN ). Then every clients on the network get laggy. By laggy I mean it's like I were on a network with 500+ms ping. A real ping command while this lag is active shows no change in ping values btw machines. Lag stay even after the process stops. Situation is resolved only by restarting synergyd on client using services.

What makes no difference : 
- install/uninstall bonjour
- stopping the mac to get the 2 win machines only communicating.
- isolating the 2 machines from network by making a point to point network (connecting by wire, static IP).
- enable/disable SSL

My guess : 
- It's seems to concerns the client. Because restarting server, so resetting client do not make resolve the lag issue. I have to restart every client (event the macos). and unexpectidly, I have to do the same with the mac client. 
- May be a scheduler/watchdog pb that got stuck on wrong variables and disturb server enough to distrub the whole chain ?

This bug annoys me for years now. I would really like it to be solved. Now I can reproduce it I know it's not random.

**Comment by vanowm** [comment]
The lag starts after client hasn't been rebooted for a while (a week?). Rebooting server doesn't help much.

Server: W10 x64
Client: W7 x64

I didn't have this issue at all when ran both client and server on W7 (although I was probably was using old synerger version as well)

**Comment by yepthatsjason** [comment]
I'm also seeing this issue FWIW. My Windows 10 synergy server has a ton of lag for my mac client. Something I've noticed is if I bring the Windows synergy app into the foreground, it suddenly gets better. Seems like the process isn't running as aggressively in the background maybe?

**Comment by danalec** [comment]
I can confirm the lag caused by high polling rate

setup:
qemu vfio kvm passthrough: archlinux but usb host is w10 under qemu
razer naga: polling rate 1000 slows down cursor, 500 lags sometimes, 125 no lag
tested on 3600 dpi

**Comment by Cedricbob** [comment]
@danalec It look like it is the issue, reducing my polling rate from 1000 to 125 fix the problem.
Logitech G502 at 2700 dpi.

**Comment by tmjorud** [comment]
Same for me as well, got a Logitech gaming mouse, reduced the polling rate from 1000 to 125, and the lag is completely gone! :)

**Comment by vanowm** [comment]
This doesn't explain why it works fine with 1000dpi after reboot and lag starts only after a while (in my case a few days)

**Comment by tmjorud** [comment]
@vanowm I notice you are writing "dpi" this is not the same as polling rate, are you sure you are adjusting the right setting in your mouse config tool? Or was it just a mistype? :)

**Comment by vanowm** [comment]
Yes, sorry, I did mean poling rate, not dpi

![Imgur](http://i.imgur.com/4FZZHFA.png?1)

**Comment by KerryRitter** [comment]
I am having this problem as well fro ma Windows 10 server to a Mac client. Significant multi-second delays. I don't have mouse settings mentioned above... Suggestions?

**Comment by junioma** [comment]
Same problem. Linux Mint Server and W10 client.

**Comment by mossiv** [comment]
Same problem here. Windows 10 server to Mac Sierra 10.12.5 client. Mouse is practically unusable. Jitters and random freezing. Keyboard isn't so bad.

**Comment by rh71el2** [comment]
It surprises me that there are such bugs like this reported nearly 2 years ago and it's still happening like it is to us.

**Comment by unbwogable** [comment]
I agree that this bug is old enough that it should have been resolved. I was using the trial version of another app, no issues, other than the fact I've already paid for Synergy. With the lack of response to old issues like this, sometimes I regret paying for it.

**Comment by chevex** [comment]
Came to report issues with the polling rate as well. Windows 10 Server with Macbook Pro client running OS X Sierra (10.12.5). Mouse is a Logitech G700s.

![image](https://user-images.githubusercontent.com/874394/27099496-6377cea8-5038-11e7-81bb-7bc3463c78ab.png)

500 polling rate or lower seems to work fine with no lag on Mac client. Polling rate 1000 will work okay for a while and then the mouse on the client will start feeling like you're dragging it through molasses.

**Comment by alanaasmaa** [comment]
@danalec Can also confirm latest Version 1. No lag at 250, laggs with 1000.

**Comment by Jrawke** [comment]
I have the same issue caused by a Razer mouse and a polling rate of 1000Hz. I have a Linux server and Win10 client. The client runs in a VM. CPU usage is very high, which causes lag on the client.

**Comment by Jrawke** [comment]
@unbwogable you mentioned there is other KVM software which does not have this problem, could you please provide the name of it so I can try it out? Thanks

**Comment by nathannli** [comment]
wanted to confirm that by reducing polling rate, the mouse becomes stable. I occassionaly get mouse jitter when the client experiences load (my client is weak laptop, whereas the server is a desktop). 

v1.14.0-stable build date June 8 2021
Server W11 64bit
Client W10 64bit

original mouse polling rate: 1000
adjusted mouse polling rate: 125
Mouse: razer viper mini

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
