### ISSUE TITLE
Add Visual Studio 2015 support on Windows 10

### ISSUE THREAD

**Issue by elpagano3** [symless/synergy#4978]
I get this error when i try to compile on Windows 10:

Entering dir: src/gui
Qt: Untested Windows version 6.2 detected!
QMAKESPEC has not been set, so configuration cannot be deduced.
Error processing project file: gui.pro
Going back to: C:\install\synergy-1.7.4-stable
Error: QMake encountered error: 3

I have:
Visual Studio 2015
cmake 3.3.1
Qt 4.6.2
Python 2.7.10
Windows 10 64 Bits

Thanks.

**Comment by jakepetroules** [comment]
Qt 4.6.2 is absolutely ancient, and does not support VS 2015 or Windows 10. You should uninstall it and download the latest Qt 5.5.0 from http://www.qt.io/download-open-source/ instead.

**Comment by elpagano3** [comment]
I' ll try that. I just follow the wiki.

**Comment by elpagano3** [comment]
Good.
So, I get this error when try to build on VS:
*Warning	C4005	'for': redefinición de macro	project client	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xkeycheck.h	line 199*

**Comment by jakepetroules** [comment]
This is due to Synergy attempting to work around an ancient MSVC bug. Delete this line: https://github.com/synergy/synergy/blob/master/src/lib/common/common.h#L95

**Comment by elpagano3** [comment]
I skipped the second step: hm build. So, i did it and a i get this error:
*Error: Cannot determine vcvarsall.bat location for: Visual Studio 14*

I have Visual Studio 2008 SP1 installed already. Maybe it is a python error.

**Comment by Vdragon** [comment]
I have upgraded Windows 10 and wanna try Synergy lately, maybe I can help.

**Comment by XinyuHou** [comment]
@elpagano3 @Vdragon 
Please check this pull request. It adds 2013 support. But it should be good direction to go.

https://github.com/synergy/synergy/pull/4665

**Comment by tommydrum** [comment]
Lines 140 needs to be changed to "#if defined(nullptr)" to correctly detect if nullptr is a keyword in VS 2015. Nullptr is not defined in the preprocessor, but instead a keyword as per the standard, so the current code would still execute line 141(# define nullptr NULL), which would trigger C4005.
