### ISSUE TITLE
Auto config mode toggle for GUI

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#5008]
Problem: Currently auto config is always enabled, so if another user on the same network wants to install Synergy, it will try to connect to an existing user's GUI. To the new user it looks like the auto config just does nothing, and to the existing user it causes confusion.

Solution: Allow the user to toggle between *auto config* mode and *running* mode. This way, the existing user won't be disturbed while the new user is configuring.

**Comment by nbolton** [comment]
May solve or may be related to #4426

**Comment by nlyan** [comment]
Deprecated by #5655
