### ISSUE TITLE
Cannot click with shared mouse (either left or right) on a Mac client, requires restart

### ISSUE THREAD

**Issue by tangurano** [symless/synergy#5058]
I am using an Ubuntu machine as my server, and it was working fine with my Mac client until I attached an external monitor via HDMI to my Mac. 

Now left/right mouse clicks no longer work. I can still move the mouse between machines, and the keyboard and shared clipboard still work.

**Comment by tangurano** [comment]
That is, left/right mouse clicks don't work on the Mac client. Unplugging the monitor, restoring my old .synergy.conf, restarting the client / server, and re-plugging the monitor seems to have fixed it for now. Not sure if it will come back.

**Comment by tangurano** [comment]
Yep, it's back. Not sure what triggers it, but it makes the mouse nearly useless on the client.

**Comment by tangurano** [comment]
Restarting both servers fixed it this time.

**Comment by tangurano** [comment]
The problem still happens after I took away the external monitor, so that's not the issue.

**Comment by XinyuHou** [comment]
Duplicate to #4762

**Comment by nlyan** [comment]
This sounds like #5226 , although this is only known to effect Windows servers.

**Comment by XinyuHou** [comment]
Could you give us some logging from both your server and client sides? You can copy the log from Synergy GUI and paste into [gist](https://gist.github.com/). Please use level Debug1. You can change the log level in Edit->Settings.

**Comment by XinyuHou** [comment]
Closed due to lack of information
