### ISSUE TITLE
Compile fails on OS X 10.9.5 due to -Wno-unused-local-typedef

### ISSUE THREAD

**Issue by bunjiboys** [symless/synergy#5074]
In https://github.com/synergy/synergy/commit/faa170b40dbc152123b39a29ec63424f83841baa the `-Wno-unused-local-typedef` was added to CMAKE_CXX_FLAGS but it causes an error when using clang.

```
error: unknown warning option '-Wno-unused-local-typedef' [-Werror,-Wunknown-warning-option]
```

gcc / clang version

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

Applying the following patch will fix the compile for OS X

``` patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 618902d..a737017 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -77,7 +77,11 @@ if (UNIX)

        # warnings as errors:
        # we have a problem with people checking in code with warnings.
-       set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror -Wno-unused-local-typedef")
+       set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")
+
+       if(NOT ("${CMAKE_C_COMPILER}" MATCHES "clang$" OR "${CMAKE_C_COMPILER_ID}" STREQUAL "Clang"))
+               set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-unused-local-typedef")
+       endif()

        if (NOT APPLE)
                set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
```

**Comment by ZhengRui** [comment]
I got the same problem today under OSX Yosemite, but only with `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")` make it pass.

**Comment by XinyuHou** [comment]
@bunjiboys 
Could you make a pull request please?

**Comment by bunjiboys** [comment]
@XinyuHou Done

**Comment by XinyuHou** [comment]
@bunjiboys thank you

**Comment by bavier** [comment]
Note that the -Wno-unused-local-typedef flag was introduced in clang 3.6.0, so perhaps a more appropriate fix one be one similar to https://github.com/TrinityCore/TrinityCore/commit/98e7ab44615af90d477b845802da04f4f6c4d6cf

**Comment by nlyan** [comment]
I removed the flag entirely, along with -Werror. It's just dumb given our current plans with respect to 1.9.x and 2.x
