### ISSUE TITLE
Mac server doesn't differentiate between left and right cmd

### ISSUE THREAD

**Issue by patrikaxelsson** [symless/synergy#5098]
I am currently working on https://github.com/patrikaxelsson/avr-amiga-controller which is connecting to synergy servers using the uSynergy{.c,h} code.

The synergy server sends different sets of keycodes to the client depending on the server os it is running on. I have added support for this by allowing user to specify the server type/os which makes it choose the appropriate code mapping table to translate from server key codes to amiga key codes.

However, when the server is running on os x there is one issue that cannot be solved - the server will send the same keycode and modifiers for both left and right cmd keys (keyCode=0x38, modifiers=0x0010). This is a big problem as on the amiga you need to be able to differentiate the left/right "super" keys as they have different functions.

It seems os x generates the same keycode for both cmd keys, but different with different modifiers, see this output from "Key Codes" ( https://itunes.apple.com/se/app/key-codes/id414568915?mt=12 ):
Right cmd down: KeyCode=0xffff, Modifiers=0x100110
Right cmd up: KeyCode=0xffff, Modifiers=0x100
Left cmd down: KeyCode=0xffff, Modifiers=0x100108
Left cmd up: KeyCode=0xffff, Modifiers=0x100

And with both cmd pressed down Modifiers is 0x100118.

**Comment by patrikaxelsson** [comment]
This works fine when the synergy server is running on both linux and windows - left/right windows keys are sent as separate keycodes.

**Comment by patrikaxelsson** [comment]
Why was this issue closed?

It not fixed and is still the same in 1.10.3-stable-ca35737a.

**Comment by patrikaxelsson** [comment]
This issue also applies to left and right Shift and Alt keys, which also are sent as the same codes.

Running synergy server 1.10.3-stable-ca35737a on OS X El Capitan (10.11.6).

On the OS X server computer, I press and release the following keys in order:
LeftShift, LeftAlt, LeftCmd, RightShift, RightAlt, RightCmd.

The client side observes the following KeyID, KeyModifierMask (modifiers) and KeyButton (buttonKey). Ignore the amigaKey, this is what this client translates to.:
```
DKDN (Key down),   keyId=0xEFE1, modifiers=0x0001, buttonKey=0x0039, amigaKey=0x60
DKUP (Key up),     keyId=0xEFE1, modifiers=0x0000, buttonKey=0x0039, amigaKey=0x60
DKDN (Key down),   keyId=0xEFE9, modifiers=0x0004, buttonKey=0x003B, amigaKey=0x64
DKUP (Key up),     keyId=0xEFE9, modifiers=0x0000, buttonKey=0x003B, amigaKey=0x64
DKDN (Key down),   keyId=0xEFEB, modifiers=0x0010, buttonKey=0x0038, amigaKey=0x66
DKUP (Key up),     keyId=0xEFEB, modifiers=0x0000, buttonKey=0x0038, amigaKey=0x66
DKDN (Key down),   keyId=0xEFE1, modifiers=0x0001, buttonKey=0x0039, amigaKey=0x60
DKUP (Key up),     keyId=0xEFE1, modifiers=0x0000, buttonKey=0x0039, amigaKey=0x60
DKDN (Key down),   keyId=0xEFE9, modifiers=0x0004, buttonKey=0x003B, amigaKey=0x64
DKUP (Key up),     keyId=0xEFE9, modifiers=0x0000, buttonKey=0x003B, amigaKey=0x64
DKDN (Key down),   keyId=0xEFEB, modifiers=0x0010, buttonKey=0x0038, amigaKey=0x66
DKUP (Key up),     keyId=0xEFEB, modifiers=0x0000, buttonKey=0x0038, amigaKey=0x66
```

The client used is an Amiga OS synergy client simply called SynergyClient, which I am the author of. When the Linux or Windows synergy server is used, different KeyButton codes are received for left/right Shift left/right Alt and left/right windows key - it is only the OS X server which cannot differentiate between left and right.

**Comment by patrikaxelsson** [comment]
Corresponding sequence captured in "EventViewer":

![image](https://user-images.githubusercontent.com/12885607/70184459-2bb92880-16e8-11ea-895b-037cd1cde2cd.png)

**Comment by amigo1one** [comment]
I am also using 1.10.3-stable-ca35737a and need the macOS synergy server to differentiate between those keys.

**Comment by Jickelsen** [comment]
This is a dealbreaker for me, as I am using a hyper key which binds caps lock to all the right modifiers, thus allowing me to combine it with left modifiers.

**Comment by cake808** [comment]
I'm also running into the same issues, which unfortunately breaks my workflow (similar to @Jickelsen) :confused:
Every right modifier is interpreted as a left modifier.

It happens while using Linux as the Server and MacOS as the client. 
Version: `1.14.0-stable-67d824b8`

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.

**Comment by alber70g** [comment]
This doesn't seem fixed. Can we put some eyes on this again?

**Comment by patrikaxelsson** [comment]
@nbolton : what is required for this issue to be looked at?

**Comment by nbolton** [comment]
Reopening again as it seems to be active. Someone needs to open a PR.

**Comment by sithlord48** [comment]
i think this is part of it https://github.com/deskflow/deskflow/pull/9916

**Comment by nbolton** [comment]
So is this a dupe of #8486 which that PR fixes?

Edit: Going to assume yes
