### ISSUE TITLE
Client won't connect, requires server machine restart

### ISSUE THREAD

**Issue by dinomite** [symless/synergy#5181]
Every few days when I wake my client (2013 rMBP) it fails to connect to the server saying:

    [2016-01-14T09:27:46] INFO: starting client
    [2016-01-14T09:27:46] INFO: config file: /var/folders/bd/0_1pp9qn1mn052_g6_gmym7sdm186t/T/Synergy.xJL871
    [2016-01-14T09:27:46] INFO: log level: INFO
    [2016-01-14T09:27:46] INFO: drag and drop enabled
    [2016-01-14T09:27:46] NOTE: started client
    [2016-01-14T09:27:46] NOTE: connecting to '192.168.2.101': 192.168.2.101:24800
    2016-01-14 09:27:46.460 synergyc[879:10753] starting cocoa loop
    [2016-01-14T09:28:01] WARNING: failed to connect to server: Timed out
    [2016-01-14T09:28:02] NOTE: connecting to '192.168.2.101': 192.168.2.101:24800
    [2016-01-14T09:28:17] WARNING: failed to connect to server: Timed out
    [2016-01-14T09:28:18] NOTE: connecting to '192.168.2.101': 192.168.2.101:24800

Funny thing is, the server see the connections and after 30 seconds logs that the client is unresponsive:

    [2016-01-14T09:27:36] INFO: starting server
    [2016-01-14T09:27:36] INFO: config file: /var/folders/77/xjt9xv456nzfx5y1vwsq80480000gn/T/Synergy.J41918
    [2016-01-14T09:27:36] INFO: log level: INFO
    [2016-01-14T09:27:36] INFO: drag and drop enabled
    [2016-01-14T09:27:36] NOTE: started server, waiting for clients
    2016-01-14 09:27:37.006 synergys[41925:3630971] starting cocoa loop
    [2016-01-14T09:27:46] NOTE: accepted client connection
    [2016-01-14T09:28:02] NOTE: accepted client connection
    [2016-01-14T09:28:16] NOTE: new client is unresponsive
    [2016-01-14T09:28:18] NOTE: accepted client connection
    [2016-01-14T09:28:32] NOTE: new client is unresponsive
    [2016-01-14T09:28:34] NOTE: accepted client connection

Perhaps helpful is to view these logs interleaved:

    Server [2016-01-14T09:27:36] NOTE: started server, waiting for clients
    Server 2016-01-14 09:27:37.006 synergys[41925:3630971] starting cocoa loop
    Client 2016-01-14 09:27:46.460 synergyc[879:10753] starting cocoa loop
    Client [2016-01-14T09:27:46] NOTE: started client
    Client [2016-01-14T09:27:46] NOTE: connecting to '192.168.2.101': 192.168.2.101:24800
    Server [2016-01-14T09:27:46] NOTE: accepted client connection
    Client [2016-01-14T09:28:01] WARNING: failed to connect to server: Timed out
    Client [2016-01-14T09:28:02] NOTE: connecting to '192.168.2.101': 192.168.2.101:24800
    Server [2016-01-14T09:28:02] NOTE: accepted client connection
    Server [2016-01-14T09:28:16] NOTE: new client is unresponsive
    Client [2016-01-14T09:28:17] WARNING: failed to connect to server: Timed out
    Client [2016-01-14T09:28:18] NOTE: connecting to '192.168.2.101': 192.168.2.101:24800
    Server [2016-01-14T09:28:18] NOTE: accepted client connection
    Server [2016-01-14T09:28:32] NOTE: new client is unresponsive
    Server [2016-01-14T09:28:34] NOTE: accepted client connection

The most unfortunate part is that restarting the Synergy daemons on the machines doesn't fix it—I have to restart the server (the whole machine) for them to get together again.

**Comment by XinyuHou** [comment]
Do you use SSL? Could you turn your log level to Debug and send us another log?

**Comment by dinomite** [comment]
@XinyuHou I do not use SSL, I turned it off when the latest version was released and Synergy wouldn't work for me with SSL on.

I'll grab another log at debug next time I experience this.

**Comment by dinomite** [comment]
@XinyuHou Here is a debug log, again interleaved for legibility, but beware that some events occurred in the same second so their exact ordering may be incorrect.

    Server [2016-02-09T09:55:41] DEBUG: opening configuration "/var/folders/77/xjt9xv456nzfx5y1vwsq80480000gn/T/Synergy.L72545"
    Server [2016-02-09T09:55:41] DEBUG: configuration read successfully
    Server [2016-02-09T09:55:41] DEBUG: plugins dir: /Users/dinomite/Library/Synergy/Plugins
    Server [2016-02-09T09:55:41] DEBUG: loading plugin: libns.dylib
    Server [2016-02-09T09:55:41] DEBUG: plugin loaded: libns.dylib (version 1.3)
    Server [2016-02-09T09:55:41] DEBUG: screen shape: center=0,0 size=2560x1440 on 1 display
    Server [2016-02-09T09:55:41] DEBUG: starting watchSystemPowerThread
    Server [2016-02-09T09:55:41] DEBUG: adopting new buffer
    Server [2016-02-09T09:55:41] DEBUG: opened display
    Server [2016-02-09T09:55:41] DEBUG: started watchSystemPowerThread
    Server [2016-02-09T09:55:41] DEBUG: waiting for event loop
    Server [2016-02-09T09:55:41] DEBUG: could not map hotkey id=ef14 mask=0000
    Server [2016-02-09T09:55:41] NOTE: started server, waiting for clients
    Server [2016-02-09T09:55:41] DEBUG: waiting for carbon loop
    Server [2016-02-09T09:55:41] DEBUG: event queue is ready
    Server [2016-02-09T09:55:41] DEBUG: signalling carbon loop ready
    Server [2016-02-09T09:55:41] DEBUG: add pending events to buffer
    Server [2016-02-09T09:55:41] DEBUG: starting carbon loop
    Server [2016-02-09T09:55:41] DEBUG: carbon loop ready
    Server [2016-02-09T09:55:41] DEBUG: add pending events to buffer
    Server [2016-02-09T09:55:41] DEBUG: screen "Caracalla" shape changed
    Server [2016-02-09T09:55:41] DEBUG: screen "Caracalla" shape changed
    Server [2016-02-09T09:55:58] NOTE: accepted client connection
    Client [2016-02-09T09:55:58] DEBUG: plugins dir: /Users/dstep8/Library/Synergy/Plugins
    Client [2016-02-09T09:55:58] DEBUG: loading plugin: libns.dylib
    Client [2016-02-09T09:55:58] DEBUG: plugin loaded: libns.dylib (version 1.3)
    Client [2016-02-09T09:55:58] DEBUG: screen shape: center=0,-1440 size=3416x2490 on 2 displays
    Client [2016-02-09T09:55:58] DEBUG: starting watchSystemPowerThread
    Client [2016-02-09T09:55:58] DEBUG: adopting new buffer
    Client [2016-02-09T09:55:58] DEBUG: opened display
    Client [2016-02-09T09:55:58] NOTE: started client
    Client [2016-02-09T09:55:58] DEBUG: started watchSystemPowerThread
    Client [2016-02-09T09:55:58] NOTE: connecting to '192.168.2.101': 192.168.2.101:24800
    Client [2016-02-09T09:55:58] DEBUG: waiting for event loop
    Client [2016-02-09T09:55:58] DEBUG: waiting for carbon loop
    Client [2016-02-09T09:55:58] DEBUG: event queue is ready
    Client [2016-02-09T09:55:58] DEBUG: signalling carbon loop ready
    Client [2016-02-09T09:55:58] DEBUG: add pending events to buffer
    Client [2016-02-09T09:55:58] DEBUG: starting carbon loop
    Client [2016-02-09T09:55:58] DEBUG: carbon loop ready
    Client [2016-02-09T09:56:13] WARNING: failed to connect to server: Timed out
    Client [2016-02-09T09:56:13] DEBUG: retry in 1 seconds
    Server [2016-02-09T09:56:14] NOTE: accepted client connection
    Client [2016-02-09T09:56:14] NOTE: connecting to '192.168.2.101': 192.168.2.101:24800
    Server [2016-02-09T09:56:28] NOTE: new client is unresponsive
    Client [2016-02-09T09:56:29] WARNING: failed to connect to server: Timed out
    Client [2016-02-09T09:56:29] DEBUG: retry in 1 seconds
    Server [2016-02-09T09:56:30] NOTE: accepted client connection
    Client [2016-02-09T09:56:30] NOTE: connecting to '192.168.2.101': 192.168.2.101:24800
    Server [2016-02-09T09:56:44] NOTE: new client is unresponsive
    Server [2016-02-09T09:56:46] NOTE: accepted client connection

**Comment by dinomite** [comment]
Closing this—I did some pcaping and this is a Personal Problem™ of sockets being prematurely closed.
