### ISSUE TITLE
High resolution App icon on Mac

### ISSUE THREAD

**Issue by jasonosei** [symless/synergy#5192]
OS X Logo looks terribly out of place please see screenshot
![screen shot 2016-01-22 at 09 40 14](https://cloud.githubusercontent.com/assets/12104843/12510121/63b6660a-c0ff-11e5-928c-aab0454923fd.png)

**Comment by noAlvaro** [comment]
I have made one for personal use.
Please feel free to use it as you want.

![Synergy new app icon](https://www.dropbox.com/s/7vn9q6qibv4naiz/synergy-logo.png?raw=1)

**Comment by hruettimann** [comment]
Second that. The icons need a refresh and higher resolution. Also a less obtrusive icon in gray or black and white would be very welcome.

**Comment by nbolton** [comment]
@XinyuHou Duplicates #5192
