### ISSUE TITLE
Mouse flickering in World of Warcraft

### ISSUE THREAD

**Issue by Discover-** [symless/synergy#5215]
Hi.

I use Synergy to extend my desktop to a Mac Mini as well as a Windows laptop. It starts up along with my operating system on all three systems so I can easily access everything when I start my day.

When I open up World of Warcraft and hold my mouse, it acts as if I am *very rapidly* moving it around, way faster than is humanly possible. After a lot of investigating I finally figured out it's Synergy that is causing this issue. I had already written a script that would auto kill an useless process every few seconds because killing a process made the mouse movement normal for a brief period.

**Comment by cleverca22** [comment]
you need to use relative mouse moves

**Comment by patoupatou** [comment]
I have a linux machine acting as server and windows machine acting as client. Even with relative mouse moves, the mouse moves extremely fast in some games like Tera.

**Comment by Discover-** [comment]
The article mentioning the relative mouse seems to only count for clients, whereas both me and @patoupatou experience this issue on our server, not client.

**Comment by XinyuHou** [comment]
Duplicate to #2631
