### ISSUE TITLE
Mac client key quotation mark doesn't work

### ISSUE THREAD

**Issue by neowinston** [symless/synergy#5216]
I'm using a Windows 7 as the server and a Mac as the client. On the server all keys work fine, of course, on the Mac the quotation mark key doesn't work.

**Comment by XinyuHou** [comment]
@neowinston 

Please check your keyboard layout.

If you still experience this issue, please leave us some logging information.

**Comment by hodor** [comment]
I had this issue as well. I debugged the server app, and it was sending the key events correctly.
When I went to the client to debug it, the quote key just wasn't appearing at all in the Mac Keyboard Viewer. However, after changing the Synergy logging level to Debug and applied, it fixed itself. I was able to see my key events on the Keyboard Viewer.

It's working now even after I reset my logging level back to Info.
So it appears that there's a bug in there, but the client fixes it when you're applying changes in the client synergy app.
