### ISSUE TITLE
Windows 10 Action Centre causes "wrapping" between adjacent monitors

### ISSUE THREAD

**Issue by aledt** [symless/synergy#5220]
**Scenario**

Mac Mini running 1.7.5 with dual screens as server. Microsoft Surface Book Windows 10 running 1.7.5 as client. Second monitor is connected to Surface book. Devices are ordered from left to right:

Surface book --- Extra Monitor --- Mac Mini Monitor 1--- Mac Mini Monitor 2

**Steps to reproduce**

1. Connect as above. Windows Action Centre is hidden.
2. Scroll mouse from right to left across all screens.
3. Cursor cross both Mac Mini screens without issue and onto extra monitor. Cursor will cross extra monitor and onto Surface Book screen.
4. Approximately at the edge of where the Action Centre opens to, the cursor will disappear and reappear on Extra monitor, approx. the same distance from extra monitor's right edge as the width of the Action centre.
5. Continue moving mouse left, cursor will cross onto surface book screen without issue to far left.

Executing in reverse will exhibit the same "jump" in location.

**Expected behaviour**

Smooth movement across all 4 monitors.

**Comment by XinyuHou** [comment]
Duplicate to #5201
