### ISSUE TITLE
Synergy is Unuasble in Ubuntu - Client Disconnects From Server Periodically

### ISSUE THREAD

**Issue by suprafly** [symless/synergy#5221]
I have reported a similar issue #5132, but I am not sure if this is related. I am running a Ubuntu 15.10 client and a Ubuntu 14.04 server. Both have Synergy 1.7.5

The problem is functionally equivalent to the aforementioned bug, but it is not yet clear to me if the clipboard is the culprit.

**Comment by suprafly** [comment]
I've done some more testing and I've found it is much worse than the previous bug.

The server seems to disconnect the client, but the server's icon doesn't show that it is stopped, though it clearly is. Restarting the server usually fixes it, but this problem seems to happen once every 5-10 minutes, and sometimes more often.

Doesn't seem to have anything to do with the clipboard.

**Comment by XinyuHou** [comment]
@suprafly  do you normally experience disconnection after/before trying to switch to anther screen?

**Comment by suprafly** [comment]
I'm not sure what you mean when you say "normally" but I'll answer both possibilities:

In the past, various versions of Synergy have had disconnection issues. It seems to have degraded further with each newer release.

With the present release that I am running, it seems to be intermittent and only one way. One way meaning, when I am on the client's screen I won't ever be kicked off. But sometimes I go to the servers display, then I cannot go back to the client.

This *may* be two issues, but it's hard to tell. Most times I can stop the server, wait for the clients icon to show disconnection, the start the server. That's annoying, but it fixes it.

Occasionally, I will get an error that the client has crashed and an option to restart.

**Comment by XinyuHou** [comment]
@suprafly 
It looks like a clipboard issue. Have you tried our 1.7.6-rc2 beta version?

**Comment by benmao** [comment]
@XinyuHou When to release a new version to solve the clipboard issue?

**Comment by suprafly** [comment]
Just installed, still broken. And, clipboard from client to server does not work.

**Comment by suprafly** [comment]
I would love to be able to disable the clipboard sharing and just have a stable and usable Synergy.

I mean, clipboard sharing is nice, but it's not worth the frustration I face everyday using this application.

**Comment by XinyuHou** [comment]
@suprafly 
Sorry for the inconvenience, I don't have disable clipboard feature. But I can add one as feature request.

Meanwhile wound you mind send us some logging to help us diagnose the issue?

**Comment by XinyuHou** [comment]
This is the issue for disabling clipboard. We will prioritize it.
#123

**Comment by suprafly** [comment]
I'm happy to help, just let me know what you need.

Also, I'm a C++/Qt programmer, so I can probably help out on the technical end a bit too.

**Comment by XinyuHou** [comment]
@suprafly 
Awesome! Let's try get some logging first. You can go to edit->settings, change log level to Debug and do the same thing on both machines. When the issue happens, come back to GUI and save the logging. If you experience crash, you could use save log to file feature which is located at the same place as log level.

Our github repository is here. You can download and have a look at the Linux clipboard part. We have wiki page about how to compile Synergy for each platform. The issue here is the Linux clipboard doesn't play well with threading.

Let me know if you need any help with compile Synergy.

https://github.com/symless/synergy/wiki/Compiling
https://github.com/symless/synergy

**Comment by suprafly** [comment]
Sounds good. And out of curiosity, are you using QThreads?

**Comment by XinyuHou** [comment]
We actually have two parts in Synergy. 1. Core binary, c++ code, that does all the low level stuff. 2. GUI, c++(qt), which is for starting and monitoring core binary. So we need to look into the low level part to diagnose clipboard issue, not using QThreads.

**Comment by suprafly** [comment]
Sounds good, I will get the logging going to provide you with some more info and poke around a bit in the library to get a feel for what's happening.

Thanks for all your help with this! I love this project, enough that I keep using it despite the frustrations :)

**Comment by XinyuHou** [comment]
@suprafly 
Thank you for the support, we appreciate your help.

**Comment by XinyuHou** [comment]
@suprafly 
How is it going with the log?

**Comment by tdwalton** [comment]
I'm having the same issue. Client intermittently disconnects. Mac client v. 1.7.6 running on OSX 10.10.5, Ubuntu Server v. 1.7.5 running on Ubuntu 14.04. Maybe these logs will be useful. 

[synergy_server.log.txt](https://github.com/symless/synergy/files/190135/synergy_server.log.txt)
[synergy_client.log.txt](https://github.com/symless/synergy/files/190136/synergy_client.log.txt)

**Comment by suprafly** [comment]
Sorry about the delay, I've been offline for a couple of weeks. Here's some logs.

[syn_client_xubuntu_15.10.txt](https://github.com/symless/synergy/files/192171/syn_client_xubuntu_15.10.txt)
[syn_server_xubuntu_14.04.txt](https://github.com/symless/synergy/files/192172/syn_server_xubuntu_14.04.txt)

**Comment by XinyuHou** [comment]
@suprafly 
Seems to be duplicated to #4768 and #4827

**Comment by suprafly** [comment]
Might be a bit too preemptie, it's not clear to me that it's the same issue. I never see a server is dead message, and I never receive only 4 bytes.
