### ISSUE TITLE
Mouse scroll randomly doesn't work on Mac client

### ISSUE THREAD

**Issue by cloim** [symless/synergy#5227]
Sorry, If there a solution But I can't find it. So, Post this.

My situation is exactly same with #4054.
I'm using Synergy Version 1.7.5 on Windows 10 (Server) and OSX 10.11 El Capitan (Client).

I don't know how to reproduce this issue, too. Somtimes, When I switch to client, mouse scroll doesn't work. And then time, Clipboard doesn't work, too. 

So, I press Apply button on Server, It works again.

It's so annoying me. Please, Tell me If there a solution to fix this.

Thanks.

**Comment by skywebdeveloper** [comment]
I am having same issue with Windows 10 Metro apps only..

Scroll work fine everywhere except in Metro apps

**Comment by ming4883** [comment]
I encounter the same issue after upgrading to 1.7.6 with
Windows 10 (Server) and OSX 10.11 El Capitan (Client)

**Comment by shawnkhall** [comment]
I'm seeing the same behavior. Also on the server, double-clicking won't select a word and triple clicking won't select a paragraph. Restarting the Synergy service resolves it.

**Comment by K-4U** [comment]
Having the same issue.
Host is windows 10 pro
Client is Ubuntu 16.04 with Unity
Stopping the server and starting "fixes it"

**Comment by bigatg** [comment]
I have the same problem with Windows 10 Preview version 14342.
When I go back to the host machine and press <Apply> again then the mouse works again.

Microsoft's "Mouse without Borders" has the same problem. 

This makes me think it might be a problem in Windows 10.

**Comment by ming4883** [comment]
FYI, after rolling back the Windows 10 host to Synergy v1.7.5, this problem doesn't appear

**Comment by thejae** [comment]
Also experiencing the same problem as @cloim under similar environment but with Synergy 1.8.2-beta.

Windows 10 Enterprise 2015 LTSB x64 (Server) and OSX 10.11 El Capitan (Client).

**Comment by nyetwurk** [comment]
Still happens for me occasionally on the master branch, as of commit 1796150

The only solution is to restart the server (not the client).

Server is windows, client is linux.

**Comment by nyetwurk** [comment]
Should not have been labeled stale or closed.

**Comment by nbolton** [comment]
@nyetwurk A simple "Please reopen" would suffice. No need to waste keystrokes.

**Comment by shawnkhall** [comment]
@b100dian - have you disabled the feature to automatically hide scrollbars on the Win10 server (Settings, Ease of Access, Automatically hide scroll bars in Windows)?

**Comment by b100dian** [comment]
@shawnkhall it didn't look like that setting changed anything.
However it made me wonder what else can affect my scrolling. So I've discovered that in my case it was the SetPoint Logitech app! So if I quit that app, things work. Sorry for the noise on this bug, maybe the original poster has SetPoint too.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
