### ISSUE TITLE
Diacritics

### ISSUE THREAD

**Issue by rodolfoul** [symless/synergy#5228]
Hello,

In portuguese it is very common to type accented letters with two keyboard presses.
I.e.:
One needs a configured US Keyboard international as keyboard for the following to work.
To generate Á
You would have to type (A) plus (')
Unfortunately both accents and accented letters don't seem to work.

I'm currently using Ubuntu 14.04 as a server and Windows 10 as client.
My synergy client is version 1.7.5

**Comment by rodolfoul** [comment]
Adding to the issue: mouse button `back` also does not work.

**Comment by XinyuHou** [comment]
@rodolfoul 
Please have a look if this is related to your issue
#4280
