### ISSUE TITLE
synergys on Fedora Crashes from copy and paste function

### ISSUE THREAD

**Issue by cThrice** [symless/synergy#5235]
Issue:
synergy server crashes when extensively using the copy paste functionality between screens.

Recreate:

install latest stable on fedora 22 (1.7.6-1) (Server) (multicore desktop)
install same on Windows (client) (multicore laptop)
Register :) 
Setup ssh tunnel from Windows -> Fedora and forward default Synergy port (24800)
On Windows Client properly configure the screen "name" to match Server configs
Disable SSL on Windows client
Configure windows on Server configs

Now that we have the basic setup out of the way, the problem will appear in both the following cases:
- Setting up systemctl to start synergys
- Directly running synergys 

I have tried the following configs with the same results:
/usr/bin/synergys -d INFO -a 127.0.0.1:24800 --log /var/log/synergy.log -f
/usr/bin/synergys -d INFO -a 127.0.0.1:24800 --log /var/log/synergy.log -f --no-xinitthreads

To cause it crash (the majority of the time) do the following after starting the connection:
Copy some text from the Server (fedora box in my case), 
Move the mouse to the Client (windows) immediately copy text on that side, 
Then move the mouse back to the Server screen.  
At this point the synergy server should have crashed.

I find this crash to happen extremely often.

Both complain about thread issues

So far both myself and a friend have ran into this error independently since we have started using synergy over a year ago.  They run fedora 23, I run 22. 

Besides guessing that this is a thread issue/race condition because of the occasional non-failures that happen when trying to reproduce this, I don't have a clue why this is happening.

Though I did notice that when in no-xinitthreads mode, the process will properly "die" and abort.  Where when that flag isn't set, the process will just sit there saying it is fine, while zero logs will be produced (even in debug2)

If logs or other data are needed please just let me know.  I have seen other issues similar to this one, but they all seemed to be closed and pointed at 1.7.6 as a fix for the issue.

**Comment by XinyuHou** [comment]
Duplicate to #4353
Please use our latest release which is 1.7.6 on our official website.

http://synergy-project.org/

**Comment by cThrice** [comment]
@XinyuHou  I am already upgraded to 1.7.6 from the official site (please see my comments).  Thus why I opened a new issue.  My point was to notify you that at least for my setup (Windows 7 Client, fedora 22 server) the issue is NOT fixed.

**Comment by cThrice** [comment]
@XinyuHou  Thanks

**Comment by XinyuHou** [comment]
@cThrice 
Seems to be duplicated to #4768 and #4827. Please leave further comments in those issues.
