### ISSUE TITLE
scroll lock fails to move cursor to client with realforce 87u

### ISSUE THREAD

**Issue by ghost** [symless/synergy#5238]
With my keyboard(realforce 87u), i need to press both shift + numlock to lock/unlock the scroll lock. Whenever I get  "NOTE: Cursor is locked to screen, check Scroll Lock key" this message, I have to go to on-screen keyboard to move the cursor to client.

**Comment by XinyuHou** [comment]
> I have to go to on-screen keyboard to move the cursor to client.
Do you mean open on-screen keyboard can enable you to move your cursor to a client even it should be locked to current screen? Are you using Windows for both server and client?
