### ISSUE TITLE
Can click and type in ubuntu client but cannot move cursor

### ISSUE THREAD

**Issue by jrbenny35** [symless/synergy#5252]
Hello, just looking for a bit of insight. I have windows 10 as the server and ubuntu 15.10 as the client. I can click and type within the client but I cannot move the cursor at all. I have to move the cursor with the trackpad, but left and right click from the servers mouse works fine. Tried doing some research and cannot find a recent answer. Any help would be appreciated!

**Comment by XinyuHou** [comment]
@jrbenny35 
Are you using high DPI settings?

**Comment by jrbenny35** [comment]
Wow, just saw this email, but I think I may have been. Is 1800 high?
