### ISSUE TITLE
Hide GUI on launch

### ISSUE THREAD

**Issue by hruettimann** [symless/synergy#5253]
I got Synergy configured as startup item in OS X. On every startup the Synergy GUI appears. Is this a feature or a bug? I believe a user usually only needs to see the GUI during the setup. After this, Synergy should just do its Voodoo in the background when launched. The GUI should still be accessible of course through the menu bar icon, just hidden.

**Comment by legonigel** [comment]
@hruettimann If you open the gui click the `Edit` menu then `Settings`. You can select the `Hide on startup` option which should do what you want. If this is what you are looking for, then close this issue.

**Comment by hruettimann** [comment]
@legonigel Thank you, this is what I was looking for! So the option is here, just quite hidden in a menu I didn't look.
