### ISSUE TITLE
Can't switch keyboard layout on client

### ISSUE THREAD

**Issue by skorenyuk** [symless/synergy#5259]
On client PC typing language always same as on server PC.
When I change language on client and start typing, language automatically changes to server language.

Server: Ubuntu 15.10
Client: Win 10 and Mac OS X 10.11.

**Comment by wellprog** [comment]
i have it bug to :(

Server - Debian8
Client Win 10;

**Comment by NuclleaR** [comment]
have same issue

**Comment by legonigel** [comment]
There are a number of already open issue on this subject. I recommend closing this issue and moving discussion to an existing issue. This helps keeps the number of issues down, and keeps the devs focused. 

This issue looks most closely related to #460, but it might also be related to #4309, or another issue.

**Comment by XinyuHou** [comment]
@legonigel 
Thanks for your input.

Please comment in the mentioned issue.
