### ISSUE TITLE
Frequent disconnects, mac client ubuntu server

### ISSUE THREAD

**Issue by mengesb** [symless/synergy#5260]
I'm getting extremely frequent client or server disconnects to the point where I'm about to go back to two keyboards/mice - it is terribly often.

When returning to the server screen, the disconnect rate is about 70%, with messages at the client side of:

```
[2016-03-31T08:55:13] NOTE: server is dead
[2016-03-31T08:55:14] WARNING: failed to connect to server: server is not responding
[2016-03-31T08:55:15] NOTE: connecting to '10.240.2.129': 10.240.2.129:24800
[2016-03-31T08:55:27] ERROR: failed to connect secure socket
[2016-03-31T08:55:28] NOTE: disconnected from server
```

This is getting rather upsetting - also in that the mac client does not auto-reconnect! I always have to stop and start the client... which I thought there was an option to 'auto reconnect' but can't find it in the mac client!

Running v1.7.6 releases on both ubuntu 14.04 LTS and Mac OSX 10.11

**Comment by legonigel** [comment]
Do you have any more information on what is causing this issue?
Is this a new install, an upgrade? Has this issue always existed in your setup, or did it recently start happening? If it recently started happening what changed? 

This looks from a distance like it might simply be a networking issue, but it is hard to tell. Is one of the computers on wifi? Synergy doesn't always play well on wifi.

**Comment by samdfonseca** [comment]
So I've been running into this as well, also on ubuntu 14.04 server. Dug around in the syslog and found the below error showing up several times

```systemd-hostnamed[11084]: Warning: nss-myhostname is not installed. Changing the local hostname might make it unresolveable. Please install nss-myhostname!```

Installed libnss-myhostname and haven't had a disconnect for a few hours now, so it looks promising.

**Comment by mengesb** [comment]
@legonigel So at first I thought, "OK, maybe wifi..." so I've been running the last week without wifi on. This is an upgrade from an earlier beta build of 1.7.6.

The problem persists and is completely random. I've investigated 'libnss-myhostname', installed, no effect. I also have local entries pointing to each host in the /etc/hosts file referencing each other - they work just fine and resolution is happening.

I'm not sure under what conditions it exaclty is breaking but it is frequent and often involves the clipboard, but doesn't always (breaks after fresh restart of both client/server too).

**Comment by XinyuHou** [comment]
Duplicate to #4768
