### ISSUE TITLE
Another key mapping issue between Mac and Windows

### ISSUE THREAD

**Issue by joaogl** [symless/synergy#5261]
Hello,

I'm using El Capitain(server) and Windows 10 (client) and I can't map the { and } keys.
I tried setting the altgr = alt on the configs and it doesnt affect anything.
I also tried a few things that I saw like setting super = alt and vice versa and a few more, none of them work. Is it because of win 10? how can I fix this?

**Comment by XinyuHou** [comment]
@joaogl 
It seems duplicate to #4280.

Please let me know if it's not the case.
