### ISSUE TITLE
1.7.6: connecting client garbles mouse buttons on Windows server

### ISSUE THREAD

**Issue by NicApicella** [symless/synergy#5264]
**Server: Synergy 1.7.6 on Windows 7 (64-bit)**
**Client: Synergy 1.7.6 on Mac OS El Capitan (10.11.4)**

Since upgrading the server from 1.7.5 to 1.7.6 whenever the client connects, the keybinding I set on my Logitech mouse (a thumb-button set to "CTRL-W"; set through SetPoint Control Center 6.67.83) stops working correctly. (Other bindings, such as doubleclick, work fine; double-checked that it's not the button itself.)
The command "CTRL-W" doesn't work at all—sometimes, though, the CTRL-key gets stuck (with all the obnoxious side-effects that creates).

**Current workaround:** Fire up Synergy on the server, stop it, then restart it. Everything works fine afterwards.
The error arises again when disconnecting and then reconnecting the client.

Issue was **not** present with 1.7.5 as a server.

(Currently figuring out minimal reproduction steps and how to generate relevant log-files.)

**Comment by XinyuHou** [comment]
@NicApicella 
Duplicate to #4493. I have moved your comment in to #4493.

**Comment by NicApicella** [comment]
@XinyuHou 
I thought of adding my comment to that particular bug as well before opening a new one. On the other hand, this issue has arisen for me since upgrading from 1.7.5 to 1.7.6 on the server (Windows 7 64-bit). Never had any issues like that before. (Haven't gotten around to it, but I'm thinking of downgrading back to 1.7.5 in hopes of fixing it…)

**Comment by XinyuHou** [comment]
@NicApicella 
Give 1.7.5 a try, sometimes bugs are random

**Comment by NicApicella** [comment]
@XinyuHou I can confirm: The issue isn't present with 1.7.5. Must be something that has been touched since; at least in my case. (Still think it's wise to merge the issue with a – probably – unrelated one?)

**Comment by JonathanNEMRY** [comment]
Hello is there anything new with this issue? Or a workaround to avoid restarting computer? thanks
