### ISSUE TITLE
how to REALLY do NOT synchronize screen savers..?

### ISSUE THREAD

**Issue by masavini** [symless/synergy#5272]
hi,
i'm a synergy newbie, hope you can help me with this issue...

"synchronize screen savers" is NOT selected, but this setup seems to work properly 1-way only: the client exits screensaver only if the cursor is moved on its desktop, no matter if i move it within server desktop. this is fine.

the opposite, however, does not seem to work: the server exits screensaver each time i move the cursor, even if i move it within the client desktop...

can you tell me if there's a way to achieve the behaviour i described?

thanks!

**Comment by XinyuHou** [comment]
@masavini 
This looks like a support ticket. Please contact our help desk or forum.
http://synergy-project.org/forum/
https://synergy-project.org/contact/
