### ISSUE TITLE
Mouse clicks stop working on client after some idle time

### ISSUE THREAD

**Issue by Boomkop3** [symless/synergy#5274]
I have a client running windows 7
And a server running windows 10

After a couple of minutes of minutes the client stops reacting to mouse clicks

After I click the synergy window on the server or the desktop when it's the only window open the client start reacting to clicks again, to then stop again after a couple of minutes

**Comment by Boomkop3** [comment]
The problem can be worked around by moving the synergy window to it's own desktop

**Comment by XinyuHou** [comment]
@Boomkop3 
This is duplicate to #5226
I have shared your workaround in #5226.
