### ISSUE TITLE
Auto restart service when synwinhk.dll fails on Windows

### ISSUE THREAD

**Issue by XinyuHou** [symless/synergy#5277]
Problem: A number of issues can cause the hook DLL (synwinhk.dll) to fail to load.
Solution: Automatically restart the service when DLL fails to load.

**Comment by sunk818** [comment]
In Windows, the command line would be:

`net stop synergy`
wait until service is stopped then
`net start synergy`

I had to run this as Administrator

**Comment by nbolton** [comment]
Duplicate of #4957
