### ISSUE TITLE
Grave accent / backtick ( ` ) does not work on client, using Swedish keyboard

### ISSUE THREAD

**Issue by code77se** [symless/synergy#5278]
Similar to #5185, using a Swedish keyboard I am unable to type grave accent `` ` `` and circumflex accent ``^``. However, on a Swedish keyboard layout, none of these characters are produced using alt-gr, instead they are produced using the shift key, see a typical Swedish layout here:

https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/KB_Sweden.svg/2000px-KB_Sweden.svg.png

I do have the `altgr = alt` config, but it doesn't help. Note that tilde ``~`` works, using altgr together with the same physical key that should produce a circumflex using shift, but doesn't.

Server running Synergy 1.5.1 @ Ubuntu 12.02
Client running Synergy 1.4.10 @ Windows 7

**Comment by XinyuHou** [comment]
Duplicate to #5185
