### ISSUE TITLE
Out of Band Reset Functionality

### ISSUE THREAD

**Issue by theochino** [symless/synergy#5282]
Would be nice to have a reset (start/stop) button that would send an OutOfBand signal to all the client to reset.

Right now I have to plug keyboard or RDC to each device just to reset the non compliant device.

**Comment by XinyuHou** [comment]
@theochino 
This looks like a feature request. Please use our issue guide to flesh out the details.
https://github.com/symless/synergy/wiki/Issues

This issue will be closed until we have more information.
