### ISSUE TITLE
Neither lightdm nore gdm seem to be able to autostart synergyc for Fedora 23

### ISSUE THREAD

**Issue by docbill** [symless/synergy#5285]
Consistently:

/usr/bin/synergyc  -f --no-tray --debug INFO --name $(hostname) 172.31.253.43:24800
No protocol specified
2016-04-17T13:02:18 WARNING: secondary screen unavailable: unable to open screen
	/builddir/build/BUILD/synergy-1.6.2/src/lib/synergy/ClientApp.cpp,416

Followed by a core dump, until a user is logged in.  Regardless whether gdm or lightdm is used.

**Comment by XinyuHou** [comment]
This looks like a support ticket. Please contact our help desk.
https://synergy-project.org/contact/
