### ISSUE TITLE
High resolution App icon on Mac

### ISSUE THREAD

**Issue by XinyuHou** [symless/synergy#5299]
Problem: The current App icon's resolution is too low on Mac
Solution: Create a high resolution App icon

**Comment by iamjason** [comment]
It seems the menu bar is still a low resolution icon (and I _think_ an older style, but I'll let someone closer to the project decide that).

Here is a zoomed screenshot of an example menu bar I'm seeing on my retina display:

<img width="229" alt="screenshot 2016-08-03 12 52 53" src="https://cloud.githubusercontent.com/assets/442302/17374139/36aaff1e-5979-11e6-9268-751c2a488222.png">
