### ISSUE TITLE
Photoshop CS6 broken when Synergy service is running

### ISSUE THREAD

**Issue by localpcguy** [symless/synergy#5303]
**To Reproduce:**
Install Synergy
Start Photoshop/Illustrator CS6
Attempt to perform normal actions in Photoshop on server machine (no attached client)
- select with Marquee
- select text with text tool
- zoom using CTRL/ALT
- zoom out via click/drag (scrubby zoom off)
- drag open Photoshop file windows
- reorder layers
- and more, basically, Photoshop is unusable

**Expected:** 
Normal Photoshop actions to behave properly

**Actual:** 
Unable to use Photoshop when Synergy Service is running

**Versions (Synergy, OS):**
Server: 1.7.6
Client: N/A (happens on server, no clients connected)
OS: Windows 8.1 64-bit

**Workaround:**
The only workaround is to disable the Synergy service, which allows normal behavior in CS6 programs. Restarting the service will break them again.

**Comments:**
I have seen multiple similar bugs, but all seem to be closed at the moment. This breaks my ability to use Synergy as I need Photoshop to perform my job.

**Comment by XinyuHou** [comment]
Duplicates to https://github.com/symless/synergy/issues/4508

I have added your comment into that issue
