### ISSUE TITLE
Generate server certificate fingerprint directly

### ISSUE THREAD

**Issue by tcely** [symless/synergy#5311]
Using the fingerprint saved in a text file is insecure. Whenever the certificate is loaded the fingerprint should be calculated directly from the loaded data.

**Comment by XinyuHou** [comment]
The fingerprint file is for GUI to read. Synergy core reads TrustedServers to compare the fingerprint extracted from certificate. Could you give us more supported reference to back up your idea?

**Comment by tcely** [comment]
Why doesn't the GUI read the certificate directly?

Why are you allowing the fingerprint displayed to the user to be manipulated as a text file?

I haven't checked, but assuming the client side does actually compute the fingerprint from the certificate received via the connection (and saves that into the TrustedServers) file then the fact that the server side might display a fingerprint that doesn't match the one shown on the client side only introduces confusion.

If the GUI (on the server side) displayed the fingerprint calculated directly from the certificate (used by the server) you could not have the situation where the text file is older (and therefor no longer correct) than the (replaced) certificate on the server. I'd recommend that the GUI check to see which certificate is being served by the socket rather than using the file system to avoid yet another opportunity for confusion (when the certificate file was replaced, but the server hasn't restarted to read that change yet).
