### ISSUE TITLE
Keyboard layout is permanently stuck

### ISSUE THREAD

**Issue by andenix** [symless/synergy#5312]
A client would always use Server's keyboard layout. Its gets worse because you can't change Keyboard Layouts unless you switch back to server. Its a real nightmare if you actively use two layouts.

**Comment by XinyuHou** [comment]
Server and clients use their own keyboard layouts. But we do have some mismatch issues.
https://github.com/symless/synergy/issues/4280

**Comment by andenix** [comment]
Hello Jerry,

I have noticed you closed the ticket regarding keyboard layouts.
Has the issue been fixed?
I have a client which is exact replica of the server:
Same OS version: Windows 7-64, same keyboard layouts, same Synergy 
version 1.8.0-beta-4ff3cdd
There is not way of changing layout other than switching back to the 
server, change layout, switch back to the client.

Thank you,
Artem
