### ISSUE TITLE
Windows 7 no proper edge detection at high DPI

### ISSUE THREAD

**Issue by andenix** [symless/synergy#5313]
Windows 7 with DPI set > 100% edge detection always fails jumping to the adjacent client at the half of the screen. This almost defeats the purpose of this software as you have to make special shortcuts to choose different client. In most cases I just end up using second keyboard and mouse because its more convenient in the end. I understand the price I paid for the software isn't much, why charge at all if the major advertised function isn't there.

**Comment by XinyuHou** [comment]
@andenix 
Are you using multiple screens for server?

**Comment by andenix** [comment]
No, I have a single display configuration on the server if that's what you mean.

**Comment by XinyuHou** [comment]
Please give use some logging and your environment information. You can change log level in settings. Log level to Debug is enough.

**Comment by andenix** [comment]
I apologize. I stopped using the program a while ago. Perhaps I shall find some time in future to provide logging.

**Comment by XinyuHou** [comment]
@andenix 
I'm sorry for the inconvenience.
