### ISSUE TITLE
ssl cert for https://synergy-project.org/ not valid

### ISSUE THREAD

**Issue by airtonix** [symless/synergy#5320]
This domain is used for activating synergy pro.

So I can't activate my copy of synergy pro on my fedora desktop.

Additionally, any website that uses SSL in any portion of itself, should use SSL over the whole site to simply problems with managing cookie leakage.

**Comment by GranoblasticMan** [comment]
Possibly a good time to migrate to Let's Encrypt, if they haven't already: https://letsencrypt.org/

**Comment by XinyuHou** [comment]
This looks like a support ticket. Please contact our help desk.
https://synergy-project.org/contact/
