### ISSUE TITLE
Linux host to linux client @ producing Ω instead.

### ISSUE THREAD

**Issue by drgnomage** [symless/synergy#5321]
Hi there, 

I am currently running Arch Linux (more accurately Antergos) as the server and Ubuntu 16.04 as the client.

Both are running synergy v1.7.6.

SSL is off and everything is stable (apart from the known clipboard bug).

Please let me know if there is any more info needed and any suggestions would be greatly appreciated.

**Comment by XinyuHou** [comment]
Duplicates to #4280

**Comment by drgnomage** [comment]
Keyboard layout is the same.

**Comment by brunovianarezende** [comment]
it is actually a duplicate of https://github.com/symless/synergy/issues/62

**Comment by drgnomage** [comment]
Ah excellent, a 6 year old bug. 

Thanks for the pointer brunovianarezende, now typing clients emails won't be an hourly copy and paste chore haha.

Do you know if this is a workaround for all linux distros or just Ubuntu?

**Comment by brunovianarezende** [comment]
@drgnomage: I don't know, I just tested it on my ubuntu client. And yes, I won't need to search for emails to copy the '@' symbol anymore...

**Comment by drgnomage** [comment]
@brunovianarezende Thanks, will do. I'll post here and #62 if I find a better solution.

**Comment by brunovianarezende** [comment]
synergy 1.8.3 doesn't have this bug anymore.

**Comment by drgnomage** [comment]
Excellent, thanks for the update!  I will give it a spin tomorrow.
