### ISSUE TITLE
Unable to download plugins when they are on use on Windows

### ISSUE THREAD

**Issue by XinyuHou** [symless/synergy#5323]
Problem: When users leave Synergy running with plugin loaded, and they want to rerun the wizard, they will get "unable to delete plugin" error on Windows, not on Mac.

Solution: Maybe stop the process programmatically and then download the plugin and restart the process.

**Comment by darkdragon-001** [comment]
Since it is integrated as a _service_ (run `services.msc` to see all) in Windows, maybe you can use the corresponding API to stop and start the service.

At least this worked for me.

**Comment by nlyan** [comment]
Plugins have been removed
