### ISSUE TITLE
Issue with functionality of mouse on Windows 10

### ISSUE THREAD

**Issue by jen-p** [symless/synergy#5324]
With version 1.7.6, mouse experienced difficulty with button-down states in Adobe Photoshop CS6. Couldn't click and drag anything which is a large portion of interaction in Photoshop. Issue occurred while Synergy was running the background and connected to a client computer, as well as when the program wasn't running at all. Issue desisted when Synergy was uninstalled.

**Comment by XinyuHou** [comment]
Duplicates to #4508
