### ISSUE TITLE
Issue Ubuntu Client GUI in Spanish with button in wrong state

### ISSUE THREAD

**Issue by FranWatcher** [symless/synergy#5327]
Version of Synergy 1.7.6 (both server and client)
Server is on Windows 7 Ultimate (running on a Fujitsu i3 with 8Gb RAM).
Client is on Ubuntu 14.04 (running on a Asus with Intel i5 with 8Gb RAM).

When I start the client is already trying to connect to the last server IP address.
The first of the south buttons (in spanish "Aplicar" in english "Apply") is right but the second one is on state "Iniciar" ("Start" in english I gess) and it should say "Detener" ("Stop"). If you click on it once then it doesn't change, the client stops trying to connect to the server and the button says: (this time right) "Iniciar" ("Start"). If you click once again the button's behaviour is right, switching between "Iniciar" and "Detener" depending on the state of the client. 

So it's just an issue with the initializing of the button, not a big problem but sometimes is confusing.

**Comment by nlyan** [comment]
Related to #5330 ?

**Comment by FranWatcher** [comment]
Yes, it seems the same problem

**Comment by XinyuHou** [comment]
Duplicates to #5330
