### ISSUE TITLE
Only ASCII chars write from Windows to Mint

### ISSUE THREAD

**Issue by QuAzI** [symless/synergy#5328]
In my case Windows 7 works as primary machine (server) and notebook with Mint 17 as second.
When EN language selected in Windows - all works fine. When other language selected (BY, RU or other cyrillic as example) selected in Windows - text can't be typed on Mint.

Version 1.8.1-beta-2ed3d26 on both machines

**Comment by XinyuHou** [comment]
Duplicates to https://github.com/symless/synergy/issues/4280
