### ISSUE TITLE
Current date is used for build date in about page

### ISSUE THREAD

**Issue by QuAzI** [symless/synergy#5329]
Build date wrong in about window?

![_2016-05-13_10 37 49_10 37](https://cloud.githubusercontent.com/assets/1897605/15241247/5715c5da-18f7-11e6-89c2-b407c7e85a63.png)

**Comment by alexvanacker** [comment]
Reproduced on 1.8.2-stable-36cd521 Ubuntu 64

**Comment by nlyan** [comment]
Oops that's embarassing. Thanks guys.

**Comment by nlyan** [comment]
Fixed in 1.8.4
