### ISSUE TITLE
Service state buttons inconsistent

### ISSUE THREAD

**Issue by QuAzI** [symless/synergy#5330]
Sometimes one of this items wrong. Service works at this moment.

![synergy-2016-05-13_11-29-46_inconsistent](https://cloud.githubusercontent.com/assets/1897605/15242350/7062ef34-18fe-11e6-8b14-bf07e3565118.png)

Version: synergy-master-beta-2ed3d26-Windows-x64

**Comment by nlyan** [comment]
Related to #5327 ?

**Comment by QuAzI** [comment]
Yes, looks like one problem

**Comment by XinyuHou** [comment]
Duplicates to #4836
