### ISSUE TITLE
Synergy interacting strangely with Jetbrains Intellij 

### ISSUE THREAD

**Issue by nortain** [symless/synergy#5331]
I have a windows 7 64-bit server and a Macbook Pro 10.11.4 client.  When using synergy if I don't have focus of intellij I am unable to type text into the text editor portion of the screen.  The behavior is strange because I can still manipulate text in the editor but cannot type new characters.  For example I am able insert new lines by present enter and I can delete text if I have it highlighted but cannot type in any regular ascii characters.  To be able to get the cursor to show up in intelli I need to interact with the menus in some way.  The fastest way I've found to do this is by hitting shift twice which brings up a quick context search popup.  When you click on it, it'll immediately disappears but then the cursor will become visible within the ide and it can be used as normal until you lose focus of the editor by clicking on another window.  This is all running on the client and focus is properly regained if I jump from the client to the server and then back to the client.  But if I have two windows open on the client, one being intellij and another being a terminal windows, as soon as I click on the terminal I am unable to get a cursor to show back up in intellij.  If I close synergy this behavior disappears and reverts to normal.  Normal behavior being that when you click someone in one of intellij's editors that a cursor shows up immediately where you clicked.  I didn't notice this behavior occurring  on the macbook until after upgrading the OS from yosemite to el capitain.  Still the problem seems to lie with synergy as this unusual behavior disappears as soon as you disconnect the client from the server.

**Comment by XinyuHou** [comment]
@nortain 
Which version of Synergy are you using?

It sounds like a sticky key issue.

Please follow this guide for raising an issue.
https://github.com/symless/synergy/wiki/Issues

This issue will be closed until we have more information.

**Comment by nortain** [comment]
Hi Jerry,
I had thought at one point the issue was related to a possible sticky key
issue but it is not that. Sticky key issues are inconsistent where as this
problem always happens. I have noticed it in a few different applications
and the common then among them is that they are all java applications.  So
it looks like going from a widows server to a Mac client synergy won't
select or gain focus on java applications. At least not so that the
keyboard is entirely working.  The mouse for example can highlight text but
if you press command and c nothing gets copied.  The delete key can delete
text but you cannot type new text in.  Another java application I saw this
behavior was DBVisualizer which is a java built database tool.  When
switching focus between something like Intellij and DBVisualizer each and
every time synergy loses the ability to type text.  The only way to gain
focus of one of these applications once it is lost is to interact with the
application via another interface.  Most commonly I find this can be done
by using the mac menu and selected about from the application's apple menu
at the top of the screen.  I can give a brief walk though of how this would
play out.

For example say I have a macbook I am connected to via synergy and it has 2
applications open, intellij and db visualizer.  Say i have focus on
intellij and everything is working fine.  Now if I decide I need to type in
something into db visualizer I would normally move the mouse over to the
application, click on it, then start typing.  Only since the last update
this doesn't work.  The mouse shows dbvisualizer has focus, and you can
highlight text with the mouse and even right/command click to open up the
context menu but you cannot type text from the keyboard.  And now that
you've lost focus from inteillij, if you move the mouse back over to that
and click on it and try typing no text will show up there either.  The
ability to type into either of these applications until you interact with
the application via the mouse.  So I can do this by clicking on the
inteillj menu at the top of the apple bar at the top of the screen and
clicking "About Intellij".  That brings up the intellij splash screen which
you can just click anywhere on the screen to make it go away, but once you
do that you'll get a blinking cursor in intellij and you'll be able to type
again just fine until lose focus to another application.  I have been using
this setup professionally for years but as of the most
recent synergy update all java applications seem to require this extra step
to be able to gain focus to an app.

Thanks,
-Mike


On Fri, Jun 3, 2016, 10:15 AM Jerry (Xinyu Hou) <notifications@github.com>
wrote:The z

**Comment by anands82** [comment]
I am running to the same problem

Steps to reproduce (on the client host)
1. Open IntelliJ (ver 15.0.6). Open file to edit.
2. Switch to another application using mouse click.
3. Switch back to intellij using mouse click.
4. Cannot edit open files in intellij, even though some keys (Enter, Backspace) work.

Synergy Version:
Server: Synergy 1.7.4 on Ubuntu 12.04.5
Client: Synergy 1.4.17 on OSX 10.11.5
