### ISSUE TITLE
Client disconnect during UAC dialog interaction

### ISSUE THREAD

**Issue by jamesmacwhite** [symless/synergy#5334]
**Server:**

* OS: OS X 10.11 El Capitan
* Synergy Version: 1.7.6

**Client:**

* OS: Windows 10 Professional
* Synergy Version: 1.7.6 (Running with Elevated mode enabled)

When a UAC dialog appears the connection with Synergy is dropped with a client disconnect message in console, then a few seconds later, the client will reconnect. Upon interacting with the UAC dialog box i.e. Yes/Cancel, the connection is once again dropped before reconnecting again a few moments later.

In addition similar behaviour occurs under the Windows 10 lock screen when screen saver has been activated and then resumed.

**Comment by jamesmacwhite** [comment]
Possibly related to #5139

**Comment by XinyuHou** [comment]
@jamesmacwhite 
This is by design. Doing so give Synergy a chance to restart using a elevated mode.
