### ISSUE TITLE
Korean Language Selection Correction

### ISSUE THREAD

**Issue by jenelcohen** [symless/synergy#5338]
In the language selection setting, the spelling of "Korean" (한국의 meaning of Korea) needs to be corrected to (한국어 meaning Korean language).

**Comment by Kim-BoungSeok** [comment]
Hi. jenelcohen

We look forward to fix the upper part. Thank you.

**Comment by XinyuHou** [comment]
@jenelcohen 
Thank you for letting us know.

We are planning to pay for professionals to do the translation in the future which could this issue.
