### ISSUE TITLE
Left shift doesn't work in Windows

### ISSUE THREAD

**Issue by QuAzI** [symless/synergy#5339]
Sometimes Left Shift doesn't work in Windows 7 Pro AMD64 EN SP1 while Synergy is running.
After stopping all works fine.

As example: WinAPI.GetAsyncKeyState(VK_LEFTALT)

Version: synergy-master-beta-2ed3d26-Windows-x64

**Comment by XinyuHou** [comment]
@QuAzI 

> As example: WinAPI.GetAsyncKeyState(VK_LEFTALT)

What do you mean by this?

**Comment by QuAzI** [comment]
It is just code example from C# which doesn't work while Synergy run

**Comment by XinyuHou** [comment]
Please give us more details about this issue. 

Here is a guide for raising an issue. 
https://github.com/symless/synergy/wiki/Issues

This issue will be closed until we have more information.
