### ISSUE TITLE
Modifier settings broken on OS X client

### ISSUE THREAD

**Issue by tomasnagy** [symless/synergy#5343]
Changing the modifier keys on a Windows server have no effect on a OS X client.
This seemed to be working in an earlier version.

Server: Windows 10
Client: OS X 10.11.4

Both systems are running version 1.7.6 of Synergy.

**Comment by nlyan** [comment]
Hi, thanks for the issue report. you say this seemed to be working in an earlier version, do you perhaps have a known good version number?

**Comment by tomasnagy** [comment]
Revert back to 1.6.3, changed the modifier keys and updated back to 1.7.6 fixed my problem. Can't reproduce it now, probably some incompatible config. This can be closed, thanks for the quick response!
