### ISSUE TITLE
three key combination never send to cline

### ISSUE THREAD

**Issue by cmdwin32** [symless/synergy#5346]
I can't send three key combination from PC Servrer to OSX Client like Command+Shift+Right

**Comment by XinyuHou** [comment]
Please give us more details about this issue. 

Here is a guide for raising an issue. 
https://github.com/symless/synergy/wiki/Issues

This issue will be closed until we have more information.

**Comment by XinyuHou** [comment]
Please give us more details about this issue. 

Here is a guide for raising an issue. 
https://github.com/symless/synergy/wiki/Issues

This issue will be closed until we have more information.
