### ISSUE TITLE
Incompitable with other hotkey bindings program when elevated

### ISSUE THREAD

**Issue by ashenkin** [symless/synergy#5348]
As reported in the forums (http://synergy-project.org/forum/viewtopic.php?f=16&t=1561&p=4697#p4697), Synergy 1.7.6 is breaking hotkey bindings in other programs on Windows.

Synergy 1.7.6
Windows 7 x64

**Comment by slothbag** [comment]
+1

Can't use my windows media controls even when focus is on windows or even on the target app.

**Comment by slothbag** [comment]
I was getting this issue before, but I just installed latest 1.8.2 and if windows has focus then the multimedia keys work again..

**Comment by XinyuHou** [comment]
@ashenkin 
Is this correct that hotkey stop working when Synergy is running on elevate mode and service uses elevate mode on boot up?

**Comment by moltendorf** [comment]
I have this issue as well. I fixed it by restarting the synergy service after I logged in and all my other apps were already running. In my case I've automated it by using an old app I used to rely on before SSDs, r2 Startup Delayer, by adding my AutoHotKey, etc. stuff and checking the ensure app finishes launching before running "C:\Windows\System32\schtasks.exe /Run /TN Synergy" which refers to a scheduled task that's set to run manually and does "net stop Synergy" and "net start Synergy".

You could probably move my stuff out of a scheduled task and into a batch script, but I made the scheduled task with a delay of 2 minutes after logon before I got tired of waiting 2 minutes and reinstalled r2 Startup Delayer.

Or just manually:

1. Synergy service running already.
2. Log in.
3. Wait for all apps to start (AutoHotKey, Razer Synapse, Logitech Gaming Software).
4. Stop Synergy service.
5. Start Synergy service.

**Comment by XinyuHou** [comment]
> It seems that the service that runs at Windows startup is running elevated until I stop and start it which solves the problem.

**Comment by popcorn9499** [comment]
I seem to be having this same issue here myself on synergy 1.8.8 just wanted to note it still seems to be a issue however i cant get the software to work at all. im using logitech gaming software for my hotkeys

**Comment by popcorn9499** [comment]
Extra note. my mouse works fine however its just my keyboard that it cant seem to see for some weird reason

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
