### ISSUE TITLE
Mac -> Mac: ' converted to ` when typing

### ISSUE THREAD

**Issue by dwt** [symless/synergy#5351]
When I forward my mouse & keyboard from my mac to my mac, the forwarded machine always types ` when I type '. This is especially annoying when coding. :/

(Version: Current, I haven't yet found out where to look up the version number. See also #5350 for that)

**Comment by XinyuHou** [comment]
Duplicate to #4280

**Comment by dwt** [comment]
Are you sure this is the same issue? Both macs have identical keyboard layouts and other characters seem to transfer without problems (though I haven`t done an exhaustive test of course).
