### ISSUE TITLE
Drag and drop folders between machines

### ISSUE THREAD

**Issue by dwt** [symless/synergy#5352]
Problem: When I try to drag a folder from my server to the client, I get a file on the desktop that contains some gibberish.

Solution: Support folder drag and drop.

**Comment by nlyan** [comment]
Thank you for reporting your basket of bugs. Does this only effect folders? Can you provide a hexdump of the resulting gibberish? The following command at a terminal will do this.

`hexdump -C filename `

**Comment by dwt** [comment]
When hex dumping the resulting file (incidentally called `neuer order`) this is the result:

```
dwt@atlan ~ % hexdump -C /Users/dwt/Desktop/Neuer\ Ordner 
00000000  00 00 00 70 00 00 00 70  0b 00 ff ff ef cd ab 89  |...p...p........|
00000000  00 00 00 70 00 00 00 70  0b 00 ff ff ef cd ab 89  |...p...p........|
00000010  80 bd 02 a3 80 f8 15 7b  00 00 00 00 00 00 00 00  |.......{........|
00000010  80 bd 02 a3 80 f8 15 7b  00 00 00 00 00 00 00 00  |.......{........|
00000020  00 00 00 00 00 00 00 00  00 02 00 00 00 02 00 00  |................|
00000020  00 00 00 00 00 00 00 00  00 02 00 00 00 02 00 00  |................|
00000030  01 00 00 00 00 04 00 00  ff 04 00 c0 00 00 00 00  |................|
00000030  01 00 00 00 00 04 00 00  ff 04 00 c0 00 00 00 00  |................|
00000040  00 00 00 00                                       |....|
00000040  00 00 00 00                                       |....|
00000044
```

**Comment by vanowm** [comment]
Windows users would be happy have just a file drag'n drop or at least via copy/paste...

**Comment by dwt** [comment]
@nlyan Does this make any sense to you?

**Comment by danielzen** [comment]
I noticed this today. I'm on macOS 10.12.5. Basically in place of a folder I get a gibberish file on the destination machine. In my case, I was copy from client to server with v1.8.8

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
