### ISSUE TITLE
Impossible to install on portable Windows

### ISSUE THREAD

**Issue by Pingger** [symless/synergy#5356]
Hi,
I'm using a portable Windows 7 Professional on an USB-Stick (because the internal HDD isn't changeable and there is a linux installed, which won't run on usb). And also an alternative Windows 10 Enterprise (thx to my univerity at this point) on another. On neither system it is possible to install synergy properly, because "Installation directory must be on local Harddrive". The local harddrive is in ext4 (linux), so it isn't mountable in windows. 
I'm currently using a unpacked version of the installer (7zip to unpack) and renamed the "GuiProgram" to "GuiProgram.exe" and renamed the "libgcc_s_dw2_1.dll" to "libgcc_s_dw2-1.dll".
It now works to the point that I have to start the program manually, because it's impossible to install the service corractly.
Could you please fix this issue.
Greetings
Pingger

(The Reason why I want to use Synergy is the following: When I'm Home, my Notebook automatically logs into the WLAN and I place it right next to my normal PC, now I simply want to move the mouse to the notebook and back ...)

**Comment by Pingger** [comment]
I found a workaround:
`msiexec /i <installer> /passive /norestart`
this makes the installer ignore that the default location is a usb drive, but you can't change the install dir.

**Comment by XinyuHou** [comment]
@Pingger 
Did you find a solution for this issue?

**Comment by Pingger** [comment]
I only found a temporary workaround using the given `msiexec` command, but This makes the installer chose the default settings. I normally change installation directories other settings in the installation assistant. So I'd say the issue is still valid.

**Comment by XinyuHou** [comment]
@Pingger 
Hope this could help
http://stackoverflow.com/questions/8839978/install-msi-with-msiexec-in-a-specific-directory

**Comment by Pingger** [comment]
Yes, thanks.

With this I could finally install it in a different Directory ...

Don't ask why I didn't get the Idea to search for "msiexec change 
install directory". I always search for synergy ... Now all makes sense =)

Greetings


PS: This is still an issue of the installer I would like to see fixed 
(e.g. check if system drive and then ignore if usb drive)
