### ISSUE TITLE
Drag to select text (in any application) doesn't work

### ISSUE THREAD

**Issue by njwatkins** [symless/synergy#5359]
Cannot select text in any application (word, notepad etc.) by clicking and dragging. Double clicking to select a word is OK.

Stopping the Synergy service fixes the issue. Effects server and client.

Same as this from 2014 [http://superuser.com/questions/704656/cant-select-text-with-mouse-in-word-or-outlook]

Win 10 x64 10.0.10586 build 10586
Synergy 1.7.6

**Comment by XinyuHou** [comment]
Duplicates to #3044
