### ISSUE TITLE
Traceback crash: sharing clipboard between win10 and linux mint 17.2

### ISSUE THREAD

**Issue by oriolrius** [symless/synergy#5360]
I'm using synergy 1.7.6 64 bits in:
* Windows 10 with two 1080p displays (client)
and
* Linux Mint 17.2 Cinnamon 64-bit with two 1080p displays (server)

and sometimes (about 10 times per day) my synergy server crashes with that error:

[synergy-traceback.txt](https://github.com/symless/synergy/files/293870/synergy-traceback.txt)

it happends specialy when I copy something in the clipoard.

Thanks and regards.

Oriol

**Comment by nlyan** [comment]
This appears to be the LOG call [here](https://github.com/symless/synergy/blob/v1.7.6-stable/src/lib/platform/XWindowsClipboard.cpp#L1121). This should be an easy fix

**Comment by oriolrius** [comment]
Nops, I have the same problem.

**Comment by oriolrius** [comment]
After upgrading to synergy 1.8; it works perfectly!!! 

happy to be user of synergy for a long time :+1:  :)
