### ISSUE TITLE
Error: Get plugin list failed in wizard because 301 redirect

### ISSUE THREAD

**Issue by spronkey** [symless/synergy#5361]
Just trying to install Synergy 1.7.6 fresh download on my Mac (10.11) and receive the following error:

Error: Get plugin list failed, an error occurred.

Server response:

(html html html) 301 Moved Permanently. Probably due to the synergy-project to symless transition.

Cmon guys.

**Comment by nlyan** [comment]
This should be fixed now. If not, please comment and I will reopen.
