### ISSUE TITLE
Drag and drop? Why not copy and paste?

### ISSUE THREAD

**Issue by bilogic** [symless/synergy#5362]
Hi,

I used synergy 1.3.1 in the past and the term ```drag and drop``` in this new series got my undivided attention. It was a struggle to understand how it worked and I was finally brought back down to earth in this FAQ https://github.com/symless/synergy/wiki/User-FAQ#Can_Synergy_do_drag_and_drop_of_files_between_computers

Why not perform a samba transfer instead? (Yes, I'm specifically referring to admin shares on windows). It can cover trees of folders, unicode or not, it just wipes out many of the other issues I see related to drag drop. Furthermore, many of the supported OSes have samba in some shape or form.

Just a suggestion and would like to hear the reasons why it is not considered. Thank you.

**Comment by XinyuHou** [comment]
This looks like a support ticket. Please contact our help desk.
https://synergy-project.org/contact/ 

The main reason we implement drag and drop is we aim to be more seamless. If you still have a strong  feeling about file copy and paste, please create another issue as enhancement. Here is a guide.

https://github.com/symless/synergy/wiki/Issues
