### ISSUE TITLE
Cannot drag and drop Mac OS X Applications

### ISSUE THREAD

**Issue by dmland** [symless/synergy#5363]
Dragging a Mac OS X application from one machine to another via Synergy results in a 102-byte file (which the OS interprets as an "Application (Classic)" instead of the full application.

This is likely related to #5352 because Mac OS X applications are implemented as a special kind of folder.

As a workaround: right-click the desired app, select "Compress Whatever.app" from the context menu, drag the resulting ZIP file across, then unzip on the receiving end.

I am running 1.8.1-beta-b253d99 on both ends, which are Mac OS X 10.9.5 and 10.11.5.

**Comment by XinyuHou** [comment]
Duplicates to https://github.com/symless/synergy/issues/5352.

Please sit tight, we are planning this feature.
