### ISSUE TITLE
"Auto-config" incorrectly chooses client's own IP on startup

### ISSUE THREAD

**Issue by twig** [symless/synergy#5366]
Sometimes the auto-config selects the client device's IP, making this feature fairly useless.

Reproducable on 1.7.6 Mac OSX client, haven't tried on other systems.

**Comment by nlyan** [comment]
Could you provide a screenshot of this, and details of your network configuration?

Did you switch from server to client mode in the GUI prior to this happening?

**Comment by twig** [comment]
I tends to happen when I turn on the client prior to connecting the host to the network.

Client < WiFi < Router < WiFi < Host

I just tried it 5 times and it connected reliably lol
I'll try to debug it next time it happens.
