### ISSUE TITLE
Synergy 1.7.6 | mouse select intermittently broken

### ISSUE THREAD

**Issue by cooch17** [symless/synergy#5370]
Using 1.7.6 -- Win 7 pro server, GNU/Linux (RHEL 6.xx) client. Generally, works as advertized (and I've been using Synergy for 7-8 years), but there is a nasty, somewhat unpredictable bug -- when running the synergy service, synergy periodically 'breaks' mouse select in some (but not all) applications. For example, can't use the mouse to select lines in Word, or a PDF file, or even fairly 'simple' ASCII editors I use with some frequency). 

I confirm the problem is with synergy since if I temporarily halt the synergy service, problem vanishes. 

And, the problem is intermittent --- when I first start up Word (say), I can use the mouse to select text with no problems. However, if I leave Word, do something in another application (I refuse to use the diminutive 'app', ever), then come back to Word, can't use the mouse to select anything. Seems like synergy is fighting with the clipboard buffer (which I suspect is involved when selecting lines). 

At any rate, this is a major pain in the butt (or some other sensitive body part) -- here's my vote for making this a priority fix.

**Comment by nlyan** [comment]
Duplicate to #3044
