### ISSUE TITLE
Activation fails on SSL error

### ISSUE THREAD

**Issue by ShortyFR** [symless/synergy#5379]
When trying to activate the 64bit synergy software on Ubuntu 16.04, I get this error :

An error occurred while trying to sign in. Please contact the helpdesk, and provide the following details.

```
Code: 1
Error: [2016-06-14T17:07:41] ERROR: curl perform error: SSL peer certificate or SSH remote key was not OK
[2016-06-14T17:07:41] FATAL: An error occurred: CURL perform failed.
```

It tries to reach synergy-project.org, which doesn't have a valid HTTPS certificate for this name.

**Comment by ollieh** [comment]
I get the same issue on Windows, I try through the wizard and get an error popup with error code 12038 which apparently corresponds to:
```
   12038       ERROR_INTERNET_SEC_CERT_CN_INVALID
               SSL certificate common name (host name field) is incorrect.
               For example, if you entered www.server.com and the common
               name on the certificate says www.different.com.
```
Annoying!

**Comment by nlyan** [comment]
This was a problem with our web server and is now fixed.
