### ISSUE TITLE
Add user-friendly description to change log items

### ISSUE THREAD

**Issue by jenelcohen** [symless/synergy#5385]
Problem:

The change log only shows fix titles, which can be too technical for many users to understand. 

Solution:

Add descriptive elements that are meaningful to a wider audience of users, and that clarify exactly what issues it fixes.

**Comment by XinyuHou** [comment]
@jenelcohen 
Changelog is really not a place for details, we will try our best to make the issue title user friendly.

We used to have a blog to write down the release details. I'm not sure if we still use it but gonna check out.

**Comment by XinyuHou** [comment]
Changelog shouldn't include exclusive details
