### ISSUE TITLE
Clipboard doesn't work in linux client

### ISSUE THREAD

**Issue by brunovianarezende** [symless/synergy#5386]
Env:

- client: ubuntu 14.04 latest version
- server: ubuntu 14.04 latest version

I can't copy from server to client nor from client to server. When the client is windows or mac os x, all works ok.

**Comment by nlyan** [comment]
Can you confirm what version of Synergy you are using, and whether this has previously worked for you. When did it stop working?

**Comment by brunovianarezende** [comment]
. Server: 1.7.6 - Ubuntu (14.04)
.  Client: 1.4.12, protocol version 1.4 - Ubuntu (14.04)

It never worked for me.

**Comment by nlyan** [comment]
I would recommend upgrading the client to v1.7.6. A lot of changes to clipboard operations were made in 1.7.x

**Comment by brunovianarezende** [comment]
Trying. I'll update the issue after I install it.

**Comment by nlyan** [comment]
Also, any logs you have would be welcome. To be honest, we're surprised 1.4 and 1.7 are even connecting.

**Comment by brunovianarezende** [comment]
After upgrading client to 1.7.6 it worked.

**Comment by nlyan** [comment]
Thanks
