### ISSUE TITLE
Tab Completion not working - Linux

### ISSUE THREAD

**Issue by Zpeedy** [symless/synergy#5391]
Master - Dual Boot (Linux Mint 17.3 & Windows 10)
Slave - Windows 10

Works under 1.8.1-beta-b25ed99 but fails under 1.8.3-beta-723a8a9.  Issue appears when running putty on slave.  Occurs when attempting to change directory using tab completion or when attempting to insert tab into text document using nano.  Nano reports 'Unknown Command'

Possibly related to #5373 ??

**Comment by mf-lit** [comment]
Same here.

Synergy version 1.8.3-beta
Server: Ubuntu 16.04 64bit
Client: Ubuntu 16.04 64bit

**Comment by XinyuHou** [comment]
Merge this into #5373
