### ISSUE TITLE
Option to disable scroll lock function

### ISSUE THREAD

**Issue by DeeJayhX** [symless/synergy#5396]
---EDIT: For anyone ruthlessly google searching the subject as I was, who might stumble upon this, you can set a hotkey (mine is Alt+z) to toggle off the screen lock to bypass this issue. It's still very annoying and would've been much better to just have an option to disable it, so I will leave the issue open.---

The Scroll Lock on my keyboard Activates/Deactivates the backlighting to my keys based on the scroll lock status. So in order to use Synergy, I cannot have the lights on. Some people's physical KVM switches use scroll lock as the activation button. Can you please add a checkbox in options to disable this function... If I truly want it, I'll go set my own in hotkeys.

Thank you!

**Comment by ericR-123** [comment]
I second this notion!

**Comment by BadDataBadData** [comment]
Getting an option for this would be huge for me. Especially when you have the window hidden, the fact that there's a button that could be being used for a different application that has a silent functionality in Synergy is difficult to work around.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
