### ISSUE TITLE
Synergy interferes with text insertion programs

### ISSUE THREAD

**Issue by Mithrass** [symless/synergy#5400]
I use two programs that insert characters into the keyboard stream, namely KeePass, a password container, and AutoHotkey, a simple text injector.  If Synergy is running when the PC emerges from hibernation, neither of those programs will work properly.  To fix it, all I have to do is restart the Synergy service.  Then it's ok till next time the machine hibernates.  It seems likely that Synergy is blocking the keyboard input channel.

A clue: AutoHotkey will always inject text into the Windows Command prompt, but not into any other window until I restart the Synergy service.

Obviously there is a workaround - I can restart it in the Task Manager or write a script to restart the service, but it took me a while to find out what was wrong, so you might like to take a look at it.

**Comment by nlyan** [comment]
Hi, do you have problems with Keepass or AutoHotKey outside of a hibernation scenario, or does this *only* occur after hibernation?

I suspect the solution here will be to have Synergy automatically restart itself after being awoken a hibernation/sleep.

**Comment by Mithrass** [comment]
Hi Andrew.  Thanks for your response.

As far as I can tell, the problem only occurs when the PC emerges from 
hibernation and is cured by restarting the Synergy service, until next 
hibernation.

I have tried to automate the restart using Net Use, but there are issues 
abut it needing to run elevated and there is no Restart command - you 
have to Stop, wait a bit then Start.

Can you suggest a way to do it?

Best regards - Frank

Frank Ainscow MA PhD C.Eng MIET FRSA
Chartered Electronics Engineer

Interfacing Limited

E: frank@interfacing.co.uk

**Comment by darkdragon-001** [comment]
Same problem here! 
I use Windows 10. I didn't test if the problem also occurs on Ubuntu.
This is really annoying!

**Comment by posterberg** [comment]
I never hibernate my desktop pc, it just either on or completely shutdown, and I still have this problem with Keepass.

**Comment by Mithrass** [comment]
The problem I had was fixed some time ago - well done Symless.  It stopped happening with release 1.8.2 or perhaps 1.8.5.  Either way it's fixed now.  What you are seeing must be something else - I can imagine there are lots of things that can go wrong with capturing the keyboard input.
