### ISSUE TITLE
lost brackets in OS X -> Ubuntu

### ISSUE THREAD

**Issue by alexandercerutti** [symless/synergy#5404]
Hi there,
I'm using OS X as server and Ubuntu 15.10 as client and when I type with Magic Keyboard for chars { , [ ,  ], } (and I don't know if there are others), in Ubuntu they do not show up, as if they got lost.
I tested this on OS X with versions 1.7.6 and 1.8.0 beta and on Ubuntu with 1.7.6.
Thank you.
Alexander.

EDIT: I though only after seeing this (https://github.com/symless/synergy/issues/5394) that it could be related to an unsupported Alt-GR.

**Comment by XinyuHou** [comment]
@alexandercerutti 
What is your OS, keyboard layout and input languages?

For example, I'm using English Windows 10, UK keyboard and UK english input on my server.

**Comment by alexandercerutti** [comment]
Hi, I'm usingItalian layout on Italian Keyboard. Thank you, both on server and client

**Comment by thusby** [comment]
The same is an issue using Norwegian keyboards with Ubuntu 16.04 as the server and windows 10, 
Input language: Norwegian and English
OS's is English on both platforms

**Comment by XinyuHou** [comment]
Duplicate to #4280
