### ISSUE TITLE
Typing password on server lock screen is sent to a client

### ISSUE THREAD

**Issue by dannystaple** [symless/synergy#5405]
I am using Synergy 1.7.6 with a Windows Server,and a linux Fedora client.
When the windows server is locked (for example away from keyboard), and then I go to unlock it, synergy has retained focus on the client machine and sends the password there.
I have to disconnect the server physically, or kill synergy processes on the client to be able to unlock the server again.

The mouse pointer has disappeared, and  cannot be moved back to the server.
Elevate mode does not have any effect.

**Comment by XinyuHou** [comment]
Duplicates to #5294

**Comment by XinyuHou** [comment]
I have moved your comment into the duplicated issue
