### ISSUE TITLE
Official request for beta access

### ISSUE THREAD

**Issue by pmario** [symless/synergy#5407]
Did you just send the "Beta Signup" mail the third time??? ... __Yes I do want to have beta access!__

I'm tired to fill out forms, that look and feel like phishing mails. So I'll request beta access here, where I have full control over the content. 

For other readers: [Here is a gist of the full text](https://gist.github.com/pmario/96f11dde60694f01bf5ce6473afbbaee#file-synergy-beta-signup) ... You probably know how you can use it. 

----

 * Full Name: follow the link: https://github.com/pmario
 * e-mail: follow the link: https://github.com/pmario

 * What is your main operating system? 

 [x] Windows 10
 [x]  Mint, Ubuntu or other Debian Linux
 [x] Others: Ubuntu 16.04 (latest if available)

 * How often do you want to test our beta versions? *

 [x] Once a month
 [x] Once every two weeks

 * Why do you want to be on the beta list? *

 [x] To see if there are any new features
 [x] To see if this beta includes a fix I'm waiting for
 [x] To test the bugs you fixed, following steps to reproduce

 * If we announce a bug fix and you find it still happens, what do you do? *

 [x] Raise a ticket on GitHub

 * What will you do if you find a bug NOT related to the beta version announcement? *

 [x] Raise a ticket on GitHub
 
 * What information do you think would be helpful for us to fix a bug? *

 [x] What I think might be causing it
 [x] Steps to reproduce, logs and workarounds

 * What would you tell us if you couldn't reproduce a bug reliably? *

 [x] Logs and workarounds

`*` required

**Comment by XinyuHou** [comment]
@pmario 
Sorry, github issue tracker really isn't a place for signing up beta testing. Please use our original email form.
