### ISSUE TITLE
Infinite UI cycle on first launch

### ISSUE THREAD

**Issue by jtoly** [symless/synergy#5417]
If you don't have a synergy.conf file to browse to when you first launch the app, and you select the Browse... button thinking you do have one, you get stuck in an endless cycle when you cancel from the Browse... dialog because an alert appears telling you must select a config file, and it's action button sends you back to the Browse... dialog.

Eventually you try hitting the Escape key during the "cancel" dialog phase and you can break out, but it's not a comforting experience.

**Comment by XinyuHou** [comment]
@jtoly 
Could you give us a step by step instruction to reproduce?

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
