### ISSUE TITLE
Bonjour installation failed in windows 10

### ISSUE THREAD

**Issue by lucas-g-omnidrone** [symless/synergy#5418]
Version 1.8.1 beta f7377d6 on a fairly fresh install of win 10.
Steps: 
- installed synergy 
- on main window tick client box, - accept the popup proposing to install bonjour
=>  nothing happened
- tick "autoconfig" box and accept the popup about installing bonjour
=> download popup showin, nothing happed , after a few min "not responding"  on the title. No network activity it seems (didn't recheck all the way)

**Comment by XinyuHou** [comment]
Duplicate to #5420
