### ISSUE TITLE
Issue #4327 1.8.1-beta-f7377d6 

### ISSUE THREAD

**Issue by pslack** [symless/synergy#5425]
The drag and drop does n ot work between my machines regardless of the enable setting.  Is drag and drop supposed to work?  I have OSX 10.9.5 as my server and Windows 7 as my client , I attempted to drag a file across with setting off and on and the drag and drop did not work in any case

in my client I have this error message

[2016-07-02T12:52:54] ERROR: failed to get desktop path, no drop target available, error=2

**Comment by darkenvy** [comment]
I also want to confirm that I cannot drag and drop between OSX 10.9.5 (client) & Ubuntu 14.04 LTS + Gnome3 (host). The cursor does not leave the screen when dragging a file.

This feature is not important to me however I don't mind doing extensive testing 👍 .

Dragging from host (linux) to client (osx 10.9.5):
```
[2016-07-02T12:08:31] DEBUG1: try to leave "werkinsheir-Linx" on right
[2016-07-02T12:08:31] DEBUG: locked by mouse buttonID: 0
[2016-07-02T12:08:31] DEBUG1: locked to screen
```
Dragging from client (osx 10.9.5) to host (linux):
`No log changes in Synergy; However OSX 10.9.5 changes desktops (spaces) when held against the left/right of the screen long enough.`

**Comment by jonmaustin** [comment]
After installing the 1.8.1 beta, drag and drop did not work despite it being enabled in the check box. After disabling it - during which time drag and drop did not work - and then reenabling it, I have been able to drag and drop with some degree of success. Even so, the functionality is unpredictable in terms of success - it's currently working about once out of five tries.

Success dragging and dropping from Win10 server to Win10 client, Win10 client to Win10 server, Win10 server to OSX client. Other paths not tested.

**Comment by Zpeedy** [comment]
Drag and drop not working on Linux Mint 17.3 Master and Windows 10 slave

**Comment by demolitions** [comment]
Drag and drop not working on Arch Linux x64 (both server and client), same log messages as @darkenvy, "locked by mouse buttonID: 0"

**Comment by XinyuHou** [comment]
Hi guys,

Really appreciate your feedback.

Please directly reply via our beta email next time.

Right now we haven't implemented drag and drop on Linux. And this feature is still prototype. We will polish it in the future. Please follow this ticket instead #5419
