### ISSUE TITLE
1.8.1-beta - install mouse issue

### ISSUE THREAD

**Issue by jeremeguenther** [symless/synergy#5426]
I had an issue where I installed the latest beta on two windows 10 x64 machines.  It worked great, then I rebooted, when I moved my mouse to the client screen it slammed into the left side of the screen and got stuck there, that is the side away from the server screen.

I had to restart the service to fix the issue.  I have not tried another reboot since.

**Comment by jeremeguenther** [comment]
I have noticed another issue.  I'm not certain that this one is specific to this version, however I do not recall it happening quite so frequently before.

If my main computer locks, but the secondary computer is not locked, I can move the mouse to the secondary computer after waking up the primary, but then it gets stuck on the left hand side of the screen again, only this time it was invisible.  Restarting the service on the client machine fixed it.

**Comment by jeremeguenther** [comment]
It is not a consistent issue.  So far it has only occurred when the master computer has been asleep.

**Comment by jeremeguenther** [comment]
I have reproduced it three times now by having my client win 10 x64 computer running as normal, server win 10 x64 computer goes to sleep.  I press a key on the keyboard to wake the server up, I do not log into the server, I move the mouse to the client screen, it gets stuck on the left side of the client screen invisible.

**Comment by XinyuHou** [comment]
@jeremeguenther 
Duplicate to #5294

We really appreciate your feedback on our beta test. Please directly reply to the beta test email next time, which would raise a ticket on our zendesk.
