### ISSUE TITLE
Issue 4893 - 1.8.1-beta-f7377d6

### ISSUE THREAD

**Issue by jonmaustin** [symless/synergy#5427]
I'm not sure what "Full version including branch" is but here's what it says:

Version: 1.8.1-beta-f7377d6

Screen grab attached.

![2016-07-02_16-52-15](https://cloud.githubusercontent.com/assets/20260794/16542795/abe783d4-407d-11e6-8c86-710d280f8f31.png)

**Comment by nlyan** [comment]
Thats fine Jon, thanks.
