### ISSUE TITLE
Synergy-Client crash during modal admin dialog opened on Server

### ISSUE THREAD

**Issue by Tramiko** [symless/synergy#5428]
Hello

If I start an installation, during the modal dialog is open for access the admin access, the synergy-client is crashed.

That problem is existing since many versions, include the current beta: 

[synergy_server.txt](https://github.com/symless/synergy/files/344812/synergy_server.txt)
[synergy_client.txt](https://github.com/symless/synergy/files/344813/synergy_client.txt)
![clp6a75](https://cloud.githubusercontent.com/assets/20261588/16543290/f964f3d6-40cc-11e6-88cc-145e53c73bf6.png)

Regards, Tramiko

**Comment by XinyuHou** [comment]
@Tramiko 
This is by design. Synergy would restart itself when a UAC pops up as the previous one doesn't have enough privilege.
