### ISSUE TITLE
Fails to install on Mac and Windows

### ISSUE THREAD

**Issue by stugol** [symless/synergy#5429]
I installed the latest Synergy on my Mac, and it refused to download the 'ns' plugin. No explanation was given.

I installed the latest Synergy on my Windows system, and the installer just plain crashed.

If you can't get even these basic things right after so many years of development, you should just give up. I want my $10 back.

**Comment by XinyuHou** [comment]
Please log into you account on our website and contact our customer service.
https://symless.com/account/

Thanks
