### ISSUE TITLE
Various translation issues - de_DE (Windows)

### ISSUE THREAD

**Issue by jochenkirstaetter** [symless/synergy#5431]
Choosing German - Deutsch as the UI language gives various incomplete locations.

![synergybeta_activation-de_de](https://cloud.githubusercontent.com/assets/7329802/16552706/3f9b10bc-41d4-11e6-8133-045b3e425a0a.png)
![synergybeta_activation2-de_de](https://cloud.githubusercontent.com/assets/7329802/16552705/3f99f0ec-41d4-11e6-8a98-0242b71a9358.png)
![synergybeta_serverclient-de_de](https://cloud.githubusercontent.com/assets/7329802/16552707/3f9e0498-41d4-11e6-8ead-eebfc05af74e.png)
![synergybeta_uitranslation-de_de](https://cloud.githubusercontent.com/assets/7329802/16552708/3fa02214-41d4-11e6-90bb-8f494d9f3071.png)

Also, it is a bit strange that a change of language can only be done through the Setup Wizard. It would be more practicable to offer a language switching in the main menu, ie similar to Skype.

**Comment by XinyuHou** [comment]
@jochenkirstaetter 
You can change languages via settings, please click Edit->settings

We are planning to find some professional companies to help us do the localization. Please sit tight.

**Comment by jochenkirstaetter** [comment]
FYI: Already started working on the German translations. Might be able to provide a PR these days, depending on my daily workload.
