### ISSUE TITLE
Settings doesn't assert certificate's existance

### ISSUE THREAD

**Issue by jochenkirstaetter** [symless/synergy#5435]
The Setup Wizard has been completed succesfully and the generated SSL certificates have been removed manually afterwards. The Setting dialog doesn't recognise that there is no SSL certificate available and not only offers the option "Use SSL encryption" but also (pre-)selects the checkbox.

![synergybeta_sslencryptioncertifcate](https://cloud.githubusercontent.com/assets/7329802/16552991/68d77608-41d6-11e6-8afd-58cf8c8da0b4.png)

The checkbox should be unchecked and disabled in case there are no SSL certificates present.

**Comment by djcalkins** [comment]
I have this same issue in Windows10.   But would like to add, after using the beta tester serial and reverting back to my personal (basic subscription) account, the SSL check box stays checked and activated.   Linux, and OSX seem to disable SSL automatically after reverting back to my personal account.   As the original reporter said, deleting the SSL folder also keeps the box checked and activated.

**Comment by nlyan** [comment]
This will be solved by #5627.
