### ISSUE TITLE
No tray icon visible (Linux-Ubuntu 16.04)

### ISSUE THREAD

**Issue by EvanPokroy** [symless/synergy#5437]
I'm running my server on Ubuntu 16.04. 
synergys -c /home/epokroy/synergy.conf -d DEBUG1

I don't have a tray icon visible. 
Version 1.8.1-beta-f7377d6 (in theory)

**Comment by alexandercerutti** [comment]
Me too, but with OS X 10.11.6 as server. Anyway, this not just from 1.8.1 but I don't know from which version.

**Comment by EvanPokroy** [comment]
That's true, it also happened on earlier versions.

**Comment by legonigel** [comment]
This might be related to #5304.

**Comment by XinyuHou** [comment]
@alexandercerutti 
Could you send us some screenshots?

**Comment by alexandercerutti** [comment]
![](https://cloud.githubusercontent.com/assets/5442545/16731527/db665cf0-4778-11e6-96ce-dec67343c372.png)

Here's what I see with 1.7.6 and 1.8.1 beta

**Comment by XinyuHou** [comment]
Duplicate to #5304 

@alexandercerutti 
I have created a new issue for you, please follow this instead #5457
