### ISSUE TITLE
Mouse click stops responding on client

### ISSUE THREAD

**Issue by adriano85** [symless/synergy#5440]
Hi, First bug that I'm logging, so please bear with me.
I am experiencing random instances of the mouse clicking action not responding on the client machine. Server is  running Windows 10 Pro TP BUILD 14372 and Client is running Windows 10 Pro (std release version.) 
The movement of the the mouse and the keyboard is still active, only the left and right click does not respond.

The work around I have found for this is to take the mouse to the server screen, click and drag on the server desktop, and immediately the click operations are available on the client again.

Thanks for a great products!
Adrian

**Comment by yidhoe** [comment]
I can +1 this, I thought it was an update to my mouse software but having seen this I switched mice earlier and removed my mouse drivers, using standard cheapo mouse with base drivers and it still happening. :(

**Comment by brianmullinsbsd** [comment]
+1 for me. Same work around as adriano85.

**Comment by yidhoe** [comment]
Sorry I responded quickly and missed the work around, I do something similar only I don't drag anything, I just click anywhere on server PC then clicks works on clients again.

I would say this has been happening for a few versions now but I put it down to my Wireless Mouse going into Standby and Synergy not waking it from client some how, last week or two I have used the mouse plugged in and still been getting it however. :(

**Comment by nlyan** [comment]
Hi guys, is this a new issue in Windows 10 technical preview, or does it effect regular installations of Windows 10?

**Comment by brianmullinsbsd** [comment]
@nlyan 

Not sure, but I just had it happen on the server, too. Clicks stop doing anything. Did a CTL-ALT-DEL then ESC and it was back.

**Comment by adriano85** [comment]
My server has been always been running Windows technical preview and the client is running the regular Windows 10. I haven't tried to replicate it on a regular / regular setup. It happened on the official version of synergy before I joined the beta program as well (if that helps)

**Comment by XinyuHou** [comment]
Please check this issue #5226, if it's duplicated, please let me know

**Comment by adriano85** [comment]
Hi XinyuHou, It might be, I don't think it was only on the minimize of a window, but the effects seem the same. I will have to test to see if i can replicate it. Thank you.

**Comment by adriano85** [comment]
The issue can definitely be reproduced by minimizing a window on the server pc. I will continue to test to see if it occurs without the minimizing. Would you like me to rather respond on #5226 ?

**Comment by XinyuHou** [comment]
@adriano85 
Yes, please.
I will mark this as duplicated.
