### ISSUE TITLE
Pointer locks off screen when moves from virtualbox machine to other physical

### ISSUE THREAD

**Issue by charlessteiner** [symless/synergy#5442]
Using Fedora 24 x64 as synergy server and vitrualbox host
windows 10 64 VM Guest (with current guest additions)
other physical machine windows 10 64
Synergy 1.8.1 build date July 5, but I've noticed this prob since I've been using synergy (a few years)

When I'm working in this virtual machine  and I move the pointer off the screen to another physical box I cannot bring the pointer back to host or VM (synergy warning: can't leave screen) without first hitting the right-ctrl key to release.  

I've had this problem with a Ubuntu host, too.  And Windows 8 as VM Guest.

Update:
fyi, I usually do not need to click right-ctrl to release from the VM, it goes between host and VM fluidly

**Comment by XinyuHou** [comment]
This looks more like a support ticket.

Please log into you account on our website and contact our customer service.
https://symless.com/account/

Thanks

**Comment by charlessteiner** [comment]
It's reproducible. 

For future reference, what makes it a support ticket issue?
