### ISSUE TITLE
Image Copy crashes server instance and locks up synhawk

### ISSUE THREAD

**Issue by Mutmatt** [symless/synergy#5446]
I feel like this has to be a dupe but I thought i'd throw it out just in case.

#### Server: 
Win 10 
Symless 1.8.1-beta
![image](https://cloud.githubusercontent.com/assets/872224/16629271/cdbee984-437a-11e6-894a-481e16893e39.png)

#### Client:
Win 10
Symless 1.8.1-beta
![image](https://cloud.githubusercontent.com/assets/872224/16629281/d833ad8c-437a-11e6-9ee9-658f43784c1a.png)

### Reproducing steps 
- On server copy an image that is 500px(or greater) x 500px(or greater) (give or take, the bigger the harder the crash)
- Move mouse to the client

Logging in the server instance shows that the app stopped working and tries to reconnect to the synhawk and continually fails.

### Workaround:
copy some text and restart the synergy process in the task manager

**Comment by XinyuHou** [comment]
We really appreciate your feedback.

But please directly reply via beta email next time.

Can you test this nightly? Please leave any further comment in #4768
http://symless.com/nightly?filter=85bbbd4
