### ISSUE TITLE
No tray Icon in Windows 10

### ISSUE THREAD

**Issue by Mindcloud** [symless/synergy#5449]
Version: 1.8.1-beta

Not seeing a tray icon, which would be very useful since I usually shut off synergy when playing full screen games.

**Comment by jtyle6** [comment]
lifehacker.com/how-to-customize-the-system-tray-icons-in-windows-10-1724097781

**Comment by oucil** [comment]
Closing the app hides it completely, leaving only the background service, you can use "Window -> Hide" to keep it in the tray.  I've added a feature request for what you and I undoubtedly are used to, a preference to "Close to the tray", here: #5454

**Comment by XinyuHou** [comment]
Duplicate to #5454
