### ISSUE TITLE
When UAC is initiated on client, control returns to server

### ISSUE THREAD

**Issue by ezb2013** [symless/synergy#5450]
When accessing something on the client that invokes the UAC, control and focus is returned to the server.  It should stay with the client.

**Comment by xpac1985** [comment]
Same here. One client is Windows 8 Enterprise, the other Windows 7 Enterprise. Both 64bit, both with current patch level.

**Comment by XinyuHou** [comment]
@ezb2013 
Sorry for the inconvenience.

There is a restart feature when UAC pops up to gain admin privilege. We just added an enhancement which is if Synergy is already elevated, service won't restart Synergy.
