### ISSUE TITLE
File drag and drop not working on various OS combinations

### ISSUE THREAD

**Issue by Bazzek** [symless/synergy#5453]
I personally cannot drag and drop between Xubuntu 16.04 and Kubuntu 16.04. In Issue 4327 i have seen quite a few people with the same remark but different OS combinations.

This topic is started to allow others to chip in and hopefully figure out what and why.

Typical for me:
I can drag the file and my cursor just stops on my screen at the edge of my server (and client), even if the flag enable drag and drop is on. The cursor does not change. In the log of synergy it doesn't show any respons to me trying to drag a file to the other side.

I tried files from my desktop as well as from krusader on both sides

**Comment by XinyuHou** [comment]
Duplicate to #5419

**Comment by Alion** [comment]
Just bought Synergy after reading good reviews: drag & drop not working between OSX 10.11.6 and Windows 10 Pro 1607 (OS Build 14393.187)
Also copy buffer (copy/paste) not working.
Is ther a money back protocol.

**Comment by nlyan** [comment]
@Alion if you want your money back please contact service@symless.com

Drag and drop should work in both directions between OS X and Windows, but as currently implemented you can only drag and drop small files and only to the Windows desktop.
