### ISSUE TITLE
Wrong keys are sent

### ISSUE THREAD

**Issue by Cpuroast** [symless/synergy#5458]
1. The number keys at the top of the keyboard are being sent to the client as KP0-KP9(Numpad) instead of 0-9.
2. The "/" key next to the shift key isn't getting sent correctly where as the "/" on the Numpad does.

Client: OSX 10.11.5 - synergy-v1.8.2-beta-85bbbd4-MacOSX1011-x86_64.dmg
Server: Windows 8.1 x64 - synergy-v1.8.2-beta-85bbbd4-Windows-x64.msi

**Comment by XinyuHou** [comment]
This is a side effect from the fix of #2765. We are investigating it. Please leave further comments in #2765
