### ISSUE TITLE
Windows 10 Server showing multiple IP addresses and Mac unable to connect as client after week vacation

### ISSUE THREAD

**Issue by nicklisterman** [symless/synergy#5462]
I was away for a week and since my return I have been unable to use Synergy.  Nothing has changed with either configuration and I noticed the server now shows multiple IP addresses which was never the case before.  I've tried using each of the IP addresses the server shows with no luck.

<img>http://imgur.com/TxEidSL</img>

<img>http://imgur.com/9rbp7ky</img>

**Comment by nicklisterman** [comment]
I found that my internal server IP changed while I was away and I setup a DHCP reservation for the server back to the previous IP address.  Things are working now but why would an internal IP address change mess this up?  I even manually entered my internal server IP after the change with no luck.

**Comment by XinyuHou** [comment]
This looks more like a support ticket. We use Github issue tracker to track new bugs or enhancement. 

Please log into you account on our website and contact our customer service.
https://symless.com/account/
