### ISSUE TITLE
Windows 10: successful compile, non-working Binaries

### ISSUE THREAD

**Issue by chrber** [symless/synergy#5463]
Hi,

I have built synergy using the sources provided in this repo using Visual Studio 2015, have installed all dependencies and successfully compiles using the RELEASE target. I have binaries, but when I start running it, nothing happens. Now I have a problem, not being a Windows developer, how do I debug if this is not running.

I have a patch that I can post, which shows my changes, if needed. The basic changes were that I had to add the visual studio version to the command1.py and I had to add a compiler flag, because certain pragmas were not supported any longer, but maybe this is already the culprit. I had lots of:

xkeycheck.h(87): fatal error C1189: #error :  The C Standard Library forbids macroizing keywords. Enable warning C4005 to find the forbidden macro.
--> solved by preprocessor flag _XKEYCHECK_H

Also during building the msbuild command was not found. Some googling found a result how to fix this.

Could you please help me to get this built on a windows 10 machine with visual studio 2015?

Thanks.
Christian

**Comment by XinyuHou** [comment]
@chrber 
Please check out our v1.8.3 branch
