### ISSUE TITLE
Mixed Licences Prevent Usage

### ISSUE THREAD

**Issue by agentflippy5** [symless/synergy#5469]
Steps to reproduce:
1.One server(Ubuntu, Synergy Pro), one client(Win. 10, Synergy Pro), one client(Ubuntu, Synergy Basic)
2.Connect clients to server
3.Attempt to move mouse across screens

Expected:
Synergy will continue to work on all systems normally, except for systems running Synergy Basic, which would be disallowed from connecting to server.

Actual:
After server log acknowledges new client connection(from Synergy Basic), mouse is restricted to server screen, and can't move to any other screen.

**Comment by XinyuHou** [comment]
Synergy Pro would automatically enable SSL, which cause it not connected to non-SSL client or server. You can disable it in settings.
