### ISSUE TITLE
Using Symless with Paralles on a mac

### ISSUE THREAD

**Issue by allangagnon** [symless/synergy#5472]
I have Symless on my Mac and I have Symless both version shown below.

The Symless works great on the MacBook Pro and If I am using LogMeIn on my Mac to connect to server in my office.

However if I am using Symless via my MacBook Pro to access My Paralles the Shift Keys seem to not work. I try to use any special characters and all it get is the numeric value in my Parallels Virtual Machine.

Any constructive criticism is greatly appreciated.

Thanks & Regards 
Allan F. Gagnon

**Comment by XinyuHou** [comment]
This looks more like a support ticket. We use Github issue tracker to track new bugs or enhancement. 

Please log into you account on our website and contact our customer service.
https://symless.com/account/
