### ISSUE TITLE
Server side issues on Windows 7 64-bit

### ISSUE THREAD

**Issue by ezb2013** [symless/synergy#5473]
I have encountered the following issues on the server side with Windows 7.  With Synergy Pro running, I am unable to highlight text with the mouse, tools using vk_packet method to simulate keystrokes does not function, sometimes when typing it acts as if the windows key is depressed (have to press windows key to restore functionality), and sometimes unable to get the cursor to switch to other computers.

**Comment by XinyuHou** [comment]
@ezb2013 
>  tools using vk_packet method to simulate keystrokes does not function, 

Could you give us more information, like reproduce steps and Synergy version?

**Comment by ezb2013** [comment]
I'm using an application called PhraseExpress which is a text expander allowing you to type in "hotwords" that will then automatically expand the text.  This functionality works fine on the server until after moving the mouse and keyboard to a client computer and then back.  Once returning to the server, the text expansion no longer works until you stop Synergy.

**Comment by XinyuHou** [comment]
@ezb2013 
It looks like you raise 4 issue within 1 ticket.

Please split it into 4 separate tickets and give us more information as below.

- Synergy version
- OS information
- Logging with log level set to Debug
- Reproduce steps
