### ISSUE TITLE
ctrl + left arrow ctrl+right arrow doesn't work for switching spaces

### ISSUE THREAD

**Issue by prophoto** [symless/synergy#5474]
I am testing a nightly build 85bbbd4 on Windows 10x64 as the server and macOS Sierra Beta as the client. The keyboard shortcut ctrl + left arrow or ctrl + right arrow does not work. Since I am using a pc mouse that does not have gesture support like a Magic Mouse or Apple Trackpad having the keyboard shortcut is kinda important. I tried it with a Mac keyboard directly attached to the Mac and it works fine. As does a PC keyboard attached to the mac.

Ideas?

**Comment by prophoto** [comment]
Found another issue here. Can't type the forwardslash '/' key on macOS Sierra Beta with Win10x64 as Server. Forwardslash works fine when the guest is El Capitan.

**Comment by XinyuHou** [comment]
This is caused by the fix from #2765 
We are investigating it.

**Comment by nlyan** [comment]
@prophoto Are you still experiencing that / issue on Sierra?

**Comment by prophoto** [comment]
Forwardslash and backslash both are working on last Sierra Beta with 1.8.2-stable-36cd521, I am updating my dev box now to Sierra final and I'll get back to you. Switching spaces is not working on Sierra last beta.

**Comment by prophoto** [comment]
Just checked Sierra final and I cannot hit control and right arrow to switch spaces.

**Comment by nlyan** [comment]
@prophoto the bug you're looking for is probably #5592

**Comment by prophoto** [comment]
thanks
