### ISSUE TITLE
regression in unittests in 1.8.1-stable 

### ISSUE THREAD

**Issue by anthraxx** [symless/synergy#5475]
Hi, I'm a package maintainer of a distro and a regression in the unittests keep me from rolling out the 1.8.1 update.
The following issue happens for both, 32bit and 64bit builds by trying to access a nullptr 

I cant release this update until the  the tests are passing, please take a look

```
gdb ./bin/unittests
(gdb) r
[...]
[ RUN      ] GenericArgsParsingTests.parseGenericArgs_helpCmd_showHelp

Program received signal SIGSEGV, Segmentation fault.
0x08133e1f in MockApp::help() ()
(gdb) bt
#0  0x08133e1f in MockApp::help() ()
#1  0x081c490c in ArgParser::parseGenericArgs(int, char const* const*, int&) ()
#2  0x08130c4a in GenericArgsParsingTests_parseGenericArgs_helpCmd_showHelp_Test::TestBody() ()
#3  0x081f3138 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#4  0x081ebf59 in testing::Test::Run() ()
#5  0x081ec0bc in testing::TestInfo::Run() ()
#6  0x081ec1b5 in testing::TestCase::Run() ()
#7  0x081ec491 in testing::internal::UnitTestImpl::RunAllTests() ()
#8  0x081ec7f0 in testing::UnitTest::Run() ()
#9  0x080e59ab in main ()
(gdb) x/i $eip
=> 0x8133e1f <_ZN7MockApp4helpEv+63>:	mov    (%eax),%edx
(gdb) p $eax
$1 = 0
(gdb) p $edx
$2 = 135473168

```

**Comment by XinyuHou** [comment]
@anthraxx 
Could you give us the commit hash value you are testing?

**Comment by anthraxx** [comment]
https://github.com/symless/synergy/commit/d196ec5e9a1bd60abb413ba6f7b9ded94a4141af
https://github.com/symless/synergy/archive/v1.8.1-stable.tar.gz

**Comment by anthraxx** [comment]
@XinyuHou any news? still holding back this update for the distribution.

**Comment by nlyan** [comment]
@anthraxx We have a workaround for this in 1.8.2, so you should be able to crack on with that. Let us know if you continue to have a problem and we'll reopen

**Comment by anthraxx** [comment]
@nlyan @XinyuHou nothing changed

```
[ RUN      ] GenericArgsParsingTests.parseGenericArgs_helpCmd_showHelp
Segmentation fault      (core dumped) ./bin/unittests
```

would make more sense if you point me to fixes beforehand so I can test and verify...

 v1.8.2-stable
36cd521
