### ISSUE TITLE
Connected but wont enter client screen

### ISSUE THREAD

**Issue by DotNetRockStar** [symless/synergy#5476]
Hi there.  I am running Windows 10 on two machines.  After installing synergy on both and configuring them correctly I get the following behavior:
1) When I set up server PC on the left and client on the right I would expect to see my mouse to be able to enter on to my monitors on the client machine once the mouse leaves the far RIGHT monitor on my server machine.  No matter where my mouse is in this configuration, Synergy never switches me over to the client machine.
2) When I set up server PC on the right and client on the left I would expect to see my mouse to be able to enter on to my monitors on the client machines once the mouse leaves the far LEFT monitor on my server machine.  This DOES happen as it should.
3) I read somewhere that doing the following will solve some kind of problem that I might have been experiencing: Right click on application -> options -> Compatibility -> click "Disable display scaling on high DPI settings".  Once I did this Synergy would switch screens from the server to the client BUT Synergy would enter a bugged state where I lost the mouse and keyboard until I stopped synergy on the client machine.  Synergy seemed to switch context to the client machine but then it freezes the mouse.

I had this working perfectly on Windows 7 and I am really needing a solution to my issue.  

My setup is as follows:
- Server: 4 monitors, windows 10, Synergy 1.7.6
- Client: 1 monitor, windows 10, Synergy 1.7.6

Thanks in advance.

**Comment by XinyuHou** [comment]
This looks more like a support ticket. We use Github issue tracker to track new bugs or enhancement. 

Please log into you account on our website and contact our customer service.
https://symless.com/account/

Thanks

**Comment by smorris-TW** [comment]
Hi Synergy team,

I have  just encountered the same problem, with only two screens.

I installed Synergy today (2016-10-28) on two Windows 10 machines.  When my client is set to the right, although the logs show that it has connected I cannot move the mouse to the client.  When my client is set to the left, Synergy works as expected.

@XinyuHou @DotNetRockStar - was it actually a support issue (should I contact customer service) or was it a bug?

Thanks.

**Comment by DotNetRockStar** [comment]
It never got resolved for me. Not sure if it is a support ticket or what.
