### ISSUE TITLE
Unable to click java installer buttons

### ISSUE THREAD

**Issue by xurious** [symless/synergy#5478]
$Server and $Client both Window 10 x64.
Synergy version 1.7.6

When installing java setup 8u91 from java.com on the $Client, I'm unable to click on any of the installer buttons (ok, cancel, etc). It's repeatable.

I'm able to use the local $client mouse to click the buttons, and I'm able to use the $server mouse and keyboard as normal for the rest of the sytem.

**Comment by XinyuHou** [comment]
@xurious Could you give use some reproduce steps and screenshots?

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
