### ISSUE TITLE
Enable SSL by default so it works in autostart before boot (in DMs)

### ISSUE THREAD

**Issue by SamuilDichev** [symless/synergy#5479]
**Server**
 - **OS**: Windows 10
 - **Synergy version**: 1.17.6

**Client**
- **OS**: Linux Mint 18 Sarah (Cinnamon)
- **Synergy version**: 1.17.6

So I tried enabling autostart of the client (synergyc) before logging in (Since I don't want a second keyboard just for inputting my password) by adding to `/etc/mdm/Init/Default` the following lines:

```bash
/usr/bin/killall synergyc
while [ $(pgrep -x synergyc) ]; do sleep 0.1; done
/usr/bin/synergyc --enable-crypto 192.168.0.5
```

This never worked, no matter how I tried. The same lines but without the `--enable-crypto` always worked though. I could use kb/m from the host / server PC before even logging in. I also tried ways of extracting some of the start line in variables like so:

```bash
synhost=192.168.0.5
/usr/bin/killall synergyc
while [ $(pgrep -x synergyc) ]; do sleep 0.1; done
/usr/bin/synergyc --enable-crypto "$synhost"
```

And out of desperation even tried stuff like
```bash
syndir=/usr/bin/synergyc
synhost=192.168.0.5
/usr/bin/killall synergyc
while [ $(pgrep -x synergyc) ]; do sleep 0.1; done
"$syndir" --enable-crypto "$synhost"
```

Eventually, I extracted the lines from the first example into its own script prepended with `#!/bin/bash` and put that into `/etc/profile.d`. That works fine, however, only launches after logging in (obviously). Still better than starting it manually, but I still need a second keyboard to input my password when logging in and I really don't like that. Which is why I propose making SSL enabled by default and to be honest, most people would turn this on anyway, wouldn't they? It's always better to have it ON when available, unless I'm missing something, right?

**Comment by XinyuHou** [comment]
This looks more like a support ticket. We use Github issue tracker to track new bugs or enhancement. 

Please log into you account on our website and contact our customer service.
https://symless.com/account/

Thanks

**Comment by SamuilDichev** [comment]
@XinyuHou, although I disagree as this IS an enhancement request, I have contacted customer service. Thanks.
