### ISSUE TITLE
Copy / Paste between PC and Mac crash

### ISSUE THREAD

**Issue by StephBel** [symless/synergy#5481]
Severity: crash
Reproducibility: random

On a Windows 7/64 PC select "Copy" (right mouse click) in a Powerpoint document
On a Mac OSX 10.11.5 select "Paste" (right mouse click) in a Keynote document

Synergy on PC crashes.

Signature du problème :
  Nom d’événement de problème:	APPCRASH
  Nom de l’application:	synergyc.exe
  Version de l’application:	0.0.0.0
  Horodatage de l’application:	57767c5f
  Nom du module par défaut:	synergyc.exe
  Version du module par défaut:	0.0.0.0
  Horodateur du module par défaut:	57767c5f
  Code de l’exception:	c0000005
  Décalage de l’exception:	000000000003b8d2
  Version du système:	6.1.7601.2.1.0.256.48
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	9978
  Information supplémentaire n° 2:	99786244bef8481251672fb26fa996e8
  Information supplémentaire n° 3:	8d45
  Information supplémentaire n° 4:	8d451aff1ab8b419067f47ae9a029f63

**Comment by XinyuHou** [comment]
Duplicate of #4768
