### ISSUE TITLE
Lag after Windows 10 update

### ISSUE THREAD

**Issue by fearnot2790** [symless/synergy#5486]
I am using a Surface Pro 3 running Windows 10 Pro version 1511 and OS Build 10586.420 as the client for Synergy. My server is a MacBook Pro Retina running El Capitan version 10.11.5. After the most recent update of Windows 10 Pro, Synergy has started to lag a lot. If I type some text or click on something in the client it takes about 4-6 seconds for the computer to respond. Dragging the cursor across the screen in the client is very choppy and not smooth at all. I have restarted Synergy as well as the Surface, but am sill having the lag issue.

**Comment by XinyuHou** [comment]
@fearnot2790 
Are you using WIFI?

**Comment by fearnot2790** [comment]
@XinyuHou 
Yes I am using WiFi. Speeds in my office are 155 Mbps down and 86 Mbps up.

**Comment by mprice64** [comment]
I am also experiencing this using Windows 10 as the server and Mac OS X 10.11.5 as the client, it makes Synergy unusable.

When I use Mac OS X as the server, the problem doesn't exist, but this isn't a good solution as the mouse and keyboard are attached to my desktop computer.

**Comment by XinyuHou** [comment]
@fearnot2790 
Could you check the CPU usage from Synergy on both of your server and client sides?

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
