### ISSUE TITLE
Server never locks if client has mouse

### ISSUE THREAD

**Issue by alanhoyle** [symless/synergy#5487]
Synergy 1.7.6 on client and server.  Client is OSX 10.11.6. Server is Ubuntu 16.04.

If the mouse is left alone on the client, the server's screensaver never turns on, potentially exposing user data.  If the mouse is moved to the server, the screensaver turns on after a fraction of a second, but there's enough time for a nefarious attacker to paste bad commands into a Terminal window creating a security problem (e.g. "rm -rf /").

Problem has been apparent for several versions of Synergy and OSes.

**Comment by XinyuHou** [comment]
Duplicate of #4229
