### ISSUE TITLE
Typo on Setup Synergy ->Activate window

### ISSUE THREAD

**Issue by hobothulhu** [symless/synergy#5490]
Under the Skip Activation button, the word recommended is misspe
![synergytypo](https://cloud.githubusercontent.com/assets/17790372/17062782/fbc382b4-4ff9-11e6-9073-3a84e6fddf61.PNG)
lled as 'recommanded'

**Comment by XinyuHou** [comment]
Nice spot.

I have merged this issue into #5471

Please directly reply via beta email next time for related issues.
