### ISSUE TITLE
Wizard 1.8.2-rc1

### ISSUE THREAD

**Issue by alexandercerutti** [symless/synergy#5492]
I'm writing here because of confirming that Serial box bug has been solved BUT I think that "Skip activation" description should not overflow like in the screenshot. Moreover, I would like to suggest to implement a continue "click" when Enter key is pressed, especially when focus is on input boxes.
![schermata 2016-07-22 alle 19 57 18](https://cloud.githubusercontent.com/assets/5442545/17066246/830ec7dc-5046-11e6-9fb1-6e816fdbed5d.png)

**Comment by XinyuHou** [comment]
Nice spot.

I have merged this issue into #5471

Please directly reply via beta email next time for related issues.
