### ISSUE TITLE
Server SSL setting lost on version upgrade

### ISSUE THREAD

**Issue by elklein** [symless/synergy#5493]
I leave SSL turned off on my server because I keep all of my clients unregistered (too hard to register them securely since I often need to wipe and reset client machines multiple times a week, and I don't have a secure automated way to easily enter credentials on the clients).

When I upgraded to 1.8.2-rc1 today, my server started using SSL (or at least it started enforcing that clients must connect with SSL when SSL is enabled on the server, not sure which). My clients would no longer connect because they are unregistered (and thus cannot use SSL). Once I disabled SSL on the server from preferences again, it started working. This is the first time I've had to do this after a Synergy update, so it appears to be new behavior.

**Comment by XinyuHou** [comment]
@elklein 
Did you see wizard after you installed 1.8.2-rc1?

**Comment by elklein** [comment]
Hmmm. I THINK so? I'm not absolutely sure now.

NOTE: It's possible that I only installed 1.8.2-rc1 on my server and not all of my clients. So if this is the sort of thing that could be explained by that sort of mismatch, then you're probably looking at some combination of PEBKAC and non-obvious behavior.

**Comment by XinyuHou** [comment]
@elklein 
We increased wizard number in 1.8.2 to force users to rerun wizard which would regenerate plugins and enable SSL if you are a Pro user.
