### ISSUE TITLE
Keystrokes combination

### ISSUE THREAD

**Issue by afdsilva** [symless/synergy#5496]
I'm a Unity programmer using MonoDevelop as IDE, for some reason Synergy and MonoDevelop seems to be fighting each other to understand on the client what keystrokes are being pressed. 
Both client and server are Windows 10 and some keys simply don't work on MonoDevelop, and that´s probably MonoDevelop fault for being an terrible program, but I was poking around to see if I could fix it somehow and noticed that Synergy are sending "weird" keystrokes in shortcut setting, for example: "ctrl+alt+q" shows "ctrl+alt+/", "ctrl+alt+c" shows "ctrl+alt\u20a2", since others combinations don´t show anything weird, like "ctrl+alt+a" I thought was a Keyboard Layout issue, since both my laptop and desktop (client and server) use the same kind of keyboard (Portuguese (Brazil ABNT)) I can´t really change the layout (because there are special keys in my freaking keyboard like "ç"), although when changing to US, it screws even mode.
The problem is in MonoDevelop the "/" (forward slash) are recognized as ctrl+alt+q and ctrl+alt+c = cltr+alt+w, this is just some examples to what are show in Key Bindings in MonoDevelop.
While I'm aware this is a MonoDevelop issue (I really wanted to change IDE, but I don´t want to ever deal with VS), I´m reporting it anyway because even on server side synergy seems to be showing the wrong character so most likely is a layout problem that may need to be addressed and hopefully fix my problem.

[synergy-server.txt](https://github.com/symless/synergy/files/379841/synergy-server.txt)
[synergy-client.txt](https://github.com/symless/synergy/files/379842/synergy-client.txt)

I'm appending the logs while trying to keypress some of the keys that gives problems, hopefully it's of some use for you guys.

**Comment by XinyuHou** [comment]
Merged into #4280
