### ISSUE TITLE
raw input on games

### ISSUE THREAD

**Issue by Duwaynef** [symless/synergy#5497]
When playing games on raw input, instead of the mouse being center of the screen it moves around behind the application, interfears while speed running some games when opening menu and needing mouse control fast.

**Comment by XinyuHou** [comment]
Could you give us Synergy version, OS information and reproduce steps?

**Comment by Duwayne6** [comment]
win10(64), newest as of today synergy pro 1.8.1 stable.

open synergy, hit start, open game that uses raw input(Talos principle), move ingame, click ESC to get mouse movement back, mouse wont be in center of the screen, issue for speed running Talos principle.

**Comment by pmario** [comment]
@Duwayne6 
Where did you download this version? I just can see 1.7.6

**Comment by Duwayne6** [comment]
After installing 1.7 w/e it pops up saying there is a newer version and
auto installs.idk if having the pro version changes that

**Comment by XinyuHou** [comment]
> mouse wont be in center of the screen, 
Do you mean when you press esc, you are expecting cursor in the center?

> issue for speed running Talos principle
Do you mean the speed of your cursor is too high in the game?

Is this running on your server side?

**Comment by Duwayne6** [comment]
so yes this is on the server side,

with synergy off the game uses raw input and the moment you hit ESC the
cursor is dead center everytime.
with synergy on you hit esc after moving the mouse around and the cursor is
somewhere random on the screen
based on your movement, i don't know if this means synergy is somehow
blocking raw input.

**Comment by XinyuHou** [comment]
@Duwayne6 
Could you try out our latest release, 1.8.2 please?

**Comment by Duwayne6** [comment]
i installed 1.8.2 and tried it for a bit and it seems fixed. i will try it a bit more extensively and report back.

**Comment by XinyuHou** [comment]
@Duwaynef 
Are you still experiencing this issue?

**Comment by XinyuHou** [comment]
Closed because of insufficient info.
