### ISSUE TITLE
Synergy has no control when used with Teleport

### ISSUE THREAD

**Issue by ylluminate** [symless/synergy#5510]
I am using two Macs side-by-side and use Teleport for this since it's a much more refined and cohesive experience. However, I do connect my left most Mac to another Linux box and I'd like to be able to take my cursor and mouse all the way around via Synergy.  What can be done to allow Teleport to control Synergy enabled devices?

**Comment by XinyuHou** [comment]
This looks more like a support ticket. We use Github issue tracker to track new bugs or enhancement. 

Please log into you account on our website and contact our customer service.
https://symless.com/account/
