### ISSUE TITLE
synergys crash on MacOS (10.11.6 15G7b) running 1.8.2-rc1-12e0120

### ISSUE THREAD

**Issue by elklein** [symless/synergy#5512]
Crash details follow. At the time of the crash, I had just copy-pasted something from somewhere (don't remember what precisely now).

Process:               synergys [21108]
Path:                  /Applications/Synergy.app/Contents/MacOS/synergys
Identifier:            synergy
Version:               0
Code Type:             X86 (Native)
Parent Process:        Synergy [552]
Responsible:           synergys [21108]
User ID:               501

Date/Time:             2016-07-28 11:55:49.487 -0700
OS Version:            Mac OS X 10.11.6 (15G7b)
Report Version:        11
Anonymous UUID:        6F090FE4-7AA9-BE1F-C847-344172499A72

Time Awake Since Boot: 430000 seconds

System Integrity Protection: disabled

Crashed Thread:        5

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000068
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x68:
--> 
    __TEXT                 00000000000d5000-000000000016c000 [  604K] r-x/rwx SM=COW  /Applications/Synergy.app/Contents/MacOS/synergys

Thread 5 Crashed:
0   synergys                      	0x00110e13 ClientProxy1_6::handleClipboardSendingEvent(Event const&, void*) + 19
1   synergys                      	0x00111326 TMethodEventJob<ClientProxy1_6>::run(Event const&) + 54
2   synergys                      	0x000e3b02 EventQueue::dispatchEvent(Event const&) + 98
3   synergys                      	0x000e2c8c EventQueue::loop() + 348
4   synergys                      	0x001329f4 App::runEventsLoop(void*) + 20
5   synergys                      	0x00149cae TMethodJob<ServerApp>::run() + 46
6   synergys                      	0x000f7b3c Thread::threadFunc(void*) + 140
7   synergys                      	0x000dd21c ArchMultithreadPosix::doThreadFunc(ArchThreadImpl*) + 76
8   synergys                      	0x000dc86b ArchMultithreadPosix::threadFunc(void*) + 75
9   libsystem_pthread.dylib       	0x98820780 _pthread_body + 138
10  libsystem_pthread.dylib       	0x988206f6 _pthread_start + 155
11  libsystem_pthread.dylib       	0x9881df7a thread_start + 34

**Comment by XinyuHou** [comment]
Merged into #4768
