### ISSUE TITLE
Clicking randomly stops working on Client when use a Windows server

### ISSUE THREAD

**Issue by risaku80** [symless/synergy#5513]
Hello, sometimes clicking (left or right) doesn't work on the client.  if you hover over items, quick tips display, but can't click.  Can't deduce what causes this, seems random.  Sometimes clickability returns on its own, other times I have to shut down Synergy on the Client and restart, and other times Logoff/Logon seems to work.

Thanks for yout help,

Roan

**Comment by migmruiz** [comment]
Confirmed on Windows 10 as both server and client

**Comment by xhpohanka** [comment]
I can confirm this behavior on Windows 10 server and Arch Linux (Cinnamon) client. I have feeling that it can be caused by Google Chrome...

**Comment by dsemi** [comment]
I've had this problem for a while now, just been dealing with it since it's more of an annoyance than anything else.  Windows 10 x64 server, Arch Linux x64 client.  When booting Windows and connecting the Arch client, all attempts to click on the client do nothing except trigger the Windows error bell.  Manually opening synergy and stopping then starting the server fixes the issue for me; at least until the next reboot.

**Comment by vanowm** [comment]
Probably the same bug that affect other programs on server, such as photoshop, when some features no longer work properly, such as simple selecting..

**Comment by bobberkarl** [comment]
Same problem. I'm on a Windows server with a windows client and an ubuntu client. It is quite irritating.
all on synergy 1.8.1-beta-f7377d6

**Comment by nlyan** [comment]
Can you guys please see if 1.8.2 helps at all?

**Comment by vanowm** [comment]
No, 1.8.2 has the same issue.
So far it seems happen only once after reboot. After clicking "apply" in Synergy window (no need to change anything) it fixes for good until next reboot.

Also, I don't know if it useful info or not, but when this bug occur, clicking at client produces the same sound effect as when Windows denies clicking if you click on a window which opened a modal window (for example, try click on Synergy window after you opened options window from it.

**Comment by bobberkarl** [comment]
Server windows 10 X64 build 10586 - Synergy 1.8.3-beta-fa9f30f
Client Ubuntu 16.04 64bits - Synergy 1.8.3-beta-f377d6

I don't have the click problem anymore with this update.

**Comment by dsemi** [comment]
Still reproduces on 1.8.2 for me.

**Comment by PeteM92** [comment]
Synergy 1.8.2: I have to stop server and restart server again in order to solve this problem.
server: Windows 10 x64 Pro Version 1511 Build 10586.545
client: Windows 10 x64 Home Version 1607 Build 14393.51

**Comment by risaku80** [comment]
It also work if you stop and restart client

**Comment by vanowm** [comment]
v1.8.3-beta-fa9f30f has the same issue, however this time I didn't need restart anything for it to fix itself, all I did was moved cursor back to server and opened and closed Synergy window. Next time will try move cursor first.

**Comment by vanowm** [comment]
Update: at least with v1.8.3-beta-fa9f30f on W10 x64 server and W7 x64 client, this bug occur, but the fix is simple: move cursor back to the server and click on taskbar, then go back to client and clicking now works. No need launch or restart Synergy program at all.

**Comment by PeteM92** [comment]
This does not work on my Synergy 1.8.3-beta-fa9f30f 
Only stop server and re-start server resolves click-problem.

**Comment by vanowm** [comment]
What about simply clicking on "apply" button in Synergy window? That worked for me previously without stopping server/service

P.S. using W10 x64 version 1607 build 14393.51
![](http://i.imgur.com/eKd6yDn.png)

**Comment by dsemi** [comment]
"Apply" restarts the server.

**Comment by nlyan** [comment]
This could be related to the fix we introduced in v1.8.2 for #3044 . Can any of you folks reconfirm that this issue occured with v1.8.1 and prior?

**Comment by jonl-percsolutions-com** [comment]
I have tested the 5513 clicking build and it appears to fix the issue.   I've been fighting with the issue and vmware vm's getting the mouse since upgrading to 1.8.2 and Windows 10 on my primary machine a few weeks ago.  It did not occur in version 1.7.4 on Windows 7, but I was unsure of whether or not the issue was with synergy or Windows 10.

**Comment by ninoz** [comment]
I have found this issue to happen when it appears something has the mouse focus on the server machine or a certain program is running.  If I run EA Origin i cant click, but as soon as I kill Origin I can click.

Other time I have found that killing certain tabs in Chrome will also return the click functions.

**Comment by jonl-percsolutions-com** [comment]
Whenever this problem occurs, the following error appears in the log: ERROR: failed to get desktop path, no drop target available, error=2

**Comment by vanowm** [comment]
#5542 suggests the clicking stops when server is idle a few minutes. Can anyone reproduce this? I can't.

Also, I have 100% success restoring clicking on client by clicking on server at a non-privileged window (browser or text editor) and then clicking on task bar (sometimes I might have to do it twice if non-privileged window was already in focus), no synergy restart is necessary.

Server: Windows 10 x64 built 1067, UAC enabled

**Comment by nlyan** [comment]
I'm raising the priority of this issue. We have an idea of what causes this but solving it is non-trivial.
