### ISSUE TITLE
After updating to 1.8.2 RC1 - on both server PC and Client - Client refused to connect

### ISSUE THREAD

**Issue by rmcginnis** [symless/synergy#5517]
**SERVER:**  MacBook Pro OS 10.11.6 / OS X El Capitan 64bit
**Client PC:** Windows 10 Pro 64bit 

On previous installs of betas on both my server and client, after updating  the program and installing synergy beta on my server pc and then my client pc I had no problems using keyboard and mouse.  It connected perfectly fine 

When I downloaded and installed 1.8.2 RC1 first on my server PC then on my client PC,  it wasn't connecting to the server PC.

1. First downloaded and installed 1.8.2 RC1 on the **server (MacBook Pro)**
2. Downloaded and installed  1.8.2 RC1 on client **PC (Windows 10 Pro/desktop)**
3. The server IP was blank and auto config wasn't checked. 
     - Previously when I installed two of the last beta builds, I didn't have this problem
4. I was informed by Synergy that Bonjour wasn't installed. 
     - Tried clicking yes to install Bonjour from Synergy - but the program keep locking up on me 

5. went online and downloaded Bonjour services, installed bonjour and the service automatically started after instal 
6. Re-opened Synergy 1.8.2 RC1 and now I was able to check auto-config, I clicked Start and still wasn't
 connecting - attached is the log window. 

[Synergy_Log.txt](https://github.com/symless/synergy/files/393683/Synergy_Log.txt)

**My WORKAROUND:**
Had to go into settings on both server pc and client PC and uncheck use SSL. I'm unsure if USE SSL was checked on the previous synergy beta, but I never had this problem before.

**Comment by XinyuHou** [comment]
This looks more like a support ticket. We use Github issue tracker to track new bugs or enhancement. 

Please log into you account on our website and contact our customer service.
https://symless.com/account/

Thanks

**Comment by vanowm** [comment]
Does it mean we are wasting our time even visiting this issue tracker?
Why is this issue tracker even exists then???!!!!
Are you kidding me?
