### ISSUE TITLE
Installation of 1.8.2 rc1 goes to new client wizard

### ISSUE THREAD

**Issue by Bazzek** [symless/synergy#5519]
When installing the debian package synergy-v1.8.2-rc1-12e0120-Linux-x86_64.deb the software gets installed, but first time run results in a setup wizard. 

This is very impractical if you only have a mouse connected to the client since you normally use Synergy.

Suggested way of behaving would be not overwriting the existing configuration and loading this upon start.

**Comment by XinyuHou** [comment]
We increased the wizard version so it's normal you see wizard page after installing 1.8.2-rc1
