### ISSUE TITLE
Logging level drop down in wrong location

### ISSUE THREAD

**Issue by serversage** [symless/synergy#5521]
I'm currently testing 1.8.2 RC1 on OSX 10.11.6 and have a weird location bug on one of my computers. In testing some of the bug fixes I was changing the "Logging Level" to Debug2. When I click the box it appears up above on "Language".  It's only happening on one Mac, and I can reproduce it across reboots and restarts of the App.  Steps:

1. Start Synergy
2. Click Synergy->Preferences
3. Click the "Logging level" drop down

I've attached a screen shot showing the bug. Again, this only happens on my Mac Pro, not my Macbook Pro - which is odd. I have tried changing my laptop to the exact same config as my desktop but to no avail. So, could be specific to me I guess.

![loggingleveldropdown](https://cloud.githubusercontent.com/assets/551355/17378445/e7ae554a-59b5-11e6-83c6-298e14ea9f43.png)

**Comment by nlyan** [comment]
Hmm, perhaps there is something gone awry loading the language list. Everything is fine on 10.11.6 here. Does resizing the GUI or reinstalling help at all?

**Comment by XinyuHou** [comment]
Closed due to inefficient info and not be able to reproduce.
