### ISSUE TITLE
Omega (Ω) symbol appears instead of @ on GB keyboard

### ISSUE THREAD

**Issue by harpss1ngh** [symless/synergy#5527]
This was previously reported in issue #62 a couple years ago (https://github.com/symless/synergy/issues/62)

The workaround within the issue works great for me to get around this but, I have pasted it below for your convenience. I guess you can try changing the symbol in the script if you have issues with other symbols for other keys such as "\" or  "/" or "|".

For reference I'm running 08th August's Nightly build. Server is Win 10 and client is Ubuntu 16.04.

#!/bin/bash

#Start ssh

killall ssh

sleep 1

ssh -f -N -L localhost:24800::24800 @

#Start Synergyclient

killall synergyc

sleep 1

synergyc localhost

#Workaround synergy ?/@ key issue

sleep 1

xmodmap -e "keycode 53 = x X greater greater greater greater"

xmodmap -e "keycode 52 = z Z less less less less"

xmodmap -e "keycode 24 = q Q at at at at"

**Comment by XinyuHou** [comment]
@harpss1ngh 
What keyboard layout and input source are you using?

I'm quite interested into your workaround. Could you give me some more explanations?

Thank you

**Comment by harpss1ngh** [comment]
GB.

I mentioned the issue I took this from. You can look at it to get more info

**Comment by XinyuHou** [comment]
Merged into #62
