### ISSUE TITLE
Unable to Send Accented Characters to the Client

### ISSUE THREAD

**Issue by ticorj** [symless/synergy#5532]
Hello @nbolton, I'm a Beta tester for Synergy 1.8. Even though I'm a beta tester for 1.8 this is an old issue ever since I started using Synergy in version 1.3. 
I'm using a windows 10 64bits server and a Mac 10.11 Client but this issue can also be observed when client and server as reversed.
Both keyboards are United States International Layout, using Brazilian Portuguese as Input language.
I'm Unable to send Accented Characters to the client. In Portuguese we have accented characters like ã à á â ç. I'm also unable to send quotes " and apostrophe ' to the client.
For example: In order to make a "á" character we should type Apostrophe and the letter "A". 

Here are some examples of Client Output while trying to type these characters on the Server:

_Obs: The keys aren't pressed at the same time. You should press the first one (Using shift if it applies), release, and then press the second._

ã: Tilde + a / Output: **na**
õ: Tilde + o / Output: **no**
á: Apostrophe + a / Output: **ea**
é: Apostrophe + e / Output: **ee**
ó: Apostrophe + o / Output: **eo**
â: Caret + a / Output: **6a**
ô: Caret + o / Output: **6o**
ä: Quotes + a / Output: **ua**
ö: Quotes + o / Output: **uo**
ç: Apostrophe + c / Output: **c**
' : Apostrophe + Space / Output: _**Nothing**_
" : Quotes + Space / Output: _**Nothing**_

There seems to be a pattern while trying to make those characters. _Tilde_ is being replaced for the letter "n" while _Apostrophe_ for the letter "e", _Caret_ for the number "6" and _Quotes_ for the letter "u".

While there  are replacements when trying to use theses keys to form Accented Characters using _Apostrophe_ and _Quotes_, when pressed alone the output is just Null.

Obs2: The _Crasis_ "`" Accent seems to be the only one that works fine. I can make the characters accented with _Grave_ key + _Letter_ just fine: à è ì ò ù. (_Crasis_ à is different than _Acute_ á)

General Info:

Server OS: Windows 10 64bits English
Server Keyboards Layout: United States International
Server Input Language: Brazilian Portuguese
Client OS: Mac OS 10.11 English
Client Keyboard Layout: United States International
Client Input Language: Brazilian Portuguese
Synergy Version: 1.82
Software Where Issue Where Observed: Any (Microsoft Word, Safari, Chrome, Notes...)

_Obs3: The issue does **not** affect typing theses characters locally both on the Server or on the Client._

**Comment by Fire-Dragon-DoL** [comment]
I think it's related to https://github.com/symless/synergy/issues/4280#issuecomment-238847899

**Comment by XinyuHou** [comment]
Merged into #4280
