### ISSUE TITLE
clipboard: sending failure

### ISSUE THREAD

**Issue by rdamazio** [symless/synergy#5535]
After upgrading to 1.8.2, more often than not I'm unable to copy something from the synergy client on my Mac (OSX 10.11) to my server on Ubuntu 14.04.4 (64-bit).

This is not 100% consistent, but in most cases it seems that copying formatted text (e.g. from a webpage) works, but copying something from a terminal, Chrome's URL bar, etc. doesn't.

I'm attaching DEBUG1 logs from client and server for a few attempts - some successful, some not. I've taken the liberty to replace my hostnames with MYMACHINENAME and MYOTHERMACHINENAME and to change my home directory to something that doesn't give away my company's name or computer setup.

I'll take a wild guess that this is the relevant message:
[2016-08-11T13:13:06] DEBUG1: clipboard: sending failure to 0x00c00007,31,0
Let me know if you need DEBUG2 (or if you want to send me custom binaries with more logging).

[synergy.zip](https://github.com/symless/synergy/files/414148/synergy.zip)

**Comment by XinyuHou** [comment]
Merged into #5502
