### ISSUE TITLE
Linux title-bar server menu shows "start" when server is already running

### ISSUE THREAD

**Issue by phalpern** [symless/synergy#5536]
This is similar to issue #4836 except for the menu-bar widget instead of the dialog box.  When the server is already running, you are giving the option to start it but not to stop it. In other words, the menu doesn't reflect the actual state of the server.
![image](https://cloud.githubusercontent.com/assets/984419/17605232/6da18f82-5fe7-11e6-946c-9b028f8e85c1.png)
Synergy 1.8.2 on Ubuntu 16.04

**Comment by XinyuHou** [comment]
Merged into #4466
