### ISSUE TITLE
Store configurations in the cloud

### ISSUE THREAD

**Issue by claell** [symless/synergy#5537]
I'd like to be able to have my configuration synced to my Smyless account in order to easily reuse them on other setups.

**Comment by nlyan** [comment]
Interesting idea. I'll be sure to bring this up. We certainly have the infrastructure for it.

**Comment by 0x9090** [comment]
Please be careful to not embed any passwords/hashes/keys in configs that are pushed to the cloud

**Comment by nlyan** [comment]
Duplicate of #3988
