### ISSUE TITLE
Cursor jumps at corners when use partial alignment

### ISSUE THREAD

**Issue by XinyuHou** [symless/synergy#5538]
Problem: My monitor setup consists six monitors, all the same size. The three top monitors are connected to a Raspberry Pi each. The bottom monitors are connected to my workstation. For the Synergy setup to work properly I'd needed to enter values like 33.33333333 and 66.66666667.When entering them rounded as 33 and 67, the cursor makes annoying jumps at the monitor corners.

Solution: Added support for using floating point values to specify the range instead of integers.

**Comment by nlyan** [comment]
Fixed in v1.8.8-rc1
