### ISSUE TITLE
Typing diacritics via US international keyboard doesn't work

### ISSUE THREAD

**Issue by dannysuls** [symless/synergy#5540]
Setup: Linux (Ubuntu 14.04 64-bit) server, Windows 10 client, both running Synergy stable 1.8.2.

On my Windows client (laptop), I'm unable to type diacritics (e.g. ë, á) via the dead keys using the US international keyboard. It works fine when I use the physical keyboard from the laptop, it doesn't work when I use the shared keyboard connected to the Linux Synergy server.

This is the actual behavior I see: when I type a relevant "dead key" (e.g. ', "), I see no character appearing (which is correct), but the next character I type doesn't get any added symbol / accent (e.g. I get e instead of ë when typing "+e).

**Comment by XinyuHou** [comment]
Merged into #5185

**Comment by mraveloarinjaka** [comment]
I am not sure what that issue was closed: the issue #5185 refers to a physical layout issue; I noticed the exact same problem describe above with both my computers configured to use a US qwerty keyboard with an American international layout.

**Comment by karlito139** [comment]
Using synergy 1.8.8 I get the same issue between linux (ubuntu 17.10) and windows 10 (linux is the server, windows the client). I do not have any issues between windows 10 and windows 10.

**Comment by zarkdav** [comment]
The workaround proposed by @diegoalberto does not seem to be working for me in the client in the last 1.11.1-stable-55ec3105 release of Synergy 1.

**Comment by diegoalberto** [comment]
@zarkdav Do you have installed US International Keyboard on both server and client machines?
Is the mix of on both machines what will have access working with ' + letter or AltGR + letter.
