### ISSUE TITLE
Cursor locked at position 0,0 when accessing client after server reboot

### ISSUE THREAD

**Issue by global2alex** [symless/synergy#5541]
Server: Win 7
Client: Mac 10.9.5
Synergy Ver: 1.7.2-1.8.2 and master-stable-130a248 (yesterday's nightly)

Steps to recreate issue on my setup. 
1) Start synergy on both machines
2) Stop process on Client machine (or don't, this step doesn't matter)
3) Stop process on Server machine (or end task/process) 
4) Reboot server computer (or don't, this step doesn't matter)
5) Start synergy on Server machine. (wait until running)
6) Move mouse from server screen (above in screen server configuration) down to the client screen. 

Expected behavior:
-Ability to move mouse freely on Client Machine. 
-Ability to use Server keyboard as if physically connected to the client machine

Actual Behavior: 
[1] Keyboard appears to behave on client the way it should.
[2] Cursor remains locked at screen position 0,0 on the Client machine. -OR-
[3] Cursor immediately jumps back to the Server screen. If you continue trying to move to the client, there is a random number of jumps before it gets locked as described by Actual Behavior [2]

Server Log:
> [2016-08-16T20:07:30] INFO: switch from "Server machine" to "client machine" at 199,0
> [2016-08-16T20:07:30] INFO: leaving screen
> [2016-08-16T20:07:30] DEBUG: open clipboard
> [2016-08-16T20:07:30] DEBUG: close clipboard
> [2016-08-16T20:07:30] DEBUG: ignored screen "Server machine" update of clipboard 0 (unchanged)
> [2016-08-16T20:07:30] DEBUG: open clipboard
> [2016-08-16T20:07:30] DEBUG: close clipboard
> [2016-08-16T20:07:30] DEBUG: ignored screen "Server machine" update of clipboard 1 (unchanged)
> [2016-08-16T20:07:32] DEBUG: discard ctrl+alt+del
> [2016-08-16T20:07:32] DEBUG: discard ctrl+alt+del
> [2016-08-16T20:07:32] DEBUG: shutting down because of desk switch to ""
> [2016-08-16T20:07:32] NOTE: disconnecting client "client machine"
> [2016-08-16T20:07:32] INFO: jump from "client machine" to "Server machine" at 960,540
> [2016-08-16T20:07:32] INFO: entering screen
> [2016-08-16T20:07:32] DEBUG: active sides: 10
> [2016-08-16T20:07:32] DEBUG: event queue is ready
> [2016-08-16T20:07:32] DEBUG: ssl connection closed
> [2016-08-16T20:07:32] NOTE: client "client machine" has disconnected
> [2016-08-16T20:07:33] DEBUG: unregistered hotkey id=1
> [2016-08-16T20:07:33] DEBUG: unregistered hotkey id=2
> [2016-08-16T20:07:33] DEBUG: unregistered hotkey id=3
> [2016-08-16T20:07:33] DEBUG: adopting new buffer
> [2016-08-16T20:07:33] DEBUG: discarding 1 event(s)
> [2016-08-16T20:07:33] DEBUG: closed display
> [2016-08-16T20:07:33] NOTE: stopped server
> [2016-08-16T20:07:33] DEBUG: ipc disconnect, closing stream
> [2016-08-16T20:07:33] DEBUG: unloading plugin: ns
> [2016-08-16T20:07:33] DEBUG: ipc disconnect, closing stream
> [2016-08-16T20:07:33] DEBUG: ipc client disconnected
> [2016-08-16T20:07:33] DEBUG: ipc client proxy removed, connected=1
> [2016-08-16T20:07:34] WARNING: detected application not running, pid=3828
> [2016-08-16T20:07:35] INFO: backing off, wait=2s, failures=1
> [2016-08-16T20:07:37] DEBUG: getting elevated token, elevation required
> [2016-08-16T20:07:37] DEBUG: processes in session 1: csrss.exe, winlogon.exe, nvxdsync.exe, nvwmi64.exe, taskhost.exe, avpui.exe, taskeng.exe, dwm.exe, EzUpdt.exe, explorer.exe, DipAwayMode.exe, AISuite3.exe, LCore.exe, googledrivesync.exe, SDTray.exe, CCleaner64.exe, googledrivesync.exe, U3BoostSvr64.exe, EPUShortCut.exe, ksdeui.exe, firefox.exe, plugin-container.exe, FlashPlayerPlugin_22_0_0_209.exe, FlashPlayerPlugin_22_0_0_209.exe, sublime_text.exe, synergy.exe, cmd.exe, conhost.exe, notepad.exe, 
> [2016-08-16T20:07:37] DEBUG: found winlogon.exe in session 1
> [2016-08-16T20:07:37] DEBUG: got token 996, duplicating
> [2016-08-16T20:07:37] DEBUG: duplicated, new token: 988
> [2016-08-16T20:07:37] INFO: starting new process
> [2016-08-16T20:07:39] DEBUG: launched syntool to check active desktop
> [2016-08-16T20:07:39] INFO: activeDesktop:Default
> [2016-08-16T20:07:39] DEBUG: processes in session 1: csrss.exe, winlogon.exe, nvxdsync.exe, nvwmi64.exe, taskhost.exe, avpui.exe, taskeng.exe, dwm.exe, EzUpdt.exe, explorer.exe, DipAwayMode.exe, AISuite3.exe, LCore.exe, googledrivesync.exe, SDTray.exe, CCleaner64.exe, googledrivesync.exe, U3BoostSvr64.exe, EPUShortCut.exe, ksdeui.exe, firefox.exe, plugin-container.exe, FlashPlayerPlugin_22_0_0_209.exe, FlashPlayerPlugin_22_0_0_209.exe, sublime_text.exe, synergy.exe, cmd.exe, conhost.exe, notepad.exe, syntool.exe, conhost.exe, 
> [2016-08-16T20:07:39] DEBUG: did not find logonui.exe in session 1
> [2016-08-16T20:07:39] DEBUG: getting non-elevated token
> [2016-08-16T20:07:39] DEBUG: duplicated, new token: 928
> [2016-08-16T20:07:39] INFO: starting new process
> [2016-08-16T20:07:40] INFO: drag and drop enabled
> [2016-08-16T20:07:40] DEBUG: opening configuration "C:/*/Local/Temp/qt_temp.Hp2976"
> [2016-08-16T20:07:40] DEBUG: configuration read successfully
> [2016-08-16T20:07:40] DEBUG: plugins dir: C:\*\Local\Synergy\Plugins
> [2016-08-16T20:07:40] DEBUG: loading plugin: ns.dll
> [2016-08-16T20:07:40] DEBUG: plugin loaded: ns.dll (version 1.3)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Program Files (x86)\Synergy\synergys.exe(0x013C0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\SysWOW64\ntdll.dll(0x772B0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\kernel32.dll(0x76A40000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\KERNELBASE.dll(0x76670000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\USER32.dll(0x76800000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\GDI32.dll(0x75650000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\LPK.dll(0x77280000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\USP10.dll(0x76DF0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\msvcrt.dll(0x75100000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\ADVAPI32.dll(0x75510000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\SysWOW64\sechost.dll(0x767E0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\RPCRT4.dll(0x74FC0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\SspiCli.dll(0x74BC0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\CRYPTBASE.dll(0x74BB0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\system32\MSVCP100.dll(0x6D250000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\system32\MSVCR100.dll(0x6D190000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\PSAPI.DLL(0x750B0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\SHELL32.dll(0x75A20000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\SHLWAPI.dll(0x76D90000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\ole32.dll(0x75770000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\system32\IMM32.DLL(0x756E0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\MSCTF.dll(0x766D0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\ws2_32.dll(0x750C0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\syswow64\NSI.dll(0x766C0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\system32\uxtheme.dll(0x722A0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\system32\NLAapi.dll(0x6F5E0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\system32\napinsp.dll(0x6F5D0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\system32\pnrpnsp.dll(0x6F5B0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\System32\mswsock.dll(0x71970000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\system32\DNSAPI.dll(0x6F560000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\System32\winrnr.dll(0x6F550000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Program Files (x86)\Bonjour\mdnsNSP.dll(0x6F520000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\system32\Iphlpapi.DLL(0x6FBB0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Windows\system32\WINNSI.DLL(0x6FBA0000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\*\Synergy\Plugins\ns.dll(0x68F30000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Program Files (x86)\Synergy\LIBEAY32.dll(0x5BE00000)
> [2016-08-16T20:07:40] DEBUG: libs:C:\Program Files (x86)\Synergy\SSLEAY32.dll(0x67100000)
> [2016-08-16T20:07:40] DEBUG: library use: pid:3500
> [2016-08-16T20:07:40] DEBUG: DPI: 150%
> [2016-08-16T20:07:40] DEBUG: physical resolution: 3840, 1080 scaled resolution: 2560, 720
> [2016-08-16T20:07:40] DEBUG: screen shape: 0,0 3840x1080 (multi-monitor)
> [2016-08-16T20:07:40] DEBUG: window is 0x000c0530
> [2016-08-16T20:07:40] DEBUG: using desktop for drop target: C:\*\Desktop
> [2016-08-16T20:07:40] DEBUG: adopting new buffer
> [2016-08-16T20:07:40] DEBUG: opened display
> [2016-08-16T20:07:40] DEBUG: active sides: 10
> [2016-08-16T20:07:40] DEBUG: active sides: 10
> [2016-08-16T20:07:40] DEBUG: desk Default window is 0x0005057a
> [2016-08-16T20:07:40] DEBUG: switched to desk "Default"
> [2016-08-16T20:07:40] DEBUG: desktop is now accessible
> [2016-08-16T20:07:40] DEBUG: registered hotkey Control+Alt+Down (id=ef54 mask=0006) as id=1
> [2016-08-16T20:07:40] DEBUG: registered hotkey Control+Alt+Up (id=ef52 mask=0006) as id=2
> [2016-08-16T20:07:40] DEBUG: registered hotkey ScrollLock (id=ef14 mask=0000) as id=3
> [2016-08-16T20:07:40] NOTE: started server, waiting for clients
> [2016-08-16T20:07:40] DEBUG: event queue is ready
> [2016-08-16T20:07:40] DEBUG: add pending events to buffer
> [2016-08-16T20:07:40] DEBUG: accepted ipc client connection
> [2016-08-16T20:07:40] DEBUG: screen "Server machine" shape changed
> [2016-08-16T20:07:40] DEBUG: start ipc handle data
> [2016-08-16T20:07:40] DEBUG: ipc read: IHEL
> [2016-08-16T20:07:40] DEBUG: finished ipc handle data
> [2016-08-16T20:07:40] DEBUG: ipc hello, type=node
> [2016-08-16T20:07:40] INFO: watchdog status: ok
> [2016-08-16T20:07:40] DEBUG: started process, session=1, elevated: no, command="C:/Program Files (x86)/Synergy/synergys.exe" -f --no-tray --debug DEBUG --name Server machine --ipc --stop-on-desk-switch --enable-drag-drop --enable-crypto --profile-dir "C:\*\AppData\Local" -c "C:/*/AppData/Local/Temp/qt_temp.Hp2976" --address :24800 --res-w 3840 --res-h 1080 --prm-wc 960 --prm-hc 540
> [2016-08-16T20:07:41] INFO: OpenSSL 1.0.2 22 Jan 2015
> [2016-08-16T20:07:41] NOTE: accepted client connection
> [2016-08-16T20:07:41] INFO: accepted secure socket
> [2016-08-16T20:07:41] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
> [2016-08-16T20:07:42] DEBUG: received client "client machine" info shape=0,0 1440x900 at 0,0
> [2016-08-16T20:07:42] DEBUG: active sides: 10
> [2016-08-16T20:07:42] NOTE: client "client machine" has connected

Client Log

> [2016-08-16T20:07:40]  INFO: entering screen
> [2016-08-16T20:07:40]  INFO: leaving screen
> [2016-08-16T20:07:40]  WARNING: cursor may not be visible
> [2016-08-16T20:07:40]  ERROR: corrupted clipboard data, expected size =68 actual size=0
> [2016-08-16T20:07:40]  ERROR: corrupted clipboard data, expected size =68 actual size=0

**Comment by XinyuHou** [comment]
Merged into #5533
