### ISSUE TITLE
Click stops working after a few seconds inactivity on client

### ISSUE THREAD

**Issue by rajchinna** [symless/synergy#5542]
Hi, 

I am facing an issue where leaving the Server keyboard and mouse ideal for sometime then the mouse breaks on the client side.. Again going back to server and doing a right click makes things normal. 

I am seeing this issue while running Synergy 1.8.2 stable-36cd521 on both Windows 10 (Anniversary update).  

Note, on server side I have two display connected and client has one display connected. 

Here is the log file wiht Debug2 log level when I hit the issue. 

[synergy.txt](https://github.com/symless/synergy/files/421505/synergy.txt)

Steps Followed. 

1. Enabled logs. 
2. Use the Mouse between client ans server. 
3. Leave the mouse ideal for sometime (~1-2 min)
4. Try to use the mouse click / selecting the text on client after step 3. 
5. Mouse works only like a hover (as I move towards the task bar it selects and shows the windows, if I click on them no action). 
6. Move the cursor into Server and do a right click or just do a scrol. 
7. Now, again try clicking/selecting text on the client it works fine. 

Thanks,
Raj

**Comment by W4RH4WK** [comment]
I have similar issues, Host is a WIndows 10 (including anniversary update), guest a Ubuntu 15.10 (running XFCE). Running 1.7.6 at the moment, 1.8.x did not fix this for me.

**Comment by losgann** [comment]
I also have a similar issue with a nearly identical setup to rajchinna (Synergy 1.8.2 stable-36cd521 on both Windows 10 (Anniversary update)).  In my case, however, right clicking or scrolling on the server doesn't solve the problem. I have to stop and restart Synergy on the server. Fortunately, it doesn't seem to happen as often - maybe two or three times a day. Still annoying, though.

**Comment by vanowm** [comment]
It sounds like this issue is related to #5513

**Comment by nlyan** [comment]
Thanks for flagging the dupe @vanowm
