### ISSUE TITLE
( over 3 years with the same error) A letter is typed when space bar is pressed on Mac client

### ISSUE THREAD

**Issue by Chispes** [symless/synergy#5548]
Sticking with the same error damn space , buy this application and I have not even been able to use .

Do not understand how can spend more than 3 years with this bug and nobody deigns to fix it. Each new version think it will be solved but it never happens , it is a tease .

Buy This application has been throwing money away .

**Steps to reproduce:**

Press space key in mac osx
Appears instead of the spacebar appears the key "s"
Expected: space

Actual: s

**Versions (Synergy, OS):1.8.2

Server: Mac OSX 10.11

Client 1: Mac OSX 10.11**

**Comment by srl295** [comment]
It's actually fixed.

**Comment by nlyan** [comment]
This should be fixed in 1.8.3 due for release in a week or so.
