### ISSUE TITLE
Complete loss of mouse control

### ISSUE THREAD

**Issue by bluenadas** [symless/synergy#5550]
Running on 2 machines locally. About twice a day I have the issue where my mouse/keyboard are hung on both machines. Can't move mouse or use keyboard except to ctrl/alt/delete. Can operate within the menu there but once I go back to desktop, it is still hung (attempting to force close synergy). Eventually the system will unhang, but no really idea what is causing it to finally come back.

**Comment by XinyuHou** [comment]
Duplicate of #5531
