### ISSUE TITLE
Fix bugs before writing new code

### ISSUE THREAD

**Issue by MartinDelille** [symless/synergy#5555]
724 open issue on Github is huge! Fixing bugs before writing new code is one of the [12 steps to better code](http://www.joelonsoftware.com/articles/fog0000000043.html) from @jspolsky that every project manager should at least read.

**Comment by XinyuHou** [comment]
@MartinDelille 
Thank you for the link. We are focusing on fixing bugs.

**Comment by MartinDelille** [comment]
Great! There might be ton of duplicate here!
