### ISSUE TITLE
Resolved: Mouse not usable - "try to leave" left/top - Synergy Windows v1.8.2-stable-130a248

### ISSUE THREAD

**Issue by GitHubfrd** [symless/synergy#5558]
**RESOLVED:** http://symless.com/forum/viewtopic.php?f=19&t=1830
 - I also modified synergy.exe, synergyc.exe, and synergyd.exe. Not sure which one fixed the problem, but synergys.exe alone did not resolve it for me.

**Problem:**
Mouse tries to leave client to top/left when moving from server to client ("try to leave" message). Keyboard and mouse clicks continue to work. Mouse "clamped" to top/left of client ("clamp to left" / "clamp to top" message).

Ctrl-Alt-Del or Client "Apply" resets system.

Server - Windows 10
Client - Windows 7
Synergy Windows v1.8.2-stable-130a248 - problem has existed for many versions.

Debug2 logs attached:
[synergyServer-log.txt](https://github.com/symless/synergy/files/431626/synergyServer-log.txt)
[synergyClient-log.txt](https://github.com/symless/synergy/files/431627/synergyClient-log.txt)

**Comment by esanumIT** [comment]
Thank you for this one! ... :)

**Comment by XinyuHou** [comment]
@GitHubfrd 
what is your screens' resolutions and DPI settings on both server and client side?

**Comment by RyanCarrier** [comment]
If anyone is still having issues with this; as the link above is 404.

Go to synergy executables; properties of synergys.exe, set disable high dpi to on.
