### ISSUE TITLE
change focus when using touch screen

### ISSUE THREAD

**Issue by epace** [symless/synergy#5559]
I would like to make the suggestion to have an option, that allows Synergy to jump to the cursor and change focus to another machine, that is being interacted through a touch screen.

Example:

I am surfing the web, finding art references on my larger monitors with my primary workstation. I find something I want to draw. I hover my stylus over my tablet screen and begin to draw. Then I use the same keyboard to attempt to change the brush or settings, but it begins interfering with the browser on my work station instead of the art program. So, I use the mouse to move the cursor all the way over to the tablet and continue to draw.

This is something I've gotten quite used to, but I imagine would be a very useful and easy option to add.

**Comment by XinyuHou** [comment]
Merged into #4544
