### ISSUE TITLE
MacOS gestures

### ISSUE THREAD

**Issue by cyberea** [symless/synergy#5560]
Hello and thank you for Synergy!

I am loving that I can control my MacPro workstation using my MacBook keyboard and trackpad. However mates, the gesture support pointed out in Feature #2974 of version 1.4.10 doesn't seem to be working. Am I missing something?

Tried every gesture I can think of, bar the common two-finger vertical scroll.

MacOS 10.11.6 (15G31) on both Mac Pro (Late 2013) & MacBook (Retina, 12-inch, Early 2016)
Current installed Synergy version 1.8.2-stable-36cd521

On a separate note (which probably should go into it's own issue), I also notice a visual bug being that when when I am "cursing" on the client screens, the invisible cursor on server screen stuck in the centre hovers around on any window triggering any hover state on elements that window might have.

**Comment by XinyuHou** [comment]
Merged into #2905
