### ISSUE TITLE
synergy-v1.8.3-rc1-e36a7ae breaks altgr = alt workaround

### ISSUE THREAD

**Issue by MikeAT** [symless/synergy#5562]
server: ubuntu  (i686)
client: windows 10 (x64)
both running synergy-v1.8.3-rc1 with german keyboard layout breaks the "altgr = alt" workaround. I have 
to press <ctrl>-<altgr> to get backspace or @.

If I downgrade the client to 1.8.2 altgr works fine, but it has "reconnect if already elevated"-bug #3241 :-()

**Comment by XinyuHou** [comment]
@MikeAT 
Could you report the altgr bug directly via the beta email?

Some logging would be helpful.

Thanks
