### ISSUE TITLE
1.8.2-stable-36cd521 : can't share between 2 windows 10 machines

### ISSUE THREAD

**Issue by Zorro666** [symless/synergy#5563]
I can share mouse & keyboard from Mac server to Windows 10 client
But the same laptop running in Bootcamp can't share with the same Windows 10 client.
The keyboard is shared but the mouse pointer won't move to the second screen. If I move the client virtual position around then sometimes I get control of the client machine but only with keyboard never with shared mouse.

Rebooting back into OSX and sharing from OSX works 100%.

**Comment by ccoenen** [comment]
I have two Windows 10 machines connected with, but half of the time, I can't click (pointing works, though). I have to restart the host service to make it work. Maybe that workaround helps?

**Comment by XinyuHou** [comment]
@Zorro666 
When you say you can't share the mouse, do you mean you you can't see the mouse or click on client?

What is your resolution of your Windows server?

**Comment by XinyuHou** [comment]
Closed because of insufficient info.
