### ISSUE TITLE
Various mouse actions unable when Synergy is running

### ISSUE THREAD

**Issue by babistrihos** [symless/synergy#5585]
I have installed Synergy in a combination of : 
1. XP & Vista 
2. Windows 10 & Vista 
In all cases some mouse features or actions are disabled. 

For example: 
In the first scenario I can't drag and drop on both PCs and 
in the second scenario, in Cubase 8 Pro I can't scroll using the mouse. 

It's very annoying and I had to uninstall Synergy to have all the features working :(

**Comment by nlyan** [comment]
@babistrihos Synergy no longer supports Windows XP or Windows Vista. If you have any problems with Cubase and Synergy on Windows 7 or above please get back to us and I'll reopen.
