### ISSUE TITLE
Error Compiling under Windows 7

### ISSUE THREAD

**Issue by functionpointer** [symless/synergy#5593]
I am trying to compile Synergy on Windows using a new Virtual Machine. I have read the Wiki Page on compiling and followed it. However, i can't get it to work. I have installed:
Windows 7 Professional x64
Visual Studio Community 2015
Cmake 3.6.2
WiX 3.8
Bonjour v3.0
Python 2.7 and added it to the PATH
git and added it to PATH

I also have created a new C++ Project in Visual Studio and compiled it to make sure the Compiler is there.

However, running `hm conf -g1` results in:

    CMake Error at CMakeLists.txt:40 (project):
        No CMAKE_C_COMPILER could be found.
    
    CMake Error at CMakeLists.txt:40 (project):
        No CMAKE_CXX_COMPILER could be found.

`hm genlist` shows that Generator 1 is Visual Studio 10. It also features no newer Generator than Visual Studio 10. Running `cmake -G "Visual Studio 14 2015"` works and finds the compiler. Does that mean that the wiki is wrong and synergy actually requires Visual Studio 2010?

Anyway, trying hm build after having run `cmake -G "Visual Studio 14 2015"` results in:
`Error: [Error 2] The System Cannot find the File Specified`
After digging around in `hm.py` a bit i found that `commands1.py` tries to read a registry entry belonging to Visual Studio 2010 in order to find `vcvarshall.bat`. Since i have Visual Studio 2015 that registry entry does not exist and results in the error.

So, is the wiki wrong and i need Visual Studio 2010 and not 2015?

**Comment by nlyan** [comment]
Master currently doesn't compile under MSVC 2015. Please try the 1.9.x branch. Closing because there are already open issues regarding this
