### ISSUE TITLE
Modifier keys don't work in Terminal on Mac OSX 10.11.2

### ISSUE THREAD

**Issue by pbrisson** [symless/synergy#5602]
Server: 1.8.2-stable-36cd521 (Windows 10)
Client: 1.8.3-beta-5f2f086 (Mac OSX 10.11.2 El Capitan)

In order to use Ctrl+C/Ctrl+V to copy/paste on both Windows and Mac, I remapped Ctrl to Meta key and Meta to Ctrl Key on my Mac. However, it doesn't work in Terminal window, for some reason.

To reproduce, try to save a file from nano in terminal.

- Open terminal
- Type "nano test"

In order to exit, it's required to use Command + X combination. However, hitting Ctrl + X doesn't work.

If I restore orignal key mapping for my Mac in Synergy Server, So Ctrl to Ctrl and Meta to Meta, I can use Command (windows/apple key) + X and it works fine.

**Comment by XinyuHou** [comment]
@pbrisson 
Please try to remap ctrl to super key.
