### ISSUE TITLE
Lag when moving from server to client

### ISSUE THREAD

**Issue by mnjul** [symless/synergy#5612]
### Operating Systems ###

Client: macOS Sierra 10.12

Server: macOS Sierra 10.12

### Synergy Version ###

1.8.3-rc2-89c9c58, verified to be used on both of the systems

### Steps to reproduce bug ###

Video: https://www.youtube.com/watch?v=8iKXa6JEA20 (it's a 60fps video to aid understanding, so if possible, switch to 1080p60 on YouTube)

1. Try to move the mouse cursor from server to client.
2. Observe there's a slight lag (usually around a second) between the instant when server loses its mouse cursor and the instant when the client's mouse cursor gets controlled.

### Other info ###

* Server is a Mac Mini Late-2012 and Client is a MacBook Air Early-2014. Both are on Ethernet under the same LAN (and within the same router) --- MBA using Thunderbolt-to-Ethernet adapter. No other observable network issues.
* When did the problem start to occur? I upgraded to Sierra just like yesterday when I also installed Synergy 1.8.3-rc2 from the beta tester's mail and it happened, so I'm not actually sure who's the culprit.
* Is there a way to work around it? Not really. Just need to wait patiently.
* Does this bug prevent you from using Synergy entirely? No. But the lag kills me and makes a bad Synergy experience.

**Comment by grigorovich** [comment]
Try to switch off "Enable clipboard sharing". If to do that problem will gone for me.
Its a huge bug in clipboard. @mnjul , please mark this as bug.
That problem log:
.........
[2016-09-24T08:14:24] WARNING: cursor may not be visible
**< HERE IS LAG - synergy server thinking and then exiting below... >**
[2016-09-24T08:14:24] INFO: screen "mbargo" updated clipboard 0
[2016-09-24T08:14:24] INFO: screen "mbargo" updated clipboard 1
[2016-09-24T08:14:24] INFO: switch from "mediaplayer" to "mbargo" at 652,8
[2016-09-24T08:14:24] INFO: entering screen
[2016-09-24T08:14:25] INFO: screen "mbargo" grabbed clipboard 0 from "mbargo"
[2016-09-24T08:14:25] INFO: screen "mbargo" grabbed clipboard 1 from "mbargo"
[2016-09-24T08:14:39] INFO: stopping synergy desktop process
[2016-09-24T08:14:39] INFO: process exited normally
**< and then in GUI application synergys automatically restarts, but in CLI synergys exited >**

PS: 'mbargo' - server, 'mediaplayer' - client, both macOSX 10.12

**Comment by mnjul** [comment]
I'm pretty sure this is a dupe from #5613 now... see https://github.com/symless/synergy/issues/5613#issuecomment-249339672 .
