### ISSUE TITLE
Request some enhancements for OSX server>client.

### ISSUE THREAD

**Issue by grigorovich** [symless/synergy#5614]
### Operating Systems ###

Client: mac OS X 10.12
Server: mac OS X 10.12

### Synergy Version ###

1.8.3-rc2-68bb42d

### Please add abilities for OSX Server > OSX Client: ###

1. Transfer multitouch events (handlers) for apple trackpad or magicmouse.
'smooth scroll' - two fingers. scrolling now works not smoothly and with incorrect direction in some applications (inversed).
'switch screens' - four fingers switches between screens
for example tree fingers works as LMBdrag now
FN+(F1~F12) if possible take that keyboard handlers...

2. Some applications like Blender or Unreal Engine must takes all mouse actions in window or in fullscreen - movement, dragLMB, dragRMB, dragMMB doesnt works on client right now.
For example:
--in Blender viewport dragRMB doesnt work
--in UnrealEngine when start project (Play button) mouse move doesnt works in viewport window. But as usual UE takes all events of mouse (like fullscreen) and possible exit from that mode only on Shift+F1. On client mouse cursor invisible (OK) but can move outside of screen (for ex. to Synergy server display).
--Some fullscreen application has same issue now

3. Change IP on server/client machine (hostnames did not changed, only IPs)
Please add some settings for auto restart Synergy server process on IP changes. IP must be refresh on both server and client, and then client must search server (by hostname for example). Server must wait clients with new IP also. 
Now i use some tricks with shell scripts via ssh for restart both.

4. Settings for Displays arrange 
Please add ability for setup and arrange displays grid:
-- move (X,Y)
-- scale
For example: 
[image 1](http://s16.postimg.org/j17gdko05/image.jpg)
[image 2](http://s16.postimg.org/js06jcqdh/image.jpg)
[image 3](http://s16.postimg.org/9vz3jpklh/image.jpg)

**Comment by nlyan** [comment]
@grigorovich We really appreciate your enhancement ideas. Any chance you could break these out in to separate issues?

Some quick thoughts though:

wrt 1. According to #3235 this should work. Can you attest as to whether this a Sierra regression?

wrt 2. This is a known bug, see #3992

wrt 3 &4. Definitely need a separate enhancement requests for these two. We need you to be more descriptive on 4 as well.

**Comment by grigorovich** [comment]
Ok. Im sorry for my explanation but i will try. I use synergy almost 2 years. 
And i use synergy on OSX<>Windows<>Linux. Most of time on OSX<>OSX. So.

### 1. Trackpad/MagicMouse and another multitouch events. (Enhancement)
I mean on mac-like UI apps scroll (2 fingers multitouch), for example, works like "drag" effect in X and Y axis. So it is ok, how should work.
But SynergyServer on OSX captures that event and convert(send) it to SynergyClientOSX and emulate it like legacy scroll mouse wheel effect (lines). Not smoothly. 
[https://youtu.be/9wyVwZUuKOw](url)

### 1.1. I think that because of the reason of paragraph 1 directions of scroll works differently than on original (server machine). Like a bug of events/hanling (?)

For compare i have good example in two apps - VLCplayer and Finder (both, server and client, are OSX version):

Finder
* On server machine Scroll Horizontal (2 fingers on trackpad) in Finder , but on SynergyClient in Finder not same - inverted direction scrolling. (?)
* On server machine Scroll Vertical (2 fingers on trackpad) in Finder and on SynergyClient machine in Finder same! 

VLC
* On server machine Scroll Horizontal (2 fingers on trackpad) in VLC. And on SynergyClient in VLC same - OK.
* On server machine Scroll Vertical (2 fingers on trackpad) in VLC but on SynergyClient machine in VLC inverse direction scroll ! (?)

And from which I conclude that the axis of the scroll work differently in different applications. In Finder X axis inverted, but Y is ok. In VLC X axis is OK, but Y axis inverted. 

### 2. Yes, same issue #3992 
Maybe problem is in capture mouse/keyboard hold button states.
I have this issue in Unity, UnrealEngine, Blender.
I can grab short video on both machines with full description for more explanation of that problem, if you want. 

### For 3 and 4 i will create separate issues right now.

**Comment by XinyuHou** [comment]
@grigorovich 

Thanks for creating the issue in separately.

I have merged the first two issue into our existing issues.
