### ISSUE TITLE
Cannot connect with SSL anymore

### ISSUE THREAD

**Issue by bigbear3001** [symless/synergy#5615]
### Operating Systems ###

Client: Ubuntu 16.04 LTS 64-bit

Server: Windows 10, Version 1511 (OS Build 10586.589), 64-bit

### Synergy Version ###

1.8.3-rc2-89c9c58

### Steps to reproduce bug ###

1. Have 1.8.3-rc1 on server, 1.8.2 on client (working with ssl)
2. Update Server to 1.8.3-rc2
3. SSL no longer working
4. Update Client to 1.8.3-rc2
5. SSL still not working
6. turn SSL off on client and server
7. connection working again (without encryption)

### Other info ###

Logfile Server 1.8.3-RC2 SSL:
> [2016-09-24T09:38:59] DEBUG: started process, session=2, elevated: no, command="C:/Program Files/Synergy/synergys.exe" -f --no-tray --debug DEBUG1 --name gaming --ipc --stop-on-desk-switch --enable-drag-drop --enable-crypto --profile-dir C:\Users\Andreas\AppData\Local -c C:/Users/Andreas/AppData/Local/Temp/qt_temp.fl5800 --address :24800 --res-w 7380 --res-h 2880 --prm-wc 1920 --prm-hc 1080
>[2016-09-24T09:39:01] DEBUG1: event: button press button=1
>[2016-09-24T09:39:01] DEBUG1: onMouseDown id=1
>[2016-09-24T09:39:01] DEBUG1: event: button release button=1
>[2016-09-24T09:39:01] DEBUG1: onMouseUp id=1
>[2016-09-24T09:39:04] INFO: OpenSSL 1.0.2 22 Jan 2015
>[2016-09-24T09:39:04] DEBUG1: openSSL : compiler: cl  /MD /Ox -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -Gs0 -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_STATIC_ENGINE    
>[2016-09-24T09:39:04] DEBUG1: openSSL : built on: reproducible build, date unspecified
>[2016-09-24T09:39:04] DEBUG1: openSSL : VC-WIN64A
>[2016-09-24T09:39:04] DEBUG1: OPENSSLDIR: "/usr/local/ssl"
>[2016-09-24T09:39:04] DEBUG1: registered event type ClientListenerEvents::accepted as 44
>[2016-09-24T09:39:05] ERROR: ssl error occurred (system call failure)
>[2016-09-24T09:39:05] ERROR: eof violates ssl protocol
>[2016-09-24T09:39:05] DEBUG1: registered event type ISocketEvents::stopRetry as 45
>[2016-09-24T09:39:05] DEBUG1: registered event type ISocketEvents::disconnected as 46
>[2016-09-24T09:39:05] DEBUG1: registered event type IStreamEvents::inputShutdown as 47
>[2016-09-24T09:39:05] ERROR: failed to accept secure socket

**Comment by bigbear3001** [comment]
I switched back to 1.8.3-RC1 on the server (Windows 10, 64Bit), now ssl works again
Logfile from 1.8.3-RC1:
>[2016-09-24T09:46:27] DEBUG: started process, session=2, elevated: no, command="C:/Program Files/Synergy/synergys.exe" -f --no-tray --debug DEBUG1 --name gaming --ipc --stop-on-desk-switch --enable-drag-drop --enable-crypto --profile-dir C:\Users\Andreas\AppData\Local -c C:/Users/Andreas/AppData/Local/Temp/qt_temp.Hp8556 --address :24800 --res-w 7380 --res-h 2880 --prm-wc 1920 --prm-hc 1080
>[2016-09-24T09:46:28] INFO: OpenSSL 1.0.2 22 Jan 2015
>[2016-09-24T09:46:28] DEBUG1: openSSL : compiler: cl  /MD /Ox -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -Gs0 -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_STATIC_ENGINE    
>[2016-09-24T09:46:28] DEBUG1: openSSL : built on: reproducible build, date unspecified
>[2016-09-24T09:46:28] DEBUG1: openSSL : VC-WIN64A
>[2016-09-24T09:46:28] DEBUG1: OPENSSLDIR: "/usr/local/ssl"
>[2016-09-24T09:46:28] NOTE: accepted client connection
>[2016-09-24T09:46:28] INFO: accepted secure socket

**Comment by nlyan** [comment]
@bigbear3001 Can you try upgrading again, but this time rerun the wizard. ( File -> Run Wizard ) before trying SSL?

**Comment by kti-richard** [comment]
I had the same issue.
Running the wizard post upgrade resolved the issue.

**Comment by nlyan** [comment]
Closed because this now has its own issue. #5617
