### ISSUE TITLE
Mouse speed too fast in certain directions, since upgrading to macOS Sierra

### ISSUE THREAD

**Issue by tabchas** [symless/synergy#5616]
Client: Windows 10
Server: macOS Sierra

Synergy Version: 1.8.2

When I try to move mouse around on Windows client, it acts very strangely. Whenever I move the cursor towards the edges of my Windows client monitor, it starts getting attracted very quickly towards that edge. Example: If I move towards the bottom edge, it moves very quickly and sort of "drags" towards the bottom edge.

If I keep the cursor towards the middle of the screen (away from edges), it works fine.

As far as I know, the problem started after getting macOS Sierra.

**Comment by tabchas** [comment]
Wait does Synergy support the new macOS? I just realized the current downloads are versioned up till 10.11 but not 10.12. When will 10.12 be supported?

**Comment by nlyan** [comment]
@tabchas We don't have official builds for 10.12 yet, although the 10.11 build will work, sans bugs. Known regressions in Sierra are tagged with the macos-sierra tag.

@tabchas Any details on your server machines screen size and resolution? The symptoms sound the same as #5183 and #5607

**Comment by jletellier** [comment]
I think I have the same problem. I am using version 1.8.3-stable-db9181b both on a macOS Sierra server and macOS Sierra client. It works fine on the server but the mouse seems to have a faster upward and left-ward movement on the client.

**Comment by nlyan** [comment]
Can those of you with Windows in the mix try this build?

http://symless.com/nightly?filter=synergy-v1.8.4-rc3-fcd8153

There are no changes to be expected here for macOS users. Sierra fixes have slipped to 1.8.5

**Comment by tabchas** [comment]
@nlyan Tried out 1.8.4rc3. Still having same issues. I think it tracks the mouse a bit better but still has strange behavior if I move the mouse towards the sides of my monitor

**Comment by nlyan** [comment]
Thanks @tabchas . We'll try to fix this in 1.8.5

**Comment by stingray88** [comment]
Hey I was using 1.8.6 on two Macs, the server was on El Capitan and the other Mac was on Sierra. Both worked perfectly fine for months... Just updated the Mac that was acting as the server to Sierra, and I'm having these same issues. Incredibly erratic mouse movements on the client, it's almost unusable... Any ideas?

**Comment by na-g** [comment]
I am having similar sounding issues with a server on macOS 10.12 and an Ubuntu 17.04 client. I am running Synergy 1.8.8 on both machines.
