### ISSUE TITLE
Remove redundant plugin infrastructure

### ISSUE THREAD

**Issue by nlyan** [symless/synergy#5617]
Problem: The plugin infrastructure is buggy and fragile, causes more problems than it solves and was just generally a bad idea.
Solution: Rip it out, kill it with fire.

**Comment by allanjackson** [comment]
I had the same issue. Running the setup wizard again fixed it.

**Comment by ianchan** [comment]
I had to switch to Debug1 for logging level on the client and then accept the server certificate. After that, it Synergy started working again. I went through the wizard both machines prior to trying to switch the logging level.
