### ISSUE TITLE
MacOS 10.12 Sierra support

### ISSUE THREAD

**Issue by XinyuHou** [symless/synergy#5620]
Problem: There is no MacOS 10.12 Sierra installer.
Solution: Compile and build on MacOS 10.12

**Comment by nicknlsn** [comment]
I get an error when I try this. It says it needs qt but that won't install because of an 'upstream incompatability.' Did you get this problem at all?

**Comment by XinyuHou** [comment]
@nicknlsn 
Could you test our latest 10.12 build on your sierra to see if the problem persists? Thanks.
http://symless.com/nightly?filter=synergy-v1.8.6-rc1-7ce6905
