### ISSUE TITLE
Does not build on Windows, build script broken ("TabError: inconsistent use of tabs and spaces in indentation"!)

### ISSUE THREAD

**Issue by silvium** [symless/synergy#5635]
You leave in stuff like "TabError: inconsistent use of tabs and spaces in indentation" and "Missing parentheses for print statement" and still claim that anyone is free to download and build?
There's a saying in my native language for people like you, it goes "Să vă fut în gât!"

**Comment by nlyan** [comment]
It sounds like you're trying to run our Python 2 build script with Python 3. If you do that, you're gonna have a bad time.
