### ISSUE TITLE
Allow "resizing" synergy displays

### ISSUE THREAD

**Issue by V3XATI0N** [symless/synergy#5644]
### Operating Systems ###

Client: Windows/Linux

Server: Linux

### Synergy Version ###

whatever's next

### REQUEST ###

If the server could be "resized" to occupy 2 slots, and have each client in a slot below it, that would be super rad. That would allow me to place 2 clients below the my dual-screen server and access them in a more intuitive way.

**Comment by nlyan** [comment]
Your feature request will be addressed by #4173 . We'd welcome your comments there.
