### ISSUE TITLE
Failure to render .app/.dmg container of v1.8.3 for MacOSX 10.8

### ISSUE THREAD

**Issue by auralarch** [symless/synergy#5645]
### Operating Systems ###

Mac OS X 10.8 Mountain Lion

### Synergy Version ###

1.8.3

### Steps to reproduce bug ###

It happens while attempting to build the latest version of synergy that will run on my OS.  

(I have donated to this project multiple times over the last 5-6 years. But a binary for my OS is no longer made available for download, so I have no choice but to compile & build it myself.  However, your instructions are incomplete/out-of-date/incorrect.)

I downloaded the synergy-master.zip for the latest stable version (1.8.3) here.

Instructions on the Wiki were insufficient/erroneous. I have been unable to find solutions here.   After hours of researching the errors & failures I was able to find information on adjusting numerous details of my config/build environment (which has been working smoothly for other projects) to get some things working, as well as some patches which have brought me sickenly close to success.
(My knowledge & experience with development is rather limited which has made this process/progress very painstaking & long!) 

I've had to apply several patches to ../synergy-master/CMakeLists.txt:
(I don't know how to properly, stylistically notate the patches- some of which I have probably lost track of by now.  So, I include the patched file.)
[CMakeLists.txt](https://github.com/symless/synergy/files/518676/CMakeLists.txt)

I do recall changes made at lines: 80, 172-184. 
I also found & applied patches to ../commands1.py; however, I suspect they may be unnecessary and did not apply them to my most recent attempt (which got BY FAR the closest to completion).

These are the commands I have entered, and the errors that have precipitated:

./hm.sh conf -g1 --mac-sdk 10.8 --mac-identity MountainLion
...
cmake version 3.6.2
...
-- Configuring done
-- Generating done
-- Build files have been written to: ../synergy-master/build/release
...
Error: Could not get revision, git error: 128

./hm.sh build
...
[100%] Built target
...
Make GUI command: make -w
...
make: *** No targets specified and no makefile found.  Stop.
...
Error: make -w failed with error: 512

### Other info ###

So, it seems as though I have everything (binaries, libraries, plugins, etc.) except for the .app or .dmg container.

It would be nice to see some detail added to the wiki- a bit more information there could have saved me hours of troubleshooting/research.  Perhaps I will be able to put together a proposal for changes that could prove helpful to others.

It is frustrating to discover that most of the patches I applied are (at least partially) documented in other issue threads (months ago...) but those changes were not applied to the latest release.

I have not, however, been able to find any workable solutions or useful suggestions for the I've outlined above.

**Comment by auralarch** [comment]
BTW- I wasn't able to find ANY help/reference concerning the required "mac-identity" arg- as in: formatting... (spaces allowed? if not, what then?)  So, I've run the conf (on a freshly unzipped "master") with several variations: Mountain Lion   MountainLion   Mountain-Lion   Mountain_Lion
Somewhat strangely/surprisingly there hasn't seemed to be any difference in the outcome.

The main problem seems to be the "Make GUI command".  Make -w is clearly not sufficient on its own since there aren't any Makefiles in the gui dir (no way of knowing if there are supposed to be or if some other issue is affecting args specifying target(s) that should be automatically generated).

Any assistance or insight into this issue will be immensely appreciated!!!

**Comment by auralarch** [comment]
Are there no suggestions that may help me get this compiled?
Has support for 10.8 been dropped?

**Comment by XinyuHou** [comment]
@auralarch 
Sorry for all the inconvenience. We will improve our wiki for compiling instructions.

Unfortunately we have dropped 10.8 support since 1.8. 

> Error: Could not get revision, git error: 128
To compile Synergy, please clone the project from our github page.

Please subscribe to our mailing list or contact support if you have any further issues related to compiling.
