### ISSUE TITLE
Bug with some keys

### ISSUE THREAD

**Issue by JJaeger-Ackerman** [symless/synergy#5651]
I using Synergy free, my setup is a Windows PC as the server and a ArchLinux as the client, but some keys on keyboard simply not work, that ones are the "^" and "`". I tryied to change keymap with setxkbmap on client, but don't worked. I hope someone could help me with this trouble...

**Comment by nlyan** [comment]
What Synergy version are you using?

**Comment by JJaeger-Ackerman** [comment]
I'm using the version 1.4.18 free.

**Comment by nlyan** [comment]
Hi @JJaeger-Ackerman 

I'm afraid 1.4.18 is no longer supported. If you like you can try the newer version which should have fixed this issue. There's a sale on atm http://symless.com/flash-sale-a
