### ISSUE TITLE
Linux clients grab and empty the clipboard

### ISSUE THREAD

**Issue by nlyan** [symless/synergy#5662]
### Operating Systems ###

Client: Linux (at least two clients)
Server: Any

### Synergy Version ###

1.8.4

### Steps to reproduce bug ###

1. Connect a Linux client to e.g. a Windows server
2. Attempt to copy content from one program to another wholly on the server
3. See that paste fails (the clipboard has become empty)
4. Attempt to copy to or from any other client
5. See that the result is the same as in #3

### Other info ###

* When did the problem start to occur? 1.8.3 (?)
* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? No, but the clipboard is broken if you are using a Linux client

**Comment by rootkow** [comment]
@nlyan I run two Linux clients and a Windows server daily and haven't experienced this bug on any release yet. I've been trying to replicate the bug using versions 1.8.3, 1.8.4, and 1.9.0 on both Linux machines and the Windows machine. I know you guys are super busy, but can you post a log when you have a minute?

**Comment by duk3luk3** [comment]
I have the same problem using Arch Linux client and server. Same synergy version.

Steps to reproduce in my case:

1. Put something in clipboard on one machine, verify using `xclip -o -selection clipboard` on that machine
2. Put something in clipboard on other machine, verify using `xclip -o -selection clipboard` on that machine
3. Run `xclip -o -selection clipboard` again on first machine -> displays error "Error: target STRING not available"

**Comment by nlyan** [comment]
Cause discovered. Not a bug.

**Comment by duk3luk3** [comment]
How is this not a bug? Synergy is supposed to synchronize clipboards. It doesn't manage to do that on linux. Seems like a bug to me.
