### ISSUE TITLE
run synergy on two computers that both use a VPN?

### ISSUE THREAD

**Issue by NIXOYE** [symless/synergy#5664]
### Operating Systems ###

Client: Ubuntu linux 16.04

Server: Ubuntu linux 16.04

### Synergy Version ###

1.6.2

I want to control my thinkpad with my netbook mouse and keyboard. Both computers use a vpn and I want to know if there is a way to get this to work without turning off the VPNs. I type in the IP addresses that appear in synergy onto my client machine but i just get failed to connect to server: connection refused

**Comment by XinyuHou** [comment]
@NIXOYE 
This looks like a support ticket. Please contact our support team.
