### ISSUE TITLE
cmake compile error on macOS Sierra: The C and CXX compiler identification is unknown

### ISSUE THREAD

**Issue by willem-hill** [symless/synergy#5666]
### Operating Systems ###

Client: N/A

Server: macOS Sierra

Version: Newest as of 10/14/16 @ 9:10 PM EST

### Steps to reproduce bug ###

1. Use brew to install qt5 and cmake.
2. Fix `./ext/toolchain/commands1.py` according to https://github.com/symless/synergy/wiki/Compiling#Mac_OS_X
3. Run `./hm.sh configure -g2 --mac-sdk 10.12 --mac-identity test` and get:

```
Entering dir: build

CMake command: cmake -G "Xcode" -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 -DOSX_TARGET_MAJOR=10 -DOSX_TARGET_MINOR=12 ..

-- The C compiler identification is unknown

-- The CXX compiler identification is unknown

CMake Error at CMakeLists.txt:40 (project):

  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:40 (project):

  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!

See also "/Users/~/Downloads/synergy/build/CMakeFiles/CMakeOutput.log".

See also "/Users/~/Downloads/synergy/build/CMakeFiles/CMakeError.log".

Going back to: /Users/~/Downloads/synergy

Error: CMake encountered error: 256

Wills-MBP:synergy ~$
```

I have replaced my username with `~` above for privacy.

I'm somewhat of a software developing noob. Please excuse that. Thanks for any help, and I'm not sure whether its my fault or cmake's or synergy's. Thanks.

**Comment by XinyuHou** [comment]
@willem-hill 
Try to open xcode first and if this is your first time, it should do some activation or asking for downloading tools.

This really looks like a support ticket. Please contact our support group.

**Comment by koopatroopa120** [comment]
For future reference... if you follow the compile instructions and get this error, you need to go into Xcode settings to the "locations" tab and choose the command line tools version you already installed (i think mine installed during the homebrew installation) and click ok or something. Doing this fixed this problem for me right away.

**Comment by m-deck** [comment]
Thanks @koopatroopa120 - these instructions also worked for me. I just updated the wiki instructions to reflect this suggestion.

**Comment by multidisplayad** [comment]
I changed the command line tools version.
But it still not work...

**Comment by uran1980** [comment]
Thanks @koopatroopa120 it is worked for me!!!

**Comment by jamespack** [comment]
@koopatroopa120 worked for me too!

**Comment by TimoCrafter** [comment]
@koopatroopa120 thank you!
