### ISSUE TITLE
Wrong characters with Russian keybord layout

### ISSUE THREAD

**Issue by artmnv** [symless/synergy#5678]
### Operating Systems ###

Client: MacOS Sierra 10.12

Server: Windows 10 (1607, 14393.321) x64

### Synergy Version ###

1.8.4 stable

### Steps to reproduce bug ###

1. You should have two keyboard layouts on server and client. English and Russian. Russian - PC on Mac.
2. Switch keyboard layout on server screen with mouse or Win+Space to ENG.  
3. Switch keyboard layout on client screen to RUS.
4. Some keys will produce Russian characters but other will still be in English. Example: я -> z, ч -> x, в -> d but ц -> ц, к -> к. Full map of wrong characters (yellow is bad, green are good): http://take.ms/KLga8

### Other info ###

* When did the problem start to occur? When I upgraded to 1.8.4. I think the last version without this issue is 1.8.2. But I'm not confident.
* Is there a way to work around it? No/Yes, you can change keyboard layout on server to RUS.
* Does this bug prevent you from using Synergy entirely? No

If you switch keyboard layout of the server to the Russian it will work completely normal with both layouts.

**Comment by XinyuHou** [comment]
Merged into #4280
