### ISSUE TITLE
Touch Screen Oddities...

### ISSUE THREAD

**Issue by yidhoe** [symless/synergy#5683]
Kinda of an FYI as much as a bug, not sure it can be fixed.

Basically if you have a touch screen device and this is the Synergy Server, if the mouse is moved to another PC then the screen is touched on the Server, the remote PC gets the input rather than the screen you touched! Kinda freaky at first lol. :)

Doesn't matter which synergy version I have just tested it on a few revisions all windows some 32, some 64.

Thanks

Stuart.

**Comment by JoseRolles** [comment]
Yes, this has been an issue for me too. Especially on my server computer, I detach my laptop screen (Surface Book) while my mouse is on the client computer, my mouse then gets trapped in the client computer and when I touch the laptop screen, the client computer gets affected.

**Comment by XinyuHou** [comment]
Thanks guys. Are you looking for a feature like Synergy can differentiate mouse input and touch input and keep touch input on the local machine?

**Comment by XinyuHou** [comment]
Merged into #4544
