### ISSUE TITLE
1.8.4 mouse moving slowly on Windows 10 high DPI with regular DPI server

### ISSUE THREAD

**Issue by Rajveer86** [symless/synergy#5684]
### Operating Systems

Server: Windows 10
Client: Windows 10
### Synergy Version

1.8.4
### Steps to reproduce bug
1. Setup Windows 10 server on a normal DPI computer.
2. Connect with a high DPI Windows 10 client
3. Move mouse to high DPI client, mouse moves slower than it used to
### Other info

This problem started occurring on Synergy 1.8.4. It makes Synergy very difficult to use, to the point I am no longer using it.

**Comment by wfilleman** [comment]
I've got a variation to this issue as well:

**Operating Systems**

Server: Windows 10 -> 5k High DPI Monitor
Client: MacOS Sierra -> 5k iMac High DPI Monitor

**Synergy Version**

1.8.4

**Steps to reproduce bug**

Setup Windows 10 server on a High DPI computer.
Connect with a high DPI MacOS Sierra client
Move mouse to high DPI client, mouse moves twice as fast as the host machine's mouse speed.

My back of the napkin math says that the high DPI host isn't scaling the mouse rate correctly for the client's DPI resolution considering the host's DPI/rate.

**Comment by nlyan** [comment]
There should be some improvement to this situation in 1.8.5. Can you guys give it a try?

**Comment by wfilleman** [comment]
Thanks nlyan.

I updated both the Windows host and Mac Sierra client this morning to the 1.8.5 stable release, but the behavior is the same for me. With both server and client having High DPI monitors, the client's cursor moves about twice as fast as the host. 

Wes

**Comment by XinyuHou** [comment]
@wfilleman 
Could you test this nightly please?
http://symless.com/nightly?filter=synergy-v1.8.6-rc1-eb56683-Windows

**Comment by XinyuHou** [comment]
@Rajveer86 
Please try this nightly.
http://symless.com/nightly?filter=synergy-v1.8.6-rc1-eb56683-Windows

 If your problem persists, it's likely to be a problem on client side. Please let me know. Thanks.

**Comment by wfilleman** [comment]
@XinyuHou, I installed the 1.8.6-rc1 nightly on both Windows and Mac client. Same results for me. The High DPI Mac client's mouse cursor moves twice as fast as the Windows High DPI host.

**Comment by XinyuHou** [comment]
@wfilleman 
Thanks for your feedback. The nightly only has some fixes for server side. We will look into more on the client side.

**Comment by XinyuHou** [comment]
Merged into #4245
