### ISSUE TITLE
synergys crash when client disconnects (only when crypto is enabled)

### ISSUE THREAD

**Issue by epakai** [symless/synergy#5686]
### Operating Systems ###

Server: Debian 8.6 (64-bit) (openssl version 1.0.1t-1+deb8u3)
Alternate server: Debian Stretch (64-bit) (openssl version 1.0.2j-1)
Client: Windows 10 Version 1607 (64-bit)

### Synergy Version ###

1.8.4-stable

Client is the official binary. Server was built against debian libraries. I can retest with the included openssl version if necessary, but I'm unsure how to compile against it.

### Steps to reproduce bug ###

1. Run synergys -f --enable-crypto
2. Direct windows client to connect via gui "Start" button, server IP uses hostname
3. Connection is successful and everything seems to be working.
4. Click "Stop" button on client
5. synergys crashes with a Segmentation fault

### Other info ###

* When did the problem start to occur? I did not have this issue with this in 1.7.6, but I have not tried intermediate versions since the plugins were removed.
* Is there a way to work around it? The gui tool (synergy) auto-restarts the server when it crashes, but I'd prefer to have the command line tool not crash.
* Does this bug prevent you from using Synergy entirely? No

This crash does not occur when crypto is disabled. I have included a backtrace and my synergy config file.

[debug_synergy.log.txt](https://github.com/symless/synergy/files/537673/debug_synergy.log.txt)
[synergy.conf.txt](https://github.com/symless/synergy/files/537674/synergy.conf.txt)

**Comment by Celant** [comment]
Hey,

This is actually fixed in 1.8.5!

**Comment by epakai** [comment]
I'm referencing the commit and closing this issue.
dc4beba9e915440bbfc2e01f05da60348dcba605
