### ISSUE TITLE
synergy 1.8.4 - server crash then v bad mouse cursor lag

### ISSUE THREAD

**Issue by denormalizer** [symless/synergy#5698]
### Operating Systems ###

Server: Windows 10 Pro (64 bit)
Client: Ubuntu 14.04 (64 bit)

### Synergy Version ###

1.8.4

### Steps to reproduce bug ###

Intermittent. Can't reproduce.

1. Start server
2. Start client
3. Usually operational for a good 15 minutes; Then
5. Crash
6. Lose connection to clients
7. Mouse cursor on server lags dramatically - almost unusable

### Other info ###

* When did the problem start to occur? Started happening in 1.8.4
* Is there a way to work around it? No. But restarting the synergy service seems to fix the issue
* Does this bug prevent you from using Synergy entirely? Yes

I ran a debug on the crash and extracted some data which I've included as an attachment.
[synergy-error-log.txt](https://github.com/symless/synergy/files/547109/synergy-error-log.txt)

Not sure if relevant, but the consistent error that pops up is:

> Cannot find or open the PDB file.

And also

> Access violation executing location 0x00000000039A5B10

**Comment by spronkey** [comment]
Possibly duplicate of #5691 ?

**Comment by denormalizer** [comment]
Hi @spronkey, I don't seem to have a problem with disconnecting my client on ubuntu but the result seems to be identical:

> Crash: synergys.exe stopped working, cursor on server almost impossible to move and click: close program

**Comment by nlyan** [comment]
This should be fixed in 1.8.5 

Try this build

http://symless.com/nightly?filter=v1.8.5-rc1-b66043e

**Comment by denormalizer** [comment]
@nlyan Thanks. Testing

**Comment by denormalizer** [comment]
I believe this issue has now been resolved.

**Comment by spronkey** [comment]
Yep, can confirm that disconnecting no longer causes server to crash with this build running on server.
