### ISSUE TITLE
Usage stats panel similar to stats for nerds

### ISSUE THREAD

**Issue by DanSorahan** [symless/synergy#5704]
Problem ?

Solution: Add a panel for in-depth usage stats, similar to the "stats for nerds" panel on Youtube. This could contain stats such as times moved between screens, size transferred on clipboard in megabytes, etc.

**Comment by nbolton** [comment]
@DanSorahan What problem does this solve?

**Comment by yupi2** [comment]
It wouldn't solve any problem. It's just something that would provide information that makes you go "Wow that's neat". Not a very high-priority feature though since bug fixes would be preferred.
