### ISSUE TITLE
Syslog in Ubuntu shows *** WARNING *** The program 'synergy' uses the Apple Bonjour compatibility layer of Avahi.

### ISSUE THREAD

**Issue by TafThorne** [symless/synergy#5706]
In the syslog of my Ubuntu 16.04 PC there are a lot of WARNING messages about synergy's use of the Apple Bonjour compatibility layer of Avahi.  It would be nice if these warnings did not occur, although it is just a minor annoyance at present.  That is unless the "The program 'synergy' called 'DNSServiceRegister()' which is not supported (or only supported partially)" message highlights a problem with DNS that needs to be addresses.  

Syslog sample: 
````
Oct 25 13:01:54 thorne-ul-dt gnome-session[1243]: *** WARNING *** The program 'synergy' uses the Apple Bonjour compatibility layer of Avahi.
Oct 25 13:01:54 thorne-ul-dt gnome-session[1243]: *** WARNING *** Please fix your application to use the native API of Avahi!
Oct 25 13:01:54 thorne-ul-dt gnome-session[1243]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=synergy>
Oct 25 13:01:54 thorne-ul-dt gnome-session[1243]: *** WARNING *** The program 'synergy' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Oct 25 13:01:54 thorne-ul-dt gnome-session[1243]: *** WARNING *** Please fix your application to use the native API of Avahi!
Oct 25 13:01:54 thorne-ul-dt gnome-session[1243]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=synergy&f=DNSServiceRegister>
Oct 25 13:01:54 thorne-ul-dt synergy[1484]: *** WARNING *** The program 'synergy' uses the Apple Bonjour compatibility layer of Avahi.
Oct 25 13:01:54 thorne-ul-dt synergy[1484]: *** WARNING *** Please fix your application to use the native API of Avahi!
Oct 25 13:01:54 thorne-ul-dt synergy[1484]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=synergy>
Oct 25 13:01:54 thorne-ul-dt synergy[1484]: *** WARNING *** The program 'synergy' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Oct 25 13:01:54 thorne-ul-dt synergy[1484]: *** WARNING *** Please fix your application to use the native API of Avahi!
Oct 25 13:01:54 thorne-ul-dt synergy[1484]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=synergy&f=DNSServiceRegister>
````

### Operating Systems ###

Server: Ubuntu 16.04 LTS
Client: Windows 7

### Synergy Version ###

1.8.2-stable-36cd521

### Steps to reproduce bug ###

Look in the Syslog after running a Synergy server on an Ubuntu 16.04 machines. 

### Other info ###

* When did the problem start to occur? 
Looks like it happened today.  Possibly it is a login or reboot related event.  

* Is there a way to work around it? 
You can probably just ignore it.  

* Does this bug prevent you from using Synergy entirely? 
No

**Comment by nlyan** [comment]
Avahi / Autoconfig support will be replaced entirely in version 2.0. Patches are welcome but otherwise we have no intention of fixing these warnings.
