### ISSUE TITLE
User upgrade statistics

### ISSUE THREAD

**Issue by nlyan** [symless/synergy#5707]
Problem: As a company we need better stats on what platforms and version of our software customers are using.

Solution: Implement pings when users upgrade

**Comment by ccoenen** [comment]
As a User I would very much like to know when data about me is collected. Finding out by accident via the changelog is not really pleasant.

**Comment by deckar01** [comment]
The standard UX for this functionality is a modal that asks "Would you like to provide anonymous usage statistic to help improve this product?", and not turn it on without explicit consent.
