### ISSUE TITLE
macOS client cannot receive some key combination from Windows server.

### ISSUE THREAD

**Issue by kndol** [symless/synergy#5712]
### Operating Systems

Server: Microsoft Windows 10
Client: macOS Sierra
### Synergy Version

1.8.5
### Steps to reproduce bug
1. Press key Shift-Space on Windows. (I'm using this for Korean IME.)
2. macOS doesn't recognize Shift-Space.
### Other info
- When did the problem start to occur? long long time ago
- Is there a way to work around it? No
- Does this bug prevent you from using Synergy entirely? Yes

Put anything else you can think of here.

I always patch the source code by myself:
lib/synergy/KeyMap.cpp

> const KeyMap::KeyItem*
> KeyMap::mapKey(Keystrokes& keys, KeyID id, SInt32 group,
>               ModifierToKeys& activeModifiers,
>               KeyModifierMask& currentState,
>               KeyModifierMask desiredMask,
>               bool isAutoRepeat) const
> {
>   LOG((CLOG_DEBUG1 "mapKey %04x (%d) with mask %04x, start state: %04x", id, id, desiredMask, currentState));
> 
>   // Add below line to recognize Shift-Space
>   if (id == 0xef26) id = 0x0020;

However, I cannot compile the source code on Sierra, now.

**Comment by XinyuHou** [comment]
@kndol 
Please test this nightly 
http://symless.com/nightly?filter=synergy-issue5592-ctrl-up-key-rc1-e8145aa-MacOSX-x86_64.dmg

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
