### ISSUE TITLE
Compile errors with QT 5.7 on macOS Sierra

### ISSUE THREAD

**Issue by kndol** [symless/synergy#5719]
### Operating Systems ###

macOS Sierraa

### Synergy Version ###

1.8.5~

### Steps to reproduce bug ###

1. I modified ext/toolchain/commands1.py file to correct the QT directory.
/Developer/Qt5.2.1/5.2.1 --> /Users/USERNAME/Qt/5.7

2. When I tried to compile with QT 5.7, I met errors, fail to comile it.
Error: [Errno 2] No such file or directory: '/Users/USERNAME/Qt/5.7/clang_64/lib/QtCore.framework/Contents/Info.plist'

3. I modified commands1.py file:
shutil.copy(
		frameworkRootDir + "/" + dir + "/**Contents**/Info.plist",
		target + "/" + dir + "/Resources/")
 -->
shutil.copy(
		frameworkRootDir + "/" + dir + "/**Resources**/Info.plist",
		target + "/" + dir + "/Resources/")
 
4. The next error is:
Error: Destination path '5/Resources' already exists

5. remove below line, and I can compile successfully.
self.move("../Resources", "5")

### Other info ###

* Does this bug prevent you from using Synergy entirely? No

**Comment by XinyuHou** [comment]
Please create a Pull request. Thanks.
