### ISSUE TITLE
Synergy 1.8.5 pointer can't move across multi-monitors

### ISSUE THREAD

**Issue by chepec** [symless/synergy#5720]
### Operating Systems ###

Server: Ubuntu 14.04.5 LTS
Client: Windows 10 version 1607

### Synergy Version ###

1.8.5 (same on both)

### Steps to reproduce bug ###

Installed Synergy 1.8.5 on host (3 monitor setup) and client (laptop). Setup and started connection. 
Synergy reports that machines are successfully connected.

Bug: mouse pointer stuck on whatever monitor the Synergy window was in on the host machine. No way to reach the client, mouse pointer just "flows back" to the other side of the same monitor. No way to reach the other monitors on the host itself, either. 
Snapped out of it by stopping the connection using the client's physical mousepad.

Note: Everything works as expected with Synergy 1.7.6 on host (tested, this is what I fell back to for the time being). I've used Synergy since at least 1.7.1. First time I encounter this bug.

**Comment by XinyuHou** [comment]
@chepec 
Thanks for the feedback.

Could you give us more information about your screen resolutions and alignment?

**Comment by chepec** [comment]
Ok, so this still occurs on Debian Jessie with Gnome and otherwise the same monitor config and Synergy 1.8.5 (I had reinstalled my system since the original report, but I have been able to observe the same behaviour).

== Current system
Server Debian Jessie 8.6, Gnome desktop
Client: Ubuntu 14.04.5 LTS, also Gnome desktop

Monitors: three monitors in physical portrait orientation. Each monitor is 1920 x 1200. All aligned on the same horizontal level. Primary monitor (with menus and such) in the center, on the left is #2 and on the right is #3 (according to the Display utility).

I set up a server-client share using the GUI ("configure interactively") and I can observe the following behaviour:

If I place the client *to the right* of the server in the GUI, then press Start, the mouse pointer cannot move outside the left-most monitor on the server (monitor #2 as per above). When it hits the edge between the left and center monitor it cycles back to the left edge of the left-most monitor. Vertical movement is not obstructed.

If I instead place the client *to the left" of the server in the GUI, then press Start, the mouse pointer moves freely on the server's desktop, but as soon as I move it to the client the pointer gets stuck on the left-hand edge of the client's desktop (allowing only vertical movement along the edge).

I guess this could either be due to multi-monitors in general, or perhaps more likely it's related to multi-monitors with Ubuntu/Debian acting as server?

Hope this report helps and keep up the good work.

**Comment by XinyuHou** [comment]
> Primary monitor (with menus and such) in the center, on the left is #2 and on the right is #3 (according to the Display utility).

this may be the problem. Could you try to change the primary screen to the left most one?

**Comment by alistair23** [comment]
I have the exact same problem with Ubuntu 16.04 and Synergy 1.8.6.
I am using three monitors vertically on Ubuntu which is the Synergy server. The mouse it stuck on the screen where I open Synergy. If I only place the launcher on a single screen I can move my cursor to the Windows client, but I can't access the other screens.

**Comment by chepec** [comment]
@XinyuHou Yes, that actually bypasses the issue. I just tested to switch my primary monitor to the left-most one as you suggested, and setup Synergy sharing with a Macbook. Both running Synergy v1.8.7. Works fine.

And the issue immediately returns if I switch the primary screen on the host back to the center monitor.
So it seems you've got the issue pinned down. Any hope for an actual fix? :-)

**Comment by XinyuHou** [comment]
@chepec 
Thank you for letting us know. I will mark this as closed.

**Comment by radimklaska** [comment]
Sorry, but rearranging monitors / changing primary display as described in https://github.com/symless/synergy-core/issues/5720#issuecomment-269779813 is not a fix. That's just good start for debugging process... 

This is not fixed...

Confirming this bug on Ubuntu 18 (2 screens side by side in 1st row, 3rd screen in 2nd row.) as server and Ubuntu 17 (one screen) as client. Synergy 1.10.0 setup with client and server side by side. Chnaging primary monitor does not help in this cofiguration. (It messes up other things like Ubuntu Dock placement anyway)

**Comment by mattlcbesc** [comment]
Confirm the same issue in 18.04 as well.

**Comment by crowlogic** [comment]
I'm still getting this bug in 1.8.8 , was it closed cause it was fixed?

**Comment by dyne87** [comment]
For those that find this thread googling this bug, are running their server on win10, and find @XinyuHou's "solution" incredibly lacking, here's how to solve this issue. In your synergy install directory, right click synergys.exe, click properties, compatibility tab, click "change settings for all users", click "change high dpi settings", check the box for "High DPI scaling override", then ok back out. Restart the synergy service and synergy will now let your mouse move to clients without having to set your left monitor as the main display.

There may be a similar fix to this for Ubuntu but I haven't used it since 7.4 and don't know where to look.
