### ISSUE TITLE
Win+L locks Windows Server when on client side

### ISSUE THREAD

**Issue by cmellwig** [symless/synergy#5725]
### Operating Systems ###

Server: Windows 10 1607
Client: Arch Linux

### Synergy Version ###

synergy-v1.8.5-stable-a18eba7-Windows-x64

### Steps to reproduce bug ###

Press Win+L

### Other info ###

Since v 1.8.4 I noticed that Win+L locks Windows while the cursor is on the client machine. That interferes with a lot of my Linux software. Plus it takes about half a minute until I can access the client again

**Comment by XinyuHou** [comment]
Duplicate of #5596
