### ISSUE TITLE
Synergy breaks Windows Startmenu

### ISSUE THREAD

**Issue by cmellwig** [symless/synergy#5726]
### Operating Systems ###

Server: Windows 10 1607
Client: Arch Linux

### Synergy Version ###

synergy-v1.8.5-stable-a18eba7-Windows-x64

### Steps to reproduce bug ###

Open Startmenu, type something. Items can't be clicked. Only occurs while in search/best match mode. Occurs since 1.8.5 (maybe 1.8.4 since I skipped that).

**Comment by XinyuHou** [comment]
@cmellwig 

Please send us some logs with log level set to Debug.
https://github.com/symless/synergy/wiki/Sending-logs

**Comment by Daiben** [comment]
I had the same problem. 

Fixed it on the server - > edit -> settings -> elevate always

**Comment by XinyuHou** [comment]
Can't reproduce with 1.8.6. Please try 1.8.6
