### ISSUE TITLE
2 source file include gtest files

### ISSUE THREAD

**Issue by lfarkas** [symless/synergy#5734]
./lib/synergy/KeyMap.h:#include "gtest/gtest_prod.h"
./lib/shared/SerialKey.h:#include "gtest/gtest_prod.h"

this files are include unit test file in the product which cause compile fail in case of packaging (eg fedora). imho these include should have to be deleted from these files

**Comment by XinyuHou** [comment]
Those file are for unit testing. Regarding how to compile Synergy. Please check our wiki.

https://github.com/symless/synergy/wiki/Compiling
