### ISSUE TITLE
NMAKE cannot make 'release' after building

### ISSUE THREAD

**Issue by Phildor92** [symless/synergy#5737]
### Operating Systems ###

Server/Client: Windows 7 x64

### Synergy Version ###

1.9.0

### Steps to reproduce bug ###

1. compile 1.9.0 (using hm conf -g2)
2. build 1.9.0 (using hm build)
3. After build succeeds, make GUI command starts and shortly thereafter fails
  -> NMAKE: fatal error U1073: don't know how to make 'release'

### Other info ###

attached error and traceback acquired by using -v on hm build
[nmakefail.txt](https://github.com/symless/synergy/files/580753/nmakefail.txt)

Using Visual Studio 14.0 2015

**Comment by XinyuHou** [comment]
@Phildor92 
There might be an error in configure stage. Branch 1.9 is still an experimental branch. Please subscribe to our dev mailing list rather than using issue tracker. Thanks.

https://groups.google.com/forum/#!forum/synergy-dev
