### ISSUE TITLE
download url unreachable

### ISSUE THREAD

**Issue by Usualme** [symless/synergy#5740]
### Operating Systems ###

Server: microOS Tiara
Client: Applesoft Windy OS 10

**READ ME, DELETE ME**: On Windows, hold the Windows key and press 'r', type 'winver' and hit return to get your OS version. On Mac, hit the Apple menu (top left of the screen) and check 'About this Mac'. Linux users... you know what you're using ;)

### Synergy Version ###

latest

### Steps to reproduce bug ###

1. open http://symless.com
2. click Download button and go http://symless.com/download/free/ page
3. download synergy for mac os 10.12
4. click **direct link** on waiting page
5. get 404 code

<img src="http://odr4rqxcv.bkt.clouddn.com/2016/1478930416358.png" width="1389"/>

**Comment by nlyan** [comment]
The code that renders the free download and paid download pages is the same. We currently have no plans to support additional platforms (new OS's) for old versions of Synergy (1.4.x series etc).
