### ISSUE TITLE
Can no longer move mouse to client machine

### ISSUE THREAD

**Issue by BenBergman** [symless/synergy#5743]
### Operating Systems ###

Server: Arch Linux (Linux 4.8.7-1-ARCH #1 SMP PREEMPT Thu Nov 10 17:22:48 CET 2016 x86_64 GNU/Linux)
Client: Windows 7 Enterprise (6.1 build 7601: Service Pack 1)

### Synergy Version ###

Server: synergys 1.8.5, protocol version 1.6
Client: 1.8.5-stable-a18eba7

### Steps to reproduce bug ###

My setup was working a few weeks ago. After running a system update on my server my client could no longer connect. Sorry for the lack of specific reproduction steps. :(

### Other info ###

This started a few weeks ago after a system update on my server. Initially the client was complaining about an SSL error, so I disabled SSL on the server and client to bypass that issue. Now the client can connect to the server, and the cursor disappears on the client as I'm used to upon successful reconnection, but I am unable to move my mouse to the client screen using the screen edge I am used to using. My scroll lock is off as per the FAQ. My /etc/synergy.conf is as follows:

```
# sample synergy configuration file
#
# comments begin with the # character and continue to the end of
# line.  comments may appear anywhere the syntax permits.

section: screens
        bendesktop:
        LAP38813:
end

section: links
        bendesktop:
                right = LAP38813

        LAP38813:
                left  = bendesktop
end

section: aliases
        LAP38813:
                192.168.0.10
        benusb
end

section: options
        mousebutton(6) = mousebutton(4)
        mousebutton(7) = mousebutton(5)
end
```

**Comment by BenBergman** [comment]
I decided to try running my synergy server from git instead of running the proper release. When trying to move my mouse to the other screen, I got the following error:

```
synergys: /tmp/yaourt-tmp-ben/aur-synergy-git/src/synergy/src/lib/platform/XWindowsScreen.cpp:2027: bool XWindowsScreen::grabMouseAndKeyboard(): Assertion `result != GrabNotViewable' failed.
zsh: abort (core dumped)  synergys -f
```

**Comment by wasrek404** [comment]
I have a very similar issue. Client connects without issue. When trying to switch the mouse moves all over the place (uncontrollable) on windows client (arch as server). With the same arch as server and another arch as client the cursor disappears (log says I switched screens but the cursor on the other screen is not moving). Going back to the server the mouse reappears in the middle of the screen out of nowhere. This van also be found in the log:

synergys: /build/synergy/src/synergy-1.8.5-stable/src/lib/platform/XWindowsScreen.cpp:2027: bool XWindowsScreen::grabMouseAndKeyboard(): Assertion `result != GrabNotViewable' failed.
[2016-12-02T00:46:23] ERROR: process exited with error code: 6
[2016-12-02T00:46:23] INFO: detected process not running, auto restarting

**Comment by BenBergman** [comment]
I have more information! While trying to fix a different issue on my machine I specifically loaded Gnome in Xorg mode. Within Xorg mode, everything works! I think the default on my machine is to start Gnome with Wayland, so I'm guessing synergys isn't compatible with Wayland yet.

**Comment by wasrek404** [comment]
Nice find BenBergman! I guess that is also the reason why my previous version of synergy (the ones I have) don't work anymore (but they used to). I have no clue how I can check when wayland was introduced into arch. I tried installing 2 older (other) version and none of them worked although it used to.

**Comment by XinyuHou** [comment]
@BenBergman @wasrek404 
Synergy currently doesn't support wayland yet. We do have a plan to implement the feature here is the ticket.  #4090

**Comment by BenBergman** [comment]
Thanks for the pointer! I'll be sure to watch that ticket closely so I can switch my system back over.
