### ISSUE TITLE
mouse disappears with Wayland guest. Please support Wayland.

### ISSUE THREAD

**Issue by andrewspiers** [symless/synergy#5747]
### Operating Systems ###

Server: Fedora 25
Client: Arch Linux

### Synergy Version ###

1.8.5

### Steps to reproduce bug ###

Start a Wayland gnome session in the client. Observe that the mouse is invisible. (I didn't see any warnings in the logs)

### Workaround ###

Start a gnome x session.

**Comment by nishikant** [comment]
Server: Fedora 25 Workstation.
Client: Windows 10
Synergy Version: 1.8.5
Issues: 
1\ Cannot leave screen.
2\ On trying to leave screen mouse is invisible, synergy log displays "Warning: can't leave screen"
3\ This happens with SSL and without SSL.
![screenshot from 2016-11-24 12-14-40](https://cloud.githubusercontent.com/assets/981784/20589116/585e7b2a-b240-11e6-80da-f9d7348d1c65.png)

**Comment by arquio** [comment]
Same Error
Server: Fedora 25
Client: Fedora 25

Versión: 1.7.6

**Comment by XinyuHou** [comment]
#4090

**Comment by nbolton** [comment]
Fixed by: https://github.com/symless/synergy/pull/7449
