### ISSUE TITLE
Mouse Cursor invisible

### ISSUE THREAD

**Issue by MrFastDie** [symless/synergy#5751]
### Operating Systems ###

Server: Arch Linux (Linux ArchOnlyForMe 4.8.10-1-ARCH #1 SMP PREEMPT Mon Nov 21 11:55:43 CET 2016 x86_64 GNU/Linux)
Client: Arch Linux (Linux ThisIsMyArch 4.8.8-2-ARCH #1 SMP PREEMPT Thu Nov 17 14:51:03 CET 2016 x86_64 GNU/Linux)

### Synergy Version ###

1.8.5 - (synergy from packagelist)

### Steps to reproduce bug ###

I just installed Synergy on both of my machines - one as server, the other as Client.
When moving the mouse from the server to the Client the mouse is just invisible - everything else seems work fine!

### Other info ###

* When did the problem start to occur? After the fresh installation
* Is there a way to work around it? Don't find one
* Does this bug prevent you from using Synergy entirely?Yes

My client device has a broken graphics driver - but works fine if I use it with connected hardware - thats may cause the problem.

**Comment by residentbrit** [comment]
I have this issue after I wiped and reinstalled the OS on my client from Manjaro to Fedora25, Synergy client was working fine in Manjaro.  Versions on both machines is 1.8.5-stable-a18eba7, Mac is the server and is running 10.12.1.

**Comment by MrFastDie** [comment]
I think the problem is wayland - I use Gnome as desktop manager and with Arch gnome uses Wayland as default.

**Comment by arquio** [comment]
disable wayland by setting WaylandEnable=false in /etc/gdm/custom.conf b

**Comment by residentbrit** [comment]
Ok great, that worked for me, i uncommented the line in the config file, rebooted and I'm golden.

Thanks

**Comment by r00td0wn** [comment]
This workaround worked for me as well.

**Comment by MrFastDie** [comment]
Yep it worked, but hopefully there will come a Wayland support soon - My Synergy Server machine is still running with Wayland.

**Comment by XinyuHou** [comment]
Duplicate to #4090
