### ISSUE TITLE
No mouse/keyboard movement in client via multi-monitor RDP session in thin client

### ISSUE THREAD

**Issue by Jandev** [symless/synergy#5753]
### Operating Systems ###

Server: Windows 10 Pro
Client: Thin client with an RDP session to a Citrix machine having an RDP connection to a Windows 2008R2 VM.

### Synergy Version ###

1.8.5-stable

### Steps to reproduce bug ###

1. Start server
2. Log in to the client and start Synergy. This is in a multi-monitor RDP session.
3. Move mouse cursor to client
4. Read the logs, it's saying switch from `master machine` to `client machine` at ....
5. Check the client screen, *the mouse cursor isn't moving*
6. Press [alt]-[tab], keyboard controls aren't picked up on the client, even though the logs are saying `found key in group 0`
7. Move cursor back to master machine again
8. Logs tell you the machine has been switched again and you see the mouse and keyboard working on the master.

### Other info ###

Stuff appears to be working, but I don't seen anything happen visually on the client machine.
I've also tried Input Director, which is able to move mouse and use the keyboard, so I'm pretty sure the network is working, which is also proven by the logs of course.
Probably has something to do of being in an RDP session, but I fail to see why this would pose a problem.

**Comment by Jandev** [comment]
I've also tried setting up the RDP machine as a `master` and the laptop I have as a `client`, but this doesn't work either.
This is something which I can understand, a bit, as it's probably an issue with the 'window' borders of the RDP session.

**Comment by XinyuHou** [comment]
@Jandev 
Thanks for the feedback.

What are the resolutions of your multiple screens on client?

**Comment by Jandev** [comment]
Hi,

The RDP machine, which acts as a client, has 2 screens, both on the resolution with 1920x1080. It's a session with the checkbox on `Use all my monitors for the remote session`. The master, my laptop, also has a resolution of 1920x1080, but only a single monitor.

I just noticed the machines are in different subnets, 10.150.3.x (laptop) and 10.100.140.x (RDP/VM machine), however they are able to reach eachother, so this should probably be totally unrelated.

**Comment by XinyuHou** [comment]
The resolutions look fine and if they can reach each other, different subnets should not be a problem.

Please have a look at this issue to see if it's similar.
#5665

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
