### ISSUE TITLE
Failure to build against OpenSSL v1.1.0

### ISSUE THREAD

**Issue by cyrelk** [symless/synergy#5757]
### Operating Systems ###

Server: Debian Stretch
Client: Not Applicable

I get the following error when I try to compile synergy on an up-to-date debian Stretch:

/srv/src/synergy/src/lib/net/SecureSocket.cpp: In member function ‘void SecureSocket::showSecureCipherInfo()’:
/srv/src/synergy/src/lib/net/SecureSocket.cpp:810:46: error: invalid use of incomplete type ‘SSL {aka struct ssl_st}’
  STACK_OF(SSL_CIPHER) * cStack = m_ssl->m_ssl->session->ciphers;
                                              ^~
In file included from /usr/include/openssl/crypto.h:31:0,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:47,
                 from /srv/src/synergy/src/lib/net/SecureSocket.cpp:27:
/usr/include/openssl/ossl_typ.h:144:16: note: forward declaration of ‘SSL {aka struct ssl_st}’
 typedef struct ssl_st SSL;
                ^~~~~~
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-unused-local-typedef’ [-Werror]
cc1plus: all warnings being treated as errors
src/lib/net/CMakeFiles/net.dir/build.make:134 : la recette pour la cible « src/lib/net/CMakeFiles/net.dir/SecureSocket.cpp.o » a échouée
make[2]: *** [src/lib/net/CMakeFiles/net.dir/SecureSocket.cpp.o] Erreur 1
CMakeFiles/Makefile2:549 : la recette pour la cible « src/lib/net/CMakeFiles/net.dir/all » a échouée
make[1]: *** [src/lib/net/CMakeFiles/net.dir/all] Erreur 2
Makefile:83 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
Going back to: /srv/src/synergy
Error: make failed: 512

### Synergy Version ###

 v1.8.5-stable

### Steps to reproduce bug ###

Compilation

### Other info ###

Response from the debian package maintainer:

This is not a bug in OpenSSL. Those structures are no longer
accessable and you need to use functions to get that now.

See:
https://wiki.openssl.org/index.php/1.1_API_Changes

**Comment by XinyuHou** [comment]
Pull request [5746 ](https://github.com/symless/synergy/pull/5746)would fix this issue

**Comment by level323** [comment]
I confirm I encountered the same issue on a Debian Stretch box I'm in the middle of provisioning.

FWIW An ugly interim hack which worked for me was to copy the following files from a Debian Jessie system (of the same CPU architecture) across to the stretch machine:

/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
...and...
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0

**Comment by jlafourc** [comment]
Hi,

Is this PR planned to be merged soon ? Just to know ...

Thanks 

Julien

**Comment by geeksmith** [comment]
You can compile on a newer Debian release if you use the older headers and library:
sudo apt-get install libssl1.0-dev

It would be better if synergy would conform to the changes in the latest OpenSSL library.

**Comment by nlyan** [comment]
We think we've nailed this in v1.9, please see

https://symless.com/forums/topic/2587-synergy-v190-release-candidate/

**Comment by drocsid** [comment]
It didn't seem to work on my debian system. Still seemed to reference the older release, not 1.1.0 . https://symless.com/forums/topic/4143-using-old-ssl-libraries-in-version-18/
