### ISSUE TITLE
Modifier Keys Selector Does Not Function in OS X

### ISSUE THREAD

**Issue by peterfeddo** [symless/synergy#5758]
### Operating Systems ###

Server: OS X 10.12.1
Client: Ubuntu

### Synergy Version ###

1.8.6-rc1 and previous versions

### Steps to reproduce bug ###

1. Select Configure Server
2. Double click a client machine icon
3. Select a modifier key to change
4. Nothing happens, up/down arrows don't allow a change. Pressing a key doesn't allow a change. No modifer can currently be adjusted.

**Comment by XinyuHou** [comment]
@peterfeddo 
Please try our latest release.
