### ISSUE TITLE
Allow hotkeys to be bound to specific PCs

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#576]
**Imported issue:**
- Author: malvineous (Google user)
- Date: 2010-06-23 00:00:00
- Legacy ID: 589

Currently the keystroke() option binds keys on all PCs.  If any of them fail (because the hotkey is in use) the bind will fail on all PCs.  

It should be possible to only bind a hotkey on a single PC, like this:  

  keystroke(super+f1)      = ...   # current  
  keystroke(super+f1, moe) = ...   # better  

The (long) explanation for this is if you want to use hotkeys to switch between screens:  

  section: options  
    keystroke(super+f1) = switchToScreen(moe)  
    keystroke(super+f4) = switchToScreen(larry)  
  end  

Then super+f1 will be bound on 'moe', even though that key will only ever switch to its own screen (so it's a bit pointless.)  

This causes problems if the hotkey cannot be bound because it is in use, for example with the Awesome window manager.  I have super+f1 through f3 to switch between screens on a single PC, and I want Synergy to handle super+f4 to switch to another PC.  This works fine.  However on that other PC I want to be able to press super+f1 though f3 to switch back to the original PC, but Synergy won't register those hotkeys because they're already in use on the original PC (to switch between its local screens.)  

If it were possible to only register super-f1 to f3 on a single PC, then this would work fine, and I could use super-f1 to f4 to freely switch between all screens across two PCs.

**Comment by XinyuHou** [comment]
Close as an obsolete issue

**Comment by retropc** [comment]
has this been implemented? I would very much like this fuctionality

otherwise it doesn't seem to be "obsolete"!
