### ISSUE TITLE
'cannot open secondary screen' Error

### ISSUE THREAD

**Issue by Zangoran** [symless/synergy#5761]
### Operating Systems ###

Server: Windows 10 V. 1607
Client: CentOS 6.8 Minimal

### Synergy Version ###

1.8.4

### Steps to reproduce bug ###

Install Synergy on Client and server
Setup config
Run client using command line
Get error: 'cannot open secondary screen: unable to open screen'

### Other info ###

* Is there a way to work around it? Not that I have found yet.
* Does this bug prevent you from using Synergy entirely? Yes!

Put anything else you can think of here.

Hopefully I didn't overlook something stupid. Thanks for the help!

**Comment by XinyuHou** [comment]
@Zangoran 
Please send us some logging from your client side.

https://github.com/symless/synergy/wiki/Sending-logs

**Comment by Zangoran** [comment]
@XinyuHou How can I do this using only the command line? I am running a minimal version of CentOS for the client.

**Comment by XinyuHou** [comment]
in the command append --debug DEBUG

**Comment by Zangoran** [comment]
When I try to run the client service using this command 'synergyc --debug DEBUG ip.address.is.here' it outputs this text: 
`INFO: Synergy 1.3.6 Client on Linux 2.6.32-642.6.2.e16.i686 #1 SMP Web OCT 26 06:14:53 UTC 2016 i686 /dar/build/synergy-1.3.6-Source/cmd/synergyc/synergyc.cpp,765`

Is that what you wanted?

**Comment by XinyuHou** [comment]
This looks more like a support ticket. We use Github issue tracker to track new bugs or enhancement. 

Please log into you account on our website and contact our customer service.
https://symless.com/account/

Thanks
