### ISSUE TITLE
Mouse speed on client portrait screen is inconsistent

### ISSUE THREAD

**Issue by rfratto** [symless/synergy#5764]
### Operating Systems ###

Server: microOS Sierra 10.12.1
Client: microOS Sierra 10.12.1

### Synergy Version ###

1.8.5

### Steps to reproduce bug ###

1. Orient the client display to be 90º
2. Mouse movement on client display will be approximately twice as fast when moving the mouse up or left than down or right. You can see this more clearly if you make small adjustments to the mouse in all directions. 

### Other info ###

* When did the problem start to occur? This only started to occur once I started to use my portrait-oriented screen as a Synergy client. 
* Is there a way to work around it? No.
* Does this bug prevent you from using Synergy entirely? No.

**Comment by glyph** [comment]
Possibly related: #5648 #5607

**Comment by rfratto** [comment]
Ah, I missed those in my search. Closing this as a duplicate; thanks!
