### ISSUE TITLE
Compiling on Windows 10

### ISSUE THREAD

**Issue by ricsp** [symless/synergy#5767]
### Operating Systems ###

Windows 10

### Synergy Version ###

master

### Steps to reproduce bug ###

Hi, I am trying to compile synergy from source for windows following your wiki.
First of all when I configure the build I get this warning:

Warning: Not using supported Qt version 4.6.2 (your version is 5.6.2).

which is strange because in the requirements you say Qt 5.6..

Then when I compile I get this error:

Time Elapsed 00:00:08.76
Make GUI command: mingw32-make release
Entering dir: src/gui
mingw32-make -f Makefile.Release
mingw32-make[1]: Entering directory 'C:/Users/rspica/AppData/Local/Temp/Downloads/synergy/synergy/src/gui'
g++ -c -pipe -fno-keep-inline-dllexport -O2 -std=gnu++0x -frtti -Wall -Wextra -fexceptions -mthreads -DUNICODE -DVERSION_STAGE=\"stable\" -DVERSION_REVISION=\"00db51cd\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I. -I. -Isrc -I..\lib\shared -IC:\bjr/Include -IC:\Qt\5.6\mingw49_32\include -IC:\Qt\5.6\mingw49_32\include\QtWidgets -IC:\Qt\5.6\mingw49_32\include\QtGui -IC:\Qt\5.6\mingw49_32\include\QtANGLE -IC:\Qt\5.6\mingw49_32\include\QtNetwork -IC:\Qt\5.6\mingw49_32\include\QtCore -Itmp\release -I. -IC:\Qt\5.6\mingw49_32\mkspecs\win32-g++  -o tmp\release\MainWindow.o src\MainWindow.cpp
src\MainWindow.cpp:54:0: warning: "_WIN32_WINNT" redefined
 #define _WIN32_WINNT 0x0501
 ^
In file included from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/crtdefs.h:10:0,
                 from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/wchar.h:9,
                 from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/c++/cwchar:44,
                 from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/c++/bits/postypes.h:40,
                 from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/c++/iosfwd:40,
                 from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/c++/ios:38,
                 from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/c++/ostream:38,
                 from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/c++/iostream:39,
                 from src\MainWindow.cpp:21:
C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/_mingw.h:229:0: note: this is the location of the previous definition
 #define _WIN32_WINNT 0x502
 ^
src\MainWindow.cpp:352:66: warning: unused parameter 'reason' [-Wunused-parameter]
 void MainWindow::trayActivated(QSystemTrayIcon::ActivationReason reason)
                                                                  ^
src\MainWindow.cpp: In member function 'bool MainWindow::serverArgs(QStringList&, QString&)':
src\MainWindow.cpp:815:38: error: invalid use of incomplete type 'class QDesktopWidget'
  int height = QApplication::desktop()->height();
                                      ^
In file included from C:\Qt\5.6\mingw49_32\include/QtWidgets/QApplication:1:0,
                 from ./ui_MainWindowBase.h:14,
                 from src\MainWindow.h:29,
                 from src\MainWindow.cpp:23:
C:\Qt\5.6\mingw49_32\include/QtWidgets/qapplication.h:50:7: error: forward declaration of 'class QDesktopWidget'
 class QDesktopWidget;
       ^
src\MainWindow.cpp:816:37: error: invalid use of incomplete type 'class QDesktopWidget'
  int width = QApplication::desktop()->width();
                                     ^
In file included from C:\Qt\5.6\mingw49_32\include/QtWidgets/QApplication:1:0,
                 from ./ui_MainWindowBase.h:14,
                 from src\MainWindow.h:29,
                 from src\MainWindow.cpp:23:
C:\Qt\5.6\mingw49_32\include/QtWidgets/qapplication.h:50:7: error: forward declaration of 'class QDesktopWidget'
 class QDesktopWidget;
       ^
src\MainWindow.cpp:818:37: error: invalid use of incomplete type 'class QDesktopWidget'
  QRect rec = QApplication::desktop()->screenGeometry();
                                     ^
In file included from C:\Qt\5.6\mingw49_32\include/QtWidgets/QApplication:1:0,
                 from ./ui_MainWindowBase.h:14,
                 from src\MainWindow.h:29,
                 from src\MainWindow.cpp:23:
C:\Qt\5.6\mingw49_32\include/QtWidgets/qapplication.h:50:7: error: forward declaration of 'class QDesktopWidget'
 class QDesktopWidget;
       ^
src\MainWindow.cpp: At global scope:
src\MainWindow.cpp:1082:34: warning: unused parameter 'isExpiring' [-Wunused-parameter]
 void MainWindow::beginTrial(bool isExpiring)
                                  ^
src\MainWindow.cpp: In member function 'void MainWindow::installBonjour()':
src\MainWindow.cpp:1369:25: error: 'storageLocation' is not a member of 'QDesktopServices'
  QString tempLocation = QDesktopServices::storageLocation(
                         ^
src\MainWindow.cpp:1370:9: error: 'TempLocation' is not a member of 'QDesktopServices'
         QDesktopServices::TempLocation);
         ^
Makefile.Release:5411: recipe for target 'tmp/release/MainWindow.o' failed
mingw32-make[1]: *** [tmp/release/MainWindow.o] Error 1
mingw32-make[1]: Leaving directory 'C:/Users/rspica/AppData/Local/Temp/Downloads/synergy/synergy/src/gui'
makefile:34: recipe for target 'release' failed
mingw32-make: *** [release] Error 2
Going back to: C:\Users\rspica\AppData\Local\Temp\Downloads\synergy\synergy
Error: mingw32-make release failed with error: 2

thanks for helping me.
Cheers.

Riccardo

**Comment by XinyuHou** [comment]
@ricsp 
Sorry for the confusion.

Branch 1.8.X is using Qt4.8 while 1.9 is using Qt5. Please use our dev mailing list to discuss compiling issues.

http://groups.google.com/group/synergy-dev
