### ISSUE TITLE
Cursor deadlock when PC locked and mouse cursor moved to display border

### ISSUE THREAD

**Issue by QuAzI** [symless/synergy#5768]
### Operating Systems

Client: Linux Mint 17.3
Server: Windows 7 SP1 EN AMD64

### Synergy Version

1.8.5 on both sides but on older versions bug present too

### Steps to reproduce bug

When server station locked - synergy functions must be disabled!

On Windows side (where keyboard and mouse attached) enabled password authorisation after screen locking.
![screen_saver_settings_rundll32_2016-12-11_15-10-21_50doixjj](https://cloud.githubusercontent.com/assets/1897605/21079995/b1be4fac-bfb4-11e6-933b-a020813a5d13.png)

If station locked and I move cursor to left side or right side (where other stations connected) - cursor locked at border and I can't move cursor to the password field. If I try to use keyboard I can see that keyboard events work for client (looks like security vulnerability).
Example: When I move cursor to X = 0 (left side) mouse cursor locked at X = 0 and left desktop have focus but only keyboard work.
Only one workaround I have when this happens - disable service on client (through keyboard hints or VNC client or remove LAN connector).

My current hardware configuration
![server_configuration_synergy_2016-12-11_15-29-09_mipvaqgm](https://cloud.githubusercontent.com/assets/1897605/21080083/e061eea2-bfb6-11e6-94f6-c790350221cf.png)

**Comment by XinyuHou** [comment]
Duplicate of #5772
