### ISSUE TITLE
Drag and Drop Problem found

### ISSUE THREAD

**Issue by kikokonik** [symless/synergy#5771]
### Operating Systems ###

Server: Windows 10 Pro Version 1607 Build 14393.479
Client: Windows 8.1 Pro Version 6.3 Build 9600

### Synergy Version ###

1.8.6-stable-2ab21aa

### Steps to reproduce bug ###

I got my drag and drop to work with Elevate set to As needed and turned off SSL.

But problem is when i transfer file with specific characters.
This file name crashed "Poznámky k podkladom za 4týždeň s.t.6.docx"

LOG part:
[2016-12-12T22:17:17] DEBUG: drag file name is invalid: D:\Kristi�n\Desktop\Pozn�mky k podkladom za 4t�
[2016-12-12T22:17:17] DEBUG: failed to get drag file name from OLE

(D:\Kristián\Desktop\Poznámky k podkladom za 4tý)

I tried changing name of file to see what causes it. It is the "ž" character.

Is it possible to fix it somehow? It is not big problem, but I wanted to help you make your program better.

### Other info ###

* When did the problem start to occur? When I tried to copy file above.
* Is there a way to work around it? Yes, you can delete the "ž" character from name
* Does this bug prevent you from using Synergy entirely? No

**Comment by yupi2** [comment]
This isn't a bug with Drag and Drop but with the Unicode handling in the builds for Windows.
See #5365

**Comment by kikokonik** [comment]
@yupi2 I overlooked this one somehow, thank you.
