### ISSUE TITLE
Windows: Cursor stuck on client window after lock

### ISSUE THREAD

**Issue by Celant** [symless/synergy#5772]
### Operating Systems ###

Server: Windows 10 64-bit
Client: Windows 10 64-bit

### Synergy Version ###

1.8.6

### Steps to reproduce bug ###

1. Connect Synergy client to server
2. Lock both client and server screens
3. Move cursor from server to client
4. See that cursor can't return to the server screen

**Comment by alpha14** [comment]
I have the same issue with a server on windows7 and a client on debian (with version 1.8.7)
The only difference is that I only need to lock the master computer to get this bug.

**Comment by XinyuHou** [comment]
Duplicate of #5294
