### ISSUE TITLE
[Compilation Error, 1.8.6, Mac OS Sierra 10.12.1] Cannot get ./hm.sh conf to succeed 

### ISSUE THREAD

**Issue by arooni** [symless/synergy#5775]
### Operating Systems ###
Server: MacOS Sierra (10.12.1)
Client: Ubuntu 16.04 (not relavent)

**READ ME, DELETE ME**: On Windows, hold the Windows key and press 'r', type 'winver' and hit return to get your OS version. On Mac, hit the Apple menu (top left of the screen) and check 'About this Mac'. Linux users... you know what you're using ;)

### Synergy Version ###

1.8.6

**READ ME, DELETE ME**: Go to the 'Help' (on Windows) or 'Synergy' (on macOS) menu and then 'About Synergy' to check your version. Verify that you are using the same version across all of your machines, and that your issue still occurs with the latest release available at https://symless.com/account/login

### Steps to reproduce bug ###
Followed instructions of changing 
`Fix "./ext/toolchain/commands1.py"
In the function configureCore() at approx line 433, change:
elif sys.platform == "darwin": to read if sys.platform == "darwin":
In the function macPostGuiMake() at approx line 762 and 765 change the path of frameworkRootDir to be what your Qt library path is, something like:
frameworkRootDir = "/usr/local/Cellar/qt/4.8.7_2/Frameworks"
See this github issue for more information.
`

The first instruction wasn't applicable as the code already had an if as opposed to an elif.  I did change the directory for qt framework as indicated.  

Then I tried to configure; but ran

`[I]  ~/D/synergy-1.8.6-stable  ./hm.sh conf -g2 --mac-sdk 10.12 --mac-identity MiniArooni
Mapping command: conf -> configure
cmake version 3.7.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Entering dir: build
CMake command: cmake -G "Xcode" -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 -DOSX_TARGET_MAJOR=10 -DOSX_TARGET_MINOR=12 ..
-- OSX_TARGET_MAJOR=10
-- OSX_TARGET_MINOR=12
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/david/Downloads/synergy-1.8.6-stable/build
Going back to: /Users/david/Downloads/synergy-1.8.6-stable
Error: Could not get revision, git error: 128
[I]  ✘  ~/D/synergy-1.8.6-stable 
`

I also upgraded git, qt, and cmake to latest version without effect.

### Other info ###

* When did the problem start to occur? When I...
During configuration 

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy/wiki/Sending-logs

Put anything else you can think of here.

Thanks for a great app! Eager to use the latest version!

**Comment by yupi2** [comment]
`git clone` the repository instead of downloading a zip/tar.gz from the releases tab.

**Comment by arooni** [comment]
If I clone the repo; won't I get the nightly build instead of the stable 1.8.6 build?

**Comment by yupi2** [comment]
The master branch is currently tied with the 1.8.6 release.
There's nothing wrong with using a nightly build though.

**Comment by arooni** [comment]
Thanks @yupi2 !  Cloning the repo made that error go away.  Maybe they could add a note to the compilation instructions that this is the preferred way of getting the source code.  I'd close this issue but I don't think I have the privileges.

**Comment by XinyuHou** [comment]
Closed as the problem has been solved.
