### ISSUE TITLE
Edition changes when reopening GUI

### ISSUE THREAD

**Issue by XinyuHou** [symless/synergy#5784]
### Operating Systems ###

All platforms

### Synergy Version ###

1.8.6

### Steps to reproduce bug ###

1. Activate with either a Pro or a basic account.
2. Close the GUI.
3. Reopen the GUI.

### Other info ###

* When did the problem start to occur? Since 1.8.6
* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? No

**Comment by nlyan** [comment]
Fixed in v1.8.7
