### ISSUE TITLE
RPM packages with outdated (and vulnerable) OpenSSL

### ISSUE THREAD

**Issue by bcdonadio** [symless/synergy#5787]
The RPMs of Synergy for Fedora available for download on the Symless website are being built with an obsolete and vulnerable version of OpenSSL (1.0.1e), causing both security and stability issues.

When using the RPMs available for Fedora x64 on the website, Synergy accuses protocol asserts violations (unexpected EOFs), the mouse is sluggish and some connections simply do not work.

All the problems above are simply corrected by linking Synergy to OpenSSL 1.0.2j, which is the default version on Fedora 25 and is currently supported by the OpenSSL and Fedora security teams.

The versions tested were the `synergy-v1.8.6-stable-2ab21aa-Linux-x86_64.rpm` released on the Symless website, and a locally built RPM from the ade4b7f8a2a1e9270b9fbb49160050ad1ebd285d commit.

**Comment by nlyan** [comment]
We're actually building against OpenSSL as-is available on CentOS 6.x which, as an OS, is supported by backports from Red Hat until 2020. 

I see that OpenSSL 1.0.1 went out of direct support from the OpenSSL project on the 2nd of January, so I'm not sure what CentOS are planning on doing here.

In any case we already have new Fedora 25 and CentOS 7 build machines internally. Future releases will be made from these machines. Rewritten debs and rpms are also on our todo list.

**Comment by XinyuHou** [comment]
Duplicate of #5398
