### ISSUE TITLE
Activation state reset to basic after restart

### ISSUE THREAD

**Issue by supercoffee** [symless/synergy#5790]
# Problem description
Synergy seems to "forget" it's license activation state after program restarts. This causes SSL to be disabled which prevents clients from reconnecting until manually reactivating the license. This will happen on both the server and client end, usually after a reboot. 

### Operating Systems ###

Server: macOS El Capitan 10.11.6
Client: macOS El Capitan 10.11.6

### Synergy Version ###

1.8.6-stable-2ab21aa

### Steps to reproduce bug ###

1. Activate synergy on server and client, configure using auto config
2. Kill synergy server 
3. Open synergy server
4. Observe that client cannot connect to server
5. Open Synergy preferences
6.  observe SSL option not available
7. File > Activate > OK
8. Observe that client reconnects as SSL options is automatically reactivated after license activation

**Comment by JefferE** [comment]
I had the exact same issue today. Worked fine after initial install on Mac OSx Capitan, Windows 7, and Windows 10 afew days ago.

This morning all machines were rebooted for a reason not related to Synergy but after restart none of them would reconnect with server the way it worked the day before.

After fighting with connections and trying to find a resolution googling connection refusal and failed SSL everything worked fine if I turned off SSL.

Was on the verge of asking for a refund when I found this issue. 

Reactivating Synergy on all workstations fixed it. Now works with SSL all around. Will see what happens on next machine restart if I have to reactivate them all again.

**Comment by Reanmachine** [comment]
This is happening on my Linux machine, but not my windows 10 machine. When i go to activate again only part of my key is in the input box, I imagine the culprit (at least for me) is that when it either saves/loads the configuration file the key isn't being read completely and then is considered invalid on launch.

**Comment by alanhoyle** [comment]
My macOS Sierra client has this same issue:  I have to manually go into the menus to Activate on reboot.  The full key is still there in the input box, but it thinks it's Synergy Basic until I do that.

**Comment by Reanmachine** [comment]
@alanhoyle The whole key? Mine is partial... I have to click the link and go grab the full thing from my web account.

**Comment by alanhoyle** [comment]
I hadn’t noticed before, but mine is also partial.  However, it appears to
accept it anyway.


--
  -  Alan Hoyle  -  alan@alanhoyle.com  -  http://www.alanhoyle.com/  -

**Comment by agc346** [comment]
Windows 10 Pro and Windows Server 2016, same issue, reverts to a partial key and forgets activation

**Comment by yupi2** [comment]
The key might be shortened somewhere in some Synergy configuration file or in the Windows registry.
@agc346 You check to see if the key is shortened in `regedit.exe`. Path is `HKEY_CURRENT_USER\Software\Synergy\Synergy` with the key name as `serialKey`

**Comment by nlyan** [comment]
This will be fixed in v1.8.7

**Comment by nlyan** [comment]
Fixed in v1.8.7

**Comment by jpork** [comment]
I run version 1.8.8-stable-25a8cb2 on Windows 7 and Fedora 25 (Gnome). 
On Fedora I'm required to re-activate my Synergy Pro license after system restart. It forgets about all setting not just the activation.
