### ISSUE TITLE
Issues building 1.8.6

### ISSUE THREAD

**Issue by StephanMeijer** [symless/synergy#5792]
### Operating Systems ###

- Fedora Workstation 25 with X11 and Gnome.
- Fedora Workstation 24 with X11 and Gnome

### Synergy Version ###

1.8.6

#### Fedora 25
Running command: `./hm.sh conf -g1`
Output:
```
Mapping command: conf -> configure
cmake version 3.6.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Entering dir: build/release
CMake command: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ../..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/steve/Documents/synergy-1.8.6-stable/synergy-1.8.6-stable/build/release
Going back to: /home/steve/Documents/synergy-1.8.6-stable/synergy-1.8.6-stable
Error: Could not get revision, git error: 128
```

#### Fedora 24
Same command.

Output:
```
Mapping command: conf -> configure
cmake version 3.6.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Entering dir: build/release
CMake command: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ../..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/steve/synergy-1.8.6-stable/build/release
Going back to: /home/steve/synergy-1.8.6-stable
Error: Could not get revision, git error: 128
```

**Comment by yupi2** [comment]
`git clone` the repository instead of downloading a zip/tar.gz from the releases tab.
The master branch is currently tied to 1.8.6 release too.

**Comment by JoshTheBlack** [comment]
Operating Systems

    Windows 10 Pro Version 1607 OS Build 14393.576

Synergy Version

1.8.6

Other info


Running command: hm build
Output ends with:
`C:\Qt\5.6\mingw49_32\bin\uic.exe res\FailedLoginDialog.ui -o ui_FailedLoginDialog.h
g++ -c -pipe -fno-keep-inline-dllexport -O2 -std=gnu++0x -frtti -Wall -Wextra -fexceptions -mthreads -DUNICODE -DVERSION_STAGE=\"stable\" -DVERSION_REVISION=\"ade4b7f8\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I. -I. -Isrc -I..\lib\shared -I"C:\Program Files\Bonjour SDK\"/Include -IC:\Qt\5.6\mingw49_32\include -IC:\Qt\5.6\mingw49_32\include\QtWidgets -IC:\Qt\5.6\mingw49_32\include\QtGui -IC:\Qt\5.6\mingw49_32\include\QtANGLE -IC:\Qt\5.6\mingw49_32\include\QtNetwork -IC:\Qt\5.6\mingw49_32\include\QtCore -Itmp\release -I. -IC:\Qt\5.6\mingw49_32\mkspecs\win32-g++  -o tmp\release\main.o src\main.cpp
g++: fatal error: no input files
compilation terminated.
Makefile.Release:4415: recipe for target 'tmp/release/main.o' failed
mingw32-make[1]: *** [tmp/release/main.o] Error 1
mingw32-make[1]: Leaving directory 'C:/Users/stone/Downloads/SM/synergy/src/gui'
makefile:34: recipe for target 'release' failed
mingw32-make: *** [release] Error 2
Going back to: C:\Users\stone\Downloads\SM\synergy
Error: mingw32-make release failed with error: 2`

Full output: http://pastebin.com/ZhVD9J36

**Comment by yupi2** [comment]
@JoshTheBlack That might be happening because of an escaped-quote here `-I"C:\Program Files\Bonjour SDK\"/Include`

It might be a problem with your BONJOUR_SDK_HOME variable or a problem with expanding variables in QMAKE. You can try changing this [line](https://github.com/symless/synergy/blob/fc67cdf56ea9d627598b8a343e2624396b9f8a12/src/gui/gui.pro#L145) of gui.pro to be

`INCLUDEPATH += "C:/Program Files/Bonjour SDK/Include"`

If that doesn't work you could try moving the SDK directory or creating a folder-link to a directory that doesn't have spaces in it and using that in the INCLUDEPATH

**Comment by andreyslyusar** [comment]
MacOS Sierra build failed:

`
=== BUILD AGGREGATE TARGET ALL_BUILD OF PROJECT synergy WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/Opium/Downloads/synergy/build/synergy.build/Release/ALL_BUILD.build/Script-902445819CBB42839858EB4C.sh
chmod 0755 /Users/Opium/Downloads/synergy/build/synergy.build/Release/ALL_BUILD.build/Script-902445819CBB42839858EB4C.sh

PhaseScriptExecution CMake\ Rules build/synergy.build/Release/ALL_BUILD.build/Script-902445819CBB42839858EB4C.sh
    cd /Users/Opium/Downloads/synergy
    /bin/sh -c /Users/Opium/Downloads/synergy/build/synergy.build/Release/ALL_BUILD.build/Script-902445819CBB42839858EB4C.sh
echo ""

echo Build\ all\ projects
Build all projects

** BUILD SUCCEEDED **

Going back to: /Users/Opium/Downloads/synergy
Make GUI command: make -w
Entering dir: src/gui
make: Entering directory `/Users/Opium/Downloads/synergy/src/gui'
/usr/local/Cellar/qt5/5.7.1_1/bin/uic res/MainWindowBase.ui -o ui_MainWindowBase.h
/usr/local/Cellar/qt5/5.7.1_1/bin/uic res/AboutDialogBase.ui -o ui_AboutDialogBase.h
/usr/local/Cellar/qt5/5.7.1_1/bin/uic res/ServerConfigDialogBase.ui -o ui_ServerConfigDialogBase.h
/usr/local/Cellar/qt5/5.7.1_1/bin/uic res/ScreenSettingsDialogBase.ui -o ui_ScreenSettingsDialogBase.h
/usr/local/Cellar/qt5/5.7.1_1/bin/uic res/ActionDialogBase.ui -o ui_ActionDialogBase.h
/usr/local/Cellar/qt5/5.7.1_1/bin/uic res/HotkeyDialogBase.ui -o ui_HotkeyDialogBase.h
/usr/local/Cellar/qt5/5.7.1_1/bin/uic res/SettingsDialogBase.ui -o ui_SettingsDialogBase.h
/usr/local/Cellar/qt5/5.7.1_1/bin/uic res/SetupWizardBase.ui -o ui_SetupWizardBase.h
/usr/local/Cellar/qt5/5.7.1_1/bin/uic res/AddClientDialogBase.ui -o ui_AddClientDialogBase.h
/usr/local/Cellar/qt5/5.7.1_1/bin/uic res/ActivationDialog.ui -o ui_ActivationDialog.h
/usr/local/Cellar/qt5/5.7.1_1/bin/uic res/CancelActivationDialog.ui -o ui_CancelActivationDialog.h
/usr/local/Cellar/qt5/5.7.1_1/bin/uic res/FailedLoginDialog.ui -o ui_FailedLoginDialog.h
/Applications/Xcode.app/Contents/Developer/usr/bin/g++ -c -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -O2 -std=gnu++11 -Wall -W -fPIC -DVERSION_STAGE=\"stable\" -DVERSION_REVISION=\"ade4b7f\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I. -Isrc -I../lib/shared -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers -Itmp/release -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/usr/local/Cellar/qt5/5.7.1_1/mkspecs/macx-g++ -F/usr/local/Cellar/qt5/5.7.1_1/lib -o tmp/release/main.o src/main.cpp
In file included from src/main.cpp:22:
In file included from src/QSynergyApplication.h:23:
In file included from /usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QApplication:1:
In file included from /usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qapplication.h:43:
In file included from /usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qcoreapplication.h:43:
In file included from /usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qglobal.h:1145:
In file included from /usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qatomic.h:46:
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:61:4: error: "Qt requires C++11 support"
#  error "Qt requires C++11 support"
   ^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:90:13: error: unknown type name 'QAtomicOps'
    typedef QAtomicOps<T> Ops;
            ^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:90:23: error: expected member name or ';' after declaration specifiers
    typedef QAtomicOps<T> Ops;
    ~~~~~~~~~~~~~~~~~~^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:93:23: error: use of undeclared identifier 'QAtomicOpsSupport'
    Q_STATIC_ASSERT_X(QAtomicOpsSupport<sizeof(T)>::IsSupported, "template parameter is an integral of a size not supported on this platform");
                      ^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:93:53: error: no member named 'IsSupported' in the global namespace
    Q_STATIC_ASSERT_X(QAtomicOpsSupport<sizeof(T)>::IsSupported, "template parameter is an integral of a size not supported on this platform");
                                                  ~~^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qglobal.h:746:66: note: expanded from macro 'Q_STATIC_ASSERT_X'
#define Q_STATIC_ASSERT_X(Condition, Message) static_assert(bool(Condition), Message)
                                                                 ^~~~~~~~~
In file included from src/main.cpp:22:
In file included from src/QSynergyApplication.h:23:
In file included from /usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QApplication:1:
In file included from /usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qapplication.h:43:
In file included from /usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qcoreapplication.h:43:
In file included from /usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qglobal.h:1145:
In file included from /usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qatomic.h:46:
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:95:14: error: use of undeclared identifier 'Ops'
    typename Ops::Type _q_value;
             ^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:95:19: error: expected a qualified name after 'typename'
    typename Ops::Type _q_value;
                  ^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:95:23: error: expected ';' at end of declaration list
    typename Ops::Type _q_value;
                      ^
                      ;
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:99:44: error: use of undeclared identifier 'Ops'
    T load() const Q_DECL_NOTHROW { return Ops::load(_q_value); }
                                           ^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:99:54: error: use of undeclared identifier '_q_value'
    T load() const Q_DECL_NOTHROW { return Ops::load(_q_value); }
                                                     ^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:100:45: error: use of undeclared identifier 'Ops'
    void store(T newValue) Q_DECL_NOTHROW { Ops::store(_q_value, newValue); }
                                            ^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:100:56: error: use of undeclared identifier '_q_value'
    void store(T newValue) Q_DECL_NOTHROW { Ops::store(_q_value, newValue); }
                                                       ^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:102:51: error: use of undeclared identifier 'Ops'
    T loadAcquire() const Q_DECL_NOTHROW { return Ops::loadAcquire(_q_value); }
                                                  ^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:102:68: error: use of undeclared identifier '_q_value'
    T loadAcquire() const Q_DECL_NOTHROW { return Ops::loadAcquire(_q_value); }
                                                                   ^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:103:52: error: use of undeclared identifier 'Ops'
    void storeRelease(T newValue) Q_DECL_NOTHROW { Ops::storeRelease(_q_value, newValue); }
                                                   ^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:103:70: error: use of undeclared identifier '_q_value'
    void storeRelease(T newValue) Q_DECL_NOTHROW { Ops::storeRelease(_q_value, newValue); }
                                                                     ^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:107:86: error: use of undeclared identifier 'Ops'
    static Q_DECL_CONSTEXPR bool isReferenceCountingNative() Q_DECL_NOTHROW { return Ops::isReferenceCountingNative(); }
                                                                                     ^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:107:34: error: no return statement in constexpr function
    static Q_DECL_CONSTEXPR bool isReferenceCountingNative() Q_DECL_NOTHROW { return Ops::isReferenceCountingNative(); }
                                 ^
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qbasicatomic.h:108:88: error: use of undeclared identifier 'Ops'
    static Q_DECL_CONSTEXPR bool isReferenceCountingWaitFree() Q_DECL_NOTHROW { return Ops::isReferenceCountingWaitFree(); }
                                                                                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [tmp/release/main.o] Error 1
make: Leaving directory `/Users/Opium/Downloads/synergy/src/gui'
Going back to: /Users/Opium/Downloads/synergy
Error: make -w failed with error: 512`

**Comment by yupi2** [comment]
@andreyslyusar 
You could try to putting `CONFIG += c++11` somewhere near the [top here in this file](https://github.com/symless/synergy/blob/fc67cdf56ea9d627598b8a343e2624396b9f8a12/src/gui/gui.pro#L4)

**Comment by norru** [comment]
Windows build fails with QT errors. All dependencies insstalled following instructions. Building on Windows 10 Enterprise 64bit.

```
In file included from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/crtdefs.h:10:0,
                 from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/wchar.h:9,
                 from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/c++/cwchar:44,
                 from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/c++/bits/postypes.h:40,
                 from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/c++/iosfwd:40,
                 from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/c++/ios:38,
                 from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/c++/ostream:38,
                 from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/c++/iostream:39,
                 from src\MainWindow.cpp:21:
C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/_mingw.h:229:0: note: this is the location of the previous definition
 #define _WIN32_WINNT 0x502
 ^
src\MainWindow.cpp:352:66: warning: unused parameter 'reason' [-Wunused-parameter]
 void MainWindow::trayActivated(QSystemTrayIcon::ActivationReason reason)
                                                                  ^
src\MainWindow.cpp:1063:34: warning: unused parameter 'isExpiring' [-Wunused-parameter]
 void MainWindow::beginTrial(bool isExpiring)
                                  ^
src\MainWindow.cpp: In member function 'void MainWindow::installBonjour()':
src\MainWindow.cpp:1350:25: error: 'storageLocation' is not a member of 'QDesktopServices'
  QString tempLocation = QDesktopServices::storageLocation(
                         ^
src\MainWindow.cpp:1351:9: error: 'TempLocation' is not a member of 'QDesktopServices'
         QDesktopServices::TempLocation);
         ^
Makefile.Release:5407: recipe for target 'tmp/release/MainWindow.oIn file included from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/crtdefs.h:10:0,
                 from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/wchar.h:9,
                 from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/c++/cwchar:44,
                 from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/c++/bits/postypes.h:40,
                 from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/c++/iosfwd:40,
                 from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/c++/ios:38,
                 from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/c++/ostream:38,
                 from C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/c++/iostream:39,
                 from src\MainWindow.cpp:21:
C:/Qt/Qt5.6.0/Tools/mingw492_32/i686-w64-mingw32/include/_mingw.h:229:0: note: this is the location of the previous definition
 #define _WIN32_WINNT 0x502
 ^
src\MainWindow.cpp:352:66: warning: unused parameter 'reason' [-Wunused-parameter]
 void MainWindow::trayActivated(QSystemTrayIcon::ActivationReason reason)
                                                                  ^
src\MainWindow.cpp:1063:34: warning: unused parameter 'isExpiring' [-Wunused-parameter]
 void MainWindow::beginTrial(bool isExpiring)
                                  ^
src\MainWindow.cpp: In member function 'void MainWindow::installBonjour()':
src\MainWindow.cpp:1350:25: error: 'storageLocation' is not a member of 'QDesktopServices'
  QString tempLocation = QDesktopServices::storageLocation(
                         ^
src\MainWindow.cpp:1351:9: error: 'TempLocation' is not a member of 'QDesktopServices'
         QDesktopServices::TempLocation);
         ^
```

**Comment by norru** [comment]
Tried with a few other versions of QT. Nada. The Windows Build guide is very unreliable, if not plainly misleading. Has anyone actually managed? As if there were someone somewhere trying to actively trip users over in order to sell their *paid* windows binaries.

Oh, wait...

**Comment by yupi2** [comment]
@norru No clue. Could be Qt 5.6.0. Could be MinGW. Could be version 1.8.6 of Synergy being kind of old.
You could try the v2.0.0 branch. It removes Bonjour and the auto-config stuff though if you used that.
I can build v2.0.0 successfully with Visual Studio 2015 Community edition and Qt 5.7.1 through the `VS2015 x64 Native Tools Command Prompt`. It builds binaries into their own build directories which is annoying though. There may be a download for just he VS2015 build tools so you don't have to install the entire IDE if you plan to try that.

Anyway, Qt 5.7.x works and Qt 5.8 should too so I'd recommend using those. Lots of downloads should be here https://download.qt.io/archive/qt/

My %Path% includes cmake, git, and `C:\Qt\Qt5.7.1\5.7\msvc2015_64\bin` for Qt if it helps you in your journey through compiling.

You may also be interested in [this fork I have](https://github.com/yupi2/synergy) which has a few changes along with changing to plain cmake for building. You should read the README.md and COMPILE.md if plan to check it out though.

**Comment by norru** [comment]
Hi @yupi2,

Many thanks for that!

I did indeed found, favourited and forked your fork (yo dawg!) and, guess what, it does produce a usable set of executables, by following your instructions as precisely as I could. I had to specify the path to Qt's CMake config files via an env var.

I've built against QT 5.6, which was installed using the QT official distribution tool. I have a multi-version installation for QT, with 5.6, 5.7, 58 and no MinGW. Installing MinGW actually caused the build to attempt to run against mingw's dll, which in turn crashes Synergy at boot.

I see installation/packaging feature is missing. Some post-build steps are required such as copying some QT DLLs across and installing the result as a windows service, but I resolved by stomping an existing old install obtained from an older free version with the new execs.

I haven't tried encryption yet.

Good stuff!

Cheers
Nico

**Comment by norru** [comment]
Perhaps it's time to fork Synergy into FreeSynergy ;)

**Comment by yupi2** [comment]
@norru As long as the Qt bin directory (depends on Qt version and whether building with mingw or VS) is in the system environment variable `Path` it should be able to load the DLLs. As for an installer, it's easier to just pull the latest changes from the repo and build. For the service it's pretty much the same. In the COMPILING.md there's a command that should work to create an auto-start service when ran from an admin command prompt. A more official fork isn't really necessary though since Synergy isn't a dead project and still has work done on it occasionally.

**Comment by norru** [comment]
Cool, I'll try to add the DLL path at next update, thanks.

**Comment by XinyuHou** [comment]
@yupi2 
Thank you so much for helping people out.

Please use our dev mailing list to discuss compiling problems in the future. Thanks.

synergy-dev@googlegroups.com
