### ISSUE TITLE
3 laptop/tablets with Ultrawide screen configuration help needed.

### ISSUE THREAD

**Issue by ETPH1969** [symless/synergy#5800]
### Operating Systems ###
Server: Windows 10
Client: Windows 10

### Synergy Version ###
1.8.6-Stable-2ab21aa

### Steps to reproduce bug ###

Dell U3417W ultrawide monitor (3440x1440)  connected to Surface Pro 3 (2160x1440) as server.
Surface Pro2 (1920x1080) as client
HP Omen (1920x1080).

Screen layout

+-----------------+  +---------------------------------+
|                           |    |                                                  |
| Omen                |    |             Dell U3417W                |
|                           |    |                                                  |
+-----------------+  +---------------------------------+
                                 +--------------+     +------------+
                                 |                       |       |                   |
                                 |        Pro3        |       |       Pro2    |
                                 |                       |       |                   |
                                 +--------------+     +-------------+

I would like to set this up in a way I can move easily between several screens in an intuitive way.
Can anyone help me to get the proper configuration?

Currently I have set it up as follows in the config file:

section: aliases
	Omen:
		Omen-LU
	Pro3:
		Pro3-CD
	Pro2:
		Pro2-RD
end

section: links
	Omen:
		right = Pro3
		left(0,100) = Pro3-CD
	Pro3:
		down(65,100) = Pro2
		right(51,100) = Pro2
		left = Omen
	Pro2:
		left = Pro3(50,100)
		up = Pro3-CD(50,100)

**Comment by XinyuHou** [comment]
@ETPH1969 
This is the support request. Please use our forum to get help from the community. Thank you.
https://symless.com/forum/
