### ISSUE TITLE
Failed to find the Windows kit installation directory - v1.9.0 branch

### ISSUE THREAD

**Issue by iDentity1337** [symless/synergy#5801]
Windows 10 Pro (x64 - Build 14393)
Microsoft Visual Studio 2015 (latest)
Qt 5.7
CMake 3.7.2
Python 2.7.12

Trying to build branch v1.9.0 since I've read that master ain't building on Visual Studio 2015
Error:

_C:\Users\unm4sk\Documents\synergy\synergy>hm conf -g1
Mapping command: conf -> configure
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Entering dir: build
CMake command: cmake -G "Visual Studio 14" -DDISABLE_TESTS=0 ..
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/unm4sk/Documents/synergy/synergy/build
Going back to: C:\Users\unm4sk\Documents\synergy\synergy
Warning: Not using supported Qt version 5.6.1 (your version is 5.7.1).
QMake command: qmake gui.pro -r QMAKE_VERSION_STAGE=beta QMAKE_VERSION_REVISION=a19ce2d
Entering dir: src/gui
Failed to find the Windows Kit installation directory.
WARNING: Unable to generate output for: C:/Users/unm4sk/Documents/synergy/synergy/src/gui/Makefile.Release [TEMPLATE app]
Failed to find the Windows Kit installation directory.
WARNING: Unable to generate output for: C:/Users/unm4sk/Documents/synergy/synergy/src/gui/Makefile.Debug [TEMPLATE app]
Going back to: C:\Users\unm4sk\Documents\synergy\synergy_

Can someone help me?

**Comment by yupi2** [comment]
Try using a `VS2015 x64 Native Tools Command Prompt`.
Also since you're on x64 Windows you can use [`-g2`](https://github.com/symless/synergy/blob/v1.9.0/ext/toolchain/commands1.py#L261)

**Comment by nlyan** [comment]
try cmake -G "Visual Studio 14 2015 Win64" as well

**Comment by iDentity1337** [comment]
I can't remember what fixed it, probably VS2015 CMD, but it's solved, forgot to close it. Thanks both ;)
