### ISSUE TITLE
OS X 10.7.5 Client Crash on Open

### ISSUE THREAD

**Issue by kimetime** [symless/synergy#5808]
OS X 10.7.5

Server: Windows 10
Client: OS X 10.7.5

Synergy 1.8.7

Synergy on client machine OS X 10.7.5 crashes on open. Here is the error report...

Process:         launchd [903]
Path:            /Applications/Synergy.app/Contents/MacOS/Synergy
Identifier:      synergy
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [145]

Date/Time:       2017-01-19 09:31:20.925 -0800
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          96326 sec
Crashes Since Last Report:           8
Per-App Interval Since Last Report:  190437 sec
Per-App Crashes Since Last Report:   2
Anonymous UUID:                      F55969F5-C9D3-4D84-BFAA-38D6B942C24F

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 1

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1031
    thread_create: 1
    thread_set_state: 0

Model: MacBookPro2,1, BootROM MBP21.00A5.B08, 2 processors, Intel Core 2 Duo, 2.33 GHz, 3 GB, SMC 1.14f5
Graphics: ATI Radeon X1600, ATY,RadeonX1600, PCIe, 256 MB
Memory Module: BANK 0/DIMM0, 2 GB, DDR2 SDRAM, 667 MHz, 0x7F7F7F94FFFFFFFF, 0x393731353539410000000000000000000000
Memory Module: BANK 1/DIMM1, 1 GB, DDR2 SDRAM, 667 MHz, 0x7F7F7F0B00000000, 0x4E5431475436345538484230424E2D334320
AirPort: spairport_wireless_card_type_airport_extreme, Atheros 5416: 2.1.14.9
Bluetooth: Version 4.0.8f17, 2 service, 11 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: INTEL SSDSA2M080G2GC, 80.03 GB
Parallel ATA Device: MATSHITADVD-R   UJ-85J
USB Device: Built-in iSight, apple_vendor_id, 0x8501, 0xfd400000 / 2
USB Device: Apple Internal Keyboard / Trackpad, apple_vendor_id, 0x021a, 0x1d200000 / 2
USB Device: USB Receiver, 0x046d  (Logitech Inc.), 0xc52b, 0x3d100000 / 2
USB Device: IR Receiver, apple_vendor_id, 0x8240, 0x5d200000 / 2
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x8205, 0x7d100000 / 2

**Comment by nlyan** [comment]
macOS 10.7 is no longer supported (by us or Apple). Current builds target 10.8 and above.

**Comment by kimetime** [comment]
Thanks. In the meantime, when was the last version of Synergy that supported 10.7 and where can I download that build?

**Comment by XinyuHou** [comment]
@kimetime 
Sorry to say we don't support 10.7 in the latest version. Please have a look at our alternative page. 1.7.5 supports 10.7.
http://symless.com/download/?alt
