### ISSUE TITLE
Hotkeys not working - Sierra 10.12.2 / El Capitan 10.11.6

### ISSUE THREAD

**Issue by Jamiermusic** [symless/synergy#5812]
Same issue as when I last used Synergy, about two years ago.

Running latest stable release of Synergy on both machines. El capitan is a rMBP and Sierra is a hackintosh.

Works "perfect" when a Win is served as host, mac as host on the other hand does not work properly. Synergy functions well with no lag nor mouse / keyboard input delay, but the hotkeys still ain't working :/ (if I circle the mouse on client side the mouse doesn't circle, but gradually go up to the left :P)

Any hacks I can use to make it work?

Thanks in advance.

**Comment by nlyan** [comment]
Closed. Duplicate of #3705
