### ISSUE TITLE
Missing curl library while installing on Kali Linux

### ISSUE THREAD

**Issue by cprabhjotsingh** [symless/synergy#5813]
OS: kali linux
while compiling synergy on kali linux it gives error. I am pasting the error below:- 

Mapping command: conf -> configure
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Entering dir: build/release
CMake command: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ../..
-- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:165 (message):
  Missing library: curl

-- Configuring incomplete, errors occurred!
See also "/root/Desktop/synergy-master/build/release/CMakeFiles/CMakeOutput.log".
Going back to: /root/Desktop/synergy-master
Error: CMake encountered error: 256

----------------------------------------------------------------------------------------------------------------------------------

please check it and give the solution asap

**Comment by nlyan** [comment]
Try installing the libcurl4-openssl-dev package

**Comment by cprabhjotsingh** [comment]
Thanks its working now 🙂
