### ISSUE TITLE
What happened here?

### ISSUE THREAD

**Issue by martindale** [symless/synergy#5819]
Synergy was once freely available and easily installed on short notice; now there's a fee associated with it?  Glad that the source code is being distributed, but where are the binaries?

**Comment by nicobcn** [comment]
+1 What's going on? :-O

**Comment by yupi2** [comment]
https://symless.com/nightly/

You'll have to figure out the correct download for you depending on the branch and commit.

**Comment by nlyan** [comment]
Symless are charging a modest fee for binaries now although the product remains, and will remain, Free Software. GitHub really isn't the place to discuss this.

**Comment by martindale** [comment]
Interesting.  Where _is_ the best place to discuss this?

**Comment by nikolowry** [comment]
Could this be re-opened until the following is explained:
<img width="1280" alt="synergy-screenshot" src="https://cloud.githubusercontent.com/assets/597310/24718538/5a1cc86e-1a04-11e7-9f5a-f4c887f367bd.png">
Really wasn't in the mood to compile from source on Mac
