### ISSUE TITLE
Clipboard between Win server and Mac client doesn't work

### ISSUE THREAD

**Issue by wsierakowski** [symless/synergy#5822]
### Operating Systems ###

Server: Windows 7 (6.1) SP1
Client: OSX 10.12.3

### Synergy Version ###

1.8.7-stable-9799e96 on both machines

### Steps to reproduce bug ###

Windows is the server, Mac is the client

1. Copy text to clipboard on Windows (I can confirm that the text is in the clipboard as I can paste it in Win).
2. Move mouse to Mac and try to paste using either Command + V or right click and paste.
3. Clipboard is empty, nothing is being pasted, the paste menu item is greyed out suggesting there is nothing to paste.

### Other info ###

* This is the case since updating to OSX Sierra
* Did not find any workaround
* Clipboard works in the other direction - between the Mac client and the Windows server, if I copy something to clipboard on Mac, I'm able to paste it on Windows.

**Comment by nlyan** [comment]
This is likely a conflict between Synergy and macOS Sierras 'Universal Clipboard'. Try disabling Handoff temporarily to see if it resolves your issue.

Mac: Go to System Preferences > General > uncheck Allow Handoff

**Comment by XinyuHou** [comment]
Close because of not enough information.
