### ISSUE TITLE
Keyboard/Mouse click issue with vmware horizon client and virtualbox

### ISSUE THREAD

**Issue by macbean101** [symless/synergy#5824]
Server:  Windows 10
Client1: Windows 7
Client2: Windows 7

All running Synergy 1.8.7-9799e96

Normal usage is fine.

Running Vmware horizon client  or Virtualbox (guest OS doesn't matter).  When either are the active window on the server, mouse clicks and the keyboard do not work on the clients.  The pointer moves over, if I hover over items on the task bar they come up, but clicking does nothing.  With the pointer on the client, typing on the keyboard still sends keystrokes to the server/horizon client or vbox.  

I believe this has been the behaviour since I started using synergy.

**Comment by XinyuHou** [comment]
@macbean101 
Does the order of starting Synergy and Virtualbox guest matter in the case?

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
