### ISSUE TITLE
Can't Leave Screen Fedora 25 and Windows 7

### ISSUE THREAD

**Issue by TheFuzz4** [symless/synergy#5825]
### Operating Systems ###

Server: Fedora 25
Client: Windows 7

### Synergy Version ###

1.8.7-stable-9799e96

### Steps to reproduce bug ###

1. Start synergy server on Fedora machine
2. Start client on windows machine
     (Fedora on left, Win on right)
3. Try and move mouse to the windows machine
4. Fedora machine throws: 
[2017-01-30T11:26:15] INFO: leaving screen
[2017-01-30T11:26:16] WARNING: can't leave screen
[2017-01-30T11:26:16] DEBUG: locked by mouse buttonID: 0

### Other info ###

I upgraded to Fedora 25 last week
No way to work around other than to RDP into my windows box for now
Yes this does prevent me from using synergy entirely. 

I've submitted the logs here in this window on full debug2 that are showing what happpens when it tries to leave.

I've attempted to try it with SSL enabled and disabled in case that made a difference.

On my fedora box Synergy seems to think that I have 2 IPs well I guess I do since one of them is a VirtualBox IP but I don't think that would cause an issue other than the fact that the VBIP is bold and my actual IP is not. 

Thank you for your help with this and please let me know what else I can provide to get this resolved.  I also just upgraded both synergies to this version today as well since this wasn't working with the previous build I had.

**Comment by nlyan** [comment]
Are you using a Wayland session in Fedora 25?

"loginctl show-session $XDG_SESSION_ID -p Type" at a terminal will show this. Wayland support is currently planned for v1.9

**Comment by TheFuzz4** [comment]
I do believe that I am since they switched that to the default.

**Comment by TheFuzz4** [comment]
My apologies as I now see this is a duplicate issue.  I'll close this issue since there is a the known one.
