### ISSUE TITLE
Help with Multi-Mon Manual Config

### ISSUE THREAD

**Issue by austinwilly** [symless/synergy#5829]
**Operating Systems**

Server: Windows 10 (64-bit)
Client: Windows 7 (32-bit)

**Synergy Version**

1.8.7

**Question/Issue:**

I'm trying to setup synergy with the following monitor configuration, and it doesn't seem possible to do this with the GUI configuration. I also have no idea where to even get started with the manual config doc. If it was just the top 3 monitors i could figure it out but the bottom right monitor on the main system is giving me issues.

    # Physical monitor arrangement, with machine names as used by Synergy.
    #  +-----------+-----------+-----------+
    #  | Main (TL) | Main (TC) | Main (TR) |
    #  |   24in    |   24in    |   24in    |
    #  +-----------+-----------+-----------+
    #  |   Work    |   Work    | Main (BR) |
    #  | 24in (BL) | 27in (BR) |   24in    |
    #  +-----------+-----------+-----------+
    #
    # T = TOP
    # B = Bottom
    # Monitors are arranged in a six pack
    #
    #

**Comment by auralarch** [comment]
If you have not already figured this out on your own, I hope this helps...

I remember having a similar problem trying to figure out the same thing when I first started using Synergy 5-6 years ago.

Basically, Synergy isn't aware of (or have anything to do with) your individual displays or their configuration(s) and layout that are connected to each machine.  As far as Synergy is concerned each computer has/is one "screen".
Think of all the displays connected to each computer as a block- like one single (virtual) display (which VERY confusingly is called a "screen" in Synergy).
This should work well for your configuration.  You just need to setup one screen for each computer in the GUI configuration on your server- one on top of the other, and you will be able to move the cursor between them anywhere along that edge where they meet.
The position of the mouse will be scaled if the number of pixels where they meet is not equal.

**Comment by XinyuHou** [comment]
@austinwilly 
Please use our forum to get support from our community. Thanks.

https://symless.com/forum/
