### ISSUE TITLE
Screen size misdetected on multi-monitor display with XRandR (1.8.4+)

### ISSUE THREAD

**Issue by mwilck** [symless/synergy#5831]
### Problem ###

My synergy client has 3 monitors: two 1920x1080 monitors standing vertically, and my horizontal 1920x1080 laptop screen on the right. This gives a total horizontal screen width of 1080+1080+1920 = 4080 (height is 1920).

```
mwilck@apollon:~> xrandr
Screen 0: minimum 320 x 200, current 4080 x 1920, maximum 8192 x 8192
eDP-1 connected 1920x1080+2160+840 (normal left inverted right x axis y axis) 309mm x 174mm
   1920x1080     60.02*+  47.99  
DP-1-1 connected 1080x1920+1080+0 left (normal left inverted right x axis y axis) 527mm x 297mm
   1920x1080     60.00*+
DP-1-3 connected primary 1080x1920+0+0 left (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1080     60.00* 
```

**After update of synergy client to 1.8.7, I can't move the mouse pointer beyond horizontal position 1200**.  This can be verified by the log messages of the client. The client messages on my setup with 1.8.2 (good):
```
Synergy 1.8.2: [2017-02-05T21:04:29] DEBUG: screen shape: 0,0 4080x1920 (xinerama)
```
and with 1.8.7 (bad):
```
Synergy 1.8.7: [2017-02-05T20:55:55] DEBUG: screen shape: 0,0 1200x1920 (xinerama)
```

The number 1200 is particularly strange because this size doesn't appear anywhere in my configuration. I'm also not using Xinerama (at least not conciously) but that doesn't seem to matter here.

### Preliminary analysis ###

This was apparently cased by the changes made for issue #4420, pull request #4148. These changes enabled XRandR support, but apparently this support is broken. synergy uses calls to XRRSizes() and XRRRotations() to determine the screen size. I am not sure if this is still state of the art. The Linux xrandr client, for example, uses XRRGetScreenResources(). It seems to me that XRRSizes() returns the size of one monitor rather than the whole screen. 

The xrandr library on OpenSUSE Tumbleweed is libXrandr-1.5.1-1.1. It's possible (although not very likely IMO) that XRRSizes() is broken in this library version.

### Operating Systems ###

Server: Fedora 24
Client: openSUSE Tumbleweed (20170203)

### Synergy Version ###

client: 1.8.7 (bad), 1.8.2 (good)
server: 1.7.6

### Steps to reproduce bug ###

1. Start client

### Other info ###

* When did the problem start to occur? After update from 1.8.2 to 1.8.7 on openSUSE tumbleweed.
* Is there a way to work around it? No, AFAICS, except by forcibly disabling XRandR support in synergy during compilation.
* Does this bug prevent you from using Synergy entirely? No, I've downgraded to 1.8.2 for now.

See also [openSUSE bug#1023635](https://bugzilla.novell.com/show_bug.cgi?id=1023635).

**Comment by nlyan** [comment]
Excellent work @mwilck 

I'll look in to this in detail for v1.8.9

**Comment by mwilck** [comment]
It turns out that the screen size calculation for XRandR-enabled displays as implemented in synergy was wrong (note that code had been disabled until synergy 1.8.4). It's sufficient to simply use the display properties.

Created pull request #5832. That pull request fixes the problem reported here. I haven't tried to check if issue #4420 is now solved or not.

**Comment by mwilck** [comment]
Just verified that issue #4420 is also fixed with this code. At least I can start synergyc in a 2-monitor configuration and add monitor #3, and I'm able to move the mouse pointer to the just-added monitor outside the previous screen size range.
