### ISSUE TITLE
Multiple Monitor Layout Support

### ISSUE THREAD

**Issue by bgiwi** [symless/synergy#5837]
Request the ability to layout the monitors when using varying amounts of monitors per host. 

![image](https://cloud.githubusercontent.com/assets/24484507/22762400/581d9142-ee1c-11e6-81d3-5fe3a69651c1.png)

**Comment by nlyan** [comment]
The above layout is possible currently, but it involves editing the config file manually. The new GUI we are developing for v2.0 makes the above layout trivial.
