### ISSUE TITLE
Unit test ClipboardChunkTests fails on big endian architectures.

### ISSUE THREAD

**Issue by epakai** [symless/synergy#5838]
### Operating Systems ###

Server: Debian 8.7 (amd64)
Client: Debian 9.0/unstable  (sparc64)
I also tested with the server and client roles reversed.

### Synergy Version ###

1.8.7-stable

### Steps to reproduce bug ###

1. Build synergy on a Big endian architecture machine
2. Run unittests
3. ClipboardChunkTests.data_formatDataChunk fails
    ClipboardChunkTests.end_formatDataChunk fails

### Other info ###

* Is there a way to work around it? Yes, I can ignore these tests during build
* Does this bug prevent you from using Synergy entirely? I don't think so. Clipboard was functional in both directions with the sparc64 machine as server or client.

There are additional *full* build logs at https://buildd.debian.org/status/package.php?p=synergy&suite=experimental but I tried to include the relevant information below.
Affected architectures are mips, s390x, hppa, powerpc, and sparc64. My tests were run on sparc64 because it is what I had available.

**** Build log ****

> [----------] 3 tests from ClipboardChunkTests
> [ RUN      ] ClipboardChunkTests.start_formatStartChunk
> [       OK ] ClipboardChunkTests.start_formatStartChunk (0 ms)
> [ RUN      ] ClipboardChunkTests.data_formatDataChunk
> /«BUILDDIR»/synergy-1.8.7-stable+dfsg.1/src/test/unittests/synergy/ClipboardChunkTests.cpp:48: Failure
>       Expected: sequence
>       Which is: 1
> To be equal to: (UInt32)chunk->m_chunk[1]
>       Which is: 0
> [  FAILED  ] ClipboardChunkTests.data_formatDataChunk (0 ms)
> [ RUN      ] ClipboardChunkTests.end_formatDataChunk
> /«BUILDDIR»/synergy-1.8.7-stable+dfsg.1/src/test/unittests/synergy/ClipboardChunkTests.cpp:71: Failure
>       Expected: sequence
>       Which is: 1
> To be equal to: (UInt32)chunk->m_chunk[1]
>       Which is: 0
> [  FAILED  ] ClipboardChunkTests.end_formatDataChunk (0 ms)
> [----------] 3 tests from ClipboardChunkTests (1 ms total)

I tried debugging the issue. Here is how the m_chunk looks on each architecture:

little endian
> chunk->m_chunk = "\000\001\000\000\000\002mock data"

big endian
> chunk->m_chunk = "\000\000\000\000\001\002mock data"

The test expects '\001' in m_chunk[1], but this is not the case on big endian architectures. I'm not sure what is a correct or desirable solution.

**Comment by yupi2** [comment]
Ignoring the tests should be fine. I don't think there's any deeper problems with endianness, just the tests assuming a little-endian host.

**Comment by epakai** [comment]
If the only issue is the test then I came up with this solution. I didn't look into the actual code being tested much since it seemed functional. Casting wasn't effective because it resulted in a SIGBUS. Instead II made a copy of the memory as a UInt32 to compare against.

https://github.com/epakai/synergy/commit/02b8fb7e7f41fc9a6dc54bfc245925e8da0ace09

**Comment by yupi2** [comment]
If your changes fix the test then you should create a pull-request and hopefully someone will have it merged in a timely fashion. I expect you'll need to provide it as a patch for now in the package.

As a note the protocol code does read/write integers in network-byte-order (big-endian) so it does work correctly. The ClipboardChunk class doesn't use `m_chunk` very well so it starts to implement the protocol's format for clipboard-chunks but doesn't use it so it copies the data out and then the protocol utilities sends it with correct byte-ordering. It's not the best quality of code.

**Comment by nlyan** [comment]
The unit test is indeed bogus. It works by chance even on little endian archs (because the sequence number used is 0, chunk[1] is also always 0).

The original intent would have been *(UInt32*)(&m_chunk[1]) which would have also been unsafe because of alignment issues on some platforms (which is I guess is what you discovered when you tried to correct the code before resorting a memcpy)
