### ISSUE TITLE
Use a standard icon on Linux

### ISSUE THREAD

**Issue by AsciiWolf** [symless/synergy#5844]
Synergy uses a non-standard _ico_ format icon on Linux. Because of that, the Synergy package cannot be installed using GNOME Software (or another AppStream-based package manager interface) because the needed metadata [are not](https://appstream.debian.org/sid/main/issues/synergy.html) successfully generated. Please, provide a standard (_png_ or _svg_) icon for use with the Linux version of Synergy.

**Comment by nlyan** [comment]
What version is Appstream looking at here? sid packages are currently at 1.4.x, but "experimental" is at v1.8.7

The ico file was replaced in v1.8.8-rc1 btw.

**Comment by AsciiWolf** [comment]
@nlyan Replaced? I see that the _ico_ format icon is still used in [synergy.desktop](https://github.com/symless/synergy/blob/master/res/synergy.desktop) file.

**Comment by nlyan** [comment]
@AsciiWolf v1.8.8-rc1 is in the 1.8.8 branch. synergy.ico itself was replaced

**Comment by AsciiWolf** [comment]
@nlyan I don't see any differences regarding the desktop/icon files in the 1.8.8 branch.

**Comment by AsciiWolf** [comment]
@nlyan Any news regarding this issue?

**Comment by nlyan** [comment]
@AsciiWolf the v1.9 branch now uses a SVG icon. See PR #6048 for the current status on this issue

**Comment by AsciiWolf** [comment]
Thanks!

**Comment by nlyan** [comment]
Reopening because it seems SVG doesn't work so well on CentOS or Fedora. Need to investigate

**Comment by ccl2of4** [comment]
When you say "doesn't work so well", what exactly do you mean?

**Comment by ccl2of4** [comment]
Putting the icon in `/usr/share/icons/hicolor/scalable/apps` works on my DE; it seems Gnome wants there to be an icon in at least `/usr/share/icons/hicolor/48x48/apps/`

https://developer.gnome.org/integration-guide/stable/icons.html.en

**Comment by ccl2of4** [comment]
@nlyan I have narrowed the issue down to needing to run some variation of `gtk-update-icon-cache -f /usr/share/icons/hicolor` after installing synergy.

Running these exact commands in a centos7 gnome vm resulted in a successful installation with the icon showing up correctly:

```
mkdir build
cd build
cmake3 .. -DCMAKE_INSTALL_PREFIX=/usr
make -j8
sudo make install
sudo gtk-update-icon-cache /usr/share/icons/hicolor
```

Needing to refresh the icon path after installing a new icon is perfectly normal. On Arch Linux this is done automatically by the package manager. I do not know how it works on CentOS or if you need to add something to your RPM spec file to make sure it happens
