### ISSUE TITLE
Hotkeys / Service / Autostart

### ISSUE THREAD

**Issue by homezonebenny** [symless/synergy#5847]
### Operating Systems ###
Server: Windows 10
Client: Windows 10

### Synergy Version ###
1.8.7-stable

### Missing things in Synergy ###
There are 3 things I totally would love to get in Synergy any time soon:

1. ONE hotkey to switch back and forth from Server to Client.
2. Hotkey forwarding. From Server to Client.
3. Auto "Start" Button press on program start

### 1. Hotkeys ###
I tried many different ways to get a single hotkey work like this:
Press:  _CTRL + 1_   (I want   CTRL + WIN + TAB  to switch between devices, not working too!)

**When I press:** _CTRL + 1_
on PC1 (Server) it jumps to PC2 (Client).

**When I press:** _CTRL + 1_
on PC2 (Client) it jumps to PC1 (Server).

I only can set a hotkey once to jump from PC1 to PC2.
But it's not possible to use the same hotkey to jump back from PC2 to PC1.
Any solution for that, or is this another "Feature Request" ?!

**I tested this (for example):**
http://i.imgur.com/yolPp1I.png

Or adding the hotkey in the left "Hotkey" area 2 or 3 times.
Nothing worked so far.
**WIN key** is not supported in any way 👎 

**It seems that Synergy makes no difference between:**
- Left / Right CTRL, ALT, SHIFT
- Normal Numbers or NUM Numbers (at least you can't see it on the set hotkey like a (num) in front).
this is kinda bad. Because sometimes you want a hotkey with a Numblock, sometimes with the normal numbers!

### 2. Hotkey - Forwarding ###
It seems that there is no "Hotkey - Forwarding" feature in Synergy yet.
Or mabye I doing it wrong. Or it's bugged.

**I tried this:**
http://i.imgur.com/GAkIxlK.png

**What it should do:**
- When I press: CTRL + ALT + (num) 0
on the Server PC. It should press this hotkey on the "Client" PC aswell.
Like a Hotkey-Forwarding.
So you can control a Program without switch to the Client PC from your Server by pressing a hotkey!
So theoretically you could make a hotkey forwarding from Server to Client to Play/Pause the Media Player.

### 3. Synergy Autostart + Service ###
I always run all my services (who's not used every day) on manual.
So that the program starts the service when I run the program.
But synergy seems not to start the "service" when I press the "Start" button.

**There should be a:**
[ X ] Automatically start on programm start
checkbox. Near to the "START" button in the main Gui.
So when I start the program (via shortcut in Windows Autostart folder), it automatically start the server / client.

For my use.

**Server:**
- Synergy Service (Server PC) is on manual
- Synergy Program does NOT start with windows

**Client:**
- Synergy Services is on automatic
- Synergy Program starts with Windows (shortcut in autostart folder)

I use the Server PC every day. But the Client PC not.
When I start my Server PC, and I decide to start the Client PC aswell.
I start Synergy on the Server PC manually.
Therefore Synergy SHOULD start the "Service" when I start the program.
Because the Service is on "manual" in Windows 10.
Same as the "Start" button (down right side in the Gui).
It should be pressed automatically when I start the program!

**That's why a checkbox:**
**[ X ]** Automatically start on programm start
is needed !!! :-)

**EDIT:**
Nevermind. The "Automatically start on programm start" is not neede.
This already works. When you press the START button so that the server is running.
And you close the program, without STOP server. It will still be "started" when you start the programm again. Even after PC rebot. So this is already working!
But not the "start service" part. When the program starts it have to detect if the service is running or not.

**Comment by sweetrush** [comment]
1. Problem one solution : Try mapping different hotkeys for your different screen, Remember your server will interpret any of the keys been pressed on any screen to its hot key list so if you are on any of the screen and you had pressed any of your hotkeys mapped to a particular screen it will move the curse to that screen and so forth.

**Comment by sweetrush** [comment]
2.Problem two Solution : try manually start your synergy service from the Administrator Tools in your control panel under services. Sometime the GUI has a problem trying to start the service as windows have some security feature that restrict application starting services if the application was not started in System or high level privileges

**Comment by sweetrush** [comment]
3. Problem Two Thought: 

Yeah i dont think this feature is ready yet for synergy but help me to push for it. let me know.

Its someting i have also alway wanted to the ability to send a keystroke and have it execute a command on another computer. 

Something like this:

keystroke(Win+1) = RunProgram(notepad,Screen:Com2)

like something like that

**Comment by homezonebenny** [comment]
@sweetrush 

**1. Hotkey:**
ONE hotkey to jump back and forth between 2 PCs.
Not TWO different hotkeys. That's it.
You can do this, when you save the configuration to a file.
Edit this file with editor. And load it then.
Then you can press ONE hotkey to jump back and forth.
For example:
CTRL ALT 1 (or just something like F9 key)
and you jump from server to client, and when you press again from client to server...
The problem is, NORMAL users never will be skilled to edit stuff like that.
They use the Gui and that's it! So the things I report, is not just for me.
It's to make Synergy better. So basically the Gui (Hotkey editing)
should allow that. One hotkey to jump from one machine back to the other.

**2. Hotkey forwarding**
This is another point for the "hotkey editing module" in Synergy.
This is pretty important. When you define a hotkey like (simple):
F9 Key
to be forwarded (end simulated) to a client PC. Any program on client PC will receive this pressed key.
So for example you could set "media keys" as a hotkey->forwarding.
So you could control your music player on the second PC.
Or in my case, control the scenes of the streaming program.
In the streaming program you can define hotkey to SWITCH scenes.
From webcam overlay, to the game + game overlay scene.
If you set the same hotkey in Synergy (forwarding) like you did in the stream programm.
You are able to switch scenes "remotely". While you play a game on PC1 (server) you could switch the stream scenes on PC2 (client).
What you meant, pressing a hotkey to open a program or something, is not what synergy really do.
BUT if you have a programm running, which opens other programs with a hotkey, it would work.
So you press your hotkey on PC1 (server) and it will be forwarded (and pressed) on PC2 (client) so this program will run notepad for you on the client.
For example:
Autohotkey
is a program which can do things like that, and many more.
Synergy is basically a network communication software.
Sending data to move mouse cursor / keyboard input.
So hotkey-forwarding would be something logical, something NATURAL for synergy.
Since each pressed keyboard key is "forwarded" to the clients aswell ;-)
So it wouldn't be a big deal to implement a "hotkey forwarding".

**3. Synergy Autostart + Service**
Again, this is for NORMAL users.
People who have no skills to use console and stuff like that. People who like to use the GUI instead of the console aswell. So basically a checkbox somewhere:
[ X ] Press START on program start
This means, when you open Synergy program, it automatically start the server / the client.
Sure, when you run synergy the FIRST time this is not set (checkbox).
So you can adjust all your stuff and then mark this checkbox.
Even when it would be set, it wouldn't hurt you.
Because you still can change stuff on a running server and press "apply" when done.

To the service... I set Synergy Service to Manual.
And I never start the Synergy program. And I look into the service list...
And Synergy is "started". WTF?!
So even set synergy to "manual" is not working.
So probably in my case. I have to set synergy service to:
Deactivated
Using a .bat file which starts the service, and then starts the program...
This is a point which could (should in my eyes) be fixed.
When the service is on "manual" it should not start with windows boot O.o...?
When starting the prgram (gui) it should check if the service is running.
If not, start the service. This method prevents bugs (issues) aswell.
Think about the service crashed or whatever reason stoped this service (other program or something).
A simple "close gui" and "open gui again" would fix this because service get started.

Maybe I'm a little bit "mimimi" about services.
But for me, 200 little services running in the background for no reason are to much.
IF you don't use synergy every day. Only like 2-4 times a month.
But you use your PC every day ~8h the running service is just waste.
I love synergy, no worry ;-)
But the service don't need to eat with me on the same table every day.
I'll invite him for dinner. But not every day ;-)

Oh, and please maybe try to write your posts in one message.
Makes it better for the overview ;) Thought first you are 3 people ;-)

**Comment by XinyuHou** [comment]
@homezonebenny 
Thank you for taking time to write those feature requests.

I can understand your first request, semi understand the second and don't understand the last one.

Please split them up into different issues, so we can talk about each one individually.

**Comment by homezonebenny** [comment]
@XinyuHou 
Hi and thanks for your response. I made some tickets for you, to seperate to make it better overview.


**Hotkeys:**
https://github.com/symless/synergy/issues/5868


**Hotkey - Forwarding:**
https://github.com/symless/synergy/issues/5869


**Fullscreen Game / Shooter:**
https://github.com/symless/synergy/issues/5871


**German Keyboard Layout issue: ^ Symbol:**
https://github.com/symless/synergy/issues/5870


Sadly, Github flaged me (guess for spaming posts or something).
I already wrote a Email to github to please "unflag" me. Maybe you can unflag me aswell?!
Hope my full list makes it much easier to understand for you. I just trying to help and improve Synergy as much as I can.
I always do that with new software I'm using. I test it a lot. Find bugs, find issues, doing bug reports / feature requests. I'm a programmer aswell. And it's kinda a hobby to test software.


For the point 3 (Service).
I did not create a thread (post) for that yet. Not sure if I will.
Because that's only ME. I'm a bit picky. Perfectionist you know. Nothing any other user would mind of.
**Let me explain it easy for you.**
When you install Synergy, you install the Synergy Window Service.
This service starts "automatically" with windows on start.
I always remove those things. Like I set Synergy to "manual". So Synergy Windows Service will NOT start on windows boot. Because I don't use Synergy every day. Maybe only once a week or 2 weeks.
So WHY should the service run all night long. I know the service don't harm anything. BUT 200 services running in the background for no reason = MEH.
That's why I adjust this. Just me, being picky ;-)

So, 90% of programs are fine with that behaviour.
Windows Service is on: Manual
When I start the program, the program realise, HEY service is NOT running and starts the service.
That's a normal behaviour. But Synergy don't do that.
When I start the GUI the service (which is on manual) is still NOT started.
That was the point I tried to report.
Synergy GUI should start the service, IF not running.
1st it helps to solve ISSUES when the service is crashed for some reason (stoped).
So when you close and reopen the GUI it starts the service and everything works again ;-)
2nd, it would work MY way ^_^ I can set the Synergy Service to: Manual
When I start the GUI it starts the Service aswell.

**At the moment, I just use a .bat file:**
- Starts the Service
- Runs the program

**And another .bat file to stop:**
- the program
- stop the service

Like I said, I think I shouldn't make a seperate ticket for that.
Because it's just "me". BUT it would solve issues, if the service is not running for some reason (crashed)!

**Comment by XinyuHou** [comment]
@homezonebenny 
Thank you so much for taking time to split the issues. I will reply to to them separately.

Regarding to service, I don't think that is what it's designed for from an OS point of view. A service is suppose to run at the backgroup all the time and it's ran under a higher privilage.  On contrast, an app is running under the user space. Depending on the user group or type, you can request to boost the app previlege. But in my option, let an app to start a service sounds dangerous.

I'm trying to think of any other solution for your service work around. To get Synergy work properly, you need the service because UAC detection. But if you don't care about UAC, you can simply start synergy process with a  script along with a permanent configure file.

I will mark this issue as closed. So we can do the further discussion in your separate issues.
