### ISSUE TITLE
Windows 7 client unresponsive to keyboard when trying to unlock

### ISSUE THREAD

**Issue by kulakowskin** [symless/synergy#5848]
### Operating Systems ###

Server: Ubuntu 16.04
Client: Windows 7 Enterprise

### Synergy Version ###

1.8.7

### Steps to reproduce bug ###

1. Both computers are locked.
2. Do the keyboard shortcut (Super+L) to unlock Ubuntu server
3. Do Windows unlock shortcut (Ctrl+Alt+Dlt)
4. Bug - Windows client does not respond to keyboard
5. Required to use 2nd keyboard connected directly to Windows desktop to unlock.

### Other info ###

* Is there a way to work around it? Yes, I can reach behind the monitors to use the secondary keyboard. I also tried switching the client and server between the OSen, but that caused a larger issue where Synergy stopped running when I locked computers and didn't restart on unlock. 
* Does this bug prevent you from using Synergy entirely? No

 [Debug log](https://gist.github.com/kulakowskin/d71550e91daebaf21c91b73ffffd7522)

**Comment by SamRimmer** [comment]
This should be fixable by going into **Edit > **Settings**** and changing the **Elevate** option to **Always**.
Apply the setting change and try again, it should work as expected.
