### ISSUE TITLE
Shift key is registered on client, but does not allow capital letters/special characters 

### ISSUE THREAD

**Issue by Justin-C** [symless/synergy#5855]
### Operating Systems ###

Server: windows 10
Client: ubuntu 14.04

### Synergy Version ###

1.4.18

### Steps to reproduce bug ###

1. Shift+a on client prints "a" not "A"
2. if you hold down a, then tap shift, some upper case A's do appear, so the shift key seems to be sent to client. ex: (hold a)aaaaaaaaaaaaa(push shift)AAAAAAAAAA(release shift)aaaaaaaaaaaaaaaaaaaaa
### Other info ###
I've looked at the other bugs similar to this, and I didn't see any solutions for windows 10 server.

**Comment by BrendanPotts** [comment]
Ya I'm having the same issue with, 
Server: Win 10
Client Ubuntu 16.04
Synergy 1.4.18

**Comment by unknwnz1** [comment]
I'm also having the same problem.

Server: Windows 10
Client: Linux Mint 17.1
Synergy: 1.4.18

Apparently from what I've read is certain security updates within windows is causing the problem. I tested a nightly build v1.8.7 and the shift key works fine. So it seems like a problem specifically with older versions of synergy, such as the free version that's available.

**Comment by XinyuHou** [comment]
@Justin-C @unknwnz1 @BrendanPotts 
Please update to our latest release.

**Comment by mengesb** [comment]
I'm running on 1.8.8-c30301e and I'm still unable to type a capital c on either client or ubuntu 16 server.

**Comment by XinyuHou** [comment]
@Justin-C @unknwnz1 @BrendanPotts
Please update to 1.8.8 and set debug level to Debug2.

Reproduce the shift key problem on your client side then send us the log please.

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
