### ISSUE TITLE
Errors during compilation on Windows

### ISSUE THREAD

**Issue by DRSXS** [symless/synergy#5858]
### Operating Systems ###

Server: Windows 10

### Synergy Version ###

Revision 9799e96, v1.8.7-stable

### Other Info ###

Errors during compilation on Windows using the hm script in the console.
Log of Errors:

> src\MainWindow.cpp:54:0: warning: "_WIN32_WINNT" redefined
 #define _WIN32_WINNT 0x0501
 ^
In file included from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/crtdefs.h:10:0,
                 from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/wchar.h:9,
                 from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/c++/cwchar:44,
                 from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/c++/bits/postypes.h:40,
                 from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/c++/iosfwd:40,
                 from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/c++/ios:38,
                 from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/c++/ostream:38,
                 from C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/c++/iostream:39,
                 from src\MainWindow.cpp:21:
C:/Qt/Tools/mingw492_32/i686-w64-mingw32/include/_mingw.h:229:0: note: this is the location of the previous definition
 #define _WIN32_WINNT 0x502
 ^
src\MainWindow.cpp:352:66: warning: unused parameter 'reason' [-Wunused-parameter]
 void MainWindow::trayActivated(QSystemTrayIcon::ActivationReason reason)
                                                                  ^
src\MainWindow.cpp:1063:34: warning: unused parameter 'isExpiring' [-Wunused-parameter]
 void MainWindow::beginTrial(bool isExpiring)
                                  ^
src\MainWindow.cpp: In member function 'void MainWindow::installBonjour()':
src\MainWindow.cpp:1350:25: error: 'storageLocation' is not a member of 'QDesktopServices'
  QString tempLocation = QDesktopServices::storageLocation(
                         ^
src\MainWindow.cpp:1351:9: error: 'TempLocation' is not a member of 'QDesktopServices'
         QDesktopServices::TempLocation);
         ^
mingw32-make[1]: *** [tmp/release/MainWindow.o] Error 1
mingw32-make: *** [release] Error 2
Error: mingw32-make release failed with error: 2

**Comment by yupi2** [comment]
I've had this problem before but I can't remember what the fix was. What version of Qt do you have installed?

**Comment by yupi2** [comment]
It's also worth pointing you to #5767

**Comment by DRSXS** [comment]
I have Qt 5.6.2 installed on my C:\ drive

**Comment by yupi2** [comment]
You could try one of the other branches (like v1.9, v1.9-tweaks, or v2.0) and see if they compile.
Do `git checkout v1.9` in a command line while in the synergy directory
and retry building

**Comment by DRSXS** [comment]
Alright, I tried 1.9, but it seems that it doesn't contain the hm script. I'm a little familiar with cmake but I'm not at all familiar with packaging and the WiX Toolset. 
But I guess this isn't about the same issue anymore and this issue can be closed.
