### ISSUE TITLE
Mac server and client, scrolling doesn't work at all

### ISSUE THREAD

**Issue by kraetos** [symless/synergy#5859]
### Operating Systems ###

Server: iMac 17,1 running 10.11.6
Client: MacBook Pro 10,1 running 10.12.3

### Synergy Version ###

1.8.7

### Steps to reproduce bug ###

Scrolling doesn't work on client. Tried using a Magic Trackpad and a Logitech MX Master.

### Other info ###

* When did the problem start to occur? The problem has always occurred.
* Is there a way to work around it? No.
* Does this bug prevent you from using Synergy entirely? I can use Synergy but it's borderline useless if I can't scroll. macOS doesn't even really show scrollbars anymore.

Log snippet:

[2017-02-23T10:47:16] INFO: switch from "maci" to "LilBandit" at 1439,424
[2017-02-23T10:47:16] INFO: leaving screen
[2017-02-23T10:47:16] WARNING: cursor may not be visible
[2017-02-23T10:47:19] INFO: switch from "LilBandit" to "maci" at 35,818
[2017-02-23T10:47:19] INFO: entering screen

"maci" is the iMac and "LilBandit" is the MacBook Pro. In the three seconds between these messages, I tried scrolling on the client, but it doesn't even produce error messages.

**Comment by kraetos** [comment]
Bump.

**Comment by XinyuHou** [comment]
@kraetos 
Please set log level to Debug to see if you can see any error when you do scroll.

https://github.com/symless/synergy/wiki/Sending-logs

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
