### ISSUE TITLE
Error: IPC Connection Error Prevents any usage on client.

### ISSUE THREAD

**Issue by justinwzig** [symless/synergy#5862]
### Operating Systems ###

Server: Windows 10 v1607
Client: Windows 10 v1607

### Synergy Version ###

1.8.7-stable (both machines) 

### Steps to reproduce bug ###

Not reproducible, but here's what I did:
Installed Synergy, got my server configured at IP 100.100.100.110
Started client, auto connect started fine.
Stopped and then restarted client, as soon as I open synergy on the client computer, it prints `ERROR: ipc connection error, connection refused` 
A restart fixes the issue, but I can't restart the client every time I restart synergy.

### Other info ###

The workaround is to restart the client, which shouldn't be necessary. 
I have also tried not using auto config and using manual IP, but that doesn't fix it.

Synergy isn't saving log files, even though I have it set to log to a file on my desktop with Debug2 - possibly connected issue?

**Comment by XinyuHou** [comment]
@justinwzig 
This is caused by service is not running, maybe crashed.

You can restart service by:
1. Press Win + r
2. Type services.msc
3. Find Synergy
4. Restart it

Please us our forum to get support in the future. Thank you.
https://symless.com/forum/
