### ISSUE TITLE
Can't connect from Ubuntu 16.04 client to Windows 10 server

### ISSUE THREAD

**Issue by hetong007** [symless/synergy#5863]
### Operating Systems ###

Server: Windows 10 (1607)
Client: Ubuntu 16.04 

### Synergy Version ###

1.8.7 - stable

### Steps to reproduce bug ###

1. Start synergy on both machines
2. Set the IP
3. 'Apply'
4. Connection failed 

### Other info ###

More information:

Synergy works perfectly if I set Ubuntu as the server and Windows as client.

Please see [this gist link](https://gist.github.com/hetong007/a73fbb1ccba01318fb9fe0a6f8096bb3) for the detailed log (on client). Basically the main error log I can see is `can't read property 640 on window 0x01600163`.

Sometimes I need to restrict my keyboard-mouse only on the windows machine, thus it is ideal if i can set it to be the server.

**Comment by XinyuHou** [comment]
@hetong007 
This looks more like a support ticket. We use Github issue tracker to track new bugs or enhancement. 

Please use our forum to get support from the community, thanks.
https://symless.com/forum/

**Comment by hetong007** [comment]
I understand. Thanks!

**Comment by nbolton** [comment]
I'd say this is a bug, because of the error "can't read property 640 on window 0x01600163"

**Comment by nbolton** [comment]
Ah, actually that's a debug message, I don't think it's causing an issue.

**Comment by hetong007** [comment]
It IS an issue since I cannot operate the mouse on Ubuntu from Windows.

**Comment by nbolton** [comment]
Hey, I replied to your forum post: [Can't connect from Ubuntu 16.04 client to Windows 10 server](https://symless.com/forums/topic/2305-cant-connect-from-ubuntu-1604-client-to-windows-10-server/)

I'll reopen this issue if we figure out it's actually a bug related to the "can't read property" debug message (and not a connection problem as I suspect).
