### ISSUE TITLE
Synergy GUI segmentation fault on mac OS Sierra

### ISSUE THREAD

**Issue by aristizabal95** [symless/synergy#5884]
### Operating Systems ###

Server: mac OS Sierra 10.12.3
Client: Microsoft Windows 7 v6.1

### Synergy Version ###

1.8.7

### Steps to reproduce bug ###

1. Open Synergy app inside the mac OS
2. App closes before opening
3. Try to start Synergy executable through terminal
4. Receive error message `segmentation fault: 11`
5. Run synergy server and/or client executables through terminal
6. server and client working correctly on their own

### Other info ###

* This happened to me today, out of nowhere. The app was working flawlessly yesterday. Now, for any weird reason, I can't start the app normally.
* At first, I was able to start the GUI, but not the server or client, as I received an error saying it wasn't possible to start the server/client executable because of permissions.
* Tried changing permissions with `chmod`... did not work, tried reinstalling, now the GUI doesn't work at all.
*I can still use the app, at least server and client, but I have to start it now from the terminal and modify the config files if required.

**Comment by yupi2** [comment]
I think a serial key that was unintentionally trimmed by Synergy causes this. You can try finding your configuration files for Synergy and then make sure the key is full length. There may be a version with a fix but I haven't checked.

**Comment by aristizabal95** [comment]
@yupi2 Thanks for your answer. Any chance you know where to find this configuration files? I found the CodeSignature file but to be honest I have no idea if it has something to do with this.

**Comment by yupi2** [comment]
I don't know where they are on mac OS. Might be in `$HOME/.config/` with a folder name that has synergy or symless in it. Also maybe `$HOME/Library/Preferences/`

**Comment by aristizabal95** [comment]
@yupi2 I believe I found the problem, looking for this config files inside `$HOME/Library/Preferences` I found this plist files related to synergy:
`com.http-symless-com.Synergy.plist`
`com.http-synergy-project-org.Synergy.plist`
`synergy.plist`

The thing is, the file `com.http-symless-com.Synergy.plist` occupies 1.07GB of memory, and every time I try to open it and read it my Xcode completely freezes and my computer becomes laggy. Also, when I try to `cat com.http-symless-com.Synergy.plist` my terminal displays a bunch of FFFFFFF hex code and also crashes.

So yeah.... this file is completely corrupted, any way I can recover it?

**Comment by yupi2** [comment]
No idea what it is used for or why it's like that. I assume it's a crash dump for Synergy but I don't know what yo ucan do with it

**Comment by aristizabal95** [comment]
Fixed. After renaming this file so that synergy won't automatically open it, I executed synergy and it prompted me with the first time setup display. Followed the instructions and I now have the GUI working again. thanks @yupi2 for your time, you helped me a lot.

**Comment by MartinRJ** [comment]
This issue still persists for me.
Every couple of days the file grows to 1GB+ in size, and I have to manually delete it.
Why did you close this issue? Are you going to fix this?

**Comment by aristizabal95** [comment]
@MartinRJ I closed this issue because it consisted on finding a fix for this isolated error (which, as you mentioned, is deleting the config files manually). I created another issue addressing the fact that it happens so often and without any apparent reason. You should go there: #5901 and comment about your situation.

**Comment by MartinRJ** [comment]
#5901 is not related to the insane growth of the plist file. It's about a corrupted serial key file.

**Comment by aristizabal95** [comment]
@MartinRJ It is related, the insane growth of the plist file is because the serial key gets corrupted and stores a bunch of 0xFFFFF.... inside the plist file. I created that other issue to address the cause of this corruption, which is also the cause of this enormous plist file. 

In fact, you can check out the plist file using Xcode, and you'll see how the serial key gets filled with this 0xFFFF bytes.

For example, here is mine:

![screen shot 2017-04-29 at 3 11 17 pm](https://cloud.githubusercontent.com/assets/26156883/25558537/8727d810-2cee-11e7-84f7-c1c28e197a21.png)

You can also see this corruption happen inside the GUI, if you go to File > Activate, you'll see something like this:

![screen shot 2017-04-29 at 3 15 18 pm](https://cloud.githubusercontent.com/assets/26156883/25558556/ddf0f776-2cee-11e7-9f3e-676d173a5032.png)

**Comment by aristizabal95** [comment]
Actually, the fact that the file is already corrupted, but its not crashing the program yet is new information I can add to the other issue, so thanks @MartinRJ for making me check this haha.

**Comment by aristizabal95** [comment]
@MartinRJ Please read the last comment I added to the other issue, in which I establish the relation of both the corruption of the serial key, and the enormous files generated by this corruption.
