### ISSUE TITLE
Can't copy and paste both from server or client

### ISSUE THREAD

**Issue by JackieTseng** [symless/synergy#5889]
### Operating Systems ###

Server: Windows 7
Client: Ubuntu 16.04 LTS

I have just installed and used Synergy today. Connection and Hotkeys work well. However, I can't use copy-paste form these two computer. When I drag the file trying to get across the window, my mouse just get stuck. What's the problem?

### Synergy Version ###

1.8.8-stable-c30301e

**Comment by cjgibson** [comment]
The problem is that drag-and-drop copying of files between computers is not supported to and from Linux hosts. Further discussion can be found on issue https://github.com/symless/synergy/issues/5419.

**Comment by XinyuHou** [comment]
@JackieTseng 
Please send us some log with log level set to Debug.

**Comment by andrewr01** [comment]
Also had no copy and paste with 1.8.8-stable-c30301e. Server: Windows 10 1607, Client: Mac OS Sierra 10.12.3.

**Comment by XinyuHou** [comment]
Duplicate of #4170

**Comment by jtyh89** [comment]
hi i cant copy and paste for Mac and windows as well
