### ISSUE TITLE
OSX Sierra desktop spaces functionality and window snapping issues

### ISSUE THREAD

**Issue by cedkar** [symless/synergy#5890]
### Synergy Version 1.8.8 stable  ###

I often work in multiple desktop spaces on one computer. I am finding that there is a conflict with this functionality when using Synergy Servers setup in a horizontal configuration. I can no longer drag an app or finder window to the server side of the active desktop to change desktops as Synergy will place the mouse cursor on the second computer. Can Synergy pleased be disabled when dragging windows (3 finger drag) or mouse clicking and dragging (one finger click and drag). This is also an issue when snapping windows to resize on the server side border of the screen.

thanks

**Comment by XinyuHou** [comment]
@cedkar 
You can setup a hotkey to lock to the cursor to screen on Mac. Please give it a try.

This is much like a support ticket, not a development issue. Please use our forum to get support.

https://symless.com/forum/
