### ISSUE TITLE
Selecting Auto Config on mac still runs manual config

### ISSUE THREAD

**Issue by theronl** [symless/synergy#5894]
### Operating Systems ###

Server: Windows 10 (this machine is currently 30 miles away - I will update with more exact version)
Client: MacOS Sierra 10.12.3

### Synergy Version ###

1.8.8
1.8.7

### Steps to reproduce bug ###

1. Set up windows machine as the server with SSL and auto configuration enabled.
2. Start synergy
3. click "Client (use another computer's mouse and keyboard):
4. Turn off Auto Config
5. Clear out Server IP
6. Turn on Auto Config
7. Click "Apply" and/or "Start"

Auto config will fail with a dialog because Server IP is not defined.  It will also fail with failed lookups if the information in the Server IP field is incorrect

### Other info ###

* When did the problem start to occur? 1.8.7.  It also fails in 1.8.8
* Is there a way to work around it? Manual config
* Does this bug prevent you from using Synergy entirely? No

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy/wiki/Sending-logs

Below is an animated gif of a video capture showing that the auto config feature is disabling the Server IP but still running manual config.

![synergybrokenautoconfig](https://cloud.githubusercontent.com/assets/669550/23622778/38184d74-025d-11e7-9fad-307b67258e24.gif)

**Comment by XinyuHou** [comment]
@theronl 
This is highly likely caused by this issue. Please let me know if it's not the case.
#4794

**Comment by theronl** [comment]
@XinyuHou I saw #4794 but didn't read the last comment of that issue.  It seems like two separate bugs.  If auto config is selected and it grays out the Server IP input box it shouldn't be used in auto config.  I'm guessing it's using bonjour or some multicast NSD mechanism.  That shouldn't require a server IP or name at all.  Also the logs are showing that the value in the Server IP field is being looked up and the lookup is failing when auto config is checked.  This value should be ignored.  The only thing I can conclude is that the manual configuration steps are being run rather than the auto configuration running and failing because the network changed.  This implies a different issue than auto config not working for multiple networks.  I do take my laptop to coffee shops and to my office but I am only running synergy on one network and I only start it when I'm at home.
