### ISSUE TITLE
Synergy.exe on Windows listening on 0.0.0.0:38433 

### ISSUE THREAD

**Issue by CMCDragonkai** [symless/synergy#5896]
On Windows, there's a synergy.exe besides synergyc.exe and synergys.exe. This doesn't exist on the Linux version. 

Why is this required to listen on all addresses on port 38433? I made a firewall rule for synergys, but not for synergy.exe and connections with clients broke.

**Comment by yupi2** [comment]
synergy.exe is the Qt GUI. It can be used on Linux. It is not packaged with Nix though. The GUI connects to the synergys.exe's IPC port (24801). The OS will use a random port for the GUI port. That's probably what the 38433 is.

**Comment by CMCDragonkai** [comment]
If it is only local, why not make synergy.exe bind to 127.0.0.1 instead of 0.0.0.0, presently this causes windows to require a firewall rule to allow inbound requests to synergy.exe for 0.0.0.0.

**Comment by XinyuHou** [comment]
@CMCDragonkai 
Synergy is the GUI. It uses localhost IP to connect to the service on Windows. That 0.0.0.0 probably comes from autoconfig. Did you enable auto config?

**Comment by CMCDragonkai** [comment]
I don't remember any autoconfig option under server settings.

**Comment by XinyuHou** [comment]
@CMCDragonkai 
Sorry for the confusion.

Please check if a checkbox called "Auto config" is ticked under the client settings area.

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
