### ISSUE TITLE
Never ending trouble ... you'd quit further development

### ISSUE THREAD

**Issue by sensenel** [symless/synergy#5897]
To be honest, i doubt you'll ever be able to make it run like it was 1-2 years ago - never mind which version it was 

Right now, it's laggy as hell, and yes, i tryed many of your workarounds - with every Update it's getting worse.

I was very grateful some years ago were i was a IT-apprentice and i had to pay just 10 bucks in compare to ShareMouse which was about 50
everything works just fine at this time

Right now, this is a just tremendous steal of time - so many times i have to reboot, re-configurate after every download ... make it somehow work too often within just a week ... and what is this: 808 open issues right now?! c'mon! 
Not that much for a commercial software, i know, but commercial software support usualy will not handeld over gitHub!?

However ...

This is obviously a kind of side-project and you're realy swamped right now with this thing, right? 

so, cool work, thank you for the time as it just worked fine, but this makes no sense anymore

im out 

Best

**Comment by XinyuHou** [comment]
@sensenel 
Sorry for all the inconvenience. We have couple of mouse lag issues open and we are going to look into them soon. If you are interested please subscribe to any of them.
