### ISSUE TITLE
User interface corrupts the serial key file on Mac OS Sierra

### ISSUE THREAD

**Issue by aristizabal95** [symless/synergy#5901]
### Operating Systems ###

Server: Mac OS Sierra
Client: Windows 7 PS1

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. Open Synergy
2. Look at the file `com.http-symless-com.Synergy.plist > Serial Key`
3. a bunch of 0xF bytes have been added to the original serial key.
4. Repeat steps 1 to 3 until corruption breaks the app.

### Other info ###

Even though this time this happened to me when installing 1.8.8, I can confirm this problem occurring before in 1.8.7 with no user intervention.

Here is another issue I started before, that occurred after this exact problem on Synergy 1.8.7 and how to get the app running again.
#5884

**Comment by aristizabal95** [comment]
Also, when trying to reactivate the product through the GUI, the text input is completemy messed up.

**Comment by XinyuHou** [comment]
@aristizabal95 
This sounds like a settings file corruption. Please try this clean up script to remove all Synergy related settings. Then restart the GUI. Note you would need to reactive again.
[clear-synergy-settings-mac.sh.txt](https://github.com/symless/synergy/files/844893/clear-synergy-settings-mac.sh.txt)

**Comment by aristizabal95** [comment]
@XinyuHou Thanks, that script will be helpful. 
The thing is, this is the sixth time I've had to remove synergy settings because out of nowhere the same error pops up, being caused by the same reason, the serial key completely broken. I thought it might have been caused because I shutdown my computer with the terminal command and maybe synergy was being forced to quit. But today happened to me just by closing the app with the "Quit" option from the mac bar. This has become annoying already and I have no idea how to fix it completely.

**Comment by aristizabal95** [comment]
@XinyuHou I have some new information:

**First:** the plist file seems to get corrupted in runtime, this corruption seems to add a bunch of 0xFFFF... to the serial key, but won't cause any trouble until the program is opened again. For the first time corruption, the file is only 68kb of size aprox.

**Corrupted plist file:**
![screen shot 2017-04-29 at 3 11 17 pm](https://cloud.githubusercontent.com/assets/26156883/25558652/b172533c-2cf0-11e7-99b1-c6b73771d7f0.png)

**Effects of corruption on the GUI:**
![screen shot 2017-04-29 at 3 15 18 pm](https://cloud.githubusercontent.com/assets/26156883/25558654/bb6554b6-2cf0-11e7-98b3-8690a4698d7b.png)


**Second:** Once you try to open the app again, Synergy tries to read the contents of the serial key but fails, I guess because tries to load a string bigger than the buffer it expects, hence the Segmentation Fault referenced here #5884. At this moment, the app can't be used at all.

**Third:** After unsuccessfully reading the file, synergy apparently writes the excess bytes from the serial key again, duplicating the size of the serial key slot and exponentially increasing the size of the plist file. At this point the file grows to about 120kb aprox.

If you repeat the process of opening and closing the app, you'll soon find yourself dealing with a plist file with Gigabytes of size.

I still cannot find the exact reason of why the serial key gets corrupted on the first place, but hope this info is useful for debugging this.

**PD:** Another weird thing is that the 0xFFFF added to the serial key appears to start right in the middle of the serial key, splitting the serial key in half. This behavior can be seen inside the images attached, where the first half of the serial key is "shown" in the plist file, and the other half in the GUI.

**Comment by aristizabal95** [comment]
@XinyuHou More information:

Tried starting with a backup of a working `com.http-symless-com.Synergy.plist` file, of only 2kb of size. Here is an image of the serial key on the file (obviously censored):

![screen shot 2017-04-29 at 5 24 18 pm](https://cloud.githubusercontent.com/assets/26156883/25559496/d33309fc-2d00-11e7-8874-ca2136bc20be.png)

The fact that everything is censored implies that the serial key is in perfect shape.




Now, when I open synergy for the first time, everything runs as expected. BUT! the serial key is modified already!

**Serial key after first run of the program:**

![screen shot 2017-04-29 at 5 27 07 pm](https://cloud.githubusercontent.com/assets/26156883/25559509/31e22672-2d01-11e7-9782-aa2a1dc7b7eb.png)




Pretty weird!! I can say it is consistently adding this FFFFF's to the serial key in the same spot. The structure of the corrupted serial key looks like this.

**Serial Key:** `[54 Hex Digits][6 Hex Digits of 0xF][2 Hex Digits][6 Hex Digits of 0xF][the rest of the serial key]`

Now, the second time I opened synergy, it looked like this.

![screen shot 2017-04-29 at 5 35 02 pm](https://cloud.githubusercontent.com/assets/26156883/25559541/4744120e-2d02-11e7-913b-e357c2dfffb5.png)


**Serial Key:** `[54 Hex Digits][30 Hex Digits of 0xF][2 Hex Digits][30 Hex Digits of 0xF][the rest of the serial key]`


**All of this happens at runtime.** Now, I don't understand why the app could even run in the first place, considering this file gets corrupted since the first run. Also, my guess about the `Segmentation Fault` is wrong then, since this would imply the app would crash since the first run. 

At last, I hope all this information makes it possible to reproduce this bug and localize its cause.

**Comment by aristizabal95** [comment]
Just updated the steps to reproduce the bug inside the issue

**Comment by nlyan** [comment]
Fixed by 165bfa3dd6ce9a9b695f522fbd6b94b4608fe876 . Will be released in v1.9.0

**Comment by nlyan** [comment]
We think we've nailed this in v1.9, please see

https://symless.com/forums/topic/2587-synergy-v190-release-candidate/

**Comment by paul-suarez** [comment]
Aytan72 from [forums ](https://symless.com/forums/topic/2638-macos-crash-after-sleep/#comment-8025)had the same warning.

[2017-05-15T15:54:59] WARNING: unknown quartz event type: 0x1d

Server: macOS Sierra, Version 10.12.4, iMac
Client: macOS Sierra, Version 10.12.4, MacBook Pro
