### ISSUE TITLE
Unable to use SSL Plugin when unregistered

### ISSUE THREAD

**Issue by legonigel** [symless/synergy#5906]
### Operating Systems ###

Server: All
Client: All

### Synergy Version ###

1.8.4 and later

### Other info ###

Starting in commit d6b7d8e357bf3e091e89f1a9c830c6dd906a6293 users who compile synergy themselves can no longer enable the SSL plugin through the GUI if compiled manually. 

[See the change here](https://github.com/symless/synergy/commit/d6b7d8e357bf3e091e89f1a9c830c6dd906a6293#diff-2651bcaf9cf12cd6d55f4606ef2462dfR283)

**Comment by XinyuHou** [comment]
@legonigel 
Limit SSL to Pro users is a marketing decision. So we should not count it as bug. The only solution for this is activate the GUI with a pro account. Thanks.

**Comment by legonigel** [comment]
@XinyuHou are you suggesting that @nbolton wants to alienate the open source community. I was lead to believe that @nbolton wanted to keep the open source community involved and that no features would be cut for the open source software. When SSL was first introduced developers were allowed to manually add the SSL plugin. This is a major step in the wrong direction. 

How can I help develop software which I cannot run?

**Comment by XinyuHou** [comment]
Regardless of the marketing decisions, the source code will stay in open source.
