### ISSUE TITLE
Mouse not locked into game window on Synergy Clients

### ISSUE THREAD

**Issue by kitsushadow** [symless/synergy#5910]
### Operating Systems ###

Server: Windows 10
Client: macOS Sierra 10.12.3 (16D32)

### Synergy Version ###

1.8.8 Stable

### Steps to reproduce bug ###

Setup a Windows Synergy Server and mac Synergy Client
Install Minecraft on the mac Client
Run Minecraft on the mac Client

### Other info ###

* When did the problem start to occur? When I started programming a minecraft mod and launched a test client from the IDE
* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? Yes

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy/wiki/Sending-logs

Put anything else you can think of here.
This seems to be an issue with any client which is trying to play a game that captures the mouse. This is why i moved the Synergy server to the windows machine where i play all my games. The problem is I do all my development and work on a Mac and I need to test changes I'm making.

**Comment by kitsushadow** [comment]
No response to this issue?

**Comment by yupi2** [comment]
Try enabling `Use relative mouse moves` in `Advanced server settings` then restarting the server (hitting Apply or Stop-then-Start)

**Comment by kitsushadow** [comment]
That setting is already enabled. No difference

**Comment by yupi2** [comment]
I forgot about mentioning to lock the cursor to the screen with a hotkey in Synergy. I have Pause/break to toggle `Lock cursor to screen`

**Comment by kitsushadow** [comment]
Tried that also and it didn't work, the mouse is not staying in the
Minecraft window. Fullscreening or maximizing the window is also not an
option since i need to see the console output

**Comment by yupi2** [comment]
Ah yep, according to a [comment](https://github.com/symless/synergy/blob/0eff5a95bea3c0d21c6adfa468f7696853c10692/src/lib/platform/OSXScreen.mm#L661) in the relevant file:
```
// OS X does not appear to have a fake relative mouse move function.
// simulate it by getting the current mouse position and adding to
// that.  this can yield the wrong answer but there's not much else
// we can do.
```

**Comment by XinyuHou** [comment]
@kitsushadow 

The default lock to screen key is scroll lock. In your setup, you could press that key while the cursor is on client, which would force it to stay within that client.

**Comment by kitsushadow** [comment]
I will give that a shot, thanks for the help

**Comment by kitsushadow** [comment]
This did not work, pressing scroll lock did lock the cursor to the session but seeing as the client has three screens and the server has two screens it wasn't successful

**Comment by kitsushadow** [comment]
@XinyuHou y is this closed before the issue was resolved especially seeing as the issue is not resolved.
