### ISSUE TITLE
Synergy Pro key activates Synergy Basic

### ISSUE THREAD

**Issue by justinmrkva** [symless/synergy#5911]
Server: Windows 10
Client: MacOS 10.12.3
Synergy 1.8.8

I purchased Synergy Pro specifically for SSL support. After activation, both the client and server show up as Synergy Basic.

I tried contacting you through an official help channel but your website's help section is down.

**Comment by devdoomari** [comment]
having the same issue here... but you can by pass this using ssh-forwarding.

There's 
https://superuser.com/questions/365750/an-equivalent-of-ssh-port-tunneling-for-windows-servers
but I can't vouch for this... can't try - no windows machine :( 

ps: I've actually bought it a long time ago with SSL support, but synergy downgraded me into 'basic' account without SSL.

**Comment by nlyan** [comment]
@justinmrkva Just tested this and it works for me. Our website is being transitioned to a new codebase, so there's some disruption there. There's no reason for serial activation to be disrupted

**Comment by cowens** [comment]
Same thing is happening to me.  My key is normally 34 characters long.  The key on the website is 86 characters long. The keys are the same for the first 16 characters then they differ until the last two characters.

**Comment by DanSorahan** [comment]
Hey guys,

We've recently had a huge overall of the website and there was an issue with key generation (my bad!). A fix has been deployed and the keys listed on your account page will now be working for your correct version of Synergy.

**Comment by cowens** [comment]
It still shows the 86 character key for me.

**Comment by cowens** [comment]
My key has now grown to 96 characters, but does identify as pro now.

**Comment by devdoomari** [comment]
@justinmrkva @nlyan @cowens @DanSorahan
you should re-check serial-keys on your account page - I've got mine sorted out.
(it's now recognized as 'pro')

also, using SSH-forwarding isn't the 'best' way even in security perspectives,
but it's a quick-(but-difficult-and-easy-to-screw) by-pass : )

**Comment by XinyuHou** [comment]
Closes as it's solved
