### ISSUE TITLE
build fails on mac os 10.12 with qt5 5.8.0_1

### ISSUE THREAD

**Issue by pkTux** [symless/synergy#5913]
### Operating Systems ###
Server: N/a
Client: Apple Windy OS 10,12

### Synergy Version ###
latest pull from git
### Steps to reproduce bug ###
 1) followed install guide here : 
https://github.com/symless/synergy/wiki/Compiling#Mac_OS_X-2

Had to perform extra steps of sync git repo, cp modified 'commands1.py' into repo folder.
able to run : ./hm.sh conf -g2 --mac-sdk 10.11 --mac-identity test

Ran ./hm.sh build 
Fineshed with : Error: [Errno 2] No such file or directory: '/usr/local/Cellar/qt5/5.8.0_1/Frameworks/QtCore.framework/Contents/Info.plist'

Verified, for some reason. Qtcore.framework is missing a 'contents folder or ln/sn

Can reach out to QT & see if thats on purpose, but if so, should I install older version of QT to be compatible with current  synergy?

**Comment by timclu** [comment]
Check this PR. It works fine with me.
https://github.com/symless/synergy/pull/5826/files

But here is another problem that the UI doesn't work. I have to use the CLI to start the  application.
https://github.com/symless/synergy/wiki/Command-line

**Comment by XinyuHou** [comment]
@pkTux 
Sorry for the confusion. As timclu pointed out, the 5826 pr would solve this problem.

We are in the middle of moving our old build process to a new setup.  We will make sure we update the wiki after it's done. Thanks
