### ISSUE TITLE
Language selection ceases to work on client

### ISSUE THREAD

**Issue by QuAzI** [symless/synergy#5916]
### Operating Systems

Client: Linux Mint 17.3

Server: Windows 7 Pro SP1 AMD64 EN

### Synergy Version

1.8.8-rc1-fc3cc78 on both sides

### Bug

On all hosts Ctrl+Shift configured to change language.
Sometimes language selection ceases to work on client. I press Ctrl+Shift to select EN, tray icon was changed but changes backward to RU on any alphabet char pressed. Even if I try to change language by clicking in tray language will changed to wrong on key press.

### Workaround

Restart Synergy on client

Log from client before it restarted: [synergy-client.log.txt](https://github.com/symless/synergy/files/853398/synergy-client.log.txt)

**Comment by XinyuHou** [comment]
Duplication of #5798
