### ISSUE TITLE
Right click menu intermittently disappears on MacOS Client

### ISSUE THREAD

**Issue by Dippyskoodlez** [symless/synergy#5920]
### Operating Systems ###

Server: Windows 10 Pro 14393.953
Client: MacOS 10.12.3

Note: Client is a Macbook Pro with Intel and Nvidia GPU. 

### Synergy Version ###

1.8.8-stable-25a8cb2

### Steps to reproduce bug ###

1. Open 'openEMU' game library
2. right click game in library
3. Right click menu should appear and disappear occasionally. 

This appears to happen once or twice every few right clicks.

Video: https://youtu.be/AQQSZvBNQ-8

### Other info ###

* When did the problem start to occur? Not sure if previous versions exhibited this issue. This is the latest version I have used OpenEMU with. OpenEMU 2.0.5 used.
* Is there a way to work around it? Use a local mouse.
* Does this bug prevent you from using Synergy entirely? No

**Comment by XinyuHou** [comment]
@Dippyskoodlez 
Looks like the client does 2 right clicks even when you just did once. Is this right?

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
