### ISSUE TITLE
How can I compile version 1.9 or 2.0?

### ISSUE THREAD

**Issue by 727yubin** [symless/synergy#5922]
I want to compile synergy on Windows 10 Pro 64bit. I have all the requirements, so I want to compile 1.9 or 2.0 (since 1.8 needs older versions from what I have read in the issues). However, there is no hm.py in either the 1.9 or the 2.0 branch. Is there any other way to compile it?

**Comment by yupi2** [comment]
They build with CMake. Qt5 is what you need too. I haven't tested but something like this might work:
```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug -G"Visual Studio 14 2015 Win64" ../
cmake --build ./ --config Debug
```
Feel free to check out my [fork](https://github.com/yupi2/synergy) too

**Comment by 727yubin** [comment]
C:\Users\jorda\Desktop\synergy-1.9\build>cmake -DCMAKE_BUILD_TYPE=Debug -G"Visual Studio 14 2015 Win64" ../
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:18 (project):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:18 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "C:/Users/jorda/Desktop/synergy-1.9/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/jorda/Desktop/synergy-1.9/build/CMakeFiles/CMakeError.log".

**Comment by 727yubin** [comment]
I do have Qt5.8 and VS2015 64 bit.

**Comment by 727yubin** [comment]
[CMakeError.txt](https://github.com/symless/synergy/files/870216/CMakeError.txt)
[CMakeOutput.txt](https://github.com/symless/synergy/files/870217/CMakeOutput.txt)

**Comment by yupi2** [comment]
I think you're missing the C\C++ compiler. I think there's an option that's disabled by default in the VS2015 installer for C\C++ tools but I'm not positive. You can try rerunning the VS2015 installer and see if you can install C\C++ tools from it. If not then you could try running the [Visual C++ 2015 Build Tools installer](http://landinghub.visualstudio.com/visual-cpp-build-tools)

**Comment by nlyan** [comment]
Compile instructions for v1.9 and v2.0 will be published after they are in beta.
