### ISSUE TITLE
Global Mouse Hook on Server prevents clicks registering on Client

### ISSUE THREAD

**Issue by Road-hog123** [symless/synergy#5931]
### Operating Systems ###

Server: Windows 10 Home Build 14393
Client: Windows 10 Home Build 14393

### Synergy Version ###

1.8.8-stable-c30301e

### Steps to reproduce bug ###

1. Observe that Synergy functions normally on the client.
2. Have a program that registers a global mouse hook start _after_ Synergy. In my case, 7+ Taskbar Tweaker starts at startup several seconds after Synergy does.
3. Observe that clicks on the client machine do not register (mouse movements and keystrokes do).
4. Restart the Synergy server (clicking "Apply" is easiest I find).
5. Observe that mouse clicks now register as they should.

### Other info ###

* When did the problem start to occur? When I decided I wanted to run Synergy and 7+TT together.
* Is there a way to work around it? Yes, as detailed above.
* Does this bug prevent you from using Synergy entirely? Before workaround: Yes. After: No.

I previously [reported this issue to the 7+TT bug tracker](http://tweaker.userecho.com/topics/635-cant-click-on-client-monitors-when-using-synergy/), but after some investigation it was found that 7+TT was not at fault. I detailed my findings from investigation in my final response to that report.

**Comment by XinyuHou** [comment]
@Road-hog123 
I doubt this is the bug in Synergy. The way OS works is it keeps a chain of hooks. The newer opened ones would be on the top. In general, an App should only copy the input data and pass the original to the next layer. From what you described, it sounds 7+TT didn't pass that event down to the chain.

A quick test would be set Debug level to Debug2 and see if server side detects any clicks when 7+TT is open after Synergy.

**Comment by figuerres** [comment]
There are several other threads that seem to all be related, look at a few of them:
[https://github.com/symless/synergy/issues/5976](url)  and [https://github.com/symless/synergy/issues/5964](url)
for a start.

something is happening that keeps mouse clicks from working on clients for some reason.
in my case i do not know of any event or program just a after a while i have to move the mouse back to the server , click and then back to the client and it works again, for a while and then all over again the same thing happens.
really getting to be a pain.

**Comment by XinyuHou** [comment]
Probably relate to #5976

**Comment by Road-hog123** [comment]
The problem described in #5976 is not the same issue.
#5976 is an issue with clicks _randomly_ stopping working, with the fix simply being to click on the server and move back to the client.
With this issue, it doesn't matter how many times I click on either machine, the client will not register clicks until Synergy re-registers it's global mouse hook. The problem also doesn't return until another global mouse hook is registered that prevents Synergy's from working.

**Comment by Road-hog123** [comment]
>an App should only copy the input data and pass the original to the next layer. From what you described, it sounds 7+TT didn't pass that event down to the chain.
>A quick test would be set Debug level to Debug2 and see if server side detects any clicks when 7+TT is open after Synergy.
Debug2 is indicating that the mouse click events aren't being detected by the server. This seems strange, because I am told by the developer of 7+TT that
>These options cause 7+ Taskbar Tweaker to setup a global mouse hook, but it doesn't handle mouse clicks, only the mouse wheel.
If only the mouse wheel is captured, any action relating to the mouse clicks (including them being blocked) seems unintentional. I shall contact the 7+TT developer to see if it is actually blocking mouse click events from being passed down the chain, even if that was not intended.

**Comment by RaMMicHaeL** [comment]
@XinyuHou

> From what you described, it sounds 7+TT didn't pass that event down to the chain.

Author of 7+ Taskbar Tweaker here. The tweaker passes events as required by a well-behaved program. It [was reported](http://tweaker.userecho.com/topics/635-cant-click-on-client-monitors-when-using-synergy/#comment-5434) that the issue happens with a [simple mouse hooking example](https://www.codeproject.com/articles/7294/processing-global-mouse-and-keyboard-hooks-in-c), which means that the issue is not specific to 7+ Taskbar Tweaker.

**Comment by XinyuHou** [comment]
@RaMMicHaeL 

Thank you for paying attention to this issue.

I have tried the simple mouse hooking example (version 1) on my Windows 10 machine. Starting that program after I get Synergy server connected, I can still use my mouse clicks on the client.

The version 2 looks like a library project, probably just for the hook. My C# knowledge is so rusty now.

Is 7+ Taskbar Tweaker an open source project?

**Comment by RaMMicHaeL** [comment]
@XinyuHou 

I haven't tried it myself, but @Road-hog123 said [here](http://tweaker.userecho.com/topics/635-cant-click-on-client-monitors-when-using-synergy/#comment-5434) that he was able to reproduce the issue with the example "demo application [Version 1]".

7+ Taskbar Tweaker is not open source, but the mouse hooking code is quite straightforward. Here are the main code parts:
https://gist.github.com/RaMMicHaeL/58c8ec0ebd76a00c937e0d22cd14bd7c

**Comment by erikliland** [comment]
I have experienced this problem over a long time, and I agree that it looks like it is an external program "stealing" the mouse hook. I tried to disable one program at a time to see which was causing the problem, and I belive it was "Fraps" on my server (Win10). I was not able to forcly reporoduce my problem, so this is only based on trying and testing over time. 

Anyone else having Fraps running on their machine?

**Comment by XinyuHou** [comment]
@Road-hog123 
Could you confirm you can reproduce the issue with demo version 1?

**Comment by Road-hog123** [comment]
When I tested it previously, yes. I've not tested it since with the Demo.

**Comment by XinyuHou** [comment]
@Road-hog123 
Thanks for the information. I'm sorry we can't reproduce this with the simple mouse hook example you mentioned. Maybe worth to check if there is any other software that might install a global mouse hook on your machine.

**Comment by Katulus** [comment]
Same issue here. In my case it almost always happens when I have [WebEx](https://www.webex.com/) meeting in progress on the server. That would point to thing with mouse hooks as I would expect WebEx client registering these for sharing purposes. Sometimes clicking different window helps, sometimes only restart of Synergy helps.
But to make things more complicated the issue happens randomly also without WebEx running. When it happens randomly it's not related to any specific application start (or at least I'm not aware of any). In that case clicking some window on server usually helps, but in some cases Synergy restart/click on apply is the only solution.

**Comment by XinyuHou** [comment]
> But to make things more complicated the issue happens randomly also without WebEx running. When it happens randomly it's not related to any specific application start

This is interesting. It seems a random bug in Synergy.

**Comment by XinyuHou** [comment]
Merge into #5976
