### ISSUE TITLE
Possible fallback server IP address? Feature!!

### ISSUE THREAD

**Issue by ludakuca** [symless/synergy#5938]
### Operating Systems ###

Server: Windows 10 Pro = > Version 1607 (build 14393.953)
Client: Windows 10 Pro = > Version 1607 (build 14393.953)

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. Server is on the local domain 192.168.xx.xxx, client is through VPN that does not allow tunnelling.
2. Hack to  have this working is to use port 80 for synergy on Server, and forward all the traffic to that.  Then from the client on VPN once logged in, point to the IP address of network (whatever the IP is), and use port 80 as the port.  This works fine while the client is connected to the VPN.  

However, once we stop the VPN connection, the client machine is pinging itself (same ip address) and then synergy is not working.  It would work if the client was trying to connect to server as 192.169... local network.

It would be nice to have ability to use share on both local network as well as through VPN.  This would save us from having to log in with different keyboard to the VPN (client) in order to use the sharing of the same mouse/keyboard afterwards.

**Comment by XinyuHou** [comment]
@ludakuca 
Thanks for the suggestions. We are actually working on version 2 which is supposed to solve this problem. Please subscribe to our mailing list to get updated.
