### ISSUE TITLE
Select Network Interface for Synergy to connect through

### ISSUE THREAD

**Issue by stinker1978** [symless/synergy#5941]
### Operating Systems ###

Server: macOS 10.12.3
Client: Windows 10 1607

### Synergy Version ###

1.8.8-stable-25a8cb2

### Steps to reproduce bug ###

Please add the ability to force Synergy to a specific network interface.  My Mac is my server and has both an Ethernet and WIFI interface and Synergy defaults to the WIFI connection when it's enabled.

**Comment by deckar01** [comment]
This feature might also make is easier for VPN users to bypass the tunnel adapter and connect directly to the local network. See https://github.com/symless/synergy/issues/5952.

**Comment by XinyuHou** [comment]
I believe you can do that to specify Interface in Edit->Settings on Windows or Preferences on Mac

**Comment by stinker1978** [comment]
No setting for interface from what I saw - will double check.

One workaround - if you tell a client to connect via the hard wired IP address, will that always route there?

Sent from my iPhone

On Mar 30, 2017, at 8:37 AM, Jerry (Xinyu Hou) <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe you can do that to specify Interface in Edit->Settings on Windows or Preferences on Mac

**Comment by cobrabr** [comment]
There is an *Interface* option in the Settings, but it doesn't seem to do anything. I tried putting my Ethernet interface id in there (os macOS Sierra), but nothing changed -- it connected to the server via Wi-Fi as well, even thought the interface name for it is different that what was configured there.

**Comment by willem-tee** [comment]
Any process on that? Im on linux and my server just "goes out" on all the interfaces: wlan, eth, vm and vpn ones. Would be great to be able to choose ie wlan or  eth and keep the vpn out.
