### ISSUE TITLE
bug, cannot read config file

### ISSUE THREAD

**Issue by yeeerdley** [symless/synergy#5945]
### Operating Systems ###

Server: Windows 10
Client: Windows 8,1

### Synergy Version ###

1.8.8-stable-c30301e - on both -

### Steps to reproduce bug ###

client works, i think.
keeps putting out :"connecting to (my computer)" and then timed out

server is the problem
keeps saying:" cannot read configuration file" it sats which file it is, except the directory doesnt exist, the user it shows the config file is at, does not exist on my computer. My guess is that this might be because of me formatting my harddrive a long time ago, but i cannot remember if i have had that username before.

### Other info ###

*I have had this bug since the beginning, and thats about a month ago now.
*Pretty sure there is a solution to my problem out, just can't find it.
*This bug prevents me from using Synergu entirely

link to logs:
https://pastebin.com/4N8cP9kx

**Comment by XinyuHou** [comment]
Please check your OS account management.

You can save a configuration to a file by go to File -> Save configuratrion file then specify the configuration file by ticking using existing configuration.
