### ISSUE TITLE
VMware compatibility issue

### ISSUE THREAD

**Issue by shurik1st** [symless/synergy#5946]
### Operating Systems ###

Server: Win10
Client: Win10

### Synergy Version ###

1.8.π

### Steps to reproduce bug ###

There is one idiosyncrasy I noted with vmware. Once I move cursor out of vmware directly into client I can see it move but imouse clicks will not be registered in the client. I have to first click on vmware host / synergy server desktop to get it working on client again.

**Comment by XinyuHou** [comment]
Duplicate of #5226
