### ISSUE TITLE
Permissions on Synergy.app in OS X

### ISSUE THREAD

**Issue by gghose** [symless/synergy#5950]
### Operating Systems ###

Server: OS X
Client: any

### Synergy Version ###

All.

It might be by design (it which case I think it should be better documented), but the permissions are 700 for Synergy.app and all of its contents. The problem is I have a LaunchDaemon that starts up for all users that runs /usr/local/bin/synergys which I have as a symlink to /Applications/Synergy.app/Contents/MacOS/synergys.

So I everytime I update the App, I screw everything up for all the other users (and it always takes me a while to remember the fix!).

**Comment by XinyuHou** [comment]
@gghose 
Sorry for the inconvenience. This is by design. Synergy doesn't support multiple users on the same Mac device. If you like, you could create another issue as feature request. Thanks.
