### ISSUE TITLE
encryption does not work via synergyc, but synergy GUI does work

### ISSUE THREAD

**Issue by Delvien** [symless/synergy#5953]
Windows 10 Synergy Server
Ubuntu 16.10 Synergy Client

Ubuntu using synergyc with --crypto-pass option connects and immediately disconnects spewing the following endlessly:

accepted client connection
crypto mode: ofb
new client disconnected

When running the synergy GUI in ubuntu using they encryption turned on and nothing changing on the server, no errors, and it works just fine.

Both host (win10) and client (ubuntu) are running synergy 1.6.2.

I believe the issue is with synergyc, as synergy (its gui mode) works fine. Either there is an argument missing and the manual page is wrong, or it's simply broken.

Obviously I would like to use synergyc for scripting purposes, as the GUI is terrible anyway, and forces me to click start, instead of doing it automatically.

**Comment by deckar01** [comment]
I use the `--enable-crypto` flag on my Linux client.

> ### Use Encryption
> If you use the synergy command line client, copy the file containing the fingerprint
> `~/.synergy/SSL/Fingerprints/Local.txt` from the server into the clients home directory 
> `~/.synergy/SSL/Fingerprints/TrustedServers.txt`. To start the synergy command line client
> with encryption, type:
> ```
> $ synergyc --enable-crypto
> ```
> > **Note:** There is an open issue with the GUI client of synergy (see https://github.com/symless/synergy/issues/4737). The dialog to prompt for confirmation of the server's fingerprint, only pops up if the logging level is set to INFO, DEBUG or DEBUG2.


https://wiki.archlinux.org/index.php/synergy#Use_Encryption_2

**Comment by nlyan** [comment]
--crypto-pass was deprecated long ago and does nothing in current versions. --enable-crypto is the way forward.
