### ISSUE TITLE
Issue with Keyboard Letters: a comes up as á

### ISSUE THREAD

**Issue by markgolledge** [symless/synergy#5960]
Hi,

I seem to be having intermittent issues with Synergy in that when I use the keyboard on the second connected screen some of the letters are not coming up correctly (mainly the vowels a: á, e: €, i:í, o:ó and u:ú. There are also a couple of other keyboard errors on the use of 4: €.

It doesn't happen everytime so I'm not sure why it happens at some times and not others. Also it only happens on the second screen and not the first one.

Is this a common issue and is there a way of fixing this please?

Thanks.

OS - Windows 10 - v1607 - 14393.953
Synergy Basic - 1.8.6-stable 2ab21aa

**Comment by XinyuHou** [comment]
Duplicate of #4280
