### ISSUE TITLE
build problem synergy 1.8.8 fedora 25

### ISSUE THREAD

**Issue by jave** [symless/synergy#5962]
### Operating Systems ###

fedora 25

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

[verjo@verjo synergy-v1.8.8-stable-c30301e-Source]$ ./hm.sh
Traceback (most recent call last):
  File "hm.py", line 22, in <module>
    from toolchain import commands1
  File "ext/toolchain/commands1.py", line 130
    print 'Mapping command: %s' % ' -> '.join(cmd_map)
                              ^
SyntaxError: invalid syntax

### Other info ###

* When did the problem start to occur? While building
* Is there a way to work around it? Not known
* Does this bug prevent you from using Synergy entirely? Yes

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy/wiki/Sending-logs

Put anything else you can think of here.

I want to be able to use fedora25 on one machine, and ubuntu 16 on another.

They come with different versions of synergy in their repos, and they dont seem to speak the same protocol.
Therefore I wanted to build from src. It didnt go well.

I have a synergy pro license, and i got the src from the symless account page.

**Comment by yupi2** [comment]
In hm.sh change the `python` to `python2` and try that

**Comment by jave** [comment]
aparently I had Anaconda in the shell, and that seems to cause the problem. Sorry for the noise!
