### ISSUE TITLE
Synergy.exe Runtime Error crash on start

### ISSUE THREAD

**Issue by xpac1985** [symless/synergy#5966]
### Operating Systems ###

Server: Windows 10.1607.14393.953
Client: doesn't matter

### Synergy Version ###

synergy-v1.8.8-stable-25a8cb2-Windows-x64.msi

### Steps to reproduce bug ###

1. Start Synergy in any way (auto-start after installation/autostart on Windows boot/from Start Menu/from .exe directly)
2. See crash window.
3. Swear

### Other info ###

I've been using Synergy as a Server on this PC for years now, and have also used 1.8.8 for weeks now without problems (besides the #5939 bug).
Yesterday, after the 58349th WebEx freeze bug, I tried to restart the server side of Synergy (on this computer). After the restart, I got this:

![synergy-crash](https://cloud.githubusercontent.com/assets/6882771/24556128/aa95a902-1633-11e7-9011-4b7fe61a0ddf.png)

I tried to stop the service manually, reboot, uninstall, reboot, install, reboot, redownload the setup, uninstall again, purge anything I found in AppData and Program Files, installed - it simply refuses to start in any way.
My Windows Update log shows no update since 7 days ago, so that should not be the reason.
I didn't install any new software, graphic card driver or anything else I can imagine could cause this.

Windows Event Log shows:

```
Name der fehlerhaften Anwendung: synergy.exe, Version: 0.0.0.0, Zeitstempel: 0x58ca9147
Name des fehlerhaften Moduls: QtCore4.dll, Version: 4.6.2.0, Zeitstempel: 0x4b72bd5f
Ausnahmecode: 0x40000015
Fehleroffset: 0x0016383d
ID des fehlerhaften Prozesses: 0x1b4c
Startzeit der fehlerhaften Anwendung: 0x01d2aa2e20574073
Pfad der fehlerhaften Anwendung: C:\Program Files\Synergy\synergy.exe
Pfad des fehlerhaften Moduls: C:\Program Files\Synergy\QtCore4.dll
Berichtskennung: 904dc46b-0e81-4055-a34f-a5cd1cc6d87f
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

(Yes, this is German :P)

The error XML in event log looks like this:

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-03-31T14:50:27.863277000Z" /> 
  <EventRecordID>6862</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>trono</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>synergy.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>58ca9147</Data> 
  <Data>QtCore4.dll</Data> 
  <Data>4.6.2.0</Data> 
  <Data>4b72bd5f</Data> 
  <Data>40000015</Data> 
  <Data>0016383d</Data> 
  <Data>1b4c</Data> 
  <Data>01d2aa2e20574073</Data> 
  <Data>C:\Program Files\Synergy\synergy.exe</Data> 
  <Data>C:\Program Files\Synergy\QtCore4.dll</Data> 
  <Data>904dc46b-0e81-4055-a34f-a5cd1cc6d87f</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

I'm out of ideas, why Synergy suddenly stopped working. No other program shows any similar problems.

**Comment by XinyuHou** [comment]
@xpac1985 
Looks like QtCore4.dll is corrupted. Could you try to uninstall and double check if the QtCore4.dll file is gone. Then reinstall. If the problem persists, please check the size of that file or checksum.

**Comment by xpac1985** [comment]
@XinyuHou I have absolutely no clue, why after 5th time of uninstalling, re-downloading and installing Synergy now works, but I'm willing to attribute it to your spirit fingers, or whatever Voodoo you did ;)
