### ISSUE TITLE
Awful lag through an Ethernet LAN Cable

### ISSUE THREAD

**Issue by Spiderkey** [symless/synergy#5967]
I have got a fresh install of Windows 8.1 with Synergy installed as the server, yet I'm getting pauses every 2-3 seconds as if it I was using wireless, that I could understand, but directly from a LAN Cable, I don't.

Heres all I know.

1. This PC is a multi-boot system so tested it out on Windows 7, no problems, so it can't be hardware related or bad BIOS Settings.

2. I constantly keep an eye out on Task Manager or both machiness, there is no other CPU hogging programs getting in the way.

It's getting it's only connection from a Home Network, thur an Externet Cable.

**Comment by XinyuHou** [comment]
@Spiderkey 
Could you use ping command to check the connection between your devices?

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
