### ISSUE TITLE
Greek keyboard switch and tone marks in client's screen 

### ISSUE THREAD

**Issue by CostisB** [symless/synergy#5969]
### Operating Systems ###

Server: MacOS 10.10.5
Client: Windows 7 Professional N (v6.1 Build 7601, Service Pack 1)

### Synergy Version ###

1.8.3-stable-db9181b

### Steps to reproduce bug ###

1. While o client screen (Windows 7) I cannot switch to Greek language with both Win or Mac shortcuts. The only way to switch language is when the cursor is on the server screen
1. When in Greek language there is no way to place tone marks in client's screen. Tone marks are entered by hitting first the ";" key and then the letter to be "toned".

**Comment by XinyuHou** [comment]
Synthesis of #4309 #4280 #4344
