### ISSUE TITLE
Cannot restore synergy GUI after closing to tray

### ISSUE THREAD

**Issue by ruicovelo** [symless/synergy#5972]
### Operating Systems ###

Server: Windows 10 vesion 1607
Client: Mac OS X

### Synergy Version ###

1.8.8-stable

### Steps to reproduce bug ###

1. Start synergy
2. Configure as server and apply
3. Click close window button at the top right
4. Window closes to tray
5. Window cannot be restored. Right click menu disabled. Double click does not do anything. 

### Other info ###

Workaround: don't close. Minimise only. Deal with an extra application icon in the task bask and window to cycle through

**Comment by XinyuHou** [comment]
@ruicovelo 
Do you experience this on Windows or Mac or both?

**Comment by ruicovelo** [comment]
Windows

**Comment by XinyuHou** [comment]
@ruicovelo 
Thanks, could you leave the GUI open on Windows to see if there is any dialog popping up after you apply? I think it is some dialogs that cause this issue.

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
