### ISSUE TITLE
win 7 32 bit auto config bonjour downloader hangs

### ISSUE THREAD

**Issue by osde8info** [symless/synergy#5973]
### Operating Systems ###

Server: microOS Tiara
win 10 64 bit 
Client: Applesoft Windy OS 10
win 7 32 bit 

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. run synergy
2. chose client mode
3. click auto config TWICE
4. hangs

### Other info ###

crashed within 5 mins of brand new install

**Comment by XinyuHou** [comment]
Will be solved after #5587 is done.
