### ISSUE TITLE
windows 7 & 10 synergy server and client task icon disappears when you close synergy window

### ISSUE THREAD

**Issue by osde8info** [symless/synergy#5975]
### Operating Systems ###

Server: microOS Tiara
windows 10
Client: Applesoft Windy OS 10
windows 7

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. run synergy
2. start server
3. close window
4. task icon disappears but synergy is still running

1. run synergy
2. start client
3. close window
4. task icon disappears but synergy is still running

**Comment by XinyuHou** [comment]
@osde8info 
Please check your tray area. On Windows we have a service running at the background which is the process that starts synergy server or client. That is why sometimes even you can't see the GUI, the process is still running at background.

**Comment by osde8info** [comment]
yes the process is running fine but the ICON is invisible until i reopen the app

**Comment by osde8info** [comment]
please reopen or please upgrade me to pro (instead of a refund you promised in your marketing email)

**Comment by XinyuHou** [comment]
@osde8info 
Do you mean the icon is there but not visible or it is not there at all?

**Comment by osde8info** [comment]
how can i tell if i cant see it ?

**Comment by osde8info** [comment]
please UNCLOSE this ticket asap

**Comment by XinyuHou** [comment]
Duplicate of #4498

**Comment by osde8info** [comment]
thank you please dont CLOSE unresolved bugs in the future then you wont need to create duplicates
