### ISSUE TITLE
Synergy does not compile on Raspberry Pi 3!

### ISSUE THREAD

**Issue by Synergyst** [symless/synergy#5982]
Server: Kali Linux for the Raspberry Pi 3

Synergy source version: latest from Git repo

Steps to reproduce bug: cd ~ ; rm -rf synergy ; git clone https://github.com/symless/synergy.git ; cd synergy ; ./hm.sh conf -g1 ; ./hm.sh build 

The problem happens after running './hm.sh build'
I have been unable to find a way to fix the error during compilation..
Yes, this prevents me from using Synergy, a piece of software I use and have paid for which is no longer working on a new device.

Raw output: `root@kali:~/synergy# ./hm.sh conf -g1
Mapping command: conf -> configure
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Entering dir: build/release
CMake command: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ../..
-- Configuring done
-- Generating done
-- Build files have been written to: /root/synergy
Going back to: /root/synergy
QMake command: qmake gui.pro -r QMAKE_VERSION_STAGE=stable QMAKE_VERSION_REVISION=ec56ac44
Entering dir: src/gui
Going back to: /root/synergy
root@kali:~/synergy# ./hm.sh build
Entering dir: build/release
-- Looking for C++ include istream
-- Looking for C++ include istream - found
-- Looking for C++ include ostream
-- Looking for C++ include ostream - found
-- Looking for C++ include sstream
-- Looking for C++ include sstream - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file locale.h
-- Looking for include file locale.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Looking for include file sys/socket.h
-- Looking for include file sys/socket.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include file sys/utsname.h
-- Looking for include file sys/utsname.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file wchar.h
-- Looking for include file wchar.h - found
-- Looking for getpwuid_r
-- Looking for getpwuid_r - found
-- Looking for gmtime_r
-- Looking for gmtime_r - found
-- Looking for nanosleep
-- Looking for nanosleep - found
-- Looking for poll
-- Looking for poll - found
-- Looking for sigwait
-- Looking for sigwait - found
-- Looking for strftime
-- Looking for strftime - found
-- Looking for vsnprintf
-- Looking for vsnprintf - found
-- Looking for inet_aton
-- Looking for inet_aton - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of char
-- Check size of char - done
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
-- Check size of short
-- Check size of short - done
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found CURL: /usr/lib/arm-linux-gnueabihf/libcurl.so (found version "7.52.1")
-- Check size of XRRNotifyEvent
-- Check size of XRRNotifyEvent - done
-- Looking for 3 include files X11/Xlib.h, ..., X11/extensions/dpms.h
-- Looking for 3 include files X11/Xlib.h, ..., X11/extensions/dpms.h - found
-- Looking for include file X11/extensions/Xinerama.h
-- Looking for include file X11/extensions/Xinerama.h - found
-- Looking for 3 include files X11/Xlib.h, ..., X11/extensions/XKBstr.h
-- Looking for 3 include files X11/Xlib.h, ..., X11/extensions/XKBstr.h - found
-- Looking for include file X11/extensions/XKB.h
-- Looking for include file X11/extensions/XKB.h - found
-- Looking for include file X11/extensions/XTest.h
-- Looking for include file X11/extensions/XTest.h - found
-- Looking for include files X11/Xlib.h, X11/XKBlib.h
-- Looking for include files X11/Xlib.h, X11/XKBlib.h - found
-- Looking for include file X11/extensions/XInput2.h
-- Looking for include file X11/extensions/XInput2.h - found
-- Looking for IceConnectionNumber in SM;ICE
-- Looking for IceConnectionNumber in SM;ICE - found
-- Looking for DPMSQueryExtension in Xext;X11
-- Looking for DPMSQueryExtension in Xext;X11 - found
-- Looking for XTestQueryExtension in Xtst;Xext;X11
-- Looking for XTestQueryExtension in Xtst;Xext;X11 - found
-- Looking for XineramaQueryExtension in Xinerama
-- Looking for XineramaQueryExtension in Xinerama - found
-- Looking for XISelectEvents in Xi
-- Looking for XISelectEvents in Xi - found
-- Looking for XRRQueryExtension in Xrandr
-- Looking for XRRQueryExtension in Xrandr - found
-- Configuring done
-- Generating done
-- Build files have been written to: /root/synergy/build/release
[  0%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/Arch.cpp.o
[  1%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/ArchConsoleStd.cpp.o
[  1%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/ArchDaemonNone.cpp.o
[  2%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/IArchString.cpp.o
[  2%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/unix/ArchConsoleUnix.cpp.o
[  3%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/unix/ArchDaemonUnix.cpp.o
[  4%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/unix/ArchFileUnix.cpp.o
[  4%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/unix/ArchInternetUnix.cpp.o
[  5%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/unix/ArchLogUnix.cpp.o
[  5%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/unix/ArchMultithreadPosix.cpp.o
[  6%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/unix/ArchNetworkBSD.cpp.o
[  6%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/unix/ArchSleepUnix.cpp.o
[  7%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/unix/ArchStringUnix.cpp.o
[  8%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/unix/ArchSystemUnix.cpp.o
[  8%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/unix/ArchTaskBarXWindows.cpp.o
[  9%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/unix/ArchTimeUnix.cpp.o
[  9%] Building CXX object src/lib/arch/CMakeFiles/arch.dir/unix/XArchUnix.cpp.o
[ 10%] Linking CXX static library ../../../../../lib/libarch.a
[ 10%] Built target arch
[ 11%] Building CXX object src/lib/common/CMakeFiles/common.dir/Version.cpp.o
[ 11%] Linking CXX static library ../../../../../lib/libcommon.a
[ 11%] Built target common
[ 11%] Building CXX object src/lib/base/CMakeFiles/base.dir/Event.cpp.o
[ 12%] Building CXX object src/lib/base/CMakeFiles/base.dir/EventQueue.cpp.o
[ 13%] Building CXX object src/lib/base/CMakeFiles/base.dir/EventTypes.cpp.o
[ 13%] Building CXX object src/lib/base/CMakeFiles/base.dir/FunctionEventJob.cpp.o
[ 14%] Building CXX object src/lib/base/CMakeFiles/base.dir/FunctionJob.cpp.o
[ 14%] Building CXX object src/lib/base/CMakeFiles/base.dir/Log.cpp.o
[ 15%] Building CXX object src/lib/base/CMakeFiles/base.dir/SimpleEventQueueBuffer.cpp.o
[ 15%] Building CXX object src/lib/base/CMakeFiles/base.dir/Stopwatch.cpp.o
[ 16%] Building CXX object src/lib/base/CMakeFiles/base.dir/String.cpp.o
[ 17%] Building CXX object src/lib/base/CMakeFiles/base.dir/Unicode.cpp.o
[ 17%] Building CXX object src/lib/base/CMakeFiles/base.dir/XBase.cpp.o
[ 18%] Building CXX object src/lib/base/CMakeFiles/base.dir/log_outputters.cpp.o
[ 18%] Linking CXX static library ../../../../../lib/libbase.a
[ 18%] Built target base
[ 18%] Building CXX object src/lib/shared/CMakeFiles/shared.dir/SerialKey.cpp.o
[ 19%] Linking CXX static library ../../../../../lib/libshared.a
[ 19%] Built target shared
[ 20%] Building CXX object src/lib/io/CMakeFiles/io.dir/StreamBuffer.cpp.o
[ 20%] Building CXX object src/lib/io/CMakeFiles/io.dir/StreamFilter.cpp.o
[ 21%] Building CXX object src/lib/io/CMakeFiles/io.dir/XIO.cpp.o
[ 21%] Linking CXX static library ../../../../../lib/libio.a
[ 21%] Built target io
[ 22%] Building CXX object src/lib/mt/CMakeFiles/mt.dir/CondVar.cpp.o
[ 22%] Building CXX object src/lib/mt/CMakeFiles/mt.dir/Lock.cpp.o
[ 23%] Building CXX object src/lib/mt/CMakeFiles/mt.dir/Mutex.cpp.o
[ 23%] Building CXX object src/lib/mt/CMakeFiles/mt.dir/Thread.cpp.o
[ 24%] Building CXX object src/lib/mt/CMakeFiles/mt.dir/XMT.cpp.o
[ 25%] Linking CXX static library ../../../../../lib/libmt.a
[ 25%] Built target mt
[ 25%] Building CXX object src/lib/net/CMakeFiles/net.dir/IDataSocket.cpp.o
[ 26%] Building CXX object src/lib/net/CMakeFiles/net.dir/NetworkAddress.cpp.o
[ 26%] Building CXX object src/lib/net/CMakeFiles/net.dir/SecureListenSocket.cpp.o
[ 27%] Building CXX object src/lib/net/CMakeFiles/net.dir/SecureSocket.cpp.o
/root/synergy/src/lib/net/SecureSocket.cpp: In member function 'void SecureSocket::showSecureCipherInfo()':
/root/synergy/src/lib/net/SecureSocket.cpp:810:46: error: invalid use of incomplete type 'SSL {aka struct ssl_st}'
  STACK_OF(SSL_CIPHER) * cStack = m_ssl->m_ssl->session->ciphers;
                                              ^~
In file included from /usr/include/openssl/crypto.h:31:0,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:47,
                 from /root/synergy/src/lib/net/SecureSocket.cpp:27:
/usr/include/openssl/ossl_typ.h:144:16: note: forward declaration of 'SSL {aka struct ssl_st}'
 typedef struct ssl_st SSL;
                ^~~~~~
src/lib/net/CMakeFiles/net.dir/build.make:134: recipe for target 'src/lib/net/CMakeFiles/net.dir/SecureSocket.cpp.o' failed
make[2]: *** [src/lib/net/CMakeFiles/net.dir/SecureSocket.cpp.o] Error 1
CMakeFiles/Makefile2:549: recipe for target 'src/lib/net/CMakeFiles/net.dir/all' failed
make[1]: *** [src/lib/net/CMakeFiles/net.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Going back to: /root/synergy
Error: make failed: 512`

**Comment by yupi2** [comment]
Change the line in `synergy/src/lib/net/SecureSocket.cpp:810` to `STACK_OF(SSL_CIPHER) * cStack = SSL_get_client_ciphers(m_ssl->m_ssl);`

**Comment by Synergyst** [comment]
I changed that line and just finished compiling the program.

**Comment by Synergyst** [comment]
Good news, your suggestion allowed the software to compile successfully and not only that but it works just the same as it did before on my AMD64 Debian Synergy server I used to have!

Thank you.
