### ISSUE TITLE
Synergy not starting or working on Client

### ISSUE THREAD

**Issue by Booshway** [symless/synergy#5983]
I purchased the Pro version of Synergy less than one year ago and it was working great and I love it!! I think about 2-3 months it stopped working. I haven't had time to do much research online possible causes since Im the only caregiver for my mom as she fights cancer.  Im very overwhelmed right now and could really use some help getting this resolved to make my life a lot easier.
Im only trying to run on two computer: 
The host is a Windows 7 x64 laptop running synergy version 1.8.8-stable-25a8cb2
The Client is a iMac running OS X El Capitan version 10.11.6 running Synergy version 1.8.8-stable-25a8cb2 as well
They are both on the same home grade Router/Switch combo running wired.  But after synergy updates it no longer works.
On the client side (windows 7) synergy is running, but on the client (iMac) it always stays on "Synergy is starting" Status 
Can someone please help me I would really appropriate it.

**Comment by XinyuHou** [comment]
@Booshway 
Are you using SSL? If so, please reactivate the GUI.

This looks like a support request. Please use our mailing list for further help.
synergy-users@googlegroups.com
