### ISSUE TITLE
Stuck at "starting cocoa loop"

### ISSUE THREAD

**Issue by pakelc** [symless/synergy#5986]
I have been using synergy for years; I have run into minor issues that I've been able to resolve, but I'm stuck on this one.
Running synergy 1.8.8 on macOS 10.12.4, it doesn't go past "starting cocoa loop". Hence, I cannot use that system neither as a server or a client.
I have restarted the app, the system, reinstalled the app, deleted every synergy file I could find, reinstalled again, and created a new user to start from zero. In all these cases, synergy gets stuck at the same point.
I updated to 10.12.4 recently, but I have used synergy successfully after that, so I don't think this is the cause.
Is this a known issue? Has anyone ever run into this and if so, how was it fixed?

**Comment by XinyuHou** [comment]
@pakelc 
Please send us some logs with log level set to Debug.
https://github.com/symless/synergy/wiki/Sending-logs

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
