### ISSUE TITLE
Mac OSX client 10.1.6 crashes on startup

### ISSUE THREAD

**Issue by wdamien** [symless/synergy#5988]
### Operating Systems ###

Client: 10.11.6 (15G1421)

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

- Open synergy
- A window briefly pops up then closes, so I can't see what it says. The Synergy menu Item appears, but all the items are disabled.

### Other info ###

This happened after I updated to OSX 10.1.6

Related logs I pulled from the Console: 
https://gist.github.com/wdamien/583e508a66a03c3a5ba8742c1dc6985d

And a couple *.crash files from my system: 
https://gist.github.com/wdamien/d4e747c9b91a587165b0f4389f3da700
https://gist.github.com/wdamien/15852acedb268ea7f8ad5d757db230ad

**Comment by XinyuHou** [comment]
@wdamien 
Did you drag Synergy into Applications folder?

**Comment by wdamien** [comment]
Yep, its "Installed" just like any other OSX application is.  I even tried doing a full uninstall using AppCleaner, and re-downloading the latest version. And no luck getting it working yet.

**Comment by caMi11er** [comment]
See if QT 5.9 helps:
 https://groups.google.com/forum/#!topic/synergy-dev/f20FiartKew

**Comment by wdamien** [comment]
Same result.  I compiled the latest master using QT 5.9 and all the menu items are still disabled.

**Comment by caMi11er** [comment]
fwiw, I see you're running MAC OS 10.11., whereas I'm running 10.12.4.
I can stop and restart it at will using the menu, and turn on debug2 in Preferences, and see every little mouse movement in the log window.  I attach a screenshot.  
Let me if any info from this install might be helpful. 
![screen shot 2017-04-15 at 11 33 54 pm](https://cloud.githubusercontent.com/assets/27168247/25069413/e4e9303a-2234-11e7-8caf-98fa4ff92fbb.png)

**Comment by wdamien** [comment]
I have also updated to 10.12.4 and I can't even get as far as seeing that menu (from a fresh install as well as my newly compiled version), so unfortunately your screen captures don't help.  This is all I see:
![menu](https://cloud.githubusercontent.com/assets/299050/25093793/a9e3968c-2348-11e7-8992-b435f6fd6daa.png)

Maybe there's configuration or other file somewhere I need to delete?

**Comment by wdamien** [comment]
I should also add that I can run the client from the command line via `./synergyc [ip]`, but it would be nice to have a ui for it. :)

**Comment by XinyuHou** [comment]
Please try to compile v1.9 branch

**Comment by wdamien** [comment]
How would I go about compiling v1.9? Its missing the hm.sh file I was using to compile previously.

**Comment by XinyuHou** [comment]
Here is the script we use. You might need to modify some variables and skip code sign part.
QT_PATH=$HOME/Qt/5.8/clang_64
export CMAKE_PREFIX_PATH=$QT_PATH
export PATH=$PATH:/usr/local/bin:$QT_PATH/bin
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH

mkdir build
cd build

cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DSYNERGY_REVISION=$GIT_COMMIT ..
make -j8

make install

macdeployqt $WORKSPACE/build/bundle/Synergy.app -codesign="$CODESIGN_ID"
codesign -f -s "$CODESIGN_ID" $WORKSPACE/build/bundle/Synergy.app

ln -s /Applications $WORKSPACE/build/bundle/Applications
hdiutil create -volname Synergy -srcfolder $WORKSPACE/build/bundle/ -ov -format UDZO Synergy.dmg

**Comment by wdamien** [comment]
Thanks! I was able to get v1.9 compiling.  However it did not fix the menu issue, everything is still disabled.

When I launch the app, I now see these messages outputted in the Console:

```
default	17:55:25.658940 -0700	synergy	UNIX error exception: 17
default	17:55:25.659313 -0700	synergy	0x608000674980 opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
default	17:55:25.660355 -0700	synergy	UNIX error exception: 17
default	17:55:25.660538 -0700	synergy	UNIX error exception: 17
default	17:55:25.660648 -0700	synergy	0x6080006781c0 opened /System/Library/Keychains/SystemRootCertificates.keychain: 385940 bytes
default	17:55:25.667102 -0700	synergy	Invalid serial number length (21), must be 1..20
```

I built it using Qt5.3.2.

When I tried 5.9 I received this error when I launched the app.
```
Dyld Error Message:
  Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Users/USER/Documents/*/Synergy.app/Contents/MacOS/synergy
  Reason: Incompatible library version: synergy requires version 5.9.0 or later, but QtWidgets provides version 5.3.0
```

**Comment by XinyuHou** [comment]
My guess about the the disabled menu is Synergy pops up a dialog but some how doesn't show it to the top most. Could you try to double-click the  menu or the icon in the tray? I remember that could bring up the GUI if it's caused by a blocking dialog.

**Comment by wdamien** [comment]
@XinyuHou That was it!  I had a hidden "You have not filled in a valid configuration file for the synergy server. Do you want to browse for the configuration file now?" dialog. That only showed up when I clicked on the dock icon. I used the work around mentioned here #4020 to resolve the issue.  So just an annoying UX bug going on.  Thanks.
