### ISSUE TITLE
Cannot navigate to Client desktop when an image is in the clipboard.

### ISSUE THREAD

**Issue by quasarito** [symless/synergy#5989]
### Operating Systems ###

Server: Windows 7 Enterprise (Version 6.1 Build 7601 SP1)
Client: Windows 10 Home (Version 1607 OS Build 14393.953)

### Synergy Version ###

1.8.8-stable-25a8cb2

### Steps to reproduce bug ###

1. On Server, take a screenshot by pressing Print Screen button, or just copy an image into the clipboard.
2. Move mouse cursor to Client desktop.

Cursor will not move to Client desktop. It will "stutter" at the screen edge and will remain in the Server desktop.

### Other info ###

Note that I am not trying to copy/paste an image from Server to Client. I just want to navigate within the Client desktop, but if I inadvertently have an image in the clipboard, it will prevent me from going to the Client desktop.

The workaround is to copy some text into the clipboard (thus wiping out the image in the clipboard), and then I will be able to move the cursor to the Client desktop. It wasn't immediately obvious what was the problem, or that it was a clipboard issue.
It is a nuisance to have to clear the image from the clipboard (and remember to do so) for Synergy to work. Could you simply flush the clipboard or not bother attempting to copy the clipboard to the Client in such a case? It's make usability so much easier as it seems clipboard images are not supported across desktops.

**Comment by XinyuHou** [comment]
@quasarito 
Sorry for the inconvenience. We do have a plan to improve clipboard for big data in the future. Please follow #5531

For now, you can temporarily disable the clipboard in Configure Server -> Advanced server settings -> Enable clipboard sharing.
