### ISSUE TITLE
Service uses 100% CPU usage on Windows

### ISSUE THREAD

**Issue by XinyuHou** [symless/synergy#5995]
### Operating Systems ###

Server: Windows 10
Client: Any

### Synergy Version ###

1.9.0.2

### Steps to reproduce bug ###

1. Start Synergy server on a Windows machine
2. Connect a client
3. Open Task Manager
4. Check synergyd is using 100% CPU

### Other info ###

* When did the problem start to occur? New in 1.9
* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? No

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy/wiki/Sending-logs

Put anything else you can think of here.

**Comment by kekkokk** [comment]
same probl here

**Comment by XinyuHou** [comment]
@kekkokk 
Could you give us some more information about how to reproduce this issue? Thanks

**Comment by kekkokk** [comment]
I have OSX Sierra as host (10.12.3), Mbp early 2011 i7 15"
I have 1.8.8 stable and some clients (tried first with windows 10 and then with osx sierra 10.12.5 beta)

when i move the mouse, cpu utilization goes up to 40%

ALSO
I became crazy to find https://github.com/symless/synergy/issues/5648.
I was affected by this bug as well as everyone with sierra + external mouse I think.
It's a bug 5 months old. they finally found a fix and its NOWHERE
Tried on your "nightly" website but the link is broken.
The only one link working is this 
https://github.com/symless/synergy/issues/5648#issuecomment-292160603

PLEASE, make this file stable and public to everyone's who's paying for this software.

**Comment by XinyuHou** [comment]
@kekkokk 
 I assume  you mean when you move your cursor on you Windows client, the synergyc is using high cpu, is this correct?

**Comment by kekkokk** [comment]
it happens also without a client connected. Simply open synergy on my osx sierra host in stopped state and watch activity monitor. cpu usage, when making circles with mouse, goes up to 30%

**Comment by XinyuHou** [comment]
@kekkokk 
Sorry this issue is for Windows. Please follow this one for Mac #5991
