### ISSUE TITLE
Unable to find download links on website

### ISSUE THREAD

**Issue by zborboa-g** [symless/synergy#5999]
Wiki says "More information and download links can be found at the Synergy website." and links to http://synergy-project.org/

Where can I find the direct download links? Thanks

https://github.com/symless/synergy/wiki/User-Guide#intro

**Comment by XinyuHou** [comment]
This is our help page on the webesite which includes tutorial about how to setup.
https://symless.com/synergy/help

**Comment by zborboa-g** [comment]
The "downloads" link redirects to https://symless.com/login. Where can I find the download to the binary? Thanks

![image](https://cloud.githubusercontent.com/assets/6154360/25286853/1610c54a-2674-11e7-8df8-f7e5a5ede290.png)
