### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [symless/synergy#6007]
Would you like to wrap any pointer data members with the template class “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for std::unique_ptr")”?

Update candidates:
- [AddClientDialog](https://github.com/symless/synergy/blob/c3c0913633041584fa41180640d2e4c83fa92820/src/gui/src/AddClientDialog.h#L58)
- [EventQueue](https://github.com/symless/synergy/blob/c3c0913633041584fa41180640d2e4c83fa92820/src/lib/base/EventQueue.h#L184)

**Comment by XinyuHou** [comment]
Please use pull request for contribution.
