### ISSUE TITLE
Physical Mouse Cursor disapears on Client if Synergy Cursor is not on Client

### ISSUE THREAD

**Issue by zocker1996** [symless/synergy#6015]
I got a Windows 10 Machine as Server and one as Client. On the client there is also a phyisical mouse connected. I want to be able to use synergy as intended but use the physical mouse on the client as well.
I can use the physical mouse if the synergy cursor is on the client. But if the synergy mouse swaps back
to the server the physical mouse is still there on the client, I can move it and click with it but it is invisible.

**Comment by XinyuHou** [comment]
@zocker1996 
This is intended. You can move your physical cursor on the client to the bottom of the screen, task bar, to show the cursor again.

**Comment by towertop** [comment]
@XinyuHou
Which version start to have this behavior? I mean move cursor to task bar to let it appears. 
Your suggestion doesn't work in my side with Synergy 1.8.7 on a Windows 8.1 Client.

**Comment by towertop** [comment]
Update my comment upon, after install 1.8.8 and restart the client system, the problem got fixed.
