### ISSUE TITLE
"a" key not working when Synergy is running

### ISSUE THREAD

**Issue by parispitts** [symless/synergy#6019]
### Operating Systems ###

Server: OSX 10.12.4
Client: OSX 10.12.4 (Same machine) and Windows 10 Enterprise 1607, Build 14393.1066

### Synergy Version ###

1.8.8-stable-25a8cb2 on OSX
1.8.8-stable-25a8cb2 on Win

### Steps to reproduce bug ###

**READ ME, DELETE ME**: Try to be succinct. If your bug is intermittent, try and describe what you're doing when it happens most.

1. Start Synergy
2. Move cursor to OSX, Type "a" key on OSX; does not work
3. Move cursor to Win, Type "a" key on Windows, works
4. Stop Synergy on OSX
5. Type "a" key on OSX; works. 

### Other info ###

* Problem started today (latest installs include Xcode (8.3.2) on 4/20, and Spark (1.2.2) on 4/22.
* No real workaround; stopping Synergy is only way, then, cannot access Windows. 
* Does this bug prevent you from using Synergy entirely? Yes

Server side log -https://gist.github.com/parispitts/e92747f85cb51e2750e4c6fdbda29c58

**Comment by XinyuHou** [comment]
@parispitts 
Is it just the 'a' key not working?

When you press the 'a' key on a client, if you set log level to debug2, could you see if the client receives any message?

**Comment by parispitts** [comment]
Only the a key seems to be the issue; snip from log file

`[2017-04-29T21:19:54] DEBUG2: ignoring unknown system defined event
[2017-04-29T21:19:54] DEBUG1: event: button press button=1
[2017-04-29T21:19:54] DEBUG2: dragging file directory is cleared
[2017-04-29T21:19:54] DEBUG1: onMouseDown id=1
[2017-04-29T21:19:54] DEBUG2: ignoring unknown system defined event
[2017-04-29T21:19:54] DEBUG1: event: button release button=1
[2017-04-29T21:19:54] DEBUG1: onMouseUp id=1`

Full log here - <script src="https://gist.github.com/parispitts/533dfe4e37f0e99e6b5fb13e415c7551.js"></script>

**Comment by parispitts** [comment]
There was a hotkey defined with a in the settings.
