### ISSUE TITLE
Synergy is starting

### ISSUE THREAD

**Issue by AdamMiltonBarker** [symless/synergy#6023]
ISSUE: Server continually says Synergy is starting on Windows 10
ISSUE: Mac says continually starting, it does keep show zeroconf server detected everytime I open the server

I had the issue this morning and disabled AVG and it worked again, after a reboot, it will not start the server again, I have disabled Windows and AVG firewall, in Windows synergy is an allowed application anyway. 

I have lost a days work almost through this issue, does anyone know the solution for this ?

**Comment by XinyuHou** [comment]
@AdamMiltonBarker 
Could you give us some logging?

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
