### ISSUE TITLE
Connection problem Win10 client and OSX sierra server

### ISSUE THREAD

**Issue by olavtj** [symless/synergy#6026]
Server OS: OSX Sierra
Client OS: Win 10

client refuses to connect to server just says "connection timed out"
If i reverse it and make my Win10 computer the server it works just fine. Using only autoconfig to connect the two. It worked just fine on an earlier version of synergy (not sure which.) however now running 1.8 the problem persists. I´ve tried most solutions i could understand through google (disabling firewalls and such.) Any ideas?

**Comment by XinyuHou** [comment]
@olavtj 
Firstly please try ping each machine.

If it still doesn't work, please use our forum to get community support.

https://symless.com/forums/login/
