### ISSUE TITLE
Corners do not work

### ISSUE THREAD

**Issue by magicalbanana** [symless/synergy#6032]
### Operating Systems ###

Server: os Sierra 10.12.4
Client: Linux Xenial 16.04

When setting up the screens I put one on the top left or bottom right corner but I am unable to switch screens.

### Synergy Version ###

1.8.8-stable-25a8cb2

**Comment by blksith0** [comment]
Is it bad etiquette to bump with "me too"?
Both server and client:  Win 10 Enterprise x64 10.0.14393

**Comment by XinyuHou** [comment]
@magicalbanana 
Sorry, this is currently not supported. There is a workaround which is using hotkey switch. You can do that in server configure.

**Comment by XinyuHou** [comment]
Close because of no reply.
