### ISSUE TITLE
Synergy Client is incompatible with the Amazon Lumberyard editor.

### ISSUE THREAD

**Issue by photex** [symless/synergy#6036]
### Operating Systems ###

Server: Windows 10 Version 1703
Client: Windows 10 Version 1607

### Synergy Version ###

1.8.8-stable-25a8cb2

### Steps to reproduce bug ###

Download and run the Amazon Lumberyard editor. It works fine with the server. But the client machine has terrible interaction. Delayed mouse presses and releases. Variable mouse accelerations and so on. With Lumberyard running the mouse pointer stutters constantly even when not interacting with the viewport.

### Other info ###

You can download Lumberyard from here: https://aws.amazon.com/lumberyard/

* Workarounds? Use a physically connected second mouse in addition... :(
* Does this bug prevent you from using Synergy entirely? Yes-ish For the majority of the time perhaps I could use Synergy, however I'm actively finding and alternative that's compatible instead.

**Comment by nlyan** [comment]
I could not reproduce this issue with Synergy v1.9 on a Windows 10 1703 client. I used Lumberyard v1.9.0.1 build 398643. 

Obviously there are a few variables different between this setup and yours, so i'd recommend trying v1.9-rc3 first: https://symless.com/forums/topic/2587-synergy-v190-release-candidate/

**Comment by photex** [comment]
Sounds promising!
Should I update the client and server at the same time or is there an order you'd like me to try out?

**Comment by photex** [comment]
Unfortunately this didn't work. 

Only thing I can think of now is that this is a hidpi system (the client), and the server is not.

**Comment by photex** [comment]
Using the 1.9 release candidate on both the server and the client I have this issue still.

I next confirmed that switching the roles of each machine still exhibited the effect. Whatever machine is running the client has the problem with lumberyard.

**Comment by photex** [comment]
Howdy!

So perhaps this is an interesting update for you. Even the Lumberyard SetupAssistant application appears to cause massive mouse lag (which is what I see as the root of the problems I'm having). This is using Qt 5.6 and should really be doing anything at all. I'm not sure what Qt module might be causing this. QtCreator for examples seems to work fine (doesn't cause my mouse to jitter around or display lag). I don't see any mouse issues with a locally attached mouse. Is it possible that something in these applications is preempting Synergy?

**Comment by XinyuHou** [comment]
@photex 
There is a known bug in qt5 with their network manager. Any GUI uses that class would cause a ping spike. Syenrgy 1.8.8 had the same issue. We fixed it in 1.9.

However, to get this fixed completely, Lumberyard needs to apply the same fix in their GUI. Don't think there is anything we can do on our side.
