### ISSUE TITLE
Synergy keeps logging on desktop

### ISSUE THREAD

**Issue by alexandercerutti** [symless/synergy#6041]
### Operating Systems ###

Server: macOS 10.12.4
Client: Windows 10 w/ CU

### Synergy Version ###

1.8.8-stable

### Steps to reproduce bug ###

I don't know if there are some steps. Once I clicked for logging events and info on Desktop (on Windows) and then it started, and even if I disabled the option, it keeps logging also with names synergy.log, synergy.log.1. This is going on for months and I cannot disable it: files keeps creating.

Thank you.

**Comment by XinyuHou** [comment]
@alexandercerutti 
Please make sure you disable log to file and click ok->apply.

This is a support issue. If you have any further question please use our forum.

https://symless.com/forums/login/?cookieCheck=1

**Comment by alexandercerutti** [comment]
Log to file is disabled. That's why I opened here an issue post. Even if log to file is disabled and I clicked apply (also, various times I restarted synergcy.exe and synergyd.exe), it keeps logging.
