### ISSUE TITLE
Verify that you have sufficient priviliges to install system services - Synergy

### ISSUE THREAD

**Issue by jugos2000** [symless/synergy#6046]
Hey there, 
 I installed Synergy at first without any problems, but the service didn't start. After trying to initialize it on the "Task Manager" tab, under Services it wouldn't let me (can't remember specifically which error appeared). After that, I decided to do a fresh install. Deleted the app, downloaded a new installer, executed it and this happens in the middle of the process: "Service "Synergy" (Synergy) could not be installed. Verify that you have sufficient privileges to install system services." Now I can't by any means get around that. There are no posts about this, at least not ones that help me.....and yes, I am a system administrator.
 Any ideas?
 I'm running on Windows 10, 64 bit version. The installer version is "v1.8.8 stable 25a8cb2"
 Many thanks in advance!!

**Comment by yupi2** [comment]
Try uninstalling it then try rerunning the installer with Administrator Privileges

**Comment by jugos2000** [comment]
I tried to do that, but when right clicking the installer, I don't get the option for running it as administrator.
 Can't figure out why that happens, the option appears in other apps. Is there any other way I can try to execute this file as administrator?
 Thanks!

**Comment by yupi2** [comment]
Is there a UAC prompt that opens up at any point during the install?

**Comment by jugos2000** [comment]
I'm sorry, I don't know what an UAC prompt is

**Comment by yupi2** [comment]
This is an example of a UAC prompt
![uac prompt](https://i.stack.imgur.com/onwhy.png)

**Comment by jugos2000** [comment]
Oh, thanks. I have chosen to "never show" those prompts in settings so no, nothing appears. I only get the normal "do you want to run this app?" before executing the installer.

**Comment by XinyuHou** [comment]
@jugos2000 

Please try shift + right click.

If not working , please google "missing run as admin" on Google.

This is really a support ticket. Please use our forum to discuss support issue.
https://symless.com/forums/?_fromLogin=1
