### ISSUE TITLE
[SOLVED] Alt GR windows Server Ubuntu Client

### ISSUE THREAD

**Issue by w0www** [symless/synergy#6052]
### Operating Systems ###

Server: Windows7
Client: Ubuntu Mate 16.04

The problem was that the key ALT GR not working in client side.

With this workaround i get all keys work correctly. 

section: screens

    <WINDOWS 7 SERVER NAME>:
    altgr = alt

    <UBUNTU CLIENT NAME>: 
    alt = altgr

**Comment by XinyuHou** [comment]
Duplciate of #4411
