### ISSUE TITLE
Problems therefor requesting a refund.

### ISSUE THREAD

**Issue by teck-KRnL** [symless/synergy#6053]
### Operating Systems ###

Server: Windwos 10 1703
Client: Arch Linux w/  Wayland ; Windows 10 170

### Synergy Version ###

1.8.8-stable-25a8cb2

###Problems###

1-linux. Wayland not supported ( I know, many complaints already. But clever me didn't inform well)
1-windows. It's very laggy / file transfer doesn't work 

### Other info ###

* When did the problem start to occur? At the beginning
* Is there a way to work around it? Linux: yes/no because I don't want to turn of Wayland; Windows: no
* Does this bug prevent you from using Synergy entirely? Linux: yes; Windows: no but it's awful to witness 

Therefor I want to request a refund if possible.

**Comment by nlyan** [comment]
Please contact payment-issues@symless.com
