### ISSUE TITLE
Allow running actions on start

### ISSUE THREAD

**Issue by zelivans** [symless/synergy#6057]
I'm using a text configuration file. I would like to start the server with `lockCursorToScreen(on)`. Can you add a feature to run actions on start? Something like `onStart = (actions)` in options would do.

**Comment by XinyuHou** [comment]
@zelivans 
it's supposed the read the scroll lock key state to decide if it should lock to current screen. Please give it a try.

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
