### ISSUE TITLE
Alt + Numpad issue

### ISSUE THREAD

**Issue by cbreault** [symless/synergy#6058]
### Operating Systems ###

Server: Windows 10.1 x64 Version 1703
Client: Windows 10.1 x64 Version 1604

### Synergy Version ###

1.9

### Steps to reproduce bug ###

Add any hotkey using Alt+KP (numpad) not working.

No information shows in logs either, it's like the key isn't even being pressed.

I would like to use Alt+KP_1 etc to transfer key presses to my client machine.

**Comment by XinyuHou** [comment]
Duplicate of #4326
