### ISSUE TITLE
Feature request: Drag & Drop or full clipboard copy/paste Windows<>Linux

### ISSUE THREAD

**Issue by angelsix** [symless/synergy#6065]
You state on the site you support Windows<>Mac drag drop support. I really need this on Windows<>Linux. Your mouse/keyboard stuff is perfect and I purchased a license the last bit I really want is a clipboard copy/paste or drag drop (clipboard copy/paste of folders would be best)

**Comment by XinyuHou** [comment]
Duplicate of #4170
This is assigned to 1.10 roadmap
