### ISSUE TITLE
Master screen freezes when locked and mouse moves to slave machine

### ISSUE THREAD

**Issue by uchapaneri** [symless/synergy#6068]
Windows 10 1607
Mac OS 10.12.5

Synergy 1.8.7-stable-9799e96

When the windows machine is locked and the mouse moves to my mac screen I am unable to move the mouse back to the windows machine to then enter my password to unlock the machine. 

The only way I have managed to regain control of the Windows machine (which is the synergy master) is to disconnect synergy on the mac. 

Is this a known issue?

**Comment by XinyuHou** [comment]
Duplicate of #5294
