### ISSUE TITLE
Trackpad lags with two MacOS Sierras connected

### ISSUE THREAD

**Issue by fandy** [symless/synergy#6072]
### Operating Systems ###

Server: microOS Sierra
Client: microOS Sierra

### Synergy Version ###

 1.8.8 (latest stable)

Greetings! I'm experiencing cursor lag on the client when connected between two MacOS Sierra Macbooks. I'm using auto config on the client and they are both on a fast wifi connection. Any tips to speed things up? Due to the jankiness I'm unable to use Synergy as a second monitor.

### Other info ###

* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? Yes

**Comment by nlyan** [comment]
This is most likely related to a bug causing lag when using macOS with WiFi.

Have you tried the v1.9.0-rc3 build available on our forum? https://symless.com/forums/topic/2587-download-synergy-19-rc3-fixes-the-macos-wifi-lag-bug/

**Comment by XinyuHou** [comment]
@fandy 
Please try this and leave any feedback on the forum.

https://symless.com/forums/topic/2587-download-synergy-19-rc3-fixes-the-macos-wifi-lag-bug/
