### ISSUE TITLE
0xc000007b when trying to open Synergy built from source

### ISSUE THREAD

**Issue by FireFaced** [symless/synergy#6081]
### Operating Systems ###

Server: Windows 10 1703 x86_64
Client: N/A

### Synergy Version ###

1.8.8-git x86
### Steps to reproduce bug ###

1. Pull source code
2. Build source code
3. Try to run application
4. 0xc000007b

### Other info ###

* When did the problem start to occur? Since I built Synergy
* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? Yes

**Comment by nlyan** [comment]
It might be easier to build the v1.9 branch to diagnose where you're having problems. Run it through CMake to generate a Visual Studio solution, and then try and build and run the  program through the IDE.

**Comment by FireFaced** [comment]
I'll try that and get back to you

**Comment by FireFaced** [comment]
By running it through CMake and VS, it threw a bunch of errors from the Bonjour SDK header.

**Comment by FireFaced** [comment]
Trying v1.8.8-rgb x86_64 has no effect

**Comment by FireFaced** [comment]
Looking into it, something is wrong with libgcc_s_dw2-1.dll, which I believe is related to MinGW. Closing issue for now, I'm going to look into it.

**Comment by FireFaced** [comment]
Nevermind: It appears some DLLs are missing in the installer. After copying ALL DLLs from the Qt directories, it launched.

**Comment by nlyan** [comment]
The Bonjour SDK is a little bit of a pain to get hold of. 

@FireFaced is this still an issue?

**Comment by FireFaced** [comment]
No, it isn't. I still am not sure which Qt DLL was missing though. I just know putting ALL of them there worked.

**Comment by isundaylee** [comment]
For others stumbling on this issue, the list of Qt DLLs needed for me are:
```
Qt5Core.dll
Qt5Gui.dll
Qt5Network.dll
Qt5Widgets.dll
```
