### ISSUE TITLE
Mac OS X input languages don't work from Synergy

### ISSUE THREAD

**Issue by tzz** [symless/synergy#6082]
### Operating Systems ###

Server: Ubuntu 17.04
Client: Mac OS Sierra 10.12.5

### Synergy Version ###

1.8.8-stable

### Steps to reproduce bug ###

1. On Mac client, switch input method to non-English (I used Bulgarian).
2. Type from Linux server: only English shows up when Synergy is active.
3. Type on Mac client's local keyboard: Bulgarian shows up.

### Other info ###

* When did the problem start to occur? Unknown
* Is there a way to work around it? No/Yes, you can type on the Mac keyboard
* Does this bug prevent you from using Synergy entirely? No

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy/wiki/Sending-logs

**Comment by nlyan** [comment]
Related to #4280
