### ISSUE TITLE
Menu Bar Icon is transparent on MAC OS

### ISSUE THREAD

**Issue by hiuwo** [symless/synergy#6083]
### Operating Systems ###

Server: Windows 10 ver 1703
Client: macOS Sierra ver 10.12.4

### Synergy Version ###

1.8.8 stable-25a8cb2

### Steps to reproduce bug ###

1. it just exists I just launch synergy and it is transparent but you can still click and interact with it.
<img width="209" alt="no6wiy7qtt6ozzq0pdv_xq" src="https://user-images.githubusercontent.com/6250640/27418068-4fc1e67c-574b-11e7-90ae-0f52d9a9ba82.png">

### Other info ###

It is just very annoying to guess where the icon is since there are bigger/ smaller gaps between icons.

**Comment by nlyan** [comment]
Is this intermittent?

**Comment by XinyuHou** [comment]
Closed because of insufficient information.
