### ISSUE TITLE
Is there a way to stop sharing when playing games.

### ISSUE THREAD

**Issue by raphcadiz** [symless/synergy#6102]
My server is Mac and the client is Window7. When I play a game on windows like Dota, I need to stop the mouse going through my server computer

**Comment by yupi2** [comment]
You can set a hotkey to toggle locking the mouse and keyboard on that screen. `Configure Server... -> Hotkeys` then add a new hotkey with an action to `Lock cursor to screen`. [image](https://i.imgur.com/ATLShF1.jpg)

**Comment by XinyuHou** [comment]
like yupi2 said, or you can use the default key, scroll lock, to lock cursor to current screen
