### ISSUE TITLE
Any Conflicts With CopperLan or Bome Midi Translator?

### ISSUE THREAD

**Issue by formulatica** [symless/synergy#6103]
### Operating Systems ###

Server: Windows 10 Enterprise
Client: Windows 10 Enterprise

**READ ME, DELETE ME**: On Windows, hold the Windows key and press 'r', type 'winver' and hit return to get your OS version. On Mac, hit the Apple menu (top left of the screen) and check 'About this Mac'. Linux users... you know what you're using ;)

### 1.8.6 ###

Anyone know of possible Conflicts With CopperLan or Bome Midi Translator?
http://www.copperlan.org/
https://www.bome.com/products/miditranslator

**Comment by XinyuHou** [comment]
@formulatica 
Github issue is only for raising issues.

Please use our forum or mailing list to ask support questions.

https://symless.com/forums/login/
synergy-users@googlegroups.com
