### ISSUE TITLE
Windows 10 - Are you sure you trust this application - Boots me back to server

### ISSUE THREAD

**Issue by ViolentCrumble** [symless/synergy#6107]
### Operating Systems ###

Server: Windows 7 64bit ver 6.1 build 7601
Client: Windows 10 64 bit ver 1607 build 14393.447

### Synergy Version ###

1.8.8-stable-25a8cb2

### Steps to reproduce bug ###

1. connect to server on win7
2. works fine until you open an application
3. on Windows 10 the "Are you sure you trust this application" pops up
4. user gets kicked back to server
5. takes 3-5 seconds to be able to move to the client again.

**Comment by XinyuHou** [comment]
@ViolentCrumble 
Please open Synergy GUI and settings, then use always for elevate. Thanks.
