### ISSUE TITLE
invalid use of incomplete type `SSL` (compile failed)

### ISSUE THREAD

**Issue by edbird** [symless/synergy#6113]
### Operating Systems ###

Client: Debian 9, XFCE 4

### Synergy Version ###

1.8.π (?)

Could not compile synergy!

### Steps to reproduce bug ###

git clone https://github.com/symless/synergy.git
cd synergy/
QT_SELECT=4 ./hm.sh conf -g1
./hm.sh build

[ 27%] Building CXX object src/lib/net/CMakeFiles/net.dir/SecureSocket.cpp.o
/home/ecb/Desktop/synergy/src/lib/net/SecureSocket.cpp: In member function ‘void SecureSocket::showSecureCipherInfo()’:
/home/ecb/Desktop/synergy/src/lib/net/SecureSocket.cpp:810:46: error: invalid use of incomplete type ‘SSL {aka struct ssl_st}’
  STACK_OF(SSL_CIPHER) * cStack = m_ssl->m_ssl->session->ciphers;
                                              ^~
In file included from /usr/include/openssl/crypto.h:31:0,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:47,
                 from /home/ecb/Desktop/synergy/src/lib/net/SecureSocket.cpp:27:
/usr/include/openssl/ossl_typ.h:144:16: note: forward declaration of ‘SSL {aka struct ssl_st}’
 typedef struct ssl_st SSL;
                ^~~~~~
src/lib/net/CMakeFiles/net.dir/build.make:134: recipe for target 'src/lib/net/CMakeFiles/net.dir/SecureSocket.cpp.o' failed
make[2]: *** [src/lib/net/CMakeFiles/net.dir/SecureSocket.cpp.o] Error 1
CMakeFiles/Makefile2:549: recipe for target 'src/lib/net/CMakeFiles/net.dir/all' failed
make[1]: *** [src/lib/net/CMakeFiles/net.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

### Other info ###

See compile log above

**Comment by yupi2** [comment]
Apply this [patch](https://github.com/symless/synergy/pull/5746/commits/9385083cfc27ecaadf1eaf1d014cd6907860072b.patch) manually or build the [debian package](https://packages.debian.org/buster/synergy) which includes some other misc patches too.

**Comment by edbird** [comment]
I applied the patch manually. And that works. I'm not 100 % familiar with how to apply this patch using `patch`. I saved the entire contents of the file as patch.patch, and ran `patch ./src/lib/net/SecureSocket.cpp patch.patch` - for future reference, what should I have done instead?

**Comment by yupi2** [comment]
Using `patch` is fine. Git has `git apply patch.patch` which can apply a patch and also `git am patch.patch` which can apply the patch as a commit and keeps the patch author and subject.

**Comment by edbird** [comment]
Thanks very much for the info!

**Comment by XinyuHou** [comment]
Duplicate
