### ISSUE TITLE
Windows 10 laggy on the client

### ISSUE THREAD

**Issue by gopalaiahvinay** [symless/synergy#6114]
### Operating Systems ###

Server: Windows 10 Pro Version 1607
Client: Windows 10 Pro Version 1703

Server Configuration: 
Processor: Intel i5 2410-M @ 2.3 GHz
RAM: 12GB 

Client Configuration: 
Processor: Intel i5-5200U @ 2.2 GHz
RAM: 8GB

### Synergy Version ###

1.9.0-rc3

### Steps to reproduce bug ###

The bug usually happens when I am running Football Manager Game which is a but RAM intensive. But I usually have 40-50% free RAM on my 8GB Client. 
When I move the mouse from server to client, it is either laggy or mouse pointer is jumpy. 
Sometimes when I start streaming from sites like hotstar on server, then it becomes laggy on both server & Client. 
There are no predefined steps to create this bug, when it becomes laggy and I check the task manager. 
Neither Server/Client are running on 80%+ CPU load. 
The ping time when the mouse lag occurs is very high, it is around 250 ms on average going up to 3000ms sometimes

### Other info ###

The problem started occurring when I installed Football Manager, 

When I enable debug2 mode for logs, it becomes very slow on both server and client. 
I have attached the logs which I could capture. 
During this time client was running dead slow and laggy. 

Server Logs: https://gist.github.com/gopalaiahvinay/f2193e657c2f0435102b9aabc9d8aad6 
Client Logs: https://gist.github.com/gopalaiahvinay/42aa5964f9dd59256d142b4112200f48

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy/wiki/Sending-logs

Put anything else you can think of here.

**Comment by XinyuHou** [comment]
@gopalaiahvinay 
Could you run Football Manager without Synergy and test ping connection?

**Comment by gopalaiahvinay** [comment]
Without FM (Football Manager) running the ping time is around 100 - 200 ms.

**Comment by gopalaiahvinay** [comment]
@XinyuHou without synergy running it is around 1-3 ms on average 2ms

**Comment by XinyuHou** [comment]
Merged in #4417
