### ISSUE TITLE
Failing to automatically download and install Bonjour

### ISSUE THREAD

**Issue by bennettp123** [symless/synergy#6117]
### Operating Systems ###

Server: n/a
Client: Version 1607 (OS Build 14393.447)

### Synergy Version ###

1.8.8-stable-25a8cb2

### Steps to reproduce bug ###

Method 1: setup wizard

1. Fresh install, Synergy 1.8.8. Setup wizard launches on first run.
2. Choose client, but before connecting to server, synergy prompts to install Bonjour.
3. Click Yes.
4. "Installing bonjour, please wait".
5. Another window appears and disappears brielfy.
6 Bonjour is not installed.

Method 2: "Auto config"

1. Fresh install, Synergy 1.8.8. No setup wizard.
2. Coose "Client", click "Auto config". Synergy prompts "Auto config feature requires Bonjour. Do you want to install Bonjour?"
3. Click Yes. 
4. "Installing bonjour, please wait".
5. Another window appears and disappears brielfy.
6 Bonjour is not installed.

### Other info ###

* Seems to be similar symptoms to #5467 
* Event Viewer shows the following installer event:

```
Ending a Windows Installer transaction: C:\Users\XXX\AppData\Local\Temp\Bonjour.msi. Client Process Id: 13608.
```

* Contents of `C:\Users\XXX\AppData\Local\Temp\Bonjour.msi` :

```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.0 (Ubuntu)</center>
</body>
</html>
```

* Workarounds:
    - option 1: manual config works fine
    - option 2: [download and install bonjour manually](https://github.com/symless/synergy/issues/5467#issuecomment-247021820)
* Does this bug prevent you from using Synergy entirely? No

**Comment by XinyuHou** [comment]
Merged into #5467
