### ISSUE TITLE
Experience feedback

### ISSUE THREAD

**Issue by helloworldgnu** [symless/synergy#6118]
Operating Systems:   macOS Sierra 10.12.6,    Ubuntu 16.04 amd64

Synergy Version:   Synergy_v2.0.0-beta3_b658-489f59a6

1. how to remove the needless computer name ?
2. where is the configuration ?
3. when click the exit button, synergy application exited.
Bad experience!
4. 
The display box for displaying the computer name is too short, can not be fully displayed.

.......

There are many small problems.   Hoping to improve the user experience

**Comment by XinyuHou** [comment]
@helloworldgnu 
Thanks for the feedbacks. 

Please use our forum to discuss v2 issues.

https://symless.com/forums/forum/10-synergy-20-beta-feedback/
