### ISSUE TITLE
install - no hm.sh install scripts in root directory

### ISSUE THREAD

**Issue by mapooo** [symless/synergy#6124]
### Operating Systems ###

Fedora 26

### Synergy Version ###

Latest source download

### Steps to reproduce bug ###

1. copy dependancies required for fedora from wiki
2. .git clone...
3. cd synergy.
4.  QT_SELECT=4 ./hm.sh conf -g1 - "No such file or directory"
5. Profit?

### Other info ###

Am trying to build source on Fedora by following the wiki, but it refers to hm.sh scripts in the root directory of the project, but even on github these files are not there. Am I doing something wrong?

**Comment by nlyan** [comment]
hm.sh has been retired. v1.9 and master both now uses CMake directly. We haven't had the time to update the wiki yet, but will do sometime after v1.9 and v2.0 releases are made.

**Comment by mapooo** [comment]
Is it possible for you give give me a quick rundown of how to build with cmake? I (or some other contributor) could possibly make a temporary replacement guide to sit on the wiki for cleanliness until the next release, or should it be suggested to use and older release for now?
