### ISSUE TITLE
The latest git version of synergy doesn't have the hm.sh script at all.

### ISSUE THREAD

**Issue by hongyi-zhao** [symless/synergy#6127]
Hi all,

According to the notes here:
  https://github.com/symless/synergy/wiki/Compiling

There should be hm.sh script located under the root of project directory.  But the latest git version of synergy doesn't have the hm.sh script at all.

Any hints for this issue?

Regards

**Comment by XinyuHou** [comment]
@hongyi-zhao 
Sorry, that link is out of date.

We are using Cmake to compile the project. Please use our dev mailinglist for compiling instructions. Thanks.

synergy-dev@googlegroups.com
