### ISSUE TITLE
Lock cursor to screen did not work on Mac OS as serverside

### ISSUE THREAD

**Issue by griffinqiu** [symless/synergy#6130]
### Operating Systems ###

Server: macOS Sierra
Client: macOS Sierra

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

Cannot lock screen in server side when playing games. I have tried this config, it did not work in server side, however it works in client side. But it is not I want.

<img width="796" alt="2017-08-19 1 42 42" src="https://user-images.githubusercontent.com/179343/29483864-4cadc048-84e4-11e7-9d77-735d6f08c14e.png">

**Comment by XinyuHou** [comment]
Duplicate of #5908
