### ISSUE TITLE
Is there way to disable across the screen when under a fullscreen application

### ISSUE THREAD

**Issue by griffinqiu** [symless/synergy#6131]
Is there way to disable across the screen when under a fullscreen application between two Macs? Such as a game application.

**Comment by epakai** [comment]
You may bind a key to the lockCursorToScreen() action. 
In the graphical interface use the configure server dialog. Under the hotkeys tab add a new hotkey (I use scroll lock) then select it and add a new action for lock cursor to screen.
![hotkey](https://user-images.githubusercontent.com/1901677/29488756-0afed0d6-84d7-11e7-80d8-12e27a272694.png)

In the text config this looks like:
```
section: options
	keystroke(ScrollLock) = ; lockCursorToScreen(toggle)
end
```

You might also find the "relative mouse moves" option useful for some games. It's in advanced server settings.

**Comment by griffinqiu** [comment]
@epakai Thanks you. I have tried this way. But I have been blocked by this bug https://github.com/symless/synergy/issues/5908

**Comment by XinyuHou** [comment]
@griffinqiu 
Please use our forum to ask for support.

https://symless.com/forums/login/
