### ISSUE TITLE
Cannot Register in Ubuntu, prompting 301 Moved Permanently

### ISSUE THREAD

**Issue by starkshaw** [symless/synergy#6133]
### Operating Systems ###

Server: Ubuntu 16.04
Client: Windows 10

### Synergy Version ###

1.7.6 (Ubuntu)
1.8.8 (Windows 10)

### Steps to reproduce bug ###

When I trying to register on Ubuntu using my personal account, it always prompt a dialog box "301 Moved Permanently", hence I cannot log in use my credentials I have on symless.com

**Comment by XinyuHou** [comment]
Please upgrade your Synergy on Ubuntu side.

Please use our forum for further support question.

https://symless.com/forums/login/

**Comment by starkshaw** [comment]
When I download Synergy from my account page, it said 1.8.8 on the file name of .deb file. But after I installed it, in the About box, it said 1.7.6.
