### ISSUE TITLE
compilation instruction not current

### ISSUE THREAD

**Issue by typorian** [symless/synergy#6136]
hm.sh is nowhere to be found in the repository, so the current version of the compilation instructions don't work.

**Comment by suiye223** [comment]
hm.sh removed? how to compile now?

**Comment by Derrekito** [comment]
I've update the Linux compile section of the wiki. Synergy can be compiled by doing the following :
cmake CMakeLists.txt
make

**Comment by 7starsea** [comment]
I am trying to compile it on Window7, Fatal error, can not open file: VersionHelpers.h (No such file).
Compiler: Visual Studio 2012.

**Comment by ilyasavitski** [comment]
There are no way to make it work on Ubuntu 17.04?

`make install` installs only:
- /usr/local/bin/synergyc
- /usr/local/bin/synergys
- /usr/local/bin/syntool

**Comment by Derrekito** [comment]
What other binaries do you want to compile?

**Comment by ilyasavitski** [comment]
Seems like /usr/local/share/applications/synergy.desktop is for some gui app
`[Desktop Entry]
Type=Application
Version=1.0
Name=Synergy
Comment=Keyboard and mouse sharing solution
Path=/usr/bin
Exec=/usr/bin/synergy
Icon=synergy
Terminal=false
Categories=Utility;
Keywords=keyboard;mouse;sharing;network;share;`
But there are no any synergy executable file in /usr/bin/ directory.

**Comment by ilyasavitski** [comment]
> What other binaries do you want to compile?

Some gui app if it could be compiled.

**Comment by XinyuHou** [comment]
Sorry guys, we are in the process to move into a new version which will just use CMake to compile everything.

**Comment by Derrekito** [comment]
The binary for the GUI doesn't appear to be part of the GitHub hosted project. However, you can extract the .deb file from the Symless website. You can achieve this using the following commands and switches:
`ar x synergy-v1.8.8-stable-25a8cb2-Linux-x86_64.deb`
`tar -xzf data.tar.gz`

Then execute the `synergy` binary located in the 'usr' folder. Note that I had to compile and install 'libdaemon'. I'm going off of memory here, so feel free to followup with any questions.

**Comment by nlyan** [comment]
The GUI is now back in master

**Comment by LajnaLegend** [comment]
I cant seem to get this to work. When i do `cmake synergy-master` it fails.

Any one knows what im doing wrong?

[CMakeOutput.txt](https://github.com/symless/synergy/files/1293250/CMakeOutput.txt)

**Comment by yupi2** [comment]
@LajnaLegend I don't know why it doesn't work but you can check out [my fork](https://github.com/yupi2/synergy) for something that does work.

**Comment by XinyuHou** [comment]
Please use our dev mailing list to talk about compiling.


synergy-dev@googlegroups.com
--




Sorry for all the inconvenience. We will update our compiling instruction after we finish moving to the new build process.
