### ISSUE TITLE
Changing display configuration is not taken into account by Synergy

### ISSUE THREAD

**Issue by rprots** [symless/synergy#6146]
### Operating Systems ###

Ubuntu 16.04.

### Synergy Version ###

1.9.0

### Steps to reproduce bug ###

1. Synergy server and client running.
2. e.g. in multi-monitor client modify display configuration - disable one of the displays
3. Can move mouse on client behind the screen like there is another display.

### Other info ###

Workaround is to restart client.

**Comment by XinyuHou** [comment]
Duplicate of #4762
