### ISSUE TITLE
WebEx causes mouse to freeze on client

### ISSUE THREAD

**Issue by keatre** [symless/synergy#6200]
This has been reported as issue #5939 but was incorrectly closed, as thought it might be linked to another issue - it is not.  This issue only happens when the WebEx program is running - as soon as the program stop on the client, Synergy functions normally. 

This has been tested on both **1.8.8-stable-25a8cb2**
and
**Synergy 2.0.1**

The client computer running WebEx will freeze and the server will report the client as "dead" and attempt a reconnect.  Any client running WebEx has this issue, tested on Windows 10 Enterprise, Window 7 Ultimate, and OSX (10.11.6).

**Comment by mrmucox** [comment]
I intermittently have this issue as well.

**Comment by Fopedush** [comment]
I have this issue every single time I use webex, without fail. Whenever I'm required to join a webex meeting I'm forced to kill synergy and leave my client machines unreachable for the duration of the meeting. This bug should be assigned a higher priority.

**Comment by drtcode** [comment]
Bump. Same issue. I just purchased Synergy 2 pro yesterday and am unable to do my job, as i rely on webex regularly. It sounds like this has been an issue for quite some time. Has any resolution or workaround been offerred eyt?

**Comment by string76** [comment]
May have found a workaround to this issue.  Within the past 30 minutes I made a couple changes to Synergy.  Disabled 'Synchronize Screen Savers' and 'Allow drag and drop files and folders' under Server Configuration.  I also enabled Debug logging (had to manually create the log folder) on both the server and client.  I have not had a single freeze with WebEx running and screen shared in the past 30 minutes.  Normally I have been seeing the mouse/keyboard freeze about every minute or so.  Using Synergy 1.8.8 atm. Can someone else test and see if they can reproduce this?

**Comment by string76** [comment]
Update: have seen a couple freezes in the past 10 min or so.  Not as frequent though and each freeze only last a couple seconds so does seem to be an improvement with the changes listed above.

**Comment by Neomancer86** [comment]
Tried your settings, getting the same issue on 1.8.8 - settings don't seem to make any difference to the issue.

**Comment by kutschinsl** [comment]
I have this issue as well and would really like to highlight it! I hope it can be moved up in priority.  I've paid for Synergy Pro but had to switch products because of this issue.  Really make it unusable when I have to shut it off before every meeting.  Please fix this so I can use your product again!

**Comment by nbolton** [comment]
I've updated the title, is it accurate?

**Comment by keatre** [comment]
>I've updated the title, is it accurate?

I believe a better title would be "WebEx causes mouse to freeze on client".  As the client is the machine running WebEx in my case, and it will completely freeze the machine up until Synergy drops it and reconnects it - around 30 second freeze times.  The mouse still operates on the Server, but is locked there and cannot navigate the client.

**Comment by nbolton** [comment]
Ah, of course. Good spot.

**Comment by scrathe** [comment]
I am also experiencing this issue on Pro v1.9.1-stable. Only happens with Webex.

**Comment by OutLore** [comment]
Add another user here with Webex issues. I can't believe this has been going on for 2 years with not even acknowledgement that I can find. 
Anyone know of any alternatives? I tried the Microsoft offering Mouse without Boundaries (or something similar) but it had some odd cursor speed differences between the systems.

**Comment by nathanu** [comment]
One more user reporting in with the same issue on 1.10.1-stable8941241e. Server Debug1 logs are attached. I tried "upgrading" to the 2.0 Beta and experienced the same issue.

Server: Windows 10 v17763
Client: Windows 10 v16299

[synergyDebug1.log](https://github.com/symless/synergy-core/files/2733430/synergyDebug1.log)

Trying to modify the priority now to see if that works for me.

Nate

**Comment by doublejz** [comment]
Can't believe this issue is still on going..

**Comment by Neomancer86** [comment]
I know right..

I've moved to a different product...  Sigh

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
