### ISSUE TITLE
Short virtual keyboard appears on Mac client

### ISSUE THREAD

**Issue by Ashark** [symless/synergy#6270]
### OS
Server: ArchLinux synergy v 1.8.8
Client: Mac os synergy v 1.8.8

### The problem
Synergy's virtual keyboard is recognised as short laptop keyboard, instead of full sized keyboard.

### Use case
In Final Cut Pro (application for video editing) when you are using it via synergy, you cannot assign some buttons, for example Delete button. This is because you are not able even see such button on a picture of keyboard and fn button is also not displayed. So to be able to assign Delete button (which transfers via synergy normally), you should connect a real keyboard to mac os client and after that start Final cut.

To reproduse this, you do not have to install Final Cut. Just click your language flag in a system tray, then click "Show Keyboard Viewer" in the menu and make a test. I have attached an animated gif to demonstrate you the difference.

![full_sized_keyboard_and_small_sized_synergy](https://user-images.githubusercontent.com/22634975/37235138-57388ffc-240d-11e8-9c99-d4a997e9fd17.gif)

### Possible solution
Register synergy's virtual keyboard as normal full sized keyboard.

**Comment by Ashark** [comment]
I am not using macOS, so I do not know if this is still an issue.

**Comment by nbolton** [comment]
> I am not using macOS, so I do not know if this is still an issue.

Got it. This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
