### ISSUE TITLE
Cannot send Alt Gr special key to Linux client

### ISSUE THREAD

**Issue by rugk** [symless/synergy#6417]
### Operating Systems ###

Fedora 28, x64, GNOME
both on server + client

Both devices have the German keyboard input method set.

### Synergy Version ###

synergy-core 2.0.12, protocol version 1.6

### Steps to Reproduce ###

Test sending the following characters from server to client.

* <kbd>Alt Gr</kbd> + <kbd>.</kbd> (the dot) -> `…` (the Unicode char for three dots) -> this does not work
* <kbd>Alt Gr</kbd> + <kbd>,</kbd> (the dot) -> `·` (the Unicode char for middle dot) -> this does work. however for some strange reason

Both keys work when you are in the same device, but not when using a different device.

### Run Method ###

Config app

### Extra Info ###

This is the keyboard layout of the German keyboard in GNOME:

![image](https://user-images.githubusercontent.com/11966684/45255306-cceded80-b384-11e8-9941-725825c126b1.png)

**Comment by rugk** [comment]
The issue is still valid?

**Comment by jowilkes** [comment]
To me, yes.
Another issue had interesting updates related to this, though: https://github.com/symless/synergy-core/issues/4411#issuecomment-1698950551

**Comment by bjoernmartin** [comment]
Just an FYI: this works flawlessly on Synergy 3 between two Windows 10 machines. So if you still have issues with this, maybe just try Synergy 3 and see if it's fixed there.

Windows version: 10.0.19045.3516 (client) + 10.0.19045.3448 (server)
Synergy version: v3.0.73.7-rc2 (both)

**Comment by SpoopyBE** [comment]
This issue is still present when using between two Linux machines (Ubuntu 22.04.3 LTS) using Synergy v3.0.73.7-rc2.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
