### ISSUE TITLE
Compiling Error, cmake/Version.cmake, Lines 45 to 53, DEFINED SYNERGY_REVISION

### ISSUE THREAD

**Issue by attichicco** [symless/synergy#6462]
### Operating Systems ###

Both Client and Server: Windows 10

### Synergy Version ###

Unknown

### Steps to Reproduce ###

Compiler was not compiling, throwing out error: 
"SYNERGY_REVISION ('${SYNERGY_REVISION}') should be a short commit hash"
**at: synergy-core\cmake\Version.cmake Lines 45 to 53**
I edited my local file and commented out that error checking part that you can see here:

```
if (DEFINED SYNERGY_REVISION)
#    string(LENGTH ${SYNERGY_REVISION} SYNERGY_REVISION_LENGTH)
#    if (NOT ((SYNERGY_REVISION MATCHES "^[a-f0-9]+") AND (SYNERGY_REVISION_LENGTH EQUAL "8")))
#        message (FATAL_ERROR "SYNERGY_REVISION ('${SYNERGY_REVISION}') should be a short commit hash")
#    endif()
#    unset (SYNERGY_REVISION_LENGTH)
#else()
	set (SYNERGY_REVISION "0badc0de")
endif()
```

As you can see with my commenting out it proceeds as it was not defined, and sets it to "0badc0de"
It works for my purpose as I just need the software and don't really care about version and stuff. btw is QT useless for compiling the source-code? (i did it by command line)

### Log URLs ###

Not necessary

**Comment by Jnewbon** [comment]
Reading into this, it looks like the failure will only happen if the variable SYNERGY_REVISION is defined but does not contain the expected value.

The only two situations I can see this happening by reading lines 32-43 is if either the build was run without a git repository (for example the download as a zip feature was used or the .git folder was deleted) or if git is not installed on the machine running the build. 

Making the following change on line 45 solves the issue

`if (DEFINED SYNERGY_REVISION AND NOT SYNERGY_REVISION)`

**Comment by attichicco** [comment]
Hi, it's been a long time...
Back then I wasn't a programmer and I wasn't very familiar with github, so I lost the comment...
I got the update email from github-actions and I've found this lost issue...

Seems like it hasn't been fixed yet, I would love to contribute but looks like I'm not allowed to create a new branch
Thanks @Jnewbon for your answer and sorry for the long wait

**Comment by nbolton** [comment]
This should be fixed now as those variables have gone from our cmake config in 1.15. 
Please let me know if this issue is not fixed.
