### ISSUE TITLE
Synergy is not working while using Samsung DeX application.

### ISSUE THREAD

**Issue by iqHpi** [symless/synergy#6628]
When using Samsung Dex, no mouse clicks on the connected Ubuntu PC.  Currently, I'm using a  Windows10 notebook and Ubuntu 18.04.3 to share a mouse and keyboard. 

I'm using Synergy paid version. If you do not use Samsung Dex, the mouse moves well from the notebook to Ubuntu and the click works well. When running Samsung Dex, the mouse moves from the notebook to Ubuntu, but it can not be clicked. After moving the mouse pointer to Ubuntu after running Samsung Dex, The mouse clicks sound, but the mouse clicks do not work accordingly. It works normally again when I terminate Samsung Dex. 

Synergy Version: 1.11.0-stable-b2173efb 
Build date: 16/12/2019

**Comment by OptimisticShaggy** [comment]
Are there any updates for this issue? Very interested as this would make or break me buying a license.

**Comment by desymless** [comment]
Unfamiliar with Samsung DeX, from what I can see online it's a Android based operating system - which is unfortunately not supported with Synergy right now.

However, I can also see that a Linux OS can be operated within the DeX environment, so it might be possible to use one of our Linux installers or perhaps the flatpak version (which supports a variety of Linux distros).

**Comment by wokawoka** [comment]
Anyone who has tried synergy on samsung dex running a more recent version?

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
