### ISSUE TITLE
Please allow downloading older version on https://symless.com/synergy/download

### ISSUE THREAD

**Issue by xmstspider** [symless/synergy#7196]
Hi, would it be possible to add download support for older releases on your site?

Under https://symless.com/synergy/download, I can only download latest 1.14 version and there is a "Looking for older versions?" section which only points to Synergy 2.

I would be able to download older versions as well.

Thank you

**Comment by vitalPixel** [comment]
Hey @xmstspider,

At the moment that functionality is limited to our Business version.
We have had discussions about expanding it to our Consumer version as well but it's not clear if or when it will be implemented.

However, we usually handle requests for specific older versions through our customer support channel.
If you're looking for a particular version, do you mind opening a ticket there (https://symless.com/synergy/contact-support)?


Thanks,
Francisco

**Comment by vitalPixel** [comment]
Yes, sorry, both Synergy Basic and Pro are Consumer versions.

We agree that it would be helpful to allow download of at least one previous version.
I can't promise a timeline, but it's likely that this will be enabled from the Download page at some point.

In the meantime, let us know if you run into any issues getting the installer for those earlier versions.


Cheers,
Francisco

**Comment by xmstspider** [comment]
up

**Comment by nbolton** [comment]
We have made some progress on this, but we do not currently have an archive of old versions. As time moves forward, our archive of older versions will increase. If you need an older version, please raise [a support ticket](https://symless.com/synergy/contact).
