### ISSUE TITLE
Improved label/description of ‘Elevate privileges’

### ISSUE THREAD

**Issue by Smylers** [symless/synergy#7224]
### Problem ###

On a Windows client, setting the ‘Elevate privilges’ preference to ‘Always’ does exactly what I want; I just had no idea that was the setting I needed!

My issue was that whenever I needed to provide my password to the Windows client (such as when the screen has locked), the pointer jumped back to the server computer twice: once when activating the log-in window (such as by pressing a key when on the lock screen), and a second time once the password has correctly been provided and it's showing my desktop.

I wanted that not to happen, for Synergy to keep the focus on the client throughout logging in.

But I hadn't realized this has anything to do with elevating privileges. The setting is in an ‘Advanced’ box, suggesting it's only for users who know what they're doing — and wish to do something funky with privileges. I'd seen it many times, but never realized it was relevant to me.

I think bugs #3637, #6388, and #6881 are other people basically wanting the same thing, suggesting I'm not the only one who missed this.

### Solution ###

Either relabel the option or provide a description with it which makes clear what the user-facing effect of this preference is for, avoiding jargon which the user is likely to skip over or think doesn't apply to them.

**Comment by Smylers** [comment]
I think this is still true, and my suggested fix above is basically a doc change. But I now use Synergy 3, so it no longer affects me any more.

**Comment by nbolton** [comment]
I improved the wording in Synergy 1, so I think this is resolved now. Thanks for using Synergy 3.
