### ISSUE TITLE
README.md mentions compiled versions of Synergy 1 and 2

### ISSUE THREAD

**Issue by ls-1N** [symless/synergy#7281]
Currently, the README of this repository provides a Download link saying that one can find compiled versions of Synergy 1 and 2 there. Meanwhile, the homepage of the app mentions Synergy 3.

I would simply have submitted a PR myself, but since I am not yet a customer, I didn't know whether Synergy 1 and 2 can still be found there.

### Observed:
> [Download](https://members.symless.com/download-authentication) - Get the compiled version of Synergy 1 or Synergy 2.

### Expected:
> [Download](https://members.symless.com/download-authentication) - Get the compiled version of Synergy 1, Synergy 2, or Synergy 3.

or
> [Download](https://members.symless.com/download-authentication) - Get the compiled version of Synergy 3.

**Comment by nbolton** [comment]
I believe this is fixed, but please let me know if not.
