### ISSUE TITLE
Sponsored issue: delay when using special characters on Hungarian keyboard

### ISSUE THREAD

**Issue by xeniakadar** [symless/synergy#7299]
Synergy Version: 2.0.9

Steps to reproduce issue:
1. Use Hungarian keyboard
2. Move mouse to client
3. E.g. type "á"

expected: "á"
output: "a". 

Following the update to version 2.0.9, I've experienced a delay of nearly a second when typing accented characters, which significantly hampers my typing speed (given that we use a multitude of these characters). I attempted varying configurations and discovered that the issue resolves when I disable Synergy.
A common usage scenario is typing the suffix "áció", which entails typing "á". 

## Priority Support

- @xeniakadar is using  [Mintycode](https://mintycode.io) to fund this issue.
- If you would like to accept ![amount](https://imageupload.io/ib/zwkd2EaAY6YpPsg_1693209112.png) bounty for solving this issue join [Mintycode](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=562e797f-b2f1-423b-88c8-caed196821e6&owner=symless&name=synergy-core).
- Thank you in advance for helping.

[![mintycode](https://imageupload.io/ib/LvxMwrPxam1JW9e_1693210482.png)](https://mintycode.io)

**Comment by desymless** [comment]
Hi 👋 
Synergy 2 is no longer being developed or supported, would you mind downloading/installing Synergy 1.14.6 and see if the issue still occurs?

**Comment by nbolton** [comment]
Closing as no response and it is related to v2 which is no longer in development. Please use Synergy 3 or Synergy 1 instead. Thanks!
