### ISSUE TITLE
Wayland host mouse will not leave host system

### ISSUE THREAD

**Issue by jorstar** [symless/synergy#7420]
### Discussion

- [X] Yes, and I still want to report a bug

### What type of Synergy user are you?

Customer

### Product name

Synergy 1

### Synergy version number

1.15

### Operating systems (OS)

- [X] Windows
- [ ] macOS
- [X] Linux or Unix
- [ ] Other

### OS versions or Linux distros

Host OS: Arch Linux with Linux 6.6.42-1-lts kernel using Wayland
Client Os: windows 11 23H2

### Synergy configuration

Arch linux host. TLS is disabled
windows client is connecting through IP

using the same configuration on X11 and version 1.14.6 works fine.

### What steps will reproduce the problem?

1. start synergy
2. connect client
3. try to move to client 

### Log output

```shell
unfortunately there was no extra logs besides that the client was connected.
```

**Comment by nbolton** [comment]
Thanks for the bug report, we're due to start on Wayland support soon. Did you compile latest `master` (1.15.0) yourself? If so, just a heads up that there are a few Windows bugs we're working on. Also, just curious, did you disable the "Wayland blocker" in the GUI or did you skip the GUI and run `synergys`/`synergyc` directly?

**Comment by jorstar** [comment]
I Did clone master and then compile the source using cmake -B build --preset=linux-release
Then I used makepkg to create the package and install it using pacman

**Comment by jorstar** [comment]
When I installed it the first time I didn't actually disable anything and it opened up without the wayland is not supported. 
Now when I re-try to install it the same way I do get the wayland is not supported error.

**Comment by nbolton** [comment]
> it opened up without the wayland

Ah, that might have been a bug. The following code is used to determine if Wayland is running:
```
  if (qgetenv("XDG_SESSION_TYPE") == "wayland") {
```

You can disable that by unsetting `XDG_SESSION_TYPE` just for the app (but that might result in undefined behavior).

We're planning to start working on Wayland support in 1.15.0.

**Comment by nbolton** [comment]
> switching to x11 every day

Damn, you have to switch back and forth between X11 and Wayland? Mind if I ask what's pulling you to Wayland at the moment?

**Comment by nbolton** [comment]
@jorstar Would you mind giving PR #7449 a try?
