### ISSUE TITLE
Error 1053 the service did not respond to the start

### ISSUE THREAD

**Issue by inputuserhere** [symless/synergy#7478]
### Discussion

- [X] Yes, and I still want to request a feature

### What type of Synergy user are you?

Customer

### Product name

Synergy 3

### Operating systems (OS)

- [X] Windows
- [ ] macOS
- [ ] Linux or Unix
- [ ] Other

### OS versions or Linux distros

Windows 11
Windows 10

### Synergy configuration

Windows 11 client

Windows 10 server

### What problem are you trying to solve?

I tried adding it as a service.

I get this error when trying to start it as a service. It runs, but the error persists, and it doesn't startup with the computers.

Windows could not start the Synergy Service on Local Computer.
Error 1053 the service did not respond to the start or control request in a timely fashion.

### What solution do you propose?

I found this thread, but it was no help - https://forums.symless.com/topic/6365-issues-starting-synergycexe-on-windows-as-a-service/

**Comment by nbolton** [comment]
Hello, as a customer you're entitled to tech support included in your license. Please [raise a support ticket](https://symless.com/synergy/contact) if you'd like to take advantage of that. If that works for you, then please let me know your ticket number so we can continue the discussion there.

**Comment by inputuserhere** [comment]
I am on the Free trial. I am wondering how to do this because this is the only thing stopping me from purchasing. 

I don't know how this hasn't been implemented already or why this is difficult to add, it seems, going by other users' experiences.

**Comment by nbolton** [comment]
> I am on the Free trial. I am wondering how to do this because this is the only thing stopping me from purchasing.

Thanks for trying Synergy 3!

> I don't know how this hasn't been implemented already or why this is difficult to add, it seems, going by other users' experiences.

Synergy 3 should run in the background automatically, so it's probably a transient issue on your system that we need to fix. 

> I emailed support and spoke with Daniel and he hasn't gotten back to me.

Don't worry, our support team will respond soon. Thanks for your patience!

**Comment by inputuserhere** [comment]
> Synergy 3 should run in the background automatically, so it's probably a transient issue on your system that we need to fix. Our support team should be able to help you with that.

It runs in the system tray, I do not want that. Nor do I want it to run at startup. I want it to run as a Windows service.

**Comment by nbolton** [comment]
> So, is this possible with your software or not?

Yes, it is possible. Synergy 3 should automatically install as a service, and if it doesn't then that's a problem we can help you fix. Our support will help you with this.

> It runs in the system tray, I do not want that. Nor do I want it to run at startup. I want it to run as a Windows service.

Ok, we can help you with that too. Please let our support team respond to this.

> Support hasn't gotten back to me in a day. After I asked this question. 

Thanks again for your patience. If you could kindly let me know your ticket number, I'll look into it for you.
